#import "../../template_tufte.typ": *

L'espressione "scienze della Terra" è stata introdotta in tempi relativamente recenti. Fino a pochi anni fa, le diverse discipline scientifiche ora incluse in questa denominazione omnicomprensiva, come l'astronomia, la geografia fisica e la geologia, erano generalmente classificate sotto il termine "scienze naturali". Tale termine includeva anche discipline orientate allo studio degli esseri viventi, quali la biologia, la zoologia e la botanica. Le scienze della Terra si configurano oggi come un insieme di settori disciplinari dedicati allo studio dei corpi materiali non viventi, come masse d'aria, corpi idrici e ammassi rocciosi, nonché all'analisi di fenomeni naturali quali quelli meteorologici, sismici, vulcanici, geomorfologici, idrologici e oceanografici.

La diffusione di una maggiore sensibilità ecologica e di un interesse generalizzato per questioni ambientali ha contribuito a indirizzare le scienze della Terra verso nuovi approcci focalizzati sull'ambiente. Questo concetto viene inteso sia come fonte di risorse indispensabili per l'uomo, sia come un "bene collettivo" suscettibile di subire vari impatti negativi, tra cui inquinamento, erosione, desertificazione e rischi sismici. Le scienze della Terra integrano dunque sia le storiche discipline teoriche di stampo "classico" sia quelle sviluppatesi con un intento applicativo, ovvero finalizzate a fornire strumenti utili per le attività umane, come la geologia ambientale o la geologia applicata.

Se in passato la ricerca era incentrata prevalentemente sullo studio delle singole componenti e fenomeni isolati, oggi essa abbraccia una prospettiva maggiormente sistemica. Si tende infatti a ricostruire i cosiddetti "sistemi ambientali", correlando le diverse informazioni disponibili. Tale approccio mira a interpretare i fenomeni che interessano la superficie terrestre in modo unitario, considerando la Terra, o più propriamente il "sistema Terra", come un complesso integrato di sistemi ambientali interagenti. L'indagine si avvale così delle conoscenze derivanti dai diversi ambiti della ricerca scientifica secondo un'impostazione interdisciplinare.

Il modello più generale del sistema Terra individua alcuni grandi sistemi o domini ambientali distinti: la geosfera, l'idrosfera e l'atmosfera. La geosfera comprende la parte solida del pianeta, dal nucleo fino alla crosta terrestre; l'idrosfera include tutte le forme di acqua presenti sulla Terra, siano esse superficiali (oceani, mari, laghi, fiumi, ghiacciai), sotterranee (falde acquifere) o sotto forma di vapore acqueo atmosferico; l'atmosfera rappresenta l'involucro gassoso che circonda il pianeta. Questi domini interagiscono attraverso dinamiche di scambio di energia e materia.

A completamento di questo quadro viene considerato un quarto sistema ambientale: la biosfera o ecosfera, che rappresenta l'ambito in cui si sviluppa la vita. Essa permea gli altri tre componenti del sistema Terra e vi interagisce attivamente. Lo spazio occupato dalla biosfera comprende la parte superficiale della geosfera (litosfera), le terre emerse che affiorano dalle acque, l'idrosfera e il livello più basso dell'atmosfera, ossia la troposfera.

// Tabella