#import "../../../template/_global/template.typ": *
#import "../../../template/_global/config.typ": *

#intro[Anche la poesia venne fortemente segnata dall'eredità intellettuale di Ralph Waldo Emerson e del trascendentalismo, che affermavano ideali come la fiducia in sé stessi (_self-reliance_) e l'individualismo. Questi principi avrebbero contribuito in maniera decisiva a plasmare i valori peculiari della cultura americana. Walt Whitman, in particolare, rappresenta uno dei più espliciti seguaci di Emerson, mentre Emily Dickinson, pur utilizzando una voce più intima e indiretta nella sua produzione poetica, ne riflette ugualmente l'influsso.

Accanto a questi giganti letterari dell'Ottocento, le cui opere spesso non vennero comprese appieno dal pubblico contemporaneo, esisteva un filone poetico più accessibile, di natura narrativa, che si allineava al comune sentire dell'epoca. Questo genere di poesia, privo di intenti destabilizzanti, aveva come obiettivo quello di ispirare emozioni semplici e nobili, commuovendo oppure orientando moralmente il lettore.]

== Walt Whitman

Walt Whitman (1819-1892) fu non solo un grande poeta, ma anche un fervente oratore, cantore della democrazia americana. Mentre nelle sue manifestazioni pubbliche denunciava le instabilità politiche del suo paese e difendeva i valori democratici, nella sfera personale combatteva con il senso di solitudine, l'isolamento e la consapevolezza della morte imminente.

=== La vita

Nato a Long Island in una famiglia anglo-olandese, secondo di otto figli, conobbe presto il duro lavoro manuale, assistendo suo padre nelle attività di carpenteria. Adolescente, intraprese diversi mestieri: fu apprendista tipografo, maestro di scuola e giornalista itinerante. Nel 1848 partecipò a un viaggio decisivo: partendo per New Orleans e attraversando Chicago lungo il Mississippi e i Grandi Laghi prima di fare ritorno a New York via Hudson, scoprì l'immensità della geografia americana e riconobbe la straordinaria vitalità dei territori di frontiera e degli spiriti pionieristici che li popolavano. 

Tra il 1851 e il 1854 si stabilì momentaneamente a Brooklyn e si guadagnò da vivere come falegname. Durante quegli anni iniziò a tenere alcuni scritti personali che avrebbero costituito il nucleo iniziale della sua celebre raccolta poetica _Leaves of grass_ (_Foglie d'erba_). Più tardi, durante la Guerra civile americana (1863-1865), Whitman lavorò a Washington come impiegato governativo e operò anche come infermiere volontario, fornendo sostegno emotivo e psicologico ai soldati feriti. Da queste esperienze nacque _Drum-Taps_ (_Rulli di tamburo_, 1865), una raccolta poetica dai toni meditativi, in seguito inclusa in successive edizioni di _Foglie d'erba_.

Gli ultimi vent'anni della sua vita trascorsero nella città di Camden, nel New Jersey. Nel 1873 Whitman vi si trasferì per vivere con il fratello George dopo la morte della madre e a seguito di un grave ictus che lo lasciò parzialmente paralizzato. 

=== I temi

I temi centrali della produzione poetica di Walt Whitman si formano attraverso un processo lungo e graduale, che prende avvio da quasi vent'anni di attività giornalistica non sempre caratterizzata da un alto livello qualitativo. Whitman emerge come un poeta alla ricerca di sé, profondamente impegnato nell'osservazione minuziosa del mondo circostante, con l'intento di interiorizzarlo e integrarlo nell'ambito della propria identità poetica. Tale identità viene da lui concepita come unità indissolubile tra corpo e anima, una sintesi celebrata magistralmente nel poema _Song of myself_ (_Canto di me stesso_).

Le esperienze personali rivestono un ruolo fondamentale nella costruzione della sua sensibilità artistica e del suo immaginario poetico. Il contatto con l'atmosfera urbana e industriale delle crescenti metropoli americane alimenta in Whitman una visione ottimistica circa il progresso tecnologico; allo stesso tempo, i rapporti con i lavoratori urbani, visti come le autentiche forze motrici della nazione sotto la luce degli ideali democratici, influenzano profondamente la sua prospettiva. Le passeggiate nelle colline di Long Island, immerse nella natura, gli suscitano invece un senso di fusione estatico con l'ambiente naturale.

Whitman frequenta gli esponenti della Brooklyn Art Union e si avvicina al trascendentalismo, traendo ispirazione soprattutto dagli scritti di Ralph Waldo Emerson. Le osservazioni sulla vita quotidiana e le esperienze variegate, annotate nei numerosi quaderni personali, trovano espressione poetica nella prima edizione di _Leaves of grass_ (_Foglie d'erba_, 1855). I dodici componimenti inclusi in questa raccolta rappresentano non solo una forma di autobiografia interiore, un'esplorazione lirica delle esperienze emotive, sensoriali e sessuali dell'autore, ma anche un canto democratico che aspira a rappresentare le esperienze universali dell'umanità.

Whitman si pone obiettivi che sfidano i canoni tradizionali: rovesciare la visione puritana della vita, predominante nel panorama letterario americano, per celebrare l'uomo, anziché Dio, quale centro nevralgico dell'universo. La sua prospettiva rappresenta una scelta audace per l'America dell'epoca e per questo la sua opera, oltre a essere criticata per un linguaggio giudicato non poetico e per l'utilizzo di strutture metriche anticonvenzionali, riceve inizialmente poca attenzione.

Dal momento della pubblicazione della prima edizione fino alla sua morte, Whitman dedica la propria vita all'elaborazione e alla espansione di _Leaves of grass_. La raccolta attraversa nove edizioni successive, ciascuna arricchita e rivista fino a diventare un corpus monumentale composto da circa cinquecento poesie e alcuni frammenti di prosa poetica.

Come poeta visionario e profeta della democrazia e dell'uomo comune, Whitman celebra la pienezza e l'imponente dignità di ogni aspetto del mondo e attribuisce un valore supremo al corpo umano nella sua dimensione fisica. Tuttavia, in patria inizialmente la sua figura è osteggiata; accusato di immoralità per le sue presunte inclinazioni omosessuali e tacciato di oscenità, ottiene riconoscimenti solo in Inghilterra e Francia. La sua opera riceverà finalmente una piena rivalutazione negli Stati Uniti solo alcune generazioni più tardi, diventando una fonte d'ispirazione per la letteratura americana del XX secolo.

La lezione di Whitman – l'abbandono delle forme metriche convenzionali, l'immersione appassionata nella realtà quotidiana e la contemplazione del grande ideale americano – verrà riconosciuta come un contributo fondamentale alla cultura letteraria moderna e influenzerà profondamente lo sviluppo delle tradizioni poetiche successive.

== Emily Dickinson

Emily Dickinson (1830-1886) è considerata una delle più grandi poetesse americane, nonché tra i principali esponenti della lirica moderna.

=== La vita

Nacque ad Amherst, Massachusetts, in una famiglia dalle radicate tradizioni puritane. Trascorse un'adolescenza serena, priva di eventi particolarmente rilevanti. I legami più intensi della sua vita furono quelli con il fratello Austin, la moglie di quest'ultimo e la sorella Lavinia. Frequentò per sei anni l'Amherst Academy e nel 1848 si iscrisse al Mount Holyoke Female Seminary a South Hadley. In quel contesto rigidamente puritano, il suo temperamento indipendente e ribelle si manifestò per la prima volta attraverso il rifiuto di dichiarare pubblicamente la propria fede cristiana. Tale esperienza segnò l'inizio del suo distacco dal credo religioso della famiglia, che comunque influenzò in maniera duratura la sua produzione poetica, insieme alle idee trascendentaliste del filosofo Emerson.

Dopo un viaggio famigliare nelle città di Boston, Washington e Philadelphia, il ritorno ad Amherst avviò il suo progressivo isolamento. Le ragioni dietro la scelta della Dickinson di vivere quasi trent'anni reclusa nella casa paterna non sono mai state chiarite del tutto. Si parla di un amore impossibile; più probabilmente, potrebbe essere stata la consapevolezza dell'impossibilità di instaurare rapporti appaganti con il mondo esterno, che la portò a perseguire, nella solitudine, la sua missione poetica. Visse chiusa nella sua stanza, sempre vestita di bianco, dedicandosi alla scrittura e tenendo contatti con pochi amici tramite lettere. 

Di particolare rilievo fu la corrispondenza con il critico e giornalista T. Wentworth Higginson dell'_Atlantic Monthly_, al quale si rivolse nel 1862 chiedendo un parere sui suoi componimenti. Pur apprezzandoli, Higginson ne sconsigliò la pubblicazione, e così quasi tutta la sua produzione poetica rimase inedita fino alla sua morte, eccetto sette testi pubblicati nel 1850. Solo nel 1955 l'intero corpus delle sue 1775 poesie, privo di titoli e numerato progressivamente dal curatore T.H. Johnson, venne finalmente reso pubblico.

=== L'opera

Tra il 1890 e il 1896 furono pubblicate tre raccolte delle poesie inedite della Dickinson, ma questi volumi le garantirono soltanto una breve notorietà, presto sopraffatta dall'affermarsi del realismo negli Stati Uniti. Fu solo attorno al 1920 che l'opera della poetessa ricevette una rinnovata attenzione e la critica iniziò a considerarla una precorritrice della moderna lirica americana.

I temi centrali nella poesia della Dickinson – amore, natura, morte ed eternità – emergono in una prospettiva unica, capace di ridimensionare ciò che appare immenso e lontano per renderlo intimo e concreto, e viceversa. Il mondo della poetessa si presenta come un universo domestico popolato da piccoli dettagli: insetti, fiori, vicini di casa, albe e tramonti; dettagli che riflettono il continuo e delicato mutamento delle cose sotto vari giochi di luce e catturano l'incertezza della vita mortale. La morte è per lei fonte di sofferenza perché spezza legami con gli affetti più cari. Tuttavia, questo dolore è mitigato dalla speranza nell'immortalità, che promette di restituire ciò che la morte ha portato via.

A unificare tutti questi temi vi è un profondo senso dell'esistenza, così come una consapevolezza dell'importanza e della nobiltà insite in ogni anima che affronta la complessa avventura della vita.

Emily Dickinson si distingue per un'originalità straordinaria, sia nella forma sia nel linguaggio. La poetessa predilesse composizioni brevi o estremamente concise, spesso prive di una struttura metrica rigorosa e di rime convenzionali. Nonostante ciò, molte delle sue opere si rifanno alla metrica degli inni protestanti e delle ballate, caratterizzate dall'alternanza tra versi di quattro e tre accenti. 

La sua poesia si contraddistingue per l'intento di concentrare una potente carica espressiva in poche parole, talvolta ridotte a immagini fulminee, avvalendosi di una sintassi ellittica e di un uso estremamente parsimonioso della punteggiatura. Questi elementi concorrono a conferirle una modernità linguistica sorprendente. 

I termini utilizzati dalla Dickinson sono spesso carichi di significati contrastanti: possono essere violenti, dissacranti, scettici oppure intrisi di profonda devozione verso il sacro; altre volte si presentano graziosi, delicati, ma anche intensamente metafisici o penetranti. Nella sua opera, le parole stesse assumono il ruolo di protagoniste assolute: incisive, audaci e trasgressive, portano nella loro essenza e nella loro cesellatura sillabica i segni di una modernità impareggiabile.

== La poesia fra Ottocento e Novecento

L'influenza dei due maggiori poeti dell'Ottocento americano, Walt Whitman ed Emily Dickinson, emerse con forza soltanto nel XX secolo. Le loro opere furono recepite con lentezza dal pubblico statunitense. Anche la poesia di Herman Melville, che rielaborava tematiche presenti nella sua produzione in prosa, non trovò ampio riconoscimento fino agli anni Venti del Novecento. 

Nel frattempo, il pubblico americano si rivolgeva prevalentemente a un'altra tipologia di poesia, meno provocatoria e più in linea con i gusti comuni. Si tratta della produzione dei cosiddetti "fireside poets" (poeti del caminetto), il cui stile tradizionale evitava posizioni radicali e privilegiava temi rassicuranti. Tale corrente godette a lungo del favore del pubblico e trovò grande diffusione anche in ambiti educativi, in quanto le sue opere, confortevoli sul piano emotivo e pronte all'intrattenimento, evitavano ogni elemento potenzialmente disturbante. 

Tra i poeti più rappresentativi di questa tradizione figura Henry Wadsworth Longfellow (1807-1882), docente di lingue e letterature romanze e germaniche presso Harvard. La sua traduzione della _Divina commedia_ (1867) fu realizzata con un tono di "devota ammirazione". Sebbene incline a incursioni nel sentimentalismo e nel moralismo, Longfellow si distinse per notevoli doti compositive. 

Tra le sue opere principali figurano _Evangelina_ (1847), poemetto in esametri classici che narra eventi legati alla guerra anglo-francese in Nord America, e _Hiawatha_ (1855), che celebra la vita degli indigeni americani con intonazioni romantiche e uno stile metrico ispirato alla tradizione epica ugrofinnica. Inoltre, una sua antologia contribuì a far conoscere un vasto repertorio di autori europei al pubblico americano.

Al medesimo contesto appartengono anche Oliver Wendell Holmes (1809-1894) e James Russell Lowell (1819-1891). Holmes è noto per prose sagaci dal sapore settecentesco e per componimenti poetici raffinati, spesso destinati ai salotti culturali di Boston. Lowell, successore di Longfellow alla cattedra di Harvard e ambasciatore in Spagna e Inghilterra, si fece apprezzare per diverse raccolte poetiche. Tra queste spiccano i _Biglow papers_ (_Il carteggio Biglow_, 1848), una serie di lettere poetiche che affrontano la tematica antischiavista con uno stile critico e pungente.

=== Edwin Arlington Robinson

Edwin Arlington Robinson (1869-1935), erede della poetessa puritana Anne Bradstreet, è considerato uno dei principali poeti della transizione tra XIX e XX secolo. La sua produzione letteraria, se da un lato si collega alla tradizione dei "fireside poets", dall'altro introduce tratti innovativi, quali la componente drammatica dei suoi versi che si discostano dalla lirica, preannunciando alcune tendenze della poesia moderna.

Robinson si contrapponeva apertamente al materialismo, tornando a tematizzare ciò che nella narrativa naturalistica era definito determinismo sociale e biologico, tradotto nella sua opera poetica in una visione destinata al "fato". Pur mostrando affinità con il pensiero di Ralph Waldo Emerson, che sosteneva "Ogni qualvolta sono debole parlerò del Fato", Robinson sviluppa una prospettiva più cupa e disillusa; trasforma l'idea di self-reliance emersoniana in una filosofia della disperazione, permeata da uno stoicismo malinconico.

La sua prima raccolta poetica, _The torrent and the night before_ (_Il torrente e la notte prima_), risale al 1896 ed è seguita da opere fondamentali quali _Children of the night_ (_Figli della notte_, 1897), _Captain Craig_ (_Il capitano Craig_, 1902) e _The man against the sky_ (_L'uomo contro il cielo_, 1916). Quest'ultima raggiunge il culmine nell'esplorazione delle dinamiche tragiche dell'esistenza umana. La maestria di Robinson nella struttura metrica e ritmica gli consente di anticipare temi e stili che caratterizzeranno successivamente la poesia di Robert Frost.
#pagebreak()
#set page(fill: accent.eng.lighten(90%))
== In sintesi <senza_numero>

/ Whitman: Nato nel 1819 a Long Island da una famiglia con radici anglo-olandesi, Walt Whitman intraprese diverse attività prima di consacrarsi alla poesia: carpentiere, apprendista tipografo, insegnante e giornalista itinerante. Tra il 1851 e il 1854 lavora come falegname apprendista e successivamente come infermiere durante la Guerra Civile Americana. Dal 1873 si ritira definitivamente a Camden, dove trascorre gli ultimi anni della sua vita fino alla morte. \ La raccolta _Foglie d'erba_ (_Leaves of Grass_) pubblicata nel 1855, costituisce un'opera monumentale che include circa 500 componimenti. Essa si configura non solo come una sorta di autobiografia spirituale, ma anche come un celebrazione lirica della vita umana nelle sue esperienze emotive, sensoriali e sessuali. Il poeta diventa espressione dell'Io universale, definito come "corpo-anima", rovesciando la concezione puritana che poneva Dio al centro dell'esistenza. \ Whitman, cantore della democrazia e dell'uomo comune, riuscirà ad ottenere pieno riconoscimento nella sua patria solamente diverse generazioni dopo, influenzando profondamente la letteratura americana del Novecento.

/ Dickinson: Emily Dickinson (1830-1886) nacque ad Amherst all'interno di una famiglia puritana dalle tradizioni solide. Il suo temperamento caratterizzato da individualismo e insofferenza portò la poetessa a prendere le distanze dalla religione, pur mantenendo tracce di quest'influenza insieme a quella del trascendentalismo di Emerson. Questo distacco fu accompagnato da una vita appartata in cui Emily decise di dedicarsi esclusivamente alla poesia, trascorrendo gran parte della sua esistenza isolata nella sua stanza, interagendo sporadicamente con il mondo esterno attraverso lettere e rari incontri. \ Dickinson ha composto oltre 1700 poesie, pubblicate solo postume, in cui esplora tematiche quali amore, natura, morte ed eternità. La sua capacità di ridurre questi grandi temi in un "universo domestico" emerge particolarmente negli elementi naturali che diventano simbolo dell'incertezza della condizione mortale. La forma e il linguaggio della poetessa si distinguono per l'originalità: il ricorso ad immagini concise ed evocative, l'uso di una sintassi ellittica e la rinuncia alla punteggiatura conferiscono ai suoi componimenti un'impressionante modernità espressiva.

/ Poesia fra Ottocento e Novecento: Nel passaggio tra Ottocento e Novecento, si affermano i cosiddetti "poeti del caminetto" (fireside poets), i quali si discostano dalla radicalità di autori come Whitman, Dickinson o Melville, preferendo un genere poetico rassicurante e in sintonia con il sentire comune. Tra questi, si ricordano H.W. Longfellow (1807-1892), O.W. Holmes (1809-1894) e J.R. Lowell (1819-1891). Edwin Arlington Robinson (1869-1935), invece, pur riprendendo influenze vittoriane ed emersoniane, con la drammaticità e non liricità dei suoi versi, precorre taluni tratti essenziali della poesia del Novecento. \ Tra le sue opere principali si segnalano _Il torrente e la notte prima_ (1896), _Figli della notte_ (1897), _Captain Craig_ (1902) e _L'uomo contro il cielo_ (1916).



