#import "../../../template_tufte.typ": *
#show: frame-style(styles.thmbox)

#evidenzia[Le origini della lingua e della letteratura italiana affondano le radici nel ricco e variegato panorama della tradizione romanza, in cui, già dal IX secolo, si realizza il passaggio dal latino alle nuove formazioni linguistico-culturali costituite dai volgari, ovvero le lingue locali che daranno origine successivamente alle lingue nazionali. La letteratura franco-provenzale, che visse il suo periodo di maggiore splendore tra i secoli XII e XIII, rappresentò un modello fondamentale per gli autori italiani. Non a caso, la prima scuola poetica italiana, nota come "scuola siciliana", si ispirò al raffinato stile cortese e trobadorico. 

La lezione dei poeti siciliani passò successivamente in Toscana grazie all'opera di Guittone d'Arezzo, evolvendo poi con l'emergere del dolce stilnovo verso la fine del XIII secolo. Nel frattempo, soprattutto nel settentrione d'Italia, si diffondeva una ricca produzione letteraria di carattere didattico (Bonvesin de la Riva) e giullaresco, mentre in Toscana prendeva piede la poesia comico-realista, con autori come Cecco Angiolieri. La prosa, invece, rimase inizialmente legata al latino, limitandosi a opere di carattere preparatorio, come quelle di Brunetto Latini e Bono Giamboni, insieme ai volgarizzamenti e alla vivace raccolta di novelle del _Novellino_, precursore delle grandi opere del Trecento.]

== Le origini e la nascita del volgare

Le origini del volgare italiano e il suo sviluppo furono influenzate dal mantenimento del latino come lingua colta predominante. Questo ritardo nella nascita della letteratura italiana rispetto ad altre tradizioni europee fu dovuto tanto alla forza conservatrice del latino quanto alla vivacità linguistica generata dalla frammentazione comunale. 

Il latino volgare si trasformò progressivamente nelle lingue neolatine, tra cui l'italiano. I primi documenti scritti in volgare italiano comprendono l'Indovinello veronese (VIII-IX secolo), scoperto nel 1924 presso la biblioteca capitolare di Verona; i Placiti campani (960-963), testimonianze giuridiche inserite in verbali notarili redatti in latino; l'Iscrizione di San Clemente (XI secolo) e il Ritmo di Travale (1158). Le prime opere letterarie prodotte nel volgare italiano includono il Ritmo laurenziano, un testo giullaresco risalente al 1151-1157, il Ritmo cassinese e il Ritmo di Sant'Alessio verso la fine del XII secolo. Il Cantico di Frate Sole (o Cantico delle creature) di san Francesco d'Assisi, composto intorno al 1225, sarà tuttavia l'opera più straordinaria tra queste produzioni iniziali.

== L'influenza franco-provenzale

Nei secoli XI e XII la Francia era il cuore pulsante della civiltà europea e le sue prime manifestazioni letterarie in lingua romanza influenzarono profondamente l'Italia. Tra gli esempi più antichi spiccano la Sequenza di Santa Eulalia (fine IX secolo) e la Vita di Sant'Alessio (prima metà XI secolo). Divisa in due tradizioni linguistiche principali – quella d'oïl e quella d'oc – la letteratura francese offrì modelli distinti. A nord, la tradizione d'oïl era caratterizzata da un forte spirito epico, con opere come la Chanson de Roland (databile prima del 1100). Intorno alla metà del XII secolo si affermò un nuovo genere narrativo: il romanzo cortese, di cui Chrétien de Troyes fu il maestro indiscusso. In questo periodo nacquero anche i _lais_, racconti brevi in versi su temi amorosi, e il celebre romanzo Tristano e Isotta, presentato in due redazioni fondamentali: quella anglo-normanna di Thomas e quella normanna di Béroul.

A sud, precisamente in Provenza, si sviluppò la letteratura d'oc, che inaugurò una vasta produzione di poesia d'amore da parte dei trovatori. Il periodo di massimo splendore di questa tradizione letteraria si colloca tra il 1140 e il 1150, grazie ai poeti Arnaut Daniel, Jaufré Rudel e Bernart de Ventadorn, i quali rappresentarono un punto di riferimento fondamentale per la scuola lirica siciliana. Verso la fine del XII secolo, accanto alla poesia trobadorica, si diffusero anche i fabliaux, racconti brevi in versi caratterizzati da un realismo crudo e da toni satirici, oltre alla poesia allegorica, la cui massima espressione è il _Roman de la Rose_ (Romanzo della rosa), scritto inizialmente da Guillaume de Lorris tra il 1225 e il 1240 e successivamente completato, intorno al 1280, da Jean de Meung. Tra i trovatori italiani che si cimentarono nella composizione in provenzale si distingue Sordello da Goito, celebre per il _Compianto in morte di Ser Blacatz_ (1236).

== La scuola siciliana

La scuola poetica siciliana nacque intorno al 1230 nei circoli legati all'imperatore e re di Sicilia Federico II di Svevia, dando vita alla prima lirica in volgare italiano. L'attività di questa scuola si protrasse per circa trent'anni e si concluse con la sconfitta di Manfredi, figlio di Federico II, nella battaglia di Benevento del 1266. La disfatta segnò anche il declino del contesto culturale raffinato che aveva favorito l'emergere di tale scuola.

=== Il quadro storico-culturale

Durante la prima metà del XIII secolo, il regno di Sicilia abbracciava tutta l'Italia meridionale e viveva un periodo di stabilità politica ed economica grazie al governo di Federico II. Tra le iniziative politiche e culturali più rilevanti vi furono la fondazione dell'Università di Napoli nel 1224 e la promulgazione delle Costituzioni Melfitane nel 1231, che consolidavano l'autorità del sovrano rispetto ai feudatari. La corte palermitana divenne un centro di grande fermento culturale, accogliendo personaggi di spicco dell'epoca e promuovendo vari ambiti dell'intellettualità: dalla ricerca tecnico-scientifica e dagli studi magico-esoterici, principalmente grazie a Michele Scoto, alla letteratura filosofica araba e greco-bizantina, passando per la poesia tedesca del _Minnesang_ e le tradizioni trobadoriche provenzali in lingua d'oc. È proprio quest'ultima corrente a fungere da base per la nascita della "scuola siciliana", così definita da Dante nel _De vulgari eloquentia_.

=== Tematiche, forme poetiche e lingua

La tematica predominante nella poesia siciliana era l'amore, analizzato sotto diversi aspetti: teorici (la natura dell'amore, le sue manifestazioni e i suoi effetti) e come esaltazione della donna amata attraverso un omaggio simbolico assimilabile alla devozione feudale. Il poeta cercava di comunicare con la donna utilizzando immagini e segni comprensibili esclusivamente a lei. Le forme poetiche tipiche includevano la canzone, modellata sulla _canso_ provenzale e considerata l'espressione più elevata della scuola siciliana, riservata generalmente a componimenti dal carattere teorico e dottrinale; la canzonetta, caratterizzata da strofe brevi, era utilizzata per testi narrativi come invocazioni d'amore, lamenti per l'amata lontana o manifestazioni di gioia e dolore. Il sonetto rappresentava invece una creazione originale della scuola siciliana ed è divenuto il componimento lirico breve per eccellenza della poesia italiana.

La produzione poetica della scuola siciliana ci è giunta attraverso codici redatti tra il Quattrocento e il Cinquecento. Questi trascrittori conferivano ai testi una sfumatura toscana che ha modificato l'impostazione linguistica originale siciliana. Tuttavia, la lingua impiegata dai poeti siciliani non era quella popolare del tempo: si trattava piuttosto di un lessico ispirato a modelli latini e provenzali.

=== I poeti siciliani

Re Federico II e i suoi due figli, Enzo e Manfredi, si dedicarono alla poesia, sebbene senza raggiungere vertici di straordinaria qualità.

Tra i poeti della scuola siciliana, il più significativo fu sicuramente Iacopo da Lentini (circa 1210 - circa 1260). Dante lo cita nel Purgatorio (canto XXIV), riconoscendolo come il fondatore del movimento poetico siciliano e attribuendogli, probabilmente, l'invenzione del sonetto. Iacopo compose uno dei più ampi canzonieri del periodo, con circa 30 poesie in cui una notevole maestria retorica si coniuga con una vivace originalità inventiva. A lui dobbiamo la prima definizione dell'amore nella letteratura italiana: "Amor è uno desio che ven da core / per abondanza di gran piacimento". I suoi versi si concentrano sulla contemplazione della bellezza, sull'immagine idealizzata della donna amata e sulla totale dedizione di sé da parte dell'innamorato.

Più concisa ma stilisticamente ricercata appare la produzione di Guido delle Colonne (Messina, circa 1210 - circa 1280). La sua opera, composta da cinque canzoni giunte fino a noi, si distingue per l'uso raffinato delle figure retoriche e per il sottile gioco analogico che arricchisce la struttura poetica.

Pier della Vigna (circa 1190-1249), collaboratore di Federico II, è ricordato soprattutto grazie alla citazione di Dante nell'Inferno (canto XIII). Dopo essere caduto in disgrazia, si tolse la vita. Sebbene l'attività poetica non occupasse un ruolo predominante nella sua esistenza, Pier della Vigna partecipò alla disputa sull'amore con Iacopo da Lentini, che potrebbe aver segnato l'inizio della scuola siciliana. Tale dibattito si inserì nel solco tracciato da Iacopo Mostacci, poeta influenzato in modo piuttosto passivo dalle correnti provenzali.

Altri autori legati alla scuola siciliana includono Rinaldo d'Aquino, Giacomino Pugliese (con testi di tono popolareggiante), Stefano Protonotaro da Messina, che ci ha lasciato l'unica composizione conservata in siciliano originale.

Tra i nomi associati alla scuola siciliana figura tradizionalmente anche Cielo d'Alcamo (probabilmente una forma toscanizzata del diminutivo siciliano "Celi", derivante da Michele). Egli è l'autore del celebre contrasto Rosa fresca aulentissima, un dialogo tra una donna inizialmente ritrosa e il suo innamorato. Quest'opera combina riferimenti stilistici alla tradizione provenzale – come la pastorella e il contrasto – con elementi della cultura popolare e dialettale, alternando immagini e termini delle tradizioni auliche e cortesi a quelli della tradizione vernacolare.

== In sintesi

/ Origini:  La letteratura italiana ha tardato a svilupparsi, principalmente a causa della persistenza del latino come lingua erudita. Durante questo periodo, la produzione culturale era generalmente legata a tematiche teologiche, storiche-cronachistiche o epico-storiche, in contesti altamente formali e aristocratici.

/ Primi documenti del volgare italiano:  Tra i primi testi scritti in volgare italiano troviamo l'_Indovinello veronese_ (VIII-IX secolo), i Placiti campani (960-963), l'Iscrizione di San Clemente (XI secolo) e il Ritmo di Travale (1158). Il primo documento letterario in volgare è il Ritmo laurenziano, risalente al periodo tra il 1151 e il 1157. Nel XII secolo si segnalano anche il Ritmo cassinese e il Ritmo di Sant'Alessio, culminando nel celebre _Cantico di Frate Sole_(o Cantico delle creature), composto da San Francesco d'Assisi intorno al 1225.

/ Influenza franco-provenzale:  Le tradizioni letterarie francesi hanno avuto un peso fondamentale per la nascita della letteratura italiana. Nella Francia settentrionale, la lingua d'oïl ha coltivato una vena epica (ad esempio, la _Chanson de Roland_, antecedente al 1100) e una poetica cortese che si sviluppa verso la metà del XII secolo con i romanzi di Chrétien de Troyes. In Provenza, la lingua d'oc è invece associata alla produzione trobadorica d'amore, che raggiunge il suo massimo splendore tra il 1140 e il 1150.

/ La scuola siciliana:  La Scuola poetica siciliana rappresenta la prima espressione organizzata di lirica in volgare italiano. Fondata attorno al 1230 nella corte di Federico II, imperatore e re di Sicilia, questa corrente culturale ebbe vita per circa trent'anni, fino alla caduta della casata sveva dopo la battaglia di Benevento (1266) e la morte di Manfredi, figlio di Federico.

/ Poeti maggiori:  I protagonisti della Scuola siciliana includono Iacopo da Lentini (circa 1210-1260), Guido delle Colonne (circa 1210-1280) e Cielo d'Alcamo, autore del celebre contrasto "Rosa fresca aulentissima", composto tra il 1231 e il 1250.

/ Temi:  Questa fase della letteratura italiana si concentra principalmente sull'amore cortese e trovadorico, accompagnato dalla contemplazione della bellezza femminile. Attraverso un linguaggio elegante e raffinato, si costruisce una ricercata immagine idealizzata della donna.

