#import "../../../template_tufte.typ": *
#show: frame-style(styles.thmbox)

#evidenzia[I temi e l'elaborazione formale che avevano contraddistinto la scuola siciliana trovarono terreno fertile in Toscana, adattandosi alla realtà politica e culturale dei liberi Comuni, dove lo spirito borghese prevaleva sulle tradizioni aristocratiche e feudali. Da questa fusione nacque la scuola siculo-toscana, in cui, accanto ai consueti temi amorosi, acquisirono maggiore spazio e rilievo i contenuti politici. Parallelamente, in Umbria e Toscana si diffusero espressioni di poesia giocosa e realistica. Nell'Italia settentrionale, invece, si sviluppò una letteratura volgare con finalità prevalentemente didattiche, affiancata da esperienze popolari e giullaresche portate avanti da cantori itineranti. Di una qualità più alta fu la produzione lirica religiosa di Francesco d'Assisi e Iacopone da Todi.]

== Guittone d'Arezzo

Guittone d'Arezzo (circa 1230-1294) fu il principale rappresentante della corrente poetica siculo-toscana. Figlio del tesoriere del Comune di Arezzo ed esponente della parte guelfa, intorno ai vent'anni scelse volontariamente l'esilio. Nonostante la vita famigliare con moglie e tre figli, nel 1265 visse una profonda crisi religiosa che lo spinse a entrare nell'Ordine dei Cavalieri della Vergine. La sua opera poetica, raccolta nelle "Rime" e composta da 50 canzoni e 239 sonetti, mostra una marcata divisione: nella prima fase dominano i temi amorosi e politici, mentre nella seconda, in cui si firma come Fra Guittone, emergono insegnamenti morali e spirituali. Tra le sue opere principali figurano il _Trattato d'Amore_ in dodici sonetti e le _Lettere_, circa una trentina di testi in prosa che includono la celebre invettiva contro i "miseri infatuati fiorentini", dove l'autore mostra la sua maestria nell'ars dictandi, l'arte della composizione basata sulle norme retoriche del latino.

Guittone d'Arezzo fu considerato un indiscusso maestro di poesia nella Toscana settentrionale a partire dalla metà del XIII secolo. Il suo influsso sui contemporanei fu significativo sia per i contenuti sia per lo stile. Nella poesia d'amore adottò i modelli della scuola siciliana, concentrandosi maggiormente sui ragionamenti legati all'amore piuttosto che sulla sua rappresentazione emotiva. Per le canzoni politiche e morali si ispirò al _trobar clus_, lo stile complesso e oscuro della poesia provenzale, che adattò attraverso un uso elaborato e talvolta criptico del volgare toscano. La sua opera più nota è la canzone politica _Ahi lasso or è stagion di doler tanto_, scritta dopo la sconfitta dei guelfi a Montaperti nel 1260 per mano dei ghibellini. Questo componimento, caratterizzato da alternanze di dolore e sarcasmo pungente, rappresenta un chiaro distacco dalla tradizione siciliana sia per il forte tema politico-morale sia per la ricchezza dei registri linguistici e stilistici utilizzati. Meritano menzione anche le sue canzoni a contenuto morale-religioso, spesso altrettanto impegnative e ricche di risultati poetici significativi; tra queste spiccano le ballate-laude, genere da lui ideato e successivamente diffuso nell'ambiente toscano.

== La scuola cortese toscana

Il poeta più significativo della cerchia di Guittone fu il notaio lucchese Bonaggiunta Orbicciani (circa 1220 - circa 1290). Dante lo cita nel _De vulgari eloquentia_ come rappresentante della scuola poetica siciliana e, nel canto XXIV del _Purgatorio_, gli attribuisce il compito di definire il _stilnovo_ come nuova forma poetica. Nel suo canzoniere, Bonaggiunta sviluppò gli stilemi della scuola siciliana, diffondendoli in Toscana. La sua poesia risulta varia e intreccia le raffinatezze eleganti della lirica cortese con le forme più semplici e popolari. I temi sono quelli classici: l'amore e la critica politica. Seguaci di Guittone, seppur con diverse sfumature, si formarono anche ad Arezzo, Pistoia, Pisa e Firenze. Tra questi, il più originale fu Chiaro Davanzati (fine XIII secolo), il cui canzoniere, composto da 61 canzoni e numerosi sonetti, presenta motivi che anticipano il _stilnovo_. Meritevoli di nota furono anche Monte Andrea, un banchiere guelfo noto per il complesso _trobar clus_ fiorentino ricco di allusioni enigmatiche, e Dante da Maiano, che nel suo canzoniere oscilla tra lo stile siciliano e quello guittoniano, includendo una tenzone con Dante. Sulla figura della poetessa Compiuta Donzella (forse uno pseudonimo letterario) si è discusso a lungo; solo un codice le attribuisce tre sonetti di qualità poetica discreta.

== La poesia nell'Italia settentrionale

Nell'Italia settentrionale, la produzione letteraria volgare riveste un grande interesse, soprattutto nelle città di Cremona e Milano. Con finalità prevalentemente didattiche, essa si ispirava alla tradizione provenzale, con i motivi dell'_enueg_ (catalogazione di ciò che reca fastidio) e del _plazer_ (enumerazione di quanto suscita piacere), nonché alla tradizione biblico-apocalittica ed escatologica dei secoli XII e XIII.

Il primo rappresentante di tale tradizione fu Gherardo Patecchio, notaio cremonese attivo probabilmente nei primi decenni del XIII secolo. Egli compose lo _Splanamento de li proverbi de Salamone_, un poemetto che raccoglie precetti morali, e le _Noie_, una rassegna in versi decasillabi sui fastidi della vita.

Più complessa è la figura di Uguccione da Lodi (fine XII - inizio XIII secolo), autore di un _Libro_ scritto in lingua veneta e costituito da lasse monorime in versi alessandrini e decasillabi epici. Quest'opera propone una meditazione sui temi del peccato e della morte descritti con intenso realismo, nell'attesa del giudizio divino.

Un altro contemporaneo degno di menzione è il frate minore Giacomino da Verona. In dialetto veronese, egli scrisse il poemetto _De Ierusalem celesti e De Babilonia civitate infernali_, che si annovera tra le fonti ispiratrici della _Divina Commedia_ di Dante.

=== Bonvesin de la Riva

Bonvesin de la Riva (circa 1240 - circa 1313) è considerato il più grande scrittore in volgare lombardo del XIII secolo. Il toponimo "Riva" si riferisce probabilmente alla Ripa di Porta Ticinese a Milano, dove abitò dal 1288 fino alla sua morte. Terziario dei frati umiliati e insegnante in una scuola privata di sua proprietà, la sua attività letteraria si colloca tra il 1270 e il 1290. Tra le sue opere poetiche spicca il _De vita scholastica_ e, in prosa, il trattato _De magnalibus urbis Mediolani_ (Le meraviglie della città di Milano), scritto nel 1288. I suoi volgarizzamenti, tra cui i _Disticha Catonis_ e diversi poemetti agiografici, rispondevano a esigenze pedagogiche. La sua produzione in volgare lombardo si distingue per l'uso di quartine monorime alessandrine ed è caratterizzata da contrasti allegorici; tra i più celebri spicca la _Disputatio rosae cum viola_ (Disputa tra la rosa e la viola). Il _Libro delle tre scritture_ (circa 1274), suddiv

== Poesia popolare e giullaresca

Nel Nord Italia, durante la seconda metà del Duecento, si sviluppò una letteratura in volgare prevalentemente anonima, caratterizzata dalla forma della ballata. Questa produzione letteraria era principalmente opera di cantori girovaghi, conosciuti come "giullari", e si concentrava su canti nuziali, lamenti di giovani donne desiderose di sposarsi e lamenti di mogli insoddisfatte del proprio matrimonio. Da Mantova ci è giunta una canzone anonima per danza, mentre il _Detto di Matazone da Caligano_, proveniente da Milano o Pavia, rappresenta il primo esempio di satira contro il "villano" scritto in volgare. In Veneto prese forma il _Lamento della sposa padovana_, mentre in Emilia e Romagna si diffusero componimenti chiamati sirventesi, poesie popolari di ispirazione morale e satirica. Tra questi si annoverano il _Serventese dei Lambertazzi e dei Geremei_, che narra le faide tra guelfi e ghibellini, e il _Serventese romagnolo_, sempre legato a tematiche politiche e cittadine. In Toscana, il giullare Ruggieri Apugliese, probabilmente senese, lasciò varie opere tra cui una tenzone di argomento politico, una parodia della Passione e un sermone-epitaffio.

== La poesia religiosa

Il più antico componimento in volgare italiano è il _Cantico delle creature_ di San Francesco d'Assisi, scritto in dialetto umbro. Tuttavia, la vera affermazione della lirica religiosa in volgare avvenne nel 1260 con la nascita del movimento dei Disciplinati a Perugia, sotto la guida di Raniero Fasani. Questo gruppo laico utilizzava la flagellazione pubblica come pratica di espiazione, accompagnata da canti corali strutturati secondo lo schema della ballata profana su versi ottonari. Le "laude" furono strumenti fondamentali per la diffusione del movimento in tutta l'Italia settentrionale, svolgendo un'importante funzione di propaganda. La città di Perugia e quella di Assisi divennero i principali centri di produzione dei laudari, dei quali oggi rimangono circa 200 esemplari. Le laude trattavano tematiche liriche e drammatiche, concentrandosi su eventi religiosi pasquali o legati alla Passione. Solo con Iacopone da Todi queste opere acquisirono pienamente una dimensione artistica.

=== Francesco d'Assisi

Francesco d'Assisi (1182-1226), figlio del mercante Pietro Bernardone, ricevette una formazione letteraria discreta, che gli consentì di padroneggiare il latino e le letterature francesi prima di dedicarsi all'attività commerciale. Nel 1202-1203 partecipò al conflitto tra Perugia e Assisi, ma nel 1204, in seguito a una malattia, intraprese un radicale percorso di cambiamento interiore che lo portò a rinunciare a tutti i suoi beni nel 1206 e ad abbracciare la predicazione evangelica insieme ad alcuni seguaci. Fondò un ordine religioso nel 1210, per il quale scrisse in latino la _Regula prima_ nel 1221, successivamente rielaborata nella _Regula secunda_. Questi testi, insieme al _Testamentum_ e alle _Admonitiones_, rappresentano la produzione ufficiale di Francesco in un latino ecclesiastico abbastanza semplice. Tuttavia, l'opera che meglio esprime la sensibilità francescana è il _Cantico di Frate Sole_, noto anche come _Cantico delle creature_ (_Laudes creaturarum_), un componimento ritmico in volgare umbro considerato il più antico testo poetico in lingua italiana. Quest'inno alla creazione riprende temi biblici e liturgici reinterpretandoli attraverso la spiritualità personale del santo. Il testo esalta una concezione positiva della natura come elemento capace di accompagnare l'uomo nel cammino verso la salvezza. La scelta delle parole, spesso semplici e legate tra loro da congiunzioni, tradisce la predilezione di Francesco per immagini visive fortemente evocative, pensate per interagire con l'immaginazione vivace delle persone comuni, indipendentemente dal livello culturale.

=== Iacopone da Todi

Iacopo de' Benedetti (circa 1230/1236-1306), meglio conosciuto come Iacopone da Todi, svolse probabilmente l'attività di notaio e partecipò attivamente alla vita letteraria della sua città. Le sue opere lasciano supporre una certa familiarità con la produzione poetica di Guittone d'Arezzo. Figura di spicco e benestante della comunità tuderte, nel 1268 decise di abbandonare la sua vita precedente, intraprendendo un radicale cambiamento. Secondo la tradizione, tale decisione fu provocata dalla scoperta che la giovane moglie, morta tragicamente sotto un crollo, indossava segretamente un cilicio sotto le sue ricche vesti, segno di penitenza. Iacopone si dedicò per dieci anni a forme di penitenza sempre più rigide e umilianti, finché nel 1278 entrò nell'Ordine francescano come frate laico. Si schierò con il movimento degli "spirituali" e attaccò con fermezza l'opulenza e la corruzione della Chiesa romana.

L'elezione di Pier da Morrone a papa, sotto il nome di Celestino V nel 1294, alimentò in lui nuove speranze; il pontefice infatti approvò l'operato degli spirituali. Tali aspettative trovano espressione nella lauda _Que farai, Pier dal Morrone_. Tuttavia, l'arrivo al soglio pontificio di Bonifacio VIII e la revoca immediata di tale riconoscimento portarono Iacopone ad opporsi apertamente al nuovo papa. Scomunicato, fu imprigionato nel 1298 e costretto a condizioni dure; nonostante ciò, non implorò mai clemenza, ma cercò invano di ottenere la revoca della scomunica attraverso scritti come _O papa Bonifacio eo porto il tuo prefazio_. Solo Benedetto XI, successore di Bonifacio VIII, lo liberò e gli concesse la revoca della scomunica. Ormai debilitato dalla malattia, trascorse gli ultimi anni presso il convento di San Lorenzo a Collazzone, dove morì tre anni dopo.

La produzione poetica di Iacopone, costituita da 93 laude attribuite con certezza e altre di attribuzione incerta, tra cui lo _Stabat Mater_, si distingue per una religiosità fortemente ascetica e ardente. Nei suoi versi è evidente una riflessione continua sulla negatività insita nella vita terrena e nel mondo, visto come uno spazio dominato dalla violenza derivata dal peccato, che si manifesta in un perpetuo processo di distruzione. Questo sguardo porta Iacopone a rappresentare la quotidianità con un realismo spesso crudo e sarcastico. La sua poesia, scritta in un volgare umbro di intensa vitalità, si distingue per il rifiuto delle regole della lingua letteraria standardizzata e per l'influenza del latino ecclesiastico, arricchendosi inoltre di invenzioni linguistiche e lessicali.

L'approccio didattico di Iacopone si traduce nella drammatizzazione stilistica delle laude: questo esperimento porta alla creazione dei "contrasti", composizioni in cui differenti voci si alternano strofa dopo strofa. Molto spesso è la voce divina a cercare di scuotere l'anima dell'uomo dal torpore spirituale e dal legame con i beni materiali. A tale condizione terrena egli contrappone con fervore il mistero dell'incarnazione e della passione di Cristo, percepiti come ribaltamento radicale dei valori fondanti della società umana. Proprio su tali temi Iacopone ha scritto alcuni tra i suoi versi più celebri e intensi, tra cui il _Pianto della Madonna_, che narra i diversi momenti della Passione.

== In sintesi

/ Guittone d'Arezzo:  Considerato il maestro indiscusso della poesia toscana (circa 1230-1294), fu autore di _Rime_, di un _Trattato d'Amore_, di lettere e di ballate-laude a carattere morale e religioso. Nella sua opera poetica introdusse tematiche politiche, mentre nella poesia amorosa si ispirò ai modelli della Scuola Siciliana, privilegiando l'approfondimento intellettuale dell'amore rispetto alla sua rappresentazione attraverso immagini suggestive.

/ La scuola cortese toscana:  Imitatrice dello stile guittoniano, questa scuola si distingue per la presenza di diversi poeti, fra cui Bonaggiunta Orbicciani di Lucca (circa 1220 - circa 1290), il fiorentino Chiaro Davanzati, precursore dello stilnovo, e Dante da Maiano, noto per una tenzone con Dante Alighieri all'interno del suo canzoniere.

/ La poesia comico-realista:  A partire dalla metà del Duecento si diffonde una poesia dal tono giocoso e realista, dove invettive, sarcasmo, ribellione e comicità diventano dominanti. Tra i principali esponenti spiccano Folgore da San Gimignano (circa 1270 - circa 1330), autore di due "corone" (_Sonetti de la semana_ e _Sonetti de' mesi_), e il senese Cecco Angiolieri (circa 1260 - prima del 1313), che nei suoi 112 sonetti parodiò con raffinata abilità molti generi trobadorici. Temi chiave delle sue opere sono la donna, la taverna e il gioco d'azzardo.

/ La poesia dell'Italia settentrionale:  La letteratura volgare del Nord Italia fu prevalentemente didattica e si ispirò sia alla tradizione provenzale sia a quella scritturale-apocalittica, legata alla letteratura escatologica tra XII e XIII secolo. Il principale rappresentante fu Bonvesin de la Riva, milanese (circa 1240 - circa 1315), autore di poemetti in volgare, di opere tradotte e del _Libro delle tre scritture_ (circa 1274), una delle sue opere più note. Diviso in tre parti (_scrittura nigra_, rubra e aurea), affronta rispettivamente i temi dell'Inferno, della Passione di Cristo e del Paradiso, anticipando in qualche modo la visione dantesca.

/ La poesia religiosa: 

 / San Francesco:  _Il Cantico delle creature_, scritto probabilmente nel 1225 da san Francesco d'Assisi (1182-1226), fondatore dell'ordine francescano e redattore della _Regula_ in latino, rappresenta uno dei testi più elevati della lirica religiosa medievale. Dal 1260 si svilupparono i laudari lirici e drammatici, con temi pasquali e passionali.

 / Iacopone da Todi:  Figura centrale della poesia religiosa medievale, Iacopone da Todi (tra il 1230 e il 1236 - 1306) fu un ricco cittadino che abbracciò nel 1278 la vita francescana come frate laico. Dotato di alti ideali spirituali, si oppose con vigore a papa Bonifacio VIII, venendo scomunicato e imprigionato. La sua produzione comprende 93 laude profondamente drammatiche ed espressive, in cui coesistono elementi concreti e tensione spirituale. La sua opera rappresenta quasi un'autobiografia dell'anima.





