#import "../../../template_tufte.typ": *
#show: frame-style(styles.thmbox)

#evidenzia[Per quanto riguarda la poesia rinascimentale, possiamo riconoscere in Ariosto la voce più eminente, mentre per la prosa il punto culminante fu raggiunto da Machiavelli e Guicciardini. Nel _Principe_, Machiavelli espone la teoria dello Stato moderno e traccia il ritratto dell'uomo "prudente e virtuoso". Guicciardini, impegnato attivamente nella vita politica durante anni cruciali per la storia italiana, si afferma come storiografo lucido e scettico. Mentre la storiografia umanistica aveva cercato nel passato insegnamenti virtuosi per il presente, quella del primo Cinquecento cambia prospettiva: gli storici sviluppano una concezione drammatica e dinamica della storia.]

== Niccolò Machiavelli

Acuto osservatore della realtà storica del suo tempo e uno dei più grandi prosatori italiani, Machiavelli fu il teorico di una politica strettamente razionale, considerata l'unica risposta possibile all'egoismo umano.  

=== La vita e le opere

Nato a Firenze nel 1469, fu educato secondo principi umanistici nel periodo in cui la città, sotto Lorenzo de' Medici, viveva il suo massimo splendore culturale e politico. Dopo la caduta di Savonarola nel 1498, Machiavelli iniziò la sua carriera politica che lo portò a ricoprire vari incarichi diplomatici. Questi ruoli gli permisero di raccogliere preziose osservazioni annotate nei suoi scritti. Nel 1500 fu inviato presso Caterina Sforza, contessa di Forlì; nel 1501 si recò in Francia; tra il 1502 e il 1503 incontrò più volte Cesare Borgia, signore delle Marche e della Romagna, esperienze che ispirarono il trattato _Descrizione del modo tenuto dal duca Valentino nello ammazzare Vittellozzo Vitelli, Oliverotto da Fermo, il signor Pagolo e il duca di Gravina Orsini_ (1503).  

Nel 1503 Machiavelli fu inviato a Roma per seguire il conclave e nel 1504 tornò in Francia presso Luigi XII. Durante questi anni il suo ruolo politico acquisì maggiore importanza: scrisse il _Del modo di trattare i popoli della Valdichiana ribellati_ (1503) e fu incaricato (1505-09) di organizzare la milizia della Repubblica fiorentina. L'attività diplomatica proseguì ininterrottamente: nel 1506 seguì le campagne militari di papa Giulio II e tra il 1507-08 fu inviato presso l'imperatore Massimiliano, esperienza che portò alla stesura del _Rapporto di cose della Magna_ (1508), poi rielaborato nel _Ritratto delle cose della Magna_ (1512).  

Nel 1510 Machiavelli effettuò un altro viaggio in Francia, da cui scaturì il _Ritratto di cose di Francia_ (1510), un'analisi approfondita delle dinamiche politiche del regno francese. Nel 1512 l'equilibrio tra Francia e Spagna si spezzò; a Firenze, la Repubblica filo-francese fu costretta a cedere il potere ai Medici, sostenuti dalla Spagna. Machiavelli fu destituito da ogni incarico e condannato al confino per un anno. Nel 1513, accusato di aver partecipato a una congiura contro i Medici, fu imprigionato, torturato e nuovamente esiliato.  

Graziato con l'elezione di Leone X, papa Medici, si ritirò nella proprietà dell'Albergaccio vicino a San Casciano in Val di Pesa. In quest'isolamento nascquero i suoi capolavori: il trattato _Il Principe_ (1513-14), i _Discorsi sopra la prima deca di Tito Livio_ (1515-17), dedicati a questioni storiche e politiche, _L'arte della guerra_ (1521) e la biografia _Vita di Castruccio Castracani_ (1520).  

Machiavelli si cimentò anche nella letteratura creativa: compose il _Decennale primo_ e _Decennale secondo_ (1504-06 e 1516), poemi in terzine dantesche che narrano le vicende tumultuose dell'Italia; il _Discorso o dialogo intorno alla nostra lingua_ (1515-16), un'esaltazione del dialetto fiorentino; il poemetto satirico _L'Asino_ (1518), impregnato di temi filosofici; e la favola _Belfagor arcidiavolo_, o _Il demonio che prese moglie_ (circa 1518). Fra queste opere spicca la commedia _La mandragola_ (1518), rappresentata durante una festa medicea, che segnò un parziale riavvicinamento tra lo scrittore e i signori della città.  

Nel 1525, Machiavelli mise in scena a Firenze la commedia _Clizia_, una storia grottesca di amore senile, e concluse le _Istorie fiorentine_, pubblicate nello stesso anno. Poco dopo ottenne la revoca dell'interdizione dai pubblici uffici. Nel contesto della nuova guerra della Lega, formata da papato, Francia e Firenze contro Carlo V, fu coinvolto in attività diplomatiche e militari. Tuttavia, la Lega fu sconfitta nel 1527 con il sacco di Roma; i Medici furono cacciati e a Firenze venne restaurata la repubblica guidata da elementi savonaroliani, che consideravano Machiavelli con sospetto e avversione. Morì nel giugno dello stesso anno.

Durante la Controriforma, le opere di Machiavelli furono considerate scandalose e prive di valenza morale. Nel 1559 tutte le sue opere furono incluse nell'Indice dei libri proibiti.

=== _Il Principe_

_Il Principe_ è senza dubbio l'opera più celebre e rivoluzionaria di Machiavelli, scritta tra luglio e dicembre del 1513. Definito dallo stesso autore come un breve "ghiribizzo" composto da 26 capitoli, il testo raccoglie la riflessione politica e filosofica maturata in quindici anni al servizio dello Stato. Nella prima parte dell'opera, Machiavelli analizza i diversi tipi di principato (ereditari, nuovi, misti) e il modo in cui possono essere conquistati.

L'autore introduce anche alcune figure di fondatori di Stati, come Mosè, Ciro, Teseo e Romolo, oltre a riformatori come Girolamo Savonarola, su cui esprime il severo giudizio di "profeta disarmato". Tuttavia, il focus principale (capitolo VII) si concentra sull'azione del duca Valentino, Cesare Borgia, presentato come esempio ideale di "uomo prudente e virtuoso". Borgia viene celebrato per la sua capacità di mettere in atto un piano ambizioso volto alla creazione di uno Stato stabile nell'Italia centrale, sfruttando strumenti efficaci per indebolire i nemici, gestire gli alleati potenti senza perderne il controllo, trarre vantaggio dalle circostanze favorevoli e assicurarsi la fiducia del popolo e della nobiltà.

Machiavelli sottolinea inoltre la cruciale importanza per un principe di disporre di un esercito proprio piuttosto che affidarsi a truppe mercenarie. 

Nella seconda parte dell'opera viene completamente ribaltata l'idea tradizionale di teoria politica, che fin allora era orientata verso modelli ideali di organizzazione statale e comportamento dei governanti. Per Machiavelli, il cuore della politica sta nella ricerca del beneficio concreto per lo Stato (che coincide con l'interesse del principe e dei sudditi) e il terreno d'indagine deve basarsi sulla "verità effettuale della cosa", piuttosto che su una sua immaginazione utopica. Questo comporta un capovolgimento radicale del rapporto tra politica e morale: il valore degli atti del principe non viene valutato secondo norme astratte, ma in funzione della loro efficacia nel garantire la sicurezza dello Stato.

Famosa è la concezione della fortuna elaborata da Machiavelli, intesa come l'instabile sintesi delle forze variegate e imprevedibili che si manifestano nel corso della storia. In tale contesto, la virtù del principe deve confrontarsi con questa antagonista mutevole, prevalendo solo mediante la capacità di prevederne gli sviluppi, contrastarne i capricci e dominarla con audacia equilibrata. Machiavelli conclude il suo celebre scritto con un appello appassionato a un membro della dinastia medicea affinché raccolga l'aspirazione comune degli italiani di combattere e superare il "barbaro dominio" imposto dalle potenze straniere.

Ne "Il Principe", egli pone le basi di una nuova concezione della politica, individuando in essa il campo in cui la virtù individuale può trovare realizzazione. Questa virtù si configura come la capacità di affrontare gli eventi razionalmente, mirando a creare un sistema di convivenza tra gli uomini in cui l'interesse individuale si integri e venga riconosciuto nell'interesse collettivo.

=== I _Discorsi_ e la _Mandrangola_

Nel corpus dei "Discorsi" e nella "Mandragola", l'attenzione si sposta verso il nucleo del pensiero machiavelliano: lo studio della formazione e della conservazione dello Stato. Nei "Discorsi sopra la prima deca di Tito Livio", Machiavelli approfondisce temi quali la necessità del consenso dei cittadini, l'equilibrio tra gli interessi delle diverse classi sociali, e l'importanza di un esercito composto da cittadini, non solo per scopi militari ma anche politici. Inoltre, egli sostiene l'uso della religione come strumento di coesione all'interno dello Stato.

Esaminando la storia romana, parallela a quella fiorentina nelle "Istorie fiorentine" caratterizzate dallo stile oratorio della storiografia classica, Machiavelli evidenzia come anche le istituzioni più solide siano vulnerabili alla corruzione, agli errori e all'incostanza degli individui. La sua visione pessimistica riguardo alla natura umana rappresenta una costante nel suo pensiero, accentuatasi durante gli anni di inattività politica. Questo pessimismo trova un'espressione letteraria nella commedia "La Mandragola", dove un tema apparentemente basso e comico, ossia l'inganno finalizzato alla conquista di una donna, svela l'incapacità degli individui di trascendere il proprio tornaconto personale. La figura di Lucrezia, protagonista femminile della commedia, incarna probabilmente l'ideale machiavelliano: pur vittima di intrighi e meschinità, ella riesce a sfruttare l'opportunità offerta dalla fortuna per divenire artefice del proprio destino.

=== Il dibattito su Machiavelli

Il dibattito intorno al pensiero di Machiavelli ha assunto sfumature diverse attraverso i secoli. In ambito gesuitico fu sintetizzata la sua filosofia con l'espressione divenuta proverbiale "il fine giustifica i mezzi", mai direttamente presente nei suoi scritti. L'aggettivo "machiavellico" si diffuse in Europa con il significato negativo di astuto e privo di scrupoli, mantenendo tale accezione nel tempo. Nel Settecento, Machiavelli fu al contempo interpretato come teorico dell'assolutismo e come fervente repubblicano che, attraverso "Il Principe", avrebbe fornito ai popoli strumenti per ribellarsi ai tiranni. Durante il Risorgimento italiano, pur criticato per l'apparente amorale delle sue tesi, fu celebrato come profeta dell'unità nazionale.

Nel XX secolo, il suo pensiero è stato da un lato contestualizzato nel panorama storico del suo tempo, dall'altro impiegato come stimolo per riflessioni sull'attualità politica. In realtà, Machiavelli pone le basi per la politica intesa come disciplina autonoma, delineando il rapporto tra fini e mezzi nella prospettiva secondo cui le predicazioni morali sono estranee alla sua logica. Nessun fine, per quanto moralmente elevato, può essere raggiunto senza strumenti adeguati e coerenti con la situazione concreta.

== Francesco Guicciardini

Francesco Guicciardini (1483-1540) occupò una posizione di rilievo nella scena politica italiana durante le guerre che videro Francia e Spagna contendersi il dominio della penisola, distinguendosi anche come acuto interprete storiografico di quei tumultuosi eventi.

=== La vita e le opere

Appartenente a una delle più prestigiose famiglie fiorentine, Guicciardini ricevette una solida formazione umanistica che avrebbe influenzato profondamente il suo pensiero e le sue opere. Nel 1512 interruppe la redazione delle _Storie fiorentine_ per intraprendere un incarico diplomatico che lo portò alla corte spagnola, dove rimase fino al 1514. Questo periodo fu particolarmente produttivo: scrisse il _Discorso di Logrogno_ (1512), un progetto di riforma politica dello stato fiorentino, cui seguirono il _Discorso del governo di Firenze dopo la restaurazione dei Medici_ e un diario di viaggio che documentava le sue esperienze.

Rientrato in Italia, grazie ai buoni rapporti instaurati con i Medici, tornati nel frattempo al potere, ottenne nel 1516 l'incarico di governatore di Modena da papa Leone X. Successivamente ampliò la sua attività amministrativa governando anche Reggio Emilia e la Romagna. Durante questi anni maturò ulteriormente il suo pensiero politico, che trovò espressione nel _Dialogo del reggimento di Firenze_ (1525). Svolse inoltre un ruolo cruciale nella promozione dell'alleanza antimperiale tra Papato e Francia (lega di Cognac), ricoprendo l'importante carica di luogotenente generale della Chiesa. Tuttavia, il sacco di Roma del 1527 segnò un periodo di declino, culminato con la sua destituzione da tutte le cariche.

Guicciardini tornò quindi a Firenze, dove i Medici erano stati nuovamente esiliati. Si dedicò intensamente all'attività letteraria, arricchendo il proprio corpus con opere significative come i _Ricordi_ (1528), le _Cose fiorentine_ (1528-31) e le _Considerazioni sopra i Discorsi del Machiavelli_ (1528), documento fondamentale per comprendere la sua visione della politica. Tuttavia, le sue simpatie medicee lo portarono a essere bandito dalla città; ciò lo costrinse dapprima a ritirarsi nella proprietà di Finocchieto e successivamente a cercare protezione presso papa Clemente VII in Romagna.

Il ritorno alla collaborazione con il pontefice seguì alla caduta della Repubblica fiorentina nel 1530. In questo nuovo contesto, Guicciardini fu reintegrato ricevendo incarichi prestigiosi: nel 1531 divenne governatore di Bologna e nel 1533 accompagnò Clemente VII in un viaggio a Marsiglia per incontrare il re di Francia. Parallelamente, contribuì all'organizzazione del potere mediceo a Firenze, pur venendo gradualmente escluso dalle decisioni politiche. Da questo momento in poi preferì ritirarsi nelle sue proprietà, dedicandosi sempre più alla letteratura. Fu qui che intraprese la stesura della sua opera maggiore, la _Storia d'Italia_, iniziata nel 1536 ma rimasta incompiuta al momento della sua morte nella villa di Montici.

=== I _Ricordi_

Nessuna delle opere di Guicciardini venne pubblicata durante la sua vita: tra queste, più di duecento pensieri e aforismi rimasero custoditi tra le carte di famiglia, venendo poi pubblicati nel 1576 con il titolo _Avvertimenti_ e successivamente nell'Ottocento come _Ricordi_. La composizione di queste brevi riflessioni si estese lungo tutto l'arco della vita dello scrittore, dagli anni giovanili (la prima serie di pensieri risale addirittura al periodo spagnolo) fino al 1530. Guicciardini analizza la "ruina d'Italia" con grande lucidità, evitando qualsiasi appiglio a modelli o teorie precostituite: non cerca né accetta spiegazioni universali o chiavi interpretative della realtà politica.

L'autore ritiene, in linea generale, che i rapporti umani siano segnati da una negatività difficilmente modificabile e che, di conseguenza, gli esiti delle azioni politiche dipendano più da mutamenti superficiali che da interventi miranti a incidere sui meccanismi profondi del processo storico. Su questi dettagli deve concentrarsi "il buon occhio del saggio", esercitando la "discrezione", intesa quale capacità di interpretare e orientarsi tra le infinite variazioni che si presentano a chi è chiamato a dirigere la cosa pubblica.

In tale contesto l'obiettivo primario è il "particulare", che si articola su due fronti: da un lato quello personale, legato al "decoro" ovvero alla tutela della reputazione e dell'onore sia individuale che famigliare; dall'altro quello politico, volto a raggiungere il miglior equilibrio possibile tra le forze contrastanti e spesso violente della realtà. Il "particulare", quindi, non rappresenta una semplice strategia per perseguire interessi egoistici (come erroneamente interpretato in passato), bensì la salvaguardia della propria dignità in tempi difficili, quando risulta impossibile realizzare grandi ideali collettivi.

=== La _Storia d'Italia_

La concezione del comportamento umano proposta da Guicciardini è il riflesso di una profonda sconfitta, non solo politica o militare, ma di un'intera civiltà. La sua _Storia d'Italia_ (composta da 20 libri) venne pubblicata con numerosi interventi censori a Firenze nel 1561 e in forma più completa a Venezia nel 1564. L'opera copre un arco temporale limitato: dal 1492 (anno della morte di Lorenzo il Magnifico) al 1534 (anno della morte di Clemente VII, ultimo papa della famiglia Medici).

Durante questo periodo si passò dalla prosperità e dall'equilibrio del tardo Quattrocento alla rovina totale, dolorosamente rappresentata dal sacco di Roma del 1527 ad opera delle truppe imperiali. Questo drammatico evento è descritto da Guicciardini in pagine di straordinario valore letterario. Secondo lo storico, i principali artefici di tale disastro furono Ludovico il Moro e papa Alessandro VI: spinti da un bramoso desiderio di potere, entrambi aprirono le porte degli stati italiani agli eserciti stranieri.

In senso più ampio, la narrazione mette in luce un percorso segnato da violenze, arroganza e incapacità dei principi italiani, i quali si illusero di poter manipolare forze ben più potenti per soddisfare i loro interessi dinastici o territoriali. Da questi avvenimenti Guicciardini deduce che i tradizionali ragionamenti campanilistici non sono più adeguati, poiché le cause della rovina di ciascuno stato italiano sono strettamente legate alla crisi dell'intero sistema politico.

Lo studio del passato stimola dunque una riflessione orientata al futuro: secondo Guicciardini, l'identità storico-culturale dell'Italia necessiterebbe di concretizzarsi in un organismo unitario da concepire in forma federale. Tuttavia, egli non nutriva illusioni sulla possibilità di realizzare tale progetto in tempi brevi: il suo radicale pessimismo lo portava a percepire l'inevitabile contrasto tra le teorizzazioni razionali e la dura resistenza offerta dalla realtà.

La _Storia d'Italia_, unica opera concepita da Guicciardini per la pubblicazione, è scritta in una lingua di grande eleganza formale, influenzata anche dal confronto con le _Prose della volgar lingua_ di Pietro Bembo.

== In sintesi

/ Niccolò Machiavelli: Nato a Firenze nel 1469, Niccolò Machiavelli (1469-1527) fu un importante uomo politico e diplomatico del Rinascimento. Tra le sue opere principali figurano _Il Principe_ (1513-14), i _Discorsi sopra la prima deca di Tito Livio_ (1515-17), i dialoghi _De re militari_ (1521), la _Vita di Castruccio Castracani_ (1520) e la commedia _La Mandragola_ (1518). Il nucleo del pensiero machiavelliano è la definizione dell'utile per lo Stato, inteso come utilità comune del principe e dei sudditi. La politica, secondo Machiavelli, deve basarsi sulla “verità effettuale della cosa” e non sull'immaginazione. La creazione e conservazione dello Stato rappresentano il fulcro della sua riflessione, fondata su una visione razionale e autonoma della politica, capace di affrontare le sfide della fortuna tramite fini e mezzi coerenti.

/ Francesco Guicciardini: Francesco Guicciardini (1483-1540) fu una figura politica di spicco durante il periodo delle guerre tra Spagna e Francia. Tra i suoi lavori più significativi si annoverano i _Ricordi_, centrati sulla riflessione politica: per Guicciardini, il buon politico deve possedere “il buon occhio del saggio”, che gli consente di esercitare la “discrezione” nel comprendere le complessità della realtà, perseguendo il proprio “particulare”, ovvero il proprio onore e dignità in un periodo privo di aspirazioni collettive. Nella sua _Storia d'Italia_ (1492-1534), egli analizza le vicende storiche italiane arrivando alla convinzione che le difficoltà dei singoli stati italiani derivino dalla crisi dell'intero sistema politico. La sua riflessione storica anticipa la necessità di un'identità nazionale italiana, immaginata come un organismo unitario di tipo federale.

