#import "../../../template/_global/template.typ": *
#import "../../../template/_global/config.typ": *

#intro[La cultura umanistica trova la sua essenza nella riscoperta dei testi classici latini e greci e nella riaffermazione dell'autonomia dei valori culturali dell'antichità. Il rigoroso lavoro filologico proprio di quest'epoca alimenta un acuto spirito critico: da un lato si esercita nell'analisi della tradizione scolastica medievale, dall'altro promuove l'integrazione dei doveri politici nella sfera culturale. L'umanesimo valorizza l'importanza dell'uomo come agente attivo nel mondo, ponendolo in contrasto con la visione prevalentemente contemplativa del divino e del soprannaturale tipica del Medioevo.]

== Il preumanesimo

L'umanesimo trae origine dall'espressione _studia humanitatis_ (gli studi legati all'umanità), che nell'antichità classica indicava un percorso educativo volto a formare l'individuo in maniera completa attraverso gli studi letterari e filosofici. Nel corso del Medioevo, la cultura dell'antica Roma, pur sempre oggetto di grande ammirazione, era stata assimilata e subordinata a quella cristiana. Tuttavia, già agli inizi del Trecento, un gruppo di intellettuali, per lo più provenienti dall'ambiente universitario di Padova, sviluppò un interesse nuovo e più focalizzato verso l'epoca classica.

Un contributo fondamentale alla crescita degli studi umanistici venne da Francesco Petrarca, non solo attraverso le sue opere latine – tra cui spiccano il _De viris illustribus_ e l'_Africa_ – ma anche mediante la sua attività di scopritore di testi antichi perduti (tra cui l'orazione _Pro Archia_ e le lettere di Cicerone) e il suo lavoro filologico. Grazie al prestigio culturale acquisito, Petrarca ebbe un ruolo cruciale nell'affermazione della nuova cultura. A rafforzarne la diffusione fu anche Giovanni Boccaccio, che introdusse a Firenze lo studio del greco e contribuì alla formazione di giovani intellettuali toscani.

#note(bottom)[== *🧩* Lo sviluppo degli studi greci <senza_numero>

Lo sviluppo degli studi greci nel Quattrocento conosce una significativa rinascita culturale. La cultura greca, infatti, rappresenta in questo periodo un'apertura verso un platonismo inquieto, in netto contrasto con la teologia medievale. Un ruolo fondamentale viene svolto da Coluccio Salutati, che favorisce l'arrivo a Firenze di maestri greci: tra questi, il bizantino Manuele Crisolora, giunto nel 1396 allo Studio fiorentino per insegnare la lingua greca. Durante questa fase, grande impulso viene dato alla traduzione di testi classici, tra cui Platone e Plutarco, ma anche Omero e i tragici. L'influenza di Crisolora si estende anche alla Lombardia, lasciando un'impronta culturale duratura. 

Oltre all'opera di Crisolora, vi sono due eventi storici fondamentali per la rinascita degli studi greci: il Concilio di Ferrara-Firenze, che favorì un temporaneo avvicinamento tra la Chiesa cattolica e quella ortodossa (1438-1443), e l'arrivo di nuovi maestri greci dopo la caduta di Costantinopoli ad opera dei turchi nel 1453. Tra le figure di spicco si distingue Giorgio di Trebisonda (1395-1486), che criticò le traduzioni umanistiche, accusandole di alterare i concetti e la struttura originale dei testi in nome dell'eleganza formale. Un altro protagonista rilevante è Giorgio Gemisto (1360-1450), noto con lo pseudonimo Pletone, il quale diede vita al neoplatonismo fiorentino. Questo movimento recuperò elementi della filosofia gnostica ed ermetica, quali gli Oracoli caldaici, Zoroastro ed Ermete Trismegisto, oltre al pensiero platonico e neoplatonico, da Platone a Plotino e Proclo. Tale tradizione filosofica trovò la sua massima espressione nelle opere di Marsilio Ficino.

Un'altra figura centrale fu il cardinale Bessarione (1403-1472). Oltre al suo impegno nel promuovere l'unione tra le due Chiese, egli raccolse una straordinaria biblioteca di autori greci, un patrimonio fondamentale per la diffusione della cultura ellenica in Occidente.]

=== L'umanesimo civile di Salutati

Una delle prime figure di spicco dell'umanesimo fu Coluccio Salutati (1331-1406), cancelliere di Firenze per oltre trent'anni e convinto sostenitore del valore civile della cultura classica. Salutati scrisse vari trattati, fra cui: _De saeculo et religione_ (_Il mondo e la religione_, 1381), _De fato, fortuna et casu_ (_Il fato, la fortuna e il caso_, 1396-99), _De nobilitate legum et medicinae_ (_La nobiltà delle leggi e della medicina,_, 1399) e _De tyranno_ (_Il tiranno_, 1400), quest'ultimo incentrato sull'esaltazione dell'impegno civile contrapposto all'ascetismo. Il suo epistolario merita particolare attenzione, poiché testimonia la vasta rete di relazioni e interessi che legavano Salutati ai suoi contemporanei.

== L'umanesimo filologico e filosofico

L'interesse verso i classici diede avvio a una ricerca intensa che portò al recupero di molte opere antiche dimenticate o perdute durante il Medioevo. Questi ritrovamenti permisero di approfondire la conoscenza della lingua latina, che nella prima metà del Quattrocento tornò a essere la lingua principale per la letteratura. Inoltre, tali scoperte evidenziarono la netta differenza tra il latino classico e quello medievale, mettendo in luce le condizioni spesso deteriorate nelle quali erano giunti molti testi antichi.

Di conseguenza, si affermò la necessità di elaborare strumenti e metodi per restituire correttezza e integrità ai manoscritti ritrovati. Da questa esigenza nacque la filologia umanistica, disciplina guidata dall'attenzione agli aspetti storici e letterari e dalla sensibilità del filologo, esperto conoscitore dei testi classici. Tra i principali protagonisti della prima generazione di umanisti filologi emersero Leonardo Bruni e Poggio Bracciolini.

Leonardo Bruni (1370-1444) studiò a Firenze sotto la guida di Coluccio Salutati, formandosi in un ambiente culturale influenzato dal neoplatonismo. Ebbe rapporti con figure quali Niccolò Niccoli, Poggio Bracciolini e Cosimo de' Medici. La sua opera di traduzione dal greco fu particolarmente significativa e si estese per gran parte della sua vita: tradusse opere di Platone (_Fedone_, _Gorgia_, _Apologia_, _Critone_, _Simposio_), Aristotele (_Etica Nicomachea_), Plutarco, Senofonte, san Basilio, Omero e Demostene. Nel 1405, grazie all'intercessione di Salutati, divenne funzionario presso la corte papale di Innocenzo VII.

Tornato a Firenze nel 1427, Coluccio Salutati concluse la sua illustre carriera quale cancelliere della Repubblica Fiorentina. La sua opera più significativa è costituita dalle _Historiae Florentini populi_, iniziata nel 1414 e completata con il _Rerum suo tempore in Italia gestarum commentarius_ (_Commentari sugli avvenimenti del suo tempo in Italia_, 1440). Un momento cruciale del suo contributo alla letteratura è rappresentato dalle _Vite di Dante e Petrarca_ (1436), attraverso cui riconobbe sia l'importanza del volgare come lingua letteraria, sia il ruolo pionieristico di Petrarca nell'apertura della stagione umanistica.

Di particolare interesse è anche la produzione di Francesco Filelfo (1398-1481), rimarchevole per la sua varietà e quantità. Nel 1427, il Comune di Firenze gli attribuì l'incarico di commentare pubblicamente la _Commedia_ dantesca. Tuttavia, Filelfo fu costretto a interrompere il lavoro al canto VII dell'Inferno e a lasciare la città a causa del suo atteggiamento ostile verso i Medici. Rientrato a Firenze nel 1469, ricevette nel 1481 la cattedra di greco, morendo quindici giorni dopo la nomina. Tra le sue opere più celebri si annoverano le _Satyrae_ (1448), le _Odae_ (1498, pubblicazione postuma) e i _Convivia mediolanensia_ (1449).

Importante è anche il contributo di Flavio Biondo (1392-1463), che visse tra Forlì, sua città natale, e Bergamo, lavorando dal 1434 presso la Curia romana. La sua opera più nota, le _Historiarum ab inclinatione Romanorum decades_ (1439), riflette un approccio innovativo allo studio storico, evidenziando la necessità di analizzare la storia come fenomeno multidimensionale caratterizzato da elementi linguistici, civili e culturali.

Un altro protagonista della tradizione umanistica è Vittorino da Feltre (1373-1446), fondatore della celebre scuola "Ca' Zoiosa" a Mantova. Pur non avendo lasciato opere scritte, Vittorino fu un educatore d'eccezione, elevato a simbolo della pedagogia umanistica. La sua figura è oggetto di numerosi ritratti realizzati da illustri umanisti dell'epoca, perpetuando il suo mito come maestro ideale.

=== Poggio Bracciolini

Anche Poggio Bracciolini (1380-1459) si affermò come un esponente rilevante dell'umanesimo. Formatosi a Firenze sotto la guida di Salutati, partì nel 1403 per Roma, dove svolse l'incarico di segretario apostolico e partecipò al Concilio di Costanza (1414-1418) al fianco dell'antipapa Giovanni XXIII. I suoi frequenti viaggi in Francia, Svizzera e Germania lo portarono alla scoperta di importanti manoscritti antichi presso biblioteche monastiche, recuperando opere fondamentali come numerose orazioni di Cicerone, le _Institutiones oratoriae_ di Quintiliano e il _De rerum natura_ di Lucrezio. Dal 1418 al 1422 risiedette in Inghilterra, tornando poi a Roma fino al 1453.

Tra i suoi numerosi trattati in forma dialogica spicca il _De infelicitate principum_ (_L'infelicità dei principi_, 1440), noto per il suo tono fortemente pessimistico. La sua ultima grande opera storica fu la _Historia Florentina_ (1454-1459), che narra con erudizione gli eventi occorsi a Firenze dalla prima guerra contro Giovanni Visconti (1350) fino alla pace di Lodi (1455). Contrario all'uso letterario del volgare, Bracciolini privilegiò esclusivamente il latino nell'elaborazione delle proprie opere, incluse le _Facezie_ (_Liber facetiarum_, _Libro delle facezie_), una raccolta di aneddoti e novelle brevi composte tra il 1438 e il 1452. In queste narrazioni, sostenute da un motto arguto, si celebra la nuova civiltà umanistica ponendo al centro valori morali quali abilità, cultura e impegno dell'uomo civile consapevole dei propri diritti.

=== Leon Battista Alberti

Leon Battista Alberti (1404-1472), insigne architetto, letterato, matematico e teorico delle arti visive, rappresenta una delle figure più poliedriche e emblematiche dell'Umanesimo italiano, accanto a Leonardo da Vinci. Tra le sue opere architettoniche spiccano la facciata di Santa Maria Novella a Firenze e il Tempio Malatestiano di Rimini. Il suo principale contributo letterario è il trattato in quattro libri _Della famiglia_ (1433-1441), considerato un vero capolavoro.

Quest'opera, scritta in forma dialogica e ambientata a Padova presso il letto del padre morente, affronta temi fondamentali come la felicità, l'educazione, il matrimonio e la gestione delle proprietà domestiche. Per Alberti, il tempo, inteso anche come risorsa da ottimizzare economicamente, e la famiglia, nucleo essenziale della società, rappresentano le basi per raggiungere la perfezione della vita. Nel proemio del terzo libro, Alberti sottolinea l'eccellenza ormai raggiunta dal volgare, al punto da poter competere con il prestigioso latino.

Il modello educativo delineato nel trattato si richiama all'ideale umanistico di "rinascita", espressione di un uomo posto al centro dell'universo e impegnato nella propria costruzione personale attraverso esperienza diretta, intelletto e rielaborazione culturale del sapere. Tra il 1440 Alberti compose gli _Intercoenales_, brevi dialoghi satirici in latino ispirati a Luciano e dedicati a una varietà di temi morali. 

Del 1437, invece, sono i cento aforismi o apologhi latini di carattere filosofico, mentre il _Momus_, satira latina composta prima del 1450, indaga il potere politico denunciandone le ingiustizie. La _Grammatichetta vaticana_ segna un passo fondamentale verso la valorizzazione del volgare come lingua letteraria. Inoltre, nei sonetti scambiati con Burchiello e nelle _Rime_ — tra cui spiccano frottole, egloghe ed elegie — l'autore si distingue nella poesia in volgare. Infine, con ogni probabilità Alberti inaugurò l'egloga volgare quattrocentesca con l'opera _Tirsis_.

Di particolare importanza sono i trattati sull'arte di Alberti: _Sulla pittura_ (1436) e _De re aedificatoria_ (_Dell'architettura_, 1443-1445). Al centro di entrambe le opere si trova il concetto di "misura", principio attraverso cui l'uomo definisce con chiarezza la simmetria e le proporzioni tra sé e la natura. Questo approccio non solo permette una progettazione capace di promuovere una convivenza civile basata sull'equilibrio, sia interiore che esteriore, ma riflette anche l'imitazione dell'armonia insita nella creazione divina.

== La lezione umanistica di Lorenzo Valla e di Enea Silvio Piccolomini

Lorenzo Valla ed Enea Silvio Piccolomini sono altre due figure notevoli dell'Umanesimo italiano. Valla, con il suo approccio filologico rigoroso, mise in discussione i fondamenti documentari del potere temporale dei papi. Piccolomini, invece, fu non solo un letterato di vastissima cultura ma anche un grande papa mecenate sotto il nome di Pio II.

=== Lorenzo Valla

Proveniente da una famiglia romana di funzionari curiali, Lorenzo Valla (1407-1457) ricevette una solida formazione umanistica sotto la guida di G. Aurispa e Rinuccio da Castiglion Fiorentino. Nel 1430 ottenne la cattedra di retorica presso l'Università di Pavia, dove avanzò con rigore metodologico nella ricerca filologica. Tuttavia, nel 1433, entrando in aperto contrasto con la scuola dei glossatori dell'ateneo, pubblicò un libello in favore di una moderna scienza giuridica. Tale polemica lo costrinse a lasciare Pavia, trovando rifugio prima a Milano e successivamente a Firenze.

Nel 1435 Valla si trasferì presso la corte del re d'Aragona e di Sicilia, Alfonso V; più tardi, nel 1448, fece ritorno a Roma assumendo l'incarico di segretario apostolico sotto il pontificato di papa Niccolò V. Le sue opere si distinguono principalmente per l'uso della filologia come mezzo privilegiato di indagine e per il rifiuto di ogni principio d'autorità accettato acriticamente, promuovendo sempre la libertà di ricerca.

Tra i suoi scritti più rilevanti si annoverano i dialoghi _De vero falsoque bono_ (edizione definitiva del 1431), _De libero arbitrio_ (1439) e _De professione religiosorum_ (_(I voti dei religiosi_, 1439), che mirano a ripristinare il senso del vero bene, della libertà autentica e dell'ideale evangelico genuino oscurati dalla speculazione filosofica. Inoltre, con le _Dialecticae disputationes_ (1439), egli tentò di semplificare il linguaggio filosofico del suo tempo, sgomberandolo dalla complessità della logica aristotelica imperante.

Un'opera particolarmente famosa è il _De falso credita et ementita Constantini donatione_ (_Della falsamente creduta e inventata donazione di Costantino_, 1440), in cui dimostrò, attraverso un'analisi filologica rigorosa, la falsità della cosiddetta _Donazione di Costantino_, un documento che legittimava il potere temporale della Chiesa su basi storicamente infondate. Tale lavoro fu composto per sostenere Alfonso d'Aragona nella disputa con Roma relativa all'investitura del Regno di Napoli.

Su specifica richiesta di Alfonso V, Valla redasse anche gli _Historiarum Ferdinandi regis Aragoniae libri tres_ (1445-47), un'opera storiografica ricca di dettagli informativi e caratterizzata da uno stile narrativo vivace. Convinto che il progresso umano e civile dipendesse dalla trasparenza e dall'univocità nella comunicazione, dedicò il suo capolavoro, le _Elegantiae linguae latinae_ (pubblicate nel 1444 ma avviate già nel 1435), alla valorizzazione della lingua latina. Attraverso uno studio filologico esemplare, l'opera rappresenta una sistematica trattazione delle forme linguistiche del latino, idealmente ricondotto al modello ciceroniano e purificato dalle alterazioni dei grammatici medievali.

Infine, nel 1449, applicò i metodi innovativi della filologia al testo evangelico nelle _Adnotationes in Novum Testamentum_, anticipando così lo sviluppo degli studi biblici che avrebbero poi trovato piena espressione con Erasmo da Rotterdam.

=== Piccolomini, il papa umanista

Enea Silvio Piccolomini (1405-1464), noto come Papa Pio II, fu una figura di spicco dell'Umanesimo del Quattrocento. Distintosi inizialmente come segretario del cardinale Capranica durante il concilio di Basilea, sostenne con eloquenza le tesi conciliaristiche, che affermavano la superiorità del concilio sul papa, nel suo scritto _De gestis Basileensis concilii_ (1440). Uomo di grande erudizione, si dedicò parallelamente alla letteratura, ottenendo nel 1444 la prestigiosa corona poetica. La sua carriera ecclesiastica iniziò con la nomina a vescovo di Trieste nel 1447 e proseguì con l'elezione a vescovo di Siena nel 1450.

Nel corso della sua evoluzione intellettuale ed ecclesiastica, Piccolomini ritrattò le posizioni conciliariste, divenendo sostenitore del primato papale. Tale cambiamento si riflette nell'opera _De rebus Basileae gestis stante vel dissoluto concilio_ (_I fatti del concilio di Basilea_, 1450), in cui avallò l'autorità assoluta del pontefice. Eletto papa nel 1458, Pio II si dimostrò un grande mecenate, impegnato nella promozione dell'ideale umanista della città a misura d'uomo. Un esempio emblematico di questa visione è la trasformazione urbanistica di Corsignano, suo borgo natale, ribattezzato Pienza in suo onore. I lavori, avviati nel 1460, furono affidati all'architetto Bernardo Rossellino. Il pontefice morì mentre preparava una crociata contro i turchi, un'impresa che egli stesso aveva proclamato, preceduta dall'invio senza successo di una lettera al sultano Maometto II per esortarlo alla conversione (_Epistola ad Mahometem_, 1460).

L'attività letteraria di Piccolomini è eterogenea e si concentra prevalentemente nel periodo antecedente alla sua ordinazione ecclesiastica. Nelle sue opere giovanili affrontò temi amorosi attraverso la raccolta poetica _Cinthia_ e la commedia _Chrysis_ (1444), quest'ultima ispirata allo stile comico di Plauto. Notevole successo riscosse il romanzo _De duobus amantibus_ (_I due amanti,_, 1444), apprezzato per la sottigliezza psicologica dei personaggi, la vivacità della narrazione e la purezza stilistica del linguaggio. Accanto agli scritti sul concilio di Basilea, si dedicò anche a un'opera incompiuta di carattere geografico, la _Cosmographia_ (1461), nonché a un trattato erudito articolato in tre sezioni dedicate rispettivamente ai Germani, all'Europa e all'Asia.

Durante il pontificato, Pio II completò i dodici libri della sua autobiografia (_Commentarii rerum memorabilium quae temporibus suis contigerunt_, _Commentari agli avvenimenti notevoli accaduti ai suoi tempi_), che si spinge fino al 1563. Caratterizzata da uno stile raffinato ed elegante, questa opera rappresenta una testimonianza di notevole valore sulle dinamiche politiche ed ecclesiastiche del suo tempo.

== Umanesimo neoplatonico: Ficino e Pico della Mirandola

Nella metà del XV secolo, l'Umanesimo rinascimentale raggiunse una delle sue massime espressioni nella sintesi culturale offerta da Marsilio Ficino (1433-1499). Fondatore dell'Accademia Fiorentina nel 1462 e traduttore dell'intero corpus di Platone nel 1484, Ficino elaborò nelle sue opere fondamentali una filosofia centrata sull'anima come principio generativo dell'universo. Tra i suoi scritti più significativi si annoverano il _De voluptate_ (1457), il _De religione christiana_ (1474), la _Theologia platonica_ (1482) e il _De vita_ (1489). Il suo pensiero, radicato in una ripresa del platonismo e del neoplatonismo, esercitò una profonda influenza sulla cultura rinascimentale, contribuendo alla definizione di un'immagine rinnovata della persona e di una moderna concezione dell'amore.

Una figura di grande rilievo fu Giovanni Pico della Mirandola (1463-1494), impegnato nella costante ricerca di una sintesi tra tutte le filosofie e religioni, in particolare la cabbalà, corrente mistica dell'ebraismo, e la rivelazione cristiana. Autore dell'illustre orazione _De dignitate hominis_ (_La dignità dell'uomo_, 1486), ha dato vita a un'opera che rappresenta una preziosa sintesi del pensiero umanistico. Questo testo esprime con straordinaria efficacia la fiducia nei valori e nella grandezza dell'uomo, al quale Dio ha donato la capacità di essere artefice del proprio destino, rendendolo superiore persino agli angeli.

#pagebreak()
#set page(fill: accent.ita.lighten(90%))
== In sintesi <senza_numero>

/ Umanesimo: Attraverso la valorizzazione della tradizione greco-latina, l'Umanesimo riconsidera il ruolo centrale dell'uomo, interpretato come artefice del proprio destino, impegnato nella costruzione di modelli sociali innovativi. Questo approccio si oppone alla visione tradizionale ed esclusivamente ultraterrena del mondo.\ Figura di spicco dell'Umanesimo, Coluccio Salutati fu cancelliere di Firenze per oltre trent'anni e un tenace assertore dell'alto valore civile della cultura classica.

/ Umanisti: Nelle _Vite di Dante e Petrarca_ (1436), Leonardo Bruni riconosce il valore della lingua volgare e la validità del suo utilizzo in ambiti letterari. \ Con le _Facezie_,  Poggio Bracciolini esalta i principi della nuova civiltà umanistica, ponendo al centro delle sue narrazioni l'abilità, la cultura e l'impegno dell'uomo civile come esempio morale. \ Considerato il modello ideale dell'insegnante umanista, Vittorino da Feltre dedicò la propria attività alla formazione intellettuale e morale. \ Leon Battista Alberti invoca l'uomo come fulcro dell'universo, chiamato a forgiare se stesso attraverso l'esperienza diretta, l'ingegno personale e la rielaborazione del sapere. \ Lorenzo Valla, celebre per aver dimostrato la falsità della _Donazione di Costantino_, e Enea Silvio Piccolomini, il futuro Pio II, mecenate illuminato, emersero come figure emblematiche dell'Umanesimo, grazie al loro gusto letterario e al rigore della ricerca filologica.

/ Neoplatonismo fiorentino: Marsilio Ficino integrò il pensiero platonico e neoplatonico nella tradizione cristiana, reinterpretandone i principi alla luce delle dottrine spirituali. \ Pico della Mirandola celebrò la dignità dell'uomo, concepito come opera divina e artefice consapevole del proprio destino, superiore persino agli angeli.