#import "../../../template/_global/template.typ": *
#import "../../../template/_global/config.typ": *

#intro[Firenze, grazie all'eccezionale prestigio culturale raggiunto tra il XIII e il XIV secolo, fu sin dagli albori della civiltà umanistica il principale fulcro degli studi e il punto di riferimento per i maggiori esponenti delle arti. Lorenzo il Magnifico, signore di Firenze, incarnò perfettamente gli ideali di questa corrente umanistica, caratterizzata dal mecenatismo dei signori, da una libertà intellettuale senza precedenti, da un gusto raffinato per la bellezza e da un fervente interesse verso l'integrazione degli ideali classici con la tradizione comunale fiorentina. Proprio grazie all'ambiente mediceo si ebbe una significativa rinascita della poesia in volgare, alimentata dal contributo dello stesso Lorenzo, di Luigi Pulci e di Agnolo Poliziano.]

== La letteratura umanistica in volgare

La letteratura umanistica in volgare si sviluppò seguendo modelli linguistici toscani ispirati allo stile stilnovistico e petrarchesco, ma si caratterizzò soprattutto per l'aspirazione a forme poetiche più concrete e legate alla realtà, aperte a sperimentazioni stilistiche ed espressive.

Un esempio emblematico di questa vivacità fu Domenico di Giovanni, detto Burchiello (1404-1449). Nato in condizioni di estrema povertà, visse una vita irregolare e disordinata. Il soprannome "Burchiello", derivante da un piccolo battello da carico in cui le merci erano disposte disordinatamente, fu attribuito al poeta per lo stile caotico e fantasioso delle sue composizioni satiriche e antiletterarie. I sonetti caudati raccolti nelle _Rime_ (pubblicate postume nel 1757) sono infatti caratterizzati da uno sperimentalismo comico e giocoso che accosta parole e immagini in modo apparentemente privo di logica, con un evidente intento parodistico. Questi testi diedero origine a una peculiare tradizione poetica nota come "maniera burchiellesca".

Dal 1469 al 1492, sotto il governo di Lorenzo de' Medici, la corte medicea diventò il centro nevralgico della più alta espressione dell'umanesimo italiano. Tra i protagonisti di questa epoca d'oro spiccano Lorenzo il Magnifico, Agnolo Poliziano, Marsilio Ficino, Giovanni Pico della Mirandola e Luigi Pulci, quest'ultimo con una produzione dal tono più popolare.

== Lorenzo il Magnifico

Lorenzo de' Medici, noto come "il Magnifico", governò Firenze dal 1469 al 1492, mantenendo una facciata di rispetto per le istituzioni comunali democratiche, ma di fatto esautorandole e accentrando il potere nelle sue mani. Diplomazia e politica estera furono i fulcri della sua strategia, tramite cui riuscì a posizionarsi come figura centrale nell'equilibrio tra gli stati italiani. Sul piano letterario, le sue prime opere includono la _Nencia da Barberino_ del 1473, un idillio rustico in cui Lorenzo assume il ruolo di pastore che, con spontaneità e freschezza, celebra le bellezze della sua amata. Al medesimo periodo appartengono due poemetti di tono comico-realistico, _L'uccellagione di Starne_ (chiamato anche _Caccia col falcone_) e _Il simposio_, nel quale si fa una caricatura di famosi bevitori fiorentini sulla scia dello stile di Luigi Pulci.

Successivamente, Lorenzo dimostrò un crescente interesse verso le teorie neoplatoniche di Marsilio Ficino, con il quale dialogò sul tema del sommo bene nell'opera _Altercazione_ (1473-74). Tra il 1483 e il 1484 scrisse un _Comento_ composto da prose e poesia (41 sonetti), che, sul modello della _Vita nuova_ di Dante, racconta una storia d'amore ricca di dettagli psicologici. Dopo il 1486 compaiono poemi come _Ambra_ e _Corinto_, insieme ai due libri di strambotti raccolti nelle _Selve d'amore_, dove l'autore rilegge temi amorosi in chiave più intima e malinconica. La stessa vena malinconica risuona nelle opere della maturità, tra cui le _Canzoni a ballo_ e i _Canti carnascialeschi_, come l'emblematico _Trionfo di Bacco e Arianna_, che riflette sulla fugacità dell'esistenza. Lorenzo compose anche opere religiose, tra cui la _Rappresentazione di san Giovanni e san Paolo_ (1491) e nove _Laudi_.

== Agnolo Poliziano

Agnolo Ambrogini, conosciuto con il nome di Poliziano, rappresenta una figura centrale nel circolo mediceo, avendo saputo fondere armoniosamente la cultura classica con la tradizione letteraria volgare fiorentina di Dante, Petrarca e Boccaccio.

=== La vita e le opere

Originario di Montepulciano, Poliziano si trasferì nel 1469 a Firenze, dove fu formato dai migliori intellettuali umanisti dell'epoca: tra i suoi maestri si annoverano C. Landino, G. Argiropulo e M. Ficino. Entrò al servizio della famiglia Medici nel ruolo di precettore dei figli di Lorenzo, Piero e Giovanni (quest'ultimo futuro papa Leone X), ottenendo questa posizione prestigiosa già all'età di ventun anni. Parallelamente iniziò la sua carriera ecclesiastica, diventando priore della Collegiata di San Paolo nel 1477.

Tra le sue opere principali c'è _Le stanze per la giostra_, un componimento in onore della vittoria di Giuliano de' Medici nella celebre giostra cavalleresca del 1475. Tuttavia, dopo l'assassinio di Giuliano durante la congiura dei Pazzi nel 1478, Poliziano abbandonò quest'opera incompiuta. Successivamente inscrisse in latino il _Commentario della congiura dei Pazzi_, un'apologia del potere mediceo che rifletteva la violenta risposta di Lorenzo alla congiura.

Probabilmente nello stesso periodo portò a termine la raccolta dei _Detti piacevoli_. Nel 1479, separatosi temporaneamente da Firenze forse a causa di tensioni con Clarice Orsini, moglie di Lorenzo, si spostò tra Venezia, Padova e Mantova. Durante questo periodo scrisse la _Fabula di Orfeo_, considerata una delle prime opere teatrali in volgare ispirate a temi classici.

Nel 1480, ristabilito un saldo accordo con i suoi protettori, fece ritorno a Firenze e si dedicò completamente agli studi classici, abbandonando la poesia in volgare in favore della produzione latina, in particolare epigrammi ed elegie (note quelle _In violas_ e _In Albieram Albitiam_, scritte per la morte di una giovane quindicenne), oltre a concentrarsi sull'attività filologica. Tra le opere che testimoniano il lavoro di questi anni si trovano i poemetti composti in esametri latini, inclusi nelle prolusioni accademiche: _Manto_ (1482), _Rusticus_ (1483), _Ambra_ (1485) e _Nutricia_ (1486), caratterizzati da contenuti teorici e metodologici.

La ricerca filologica, raccolta nei _Miscellanea_ del 1489, si rivelò di straordinaria importanza, lasciando un segno profondo anche nell'interpretazione di Aristotele e nei giudizi letterari trascritti nelle sue _Epistole_ (1494). Celebri sono rimaste le sue canzoni a ballo in volgare, tra cui _I' mi trovai, fanciulle_ e _Ben venga maggio e il gonfalon selvaggio_, che esprimono con mirabile equilibrio una cantabilità gioiosa e popolare.

=== Le _Stanze per la giostra_ e la _Fabula d'Orfeo_

Scritte in ottave e interrotte poco dopo l'inizio del secondo libro, le Stanze per la giostra furono pubblicate solo nel 1494. Le prime strofe sono dedicate alla glorificazione di Firenze e di Lorenzo (Lauro), nuovo protettore delle arti e della poesia; segue la comparsa della figura di Iulo (Giuliano), la cui giovinezza rude e selvatica è trascorsa nei piaceri della caccia e nel disprezzo per l'amore. Ma un giorno, durante una caccia, egli diviene preda di Cupido, s'innamora e inizia così la sua formazione di uomo sensibile ai valori di amore e della gloria. 

Il secondo libro si apre con la celebrazione di Lorenzo, poeta e innamorato; a Iulo viene ordinato in sogno di conquistare la donna amata, dimostrando il proprio valore nelle armi. Qui si interrompe il poema, la cui importanza, al di là della trama, abbastanza fragile, consiste nella creazione di una dimensione in cui si rapportano in perfetto equilibrio la potenza illuminata dalla cultura e la bellezza che suscita l'amore. Questo mondo ideale ha come contesto una natura splendente, ancora incontaminata: una rappresentazione tutta terrena, ma non per questo meno affascinante, del mito del paradiso terrestre, in cui l'essere umano può sentirsi perfettamente appagato. 

L'ottava di origine popolare viene nobilitata attraverso una raffinata eleganza di intarsi letterari, derivati sia dalla tradizione della poesia lirica volgare, sia dall'attenzione filologica alla produzione classica, trattata e tradotta con grande maestria, mentre la lingua è costituita da una preziosa rielaborazione e fusione della tradizione fiorentina degli ultimi due secoli, senza cedimenti alla tentazione di passive imitazioni.

Ispirata al modello delle sacre rappresentazioni, la _Fabula d'Orfeo_ narra il mito eterno di Orfeo, il poeta e musico capace, grazie alla sua arte divina, di commuovere gli inferi e ottenere dal dio Plutone la possibilità di riportare sulla terra la sposa Euridice. Tuttavia, incapace di resistere al desiderio umano di guardarla durante il tragitto verso il mondo dei vivi, finisce per perderla definitivamente.

Poliziano fu uno dei pochi a credere pienamente nel valore trascendente della poesia come veicolo di bellezza eterna e armonia universale. Tuttavia, dopo il 1480, percepì fortemente il senso della fugacità della vita, del rapido sfiorire della giovinezza e dell'inevitabile perdita dei sogni. Dal punto di vista teatrale, la _Fabula d'Orfeo_ assume una rilevanza particolare perché segna l'origine del dramma pastorale, destinato a svilupparsi ampiamente nel Cinquecento.

== Luigi Pulci

Luigi Pulci (1432-1484), esponente della tradizione burlesca e popolare della cultura fiorentina, si distinse come figura alquanto dissonante nel contesto raffinato e impregnato di neoplatonismo della corte medicea. Grazie alla protezione di Lucrezia Tornabuoni, madre di Lorenzo il Magnifico, Pulci riuscì nel 1461 a entrare nella cerchia medicea, ottenendo l'incarico di comporre il suo capolavoro, il _Morgante_, il cui processo di scrittura lo occupò fino alla fine dei suoi giorni. Questo periodo segnò l'inizio di una stretta amicizia con Lorenzo, che non esitò a offrirgli aiuto economico in numerose occasioni. Dal 1466 ebbe luogo un momento particolarmente favorevole per il poeta: compose la favola villereccia _Beca da Dicomano_, una parodia della _Nencia di Barberino_ di Lorenzo; celebrò la vittoria di Lorenzo alla giostra nel 1469; partecipò a una missione diplomatica significativa presso la corte aragonese di Napoli nel 1471; e, infine, contraì matrimonio con Lucrezia degli Albrizi nel 1473.

In questi anni, Pulci si trovò coinvolto in un acceso contrasto con Matteo Franco, un sacerdote vicino a Marsilio Ficino e figura influente nella corte medicea. La polemica tra i due si manifestò attraverso una vivace produzione di sonetti satirici nei quali Pulci indirizzava la propria critica verso argomenti teologici fondamentali, tra cui l'immortalità dell'anima. Questo atteggiamento contribuì a raffreddare gradualmente l'amicizia con Lorenzo, portando il poeta a trascorrere sempre più tempo lontano da Firenze. Nel 1478 venne pubblicata una prima edizione ancora incompleta del _Morgante_, seguita da una seconda edizione in 23 cantari nel 1481 e dall'edizione definitiva, denominata _Morgante maggiore_, composta da 28 cantari e pubblicata nel 1483.

Particolarmente rilevante è la parte finale dell'opera, contenente un attacco diretto a un frate, probabilmente identificabile con Girolamo Savonarola, che aveva condannato pubblicamente Pulci per presunti contenuti sacrileghi nei suoi scritti. Nel 1484, sotto l'influenza di Mariano da Gennazano, un agostiniano, Pulci compose un'opera in terzine intitolata _Confessione_, in cui dichiarava pubblicamente ammenda. Tale atto placò le polemiche intorno alla sua figura e permise di intravedere un possibile ritorno del poeta a Firenze. Tuttavia, Pulci morì improvvisamente a Padova e, considerato eretico, fu sepolto in terra sconsacrata.

=== Il _Morgante_

Se nelle opere minori di Pulci (come i _Sonetti_ e la _Beca da Dicomano_) emerge già un'incontenibile fantasia e un gusto per la parodia accompagnati da un'irriverenza verso ciò che viene considerato intangibile, questo approccio trova il suo culmine nel poema _Morgante_. L'opera sovverte tutti i valori tradizionali dell'epica cavalleresca. La trama stessa, che rappresenta una versione grottesca delle narrazioni tipiche delle canzoni di gesta, segue uno sviluppo atipico: il poema narra le vicende di Orlando, che sceglie di partire alla ricerca di avventure in Oriente dopo essere stato colpito dalle calunnie di Gano e irritato dal comportamento ingenuo di Carlo Magno, descritto come anziano e quasi rimbambito. Tuttavia, la trama non è centrale per comprendere la natura dell'opera: l'interesse principale dell'autore risiede nella rappresentazione vivace ed esagerata di eventi improbabili e stravaganti.

Gli elementi più caratteristici del genio creativo del poeta emergono nei personaggi del gigante Morgante e del mezzo-gigante Margutte. Essi incarnano pienamente quella dimensione caricaturale e fortemente irregolare che permea l'intero poema, offrendo al contempo una denuncia implicita delle convenzioni letterarie dell'epoca e un'espressione originale della vena burlesca di Pulci.

Morgante, armato del battaglio di una campana, incarna l'eccesso nella sua forma più evidente, per l'enorme sproporzione tra la forza fisica straordinaria e la limitata lucidità mentale. Margutte, invece, destinato a morire soffocato dalle proprie risate, è la rappresentazione del capriccio della volontà e della natura. Egli simboleggia una parodia dell'ideale umanistico, quello di un uomo artefice del proprio destino, immerso in un contesto di perfezione armonica ottenuta attraverso un percorso razionale. Tuttavia, Margutte possiede un'arguzia insuperabile e un gusto unico per il male, che si traduce in una contromorale basata sul furto, l'inganno e i piaceri della gola. Questa sua indole emerge in avventure segnate da una voracità prodigiosa e da una perfidia sadica verso le sue vittime.

Lo stile di Luigi Pulci non si rifà al modello colto del volgare toscano né si appiattisce su un linguaggio strettamente popolare. Pulci attinge piuttosto al patrimonio di espressioni gergali appartenenti agli ambienti marginali della società. Egli arrivò persino a redigere un _Vocabolarietto di lingua furbesca_, un'opera che raccoglieva parole ed espressioni provenienti dai contesti della malavita. Nei suoi versi, le parole tendono costantemente all'ambiguità, e spesso il gioco creato dall'accostamento linguistico o dalle assonanze fonetiche prevale sulla narrazione stessa, imponendo svolte inaspettate e imprevedibili.

== Gerolamo Savonarola

Alla fine del Quattrocento si impone con tragica intensità la figura del predicatore domenicano Gerolamo Savonarola (1452-1498). Dopo la discesa del re di Francia Carlo VIII e la cacciata di Piero de' Medici nel 1494, Savonarola divenne promotore di una repubblica popolare a Firenze. Nonostante la sua capacità di moderare il radicalismo puritano dei "piagnoni", suoi seguaci, non riuscì a evitare gli attacchi degli "arrabbiati", partigiani dell'oligarchia, e dei "palleschi", sostenitori dei Medici. Le sue gravi accuse contro papa Alessandro VI e la denuncia dell'immoralità della Chiesa lo portarono alla scomunica e al processo per eresia. Fu impiccato nel 1498 e le sue ceneri disperse nel fiume Arno.

Ci rimangono diversi suoi scritti dottrinari, tra cui il _Compendium logicum_ (1491), il _Compendio delle rivelazioni_ (1495), l'_Epistola della sana e spirituale lezione_ (1497) e il _Trattato circa il reggimento del governo della città di Firenze_ (1498).

Il suo capolavoro sono però le _Prediche_, raccolte postume, dove, con un linguaggio drammatico intrecciato di riferimenti biblici, denuncia le corruzioni mondane della Chiesa ed esprime la speranza di un cristianesimo restituito allo spirito evangelico originario. La sua figura esercitò un fascino profondo su molti uomini di cultura, tra cui Pico della Mirandola, Guicciardini, Michelangelo e numerosi umanisti.

#pagebreak()
#set page(fill: accent.ita.lighten(90%))
== In sintesi <senza_numero>

/ Burchiello: I sonetti caudati presenti nelle _Rime_ sono caratterizzati da uno sperimentalismo comico e giocoso che accosta parole e immagini prive di connessioni logiche.

/ Lorenzo de' Medici: Illustre mecenate e figura centrale della cultura rinascimentale, Lorenzo trasformò Firenze nel fulcro della vita culturale, artistica e politica italiana. La sua opera poetica oscilla tra toni popolari ispirati alla tradizione burchiellesca e l'adesione al pensiero neoplatonico dell'Accademia fiorentina. Nelle _Selve d'amore_ e nei _Canti carnascialeschi_, la sua vena lirica si distingue per un tono malinconico.

/ Poliziano: Tra le sue opere maggiori si annoverano la _Fabula d'Orfeo_ e le _Stanze per la giostra_. Poliziano attribuì alla poesia un valore assoluto come portatrice di ideali immortali di bellezza e armonia. Tuttavia, percepì anche l'ineluttabilità della caducità dell'esistenza, il rapido declino della giovinezza e la fine inevitabile di ogni sogno.

/ Luigi Pulci: Il poema eroicomico _Morgante_, considerato il suo capolavoro, rappresenta una parodia degli ideali umanistici che vedono l'uomo come artefice del proprio destino in un universo armonico.

/ Girolamo Savonarola: Attraverso le sue prediche e la sua azione politica, Savonarola denunciò la corruzione della Chiesa e auspicò un ritorno al cristianesimo nella sua originaria semplicità evangelica.