#import "../../../template/_global/template.typ": *
#import "../../../template/_global/config.typ": *

#intro[Sugli altopiani interni dell'Asia Minore e lungo le coste del Mar Nero, agli inizi del II millennio a.C., si insediarono popolazioni provenienti dalle regioni montane situate a nord della Mesopotamia e della Siria, identificate come Cassiti e Hurriti. 

Successivamente alla caduta dell'Impero Ittita, intorno al 1200 a.C., nuovi gruppi umani diedero origine a nuove civiltà in Anatolia, come il Regno dei Frigi e il Regno dei Lidi. Queste entità politiche raggiunsero un notevole livello di prosperità economica grazie allo sviluppo dei traffici commerciali. Nell'altopiano armeno, tra il IX e il VII secolo a.C., si consolidò il Regno di Urartu, il quale però fu travolto agli inizi del VI secolo a.C. dagli Sciti e dai Cimmeri. 

La parte orientale dell'Asia rappresentò anch'essa un importante centro di sviluppo delle civiltà, favorito dalle condizioni di fertilità dei terreni attraversati da grandi corsi d'acqua. Tra questi, il fiume Indo fu cruciale per la civiltà indiana, così come i fiumi Giallo e Azzurro lo furono per la civiltà cinese. Lungo il fiume Indo, che attraversa l'area dell'attuale Pakistan, si testimoniò, sin dal 2500 a.C., l'emergere di una civiltà dedita alla caccia, all'allevamento e all'agricoltura e già in possesso di un sistema di scrittura nel corso del III millennio a.C. 

Questa civiltà fu infine distrutta dall'invasione di popolazioni chiamate Arya o Ariani, termine che nel XIX secolo fu frainteso ed esteso per designare l'intero gruppo indoeuropeo comprendente Germani, Greci, Celti e altri popoli accomunati da radici linguistiche. Gli Arya, gruppi di lingua indoeuropea provenienti da nord-ovest, diedero origine a una nuova civiltà nella regione. Analogamente, ricerche archeologiche condotte in Cina hanno individuato diverse aree in cui si consolidarono insediamenti stabili già dal 6000 a.C.]

== Hurriti e Cassiti

Gli Hurriti, originari delle regioni situate a est del Tigri e a sud del Lago Van, si spinsero verso l'Alta Siria già prima del XVIII secolo a.C. Durante la seconda metà del XVI secolo a.C., emerse il più importante organismo politico hurrita: il Regno dei Mitanni. Questo regno, al termine del XV secolo a.C., esercitò il proprio dominio sugli Assiri fino alla loro liberazione ad opera di Assuruballit I. Tuttavia, dopo avere esteso il proprio controllo su altre regioni orientali, i Mitanni vennero sconfitti nel 1365 a.C. dagli Ittiti. Gli Hurriti influenzarono gli Ittiti soprattutto in ambito artistico e religioso.

I Cassiti, originari dell'altopiano iranico, penetrarono in Mesopotamia nel XVII secolo a.C., stabilendosi a Babilonia e mantenendo il loro controllo per circa 400 anni, fino al 1160 a.C., quando furono sconfitti dagli Elamiti. Nonostante la loro lunga presenza nella regione, essi non ebbero un impatto significativo sulla vita culturale locale.

== I Regni di Urartu, Frigia e Lidia

Il Regno di Urartu si sviluppò tra il IX e il VII secolo a.C. sull'altopiano armeno, situato a est dell'alto corso dell'Eufrate, fra i monti del Tauro e dello Zagros. La prima unificazione politica fu attuata da Arame I (858-844 a.C.).

Sotto il dominio di Sarduri I (844-832 a.C.) e dei suoi successori, il Regno si espanse verso il Caucaso, approfittando della crisi dell'Impero assiro per ampliare la propria influenza fino all'alto corso dell'Eufrate. Durante il regno di Sarduri II (764-743 a.C.), Urartu raggiunse il culmine della sua potenza, ma venne a scontrarsi con la reazione degli Assiri: Tiglatpileser III inflisse una sconfitta decisiva a Sarduri II nella battaglia di Kisthan nel 743 a.C.

L'ascesa del Regno di Urartu si interruppe definitivamente all'inizio del VI secolo a.C., quando Sciti e Cimmeri lo travolsero e ne decretarono la fine. Per quanto riguarda i Frigi e i Lidi, è probabile che fossero tra i cosiddetti "Popoli del Mare", forse di origini indoeuropee. Questi gruppi si insediarono in Asia Minore dopo la caduta dell'Impero Ittita. I Frigi si stanziarono nell'Anatolia centrale, nelle vicinanze del Mar Nero. Sotto il re Mida, tra l'VIII e il VII secolo a.C., il Regno di Frigia raggiunse il suo massimo splendore. Secondo la tradizione greca, il re Mida era in grado di trasformare in oro tutto ciò che toccava; effettivamente, sotto il suo governo, il Regno conobbe un periodo di grande prosperità economica.

La capitale Gordio e Troia assunsero un ruolo di primo piano come centri commerciali. Il territorio frigio, ricco di pascoli, favoriva la produzione di lana pregiata, che veniva esportata insieme a legname e manufatti metallici, grazie alle numerose miniere presenti nella regione. L'artigianato dei tappeti frigi, celebre per la raffinatezza e la qualità, acquisì grande fama. I Frigi svolsero anche un ruolo significativo nella diffusione dell'alfabeto fenicio e si distinsero come eccellenti musicisti. Sul piano religioso, veneravano Cibele, divinità della fertilità poi adottata anche da Greci e Romani.

Nel VI secolo a.C., il Regno dei Frigi venne conquistato dai Persiani. Dopo la caduta di Gordio, furono i Lidi ad affermarsi, stabilendosi più a sud rispetto ai Frigi, in prossimità delle coste dell'Egeo. Il periodo di massimo sviluppo della Lidia si ebbe sotto il re Gige agli inizi del VII secolo a.C., ma fu Creso (561-546 a.C.) il sovrano più noto. Sebbene avesse sottomesso diverse città greche dell'Egeo, Creso mantenne un atteggiamento tollerante nei loro confronti e continuò ad inviare doni ai santuari greci, in particolare all'oracolo di Delfi.

Creso si alleò con i Medi contro i Persiani, ma fu sconfitto e fatto prigioniero dai rivali. Nel 546 a.C., la Lidia fu annessa come satrapia all'Impero persiano. Tra le sue divinità principali si trovavano Artimu (equivalente alla Artemide greca) e Dioniso, dio dell'estasi mistica già venerato nella cultura greca. I Lidi sono inoltre ricordati per aver introdotto l'uso della moneta nella storia antica.

== La civiltà indiana

In seguito all'arrivo degli Arya nella prima metà del II millennio a.C., i centri urbani costruiti dalla civiltà della Valle dell'Indo si disgregarono, poiché la nuova popolazione si distribuì in una moltitudine di piccoli villaggi. Gli Arya introdussero rilevanti innovazioni, tra cui il riso nell'agricoltura e il cavallo, l'asino e il cammello nell'allevamento. Abbandonarono inoltre l'uso della scrittura per oltre mille anni, favorendo lo sviluppo di una ricca tradizione poetica orale che sarebbe confluita nei Veda, una raccolta di inni e preghiere sacre, i testi fondamentali della religione indù.

=== Società e religione

La società indiana, fin dai tempi storici, si è sempre caratterizzata per la divisione in caste (_varna_, "colore"), nonostante la dottrina indù affermi che in origine gli uomini fossero al di sopra di tali suddivisioni (ativarna). Le caste principali sono quattro: quella dei sacerdoti, quella dei guerrieri, quella dei mercanti e quella dei servi. A queste si aggiungono i fuori casta, destinati alle mansioni più umili. Nei Veda vengono venerate numerose divinità, tra cui spiccano Varuna, il dio dell'universo (la cui figura presenta analogie con l'Urano greco), e Indra, il dio della pioggia e della guerra.

Parallelamente alle divinità vediche, uno degli elementi centrali della religione indù è il culto della Trimurti, che rappresenta i tre aspetti essenziali del divino: Brahma, lo spirito universale da cui tutto ha origine; Visnu, il custode delle realtà manifeste; e Shiva, colui che distrugge le apparenze per riassorbirle in sé. Il culto di Shiva prevede pratiche di meditazione e ascesi. Nella religione indù viene inoltre trasmessa l'idea della trasmigrazione delle anime, spesso fraintesa come reincarnazione, ma che in realtà impiega le realtà del mondo terreno per fare riferimento, tramite analogia, a stati d'esistenza superiori.

== Il risveglio economico e culturale

La civiltà degli Arya si espanse fino alle valli del Gange e intorno al VI secolo a.C. visse un periodo di significativo risveglio economico e culturale. Tra le innovazioni vi furono la lavorazione del ferro, l'introduzione della moneta e di una nuova forma di scrittura ispirata al sistema aramaico. In questo contesto emerse anche il buddhismo, fondato da Gotama Siddharta, conosciuto come il Buddha (colui che ha raggiunto l'illuminazione).

== La civiltà cinese

La civiltà cinese vide invece la successione di tre grandi dinastie prima dell'unificazione dello stato. La prima fu la dinastia Xia nel III millennio a.C.; la seconda fu quella Shang, attestata da documenti scritti e risalente alla metà del II millennio a.C., caratterizzata da una società governata da aristocratici guerrieri e da un re con potere anche religioso. Nell'XI secolo a.C. si impose la dinastia Zhou, durata ben otto secoli.

Tra il 770 e il 476 a.C., sorsero diversi centri autonomi trasformatisi in principati. Tuttavia, tra il 475 e il 221 a.C., questi principati entrarono in conflitto tra loro in una serie di guerre che indebolirono progressivamente la dinastia Zhou. Sul piano sociale si affermarono la proprietà privata e l'espansione dei commerci. Tra il VI e V secolo a.C. l'introduzione del ferro rivoluzionò le produzioni locali.

La decadenza della dinastia Zhou culminò nel III secolo a.C., con l'unificazione realizzata dalla dinastia Qin. Il pensiero di Confucio (550-479 a.C.) fu fondamentale nel processo di unificazione: egli codificò le norme etiche e politiche su cui si sarebbe basato l'ordine sociale cinese. Parallelamente, il Taoismo, legato agli insegnamenti di Lao Tzu (VI-V sec. a.C.), contemporaneo secondo alcuni di Confucio stesso, forniva i principi spirituali su cui si fondava la gerarchia interiore della Cina.

#pagebreak()
#set page(fill: accent.sto.lighten(90%))
== In sintesi <senza_numero>

/ III millennio: A partire dal 2500 a.C., nella valle dell'Indo si sviluppano le pratiche agricole e l'allevamento, nonché l'uso della scrittura. Sul finire del III millennio a.C., in Cina emerge la dinastia Xia, la prima delle tre dinastie precedenti il processo di unificazione.

/ II millennio a.C. - XII secolo a.C.: Durante la prima metà del II millennio a.C., la dinastia Shang subentra alla Xia. Con lo stesso periodo, gli Arya penetrano nella valle dell'Indo, stabilendo i loro insediamenti. Parallelamente, le tribù degli Hurriti e dei Cassiti si insediano in diverse aree dell'Asia Minore e lungo le coste del Mar Nero. \ Gli Hurriti raggiungono il culmine del loro sviluppo politico con il Regno di Mitanni nel XVI secolo a.C.; alla fine del XV secolo a.C. riescono a sottomettere gli Assiri, ma sono sconfitti dagli Ittiti verso il 1365 a.C. I Cassiti, giunti in Mesopotamia nel XVII secolo a.C., fondano un dominio duraturo a Babilonia, che si protrae per circa quattro secoli.

/ XI secolo a.C. - III secolo a.C.: Nel XI secolo a.C., la Cina vede l'ascesa della dinastia Zhou, che governerà per oltre otto secoli. Parallelamente, il Regno di Urartu si afferma tra il IX e il VII secolo a.C. sull'altopiano armeno, raggiungendo il massimo splendore sotto Sarduri II (764-743 a.C.). Tuttavia, nel 743 a.C. subisce una significativa sconfitta contro gli Assiri e verrà definitivamente annientato all'inizio del VI secolo a.C. dalle incursioni di Sciti e Cimmeri. \ I Frigi, stabilitisi in Anatolia dopo il declino degli Ittiti, sperimentano una fase di massimo sviluppo tra l'VIII e il VII secolo a.C., sotto il regno del leggendario re Mida, per poi soccombere ai Persiani nel VI secolo a.C. I Lidi occupano aree più meridionali rispetto ai Frigi, principalmente nelle regioni vicine al Mar Egeo. Il loro periodo di massimo splendore coincide con il regno di Gige agli albori del VII secolo a.C., seguito da quello di Creso (561-546 a.C.), sotto il cui dominio vengono sottomesse diverse città greche con un approccio tollerante. Tuttavia, in seguito alla sconfitta contro i Persiani nel 546 a.C., la Lidia diventa una provincia dell'impero persiano. \ In Cina, tra il 770 e il 476 a.C., emergono numerosi centri autonomi che si trasformano progressivamente in principati in conflitto fra loro. Questo clima di instabilità conduce all'indebolimento e al collasso della dinastia Zhou. Nel VI secolo a.C., la dottrina di Confucio inizia a diffondersi. \ Nel III secolo a.C., la dinastia Qin ascende al potere inaugurando il processo di unificazione del territorio cinese. Per quanto riguarda gli Arya, intorno al VI secolo a.C., la diffusione dell'uso della moneta, dell'alfabeto e del ferro imprime un forte impulso allo sviluppo economico della regione. Parallelamente, prende piede la predicazione di Buddha, segnando una svolta culturale fondamentale nella civiltà indoaria.

