#import "../../../template/_global/template.typ": *
#import "../../../template/_global/config.typ": *

#intro[Profondi mutamenti caratterizzarono la società romana a seguito delle guerre puniche e della conquista della Grecia e dell'Oriente. L'introduzione della cultura ellenistica, favorita dall'arrivo di numerosi artisti greci a Roma e dall'attrazione esercitata sulle élite romane, sempre più inclini a soggiornare in Grecia e in Oriente, contribuì a una crisi dei valori fondati sulla tradizionale moralità romana. 

L'élite senatoriale, forte delle ricchezze accumulate durante i conflitti, iniziò a impossessarsi delle terre statali, entrando in competizione con l'ordine equestre che pure rivendicava tali proprietà. Nel contempo, le classi medie, in particolare i piccoli agricoltori che avevano costituito il fulcro dell'esercito romano, caddero in un progressivo impoverimento. Fu in questo contesto che Tiberio e Caio Gracco promossero una riforma agraria volta a mitigare le disuguaglianze socio-economiche, sebbene il loro intervento si concluse tragicamente con un fallimento accompagnato da violenti scontri. Dopo un breve periodo di stabilità garantito da una politica oligarchica senatoriale, Roma si trovò nuovamente travolta da tensioni politiche e rivalità sempre più accese tra i diversi schieramenti. 

Tali contrasti culminarono nella prima guerra civile che vide contrapporsi gli _optimates_, guidati da Lucio Cornelio Silla, ai _populares_, rappresentati da Gaio Mario. La vittoria di Silla gli consentì di restaurare il potere patrizio e di ridimensionare il ruolo dei tribuni della plebe; tuttavia, il suo ritiro dalla scena politica seguito dalla sua morte non risolse i conflitti latenti, lasciando Roma sull'orlo della seconda guerra civile.]

== Dalla crisi economica e sociale alla riforma dei Gracchi

L'espansione dei domini romani nell'area greco-orientale determinò un profondo impatto culturale e sociale. L'incontro con la civiltà ellenistica generò infatti due correnti ideologiche nella società romana: da un lato quella conservatrice, incarnata da Marco Porcio Catone, promotore di un ritorno agli antichi valori e costumi tradizionali; dall'altro quella innovatrice del circolo degli Scipioni, favorevole alla cultura greca e interessata a integrarne gli elementi con la tradizione latina. 

Nel frattempo, durante le guerre d'espansione si verificò un consolidamento del potere da parte della classe senatoriale, mentre le categorie medie subirono un progressivo declino economico. Contestualmente si affermò l'ordine equestre, una nuova classe finanziaria che rivendicava maggiori prerogative rispetto al senato. L'enorme ricchezza proveniente dai territori conquistati favorì l'acquisto di vasti appezzamenti dell'_ager publicus_, terre confiscate ai popoli vinti e divenute proprietà dello Stato. Tale fenomeno sollecitò la diffusione del sistema latifondistico e l'intensificazione della schiavitù, a cui molti piccoli proprietari ruralizzati non riuscirono a competere, trovandosi costretti a migrare verso la capitale in cerca di opportunità economiche.

Una prima risposta alle crescenti disparità fu intrapresa nel 133 a.C. da Tiberio Gracco, appartenente alla classe patrizia ed eletto tribuno della plebe. Egli propose di far rispettare la legge che vietava ai privati di possedere più di 125 ettari di terreno pubblico e di redistribuire le eccedenze agli agricoltori impoveriti. Tuttavia, questa iniziativa incontrò una fiera opposizione dall'aristocrazia senatoria, ostile a qualsiasi misura che limitasse il proprio potere economico e sociale.

Tiberio Gracco, ripresentatosi per ottenere la carica di tribuno della plebe, trovò la morte durante un tumulto, mentre i suoi sostenitori furono condannati a morte. Questo evento suscitò indignazione anche tra gli Italici, i quali si vedevano privati dei propri territori e, non essendo cittadini romani, venivano esclusi dai benefici delle nuove distribuzioni. Molti di loro tentarono la ribellione, ma furono severamente repressi. Nel 123 a.C., fu eletto tribuno Caio Gracco, fratello minore di Tiberio, noto per le sue proposte di riforma ancora più audaci. Per rafforzare la sua posizione politica, Gracco cercò il sostegno della classe equestre, assicurando che i membri appartenenti al ceto dei cavalieri fossero presenti in numero superiore rispetto ai senatori nei tribunali preposti ai giudizi sui reati di concussione.

Al fine di assicurarsi il favore della plebe, promosse la creazione di nuove colonie e avanzò una proposta di legge frumentaria che garantiva ai cittadini meno abbienti l'accesso al grano a un prezzo agevolato. Rieletto _tribunus plebis_, propose inoltre l'estensione della cittadinanza romana agli Italici. Tuttavia, questa iniziativa incontrò l'opposizione dei senatori, che si avvalsero del tribuno Livio Druso per osteggiare il progetto di Gracco. Druso avanzò varie proposte demagogiche, come l'esenzione dal pagamento dell'affitto delle terre per i piccoli proprietari e la fondazione di nuove colonie, guadagnandosi il favore popolare e oscurando la figura di Caio Gracco.

In un contesto crescente di tensioni politiche e conflitti interni, nel 121 a.C., il Senato emanò il _Senatus consultum ultimum_, una disposizione che attribuiva poteri straordinari ai consoli, tra cui Lucio Opimio, acerrimo avversario di Caio Gracco, al fine di garantire la "salvezza dello Stato" con ogni mezzo possibile. Sentendosi ormai sconfitto e abbandonato, Gracco si fece uccidere da uno schiavo. I suoi sostenitori subirono un tragico massacro: ne furono uccisi circa 3000.

== Dalla Guerra giugurtina all'ascesa di Mario

Dopo la sconfitta politica dei Gracchi, l'oligarchia senatoria consolidò la propria posizione, cercando di ottenere il favore dei cavalieri e della plebe attraverso concessioni limitate. Tra il 125 e il 118 a.C., Roma trasformò la Gallia meridionale in provincia. Poco tempo dopo, fu necessario intervenire in Africa, nella regione della Numidia. Qui Giugurta, dopo aver massacrato Romani e Italici residenti nella città di Cirta, aveva usurpato il trono a discapito di Aderbale, il quale aveva invocato l'intervento romano.

La guerra contro Giugurta ebbe inizio nel 111 a.C. e si protrasse fino al 107 a.C., quando il comando militare fu affidato a Caio Mario. Mario fu affiancato dal questore Cornelio Silla, che riuscì a ottenere la consegna di Giugurta. L'usurpatore fu poi giustiziato. Al termine del conflitto, Mario ricevette tutti gli onori e fu rieletto console, mentre Silla rimase frustrato per non aver ricevuto adeguato riconoscimento per il suo ruolo nella vittoria. Mario consolidò il proprio potere attraverso una riforma dell'esercito: accettò volontari privi di proprietà terriere e garantì loro una paga.

Con un esercito ben addestrato e dotato di nuove strategie militari, Mario, nuovamente eletto console per gli anni dal 103 al 100 a.C., affrontò con successo i Cimbri e i Teutoni, popolazioni germaniche che minacciavano i confini settentrionali della Repubblica romana. Nel 100 a.C., tuttavia, Lucio Apuleio Saturnino, tribuno della plebe, insieme al pretore Gaio Servilio Glaucia, fece approvare una legge che assegnava ai veterani delle campagne militari condotte da Mario alcune terre situate nella Gallia Cisalpina.

Tale iniziativa provocò la disapprovazione del Senato, che conferì pieni poteri a Mario per eliminare politicamente Saturnino e Glaucia.

== Dalla Guerra sociale alla dittatura di Silla

Il partito degli Ottimati mantenne il potere incontrastato per circa un decennio. Nel 91 a.C., il tribunato fu assegnato a Livio Druso, figlio del precedente. Le sue proposte, tra cui la promozione di alcuni cavalieri al rango senatorio e la concessione della cittadinanza agli Italici, generarono l'ostilità del Senato, che ne ordinò l'uccisione. A seguito di questo evento, i soci Italici (da cui il nome Guerra Sociale) si ribellarono per ottenere l'indipendenza da Roma.

Diverse popolazioni, come i Marsi e i Sanniti, fondarono uno stato federale italico con capitale Corfinio, soprannominata Italica. I Romani richiamarono Mario per contrastare i Marsi, mentre altre operazioni furono guidate da Pompeo Strabone e Cornelio Silla, eletto console nell'88 a.C. La concessione della cittadinanza agli Italici non ribelli o disposti a deporre le armi contribuì a placare il conflitto, benché la resistenza dei Sanniti fu definitivamente schiacciata dall'esercito romano solo nell'80 a.C.

Contemporaneamente, Mitridate, re del Ponto, si preparava a fomentare la ribellione degli stati greci e asiatici sottomessi a Roma. Il Senato decise di inviare Silla in Asia. Intanto, il tribuno Sulpicio Rufo propose di suddividere gli Italici nelle 35 tribù esistenti invece di crearne delle nuove e fece approvare anche la nomina di Mario a capo della spedizione asiatica. Entrambe le proposte furono accettate da senatori e cavalieri, contrari alla figura di Silla.

Silla, furioso, sconfisse i sostenitori di Mario, costringendolo alla fuga, e marciò su Roma occupandola. Nell'87 a.C. ottenne nuovamente il comando delle truppe destinate all'Oriente. In Grecia assediò e prese Atene, alleata di Mitridate. Nel frattempo, Mario, con il supporto del console Lucio Cornelio Cinna, rientrò a Roma alla testa di un esercito e massacrò i nemici del partito popolare. Morì l'anno successivo, nell'86 a.C.

Silla, impegnato in Asia, riportò vittoria contro Mitridate e, nell'83 a.C., fece ritorno in Italia. Con l'aiuto di Gneo Pompeo, combatté gli Italici e i seguaci di Mario, sconfiggendoli entrambi. Dopo aver consolidato la propria posizione, si fece nominare dittatore e avviò una serie di repressioni brutali verso gli oppositori. Confiscò numerose terre per distribuirle ai suoi soldati e accrebbe la propria ricchezza approfittando delle persecuzioni. Sul piano politico, restaurò l'autorità del Senato limitando il potere dei tribuni e dei cavalieri. Infine, con grande sorpresa, abdicò dalla dittatura e si ritirò a Pozzuoli dove morì nel 78 a.C.

#pagebreak()
#set page(fill: accent.sto.lighten(90%))
== In sintesi <senza_numero>

/ Crisi economico-sociale e riforma dei Gracchi: Dopo il confronto con l'Oriente, Roma si trova ad affrontare una grave crisi amministrativa. I senatori rafforzano il loro potere, entrando in conflitto con i cavalieri, mentre gli ottimati si appropriano delle terre dell'ager publicus, impoverendo ulteriormente le classi medie. Nel 133 a.C., Tiberio Gracco viene eletto tribuno della plebe e introduce una riforma per la redistribuzione delle terre, ma trova la morte durante un tumulto. \ Dieci anni dopo, nel 123 a.C., il fratello Caio Gracco assume la carica di tribuno e propone una nuova serie di riforme, incontrando però l'opposizione del Senato. Nel 121 a.C. il Senato emana il senatus consultum ultimum, che assegna pieni poteri ai consoli, tra cui Lucio Opimio, accanito oppositore di Caio. Sentendosi sconfitto, Caio decide di togliersi la vita, mentre i suoi sostenitori vengono brutalmente eliminati.

/ Guerra giugurtina e Mario: Tra il 125 e il 118 a.C., Roma trasforma la Gallia Narbonense in provincia. Nel frattempo, deve intervenire in Africa contro Giugurta, colpevole di aver ucciso cittadini romani e italici e di aver usurpato il trono di Aderbale. La guerra, iniziata nel 111 a.C., si conclude nel 107 con la nomina del console Mario e del suo luogotenente Silla al comando delle operazioni. Giugurta viene catturato e consegnato ai Romani, che lo giustiziano. \ Mario esce dalla guerra acclamato come eroe e viene rieletto console per più mandati consecutivi tra il 103 e il 100 a.C. Durante questo periodo riforma l'esercito e sconfigge i Cimbri e i Teutoni. Tuttavia, nel 100 a.C., dopo aver fatto eliminare i leader popolari Lucio Apuleio Saturnino e Gaio Servilio Glaucia, Mario abbandona la scena politica e si ritira in Asia.

/ Guerra sociale e Silla: Nel 91 a.C., l'uccisione del tribuno Livio Druso per le sue proposte invise alla classe dirigente scatena la rivolta dei soci Italici contro Roma, dando inizio alla guerra sociale. Per contrastare l'insurrezione, Roma affida il comando a Mario, Pompeo Strabone e Cornelio Silla. Dopo anni di lotte, la rivolta viene sedata nell'88 a.C., ma la situazione si complica ulteriormente quando a Silla viene tolto il comando della guerra contro Mitridate. Silla risponde marciando su Roma con il proprio esercito, generando una guerra civile contro i suoi oppositori politici. Nell'87 a.C. Silla espugna Atene e sconfigge Mitridate. \ Nel frattempo Mario, tornato in Italia dopo una fuga, riesce temporaneamente a prendere Roma con un esercito, ma muore l'anno seguente, nell'86 a.C. Silla torna nuovamente in Italia nell'83 a.C., alleandosi con Gneo Pompeo per combattere gli Italici e liquidare i seguaci di Mario. Dopo aver consolidato il proprio potere, si fa proclamare dittatore. Muore nel 78 a.C., lasciando alle sue spalle una Roma segnata da profonde divisioni e trasformazioni politiche.

