#import "../../../template/_global/template.typ": *
#import "../../../template/_global/config.typ": *

#intro[Il regno di Augusto fu segnato dal rispetto formale della costituzione repubblicana; tuttavia, l'accentramento di poteri nelle mani del _princeps_ gettò le fondamenta per una nuova realtà politica: l'Impero.

I primi imperatori, Tiberio, Caligola, Claudio e Nerone, discendenti di Augusto e appartenenti alla dinastia Giulio-Claudia, governarono seguendo questo modello. Alla morte di Nerone, il 69 d.C., noto come "anno dei quattro imperatori", si alternarono al potere Galba, Otone, Vitellio e infine Vespasiano. In questo periodo, il trasferimento del potere non seguì modalità legittime, ma fu determinato dalla forza predominante dell'epoca: l'esercito. Un segnale analogo si era già verificato con l'ascesa di Claudio.

Vespasiano, appartenente alla dinastia Flavia, stabilì il principio della trasmissione ereditaria del potere, designando i figli Tito e Domiziano come successori. Durante il suo regno, continuò il processo di unificazione e romanizzazione dell'Impero: la lingua latina si diffuse nelle province occidentali e si concesse con moderazione la cittadinanza romana ai provinciali. Queste scelte favorirono la fusione culturale tra il mondo romano e quello ellenico. In politica estera, vennero consolidati i confini stabiliti in epoca augustea. Durante questi anni Claudio conquistò parte della Britannia meridionale (44 d.C.), dove nacque _Londinium_, oggi Londra, mentre Tito conquistò Gerusalemme e ne ordinò la distruzione (70 d.C.).]

== La dinastia Giulio-Claudia

Con la morte di Augusto, il potere passò a Tiberio, suo figlio adottivo nonché figlio naturale di Livia, moglie di Augusto, e del suo primo marito Claudio Nerone. È da qui che la dinastia prese il nome Giulio-Claudia, unendo la casata di Augusto a quella di Livia. Tiberio si era distinto nelle campagne militari contro i Germani e, per questo, Augusto lo richiamò a Roma assegnandogli importanti incarichi di governo e raccomandandolo al Senato come successore.

Nonostante Tiberio avesse inizialmente espresso il desiderio di ritirarsi a vita privata, il Senato lo proclamò imperatore. In politica estera affidò al giovane nipote Germanico la difesa dei confini settentrionali; Germanico ottenne diverse vittorie contro i Germani tra il 14 e il 16 d.C. Tuttavia, preoccupato della sua crescente popolarità, Tiberio lo inviò in Oriente per trattare con i Parti e, poco dopo, Germanico morì in circostanze sospette nel 19 d.C., evento che compromise l'immagine dell'imperatore presso il popolo.

Negli anni successivi Tiberio iniziò una politica di persecuzioni contro i suoi avversari politici e si ritirò nella sua villa a Capri, delegando il governo a Seiano, prefetto del pretorio. Quando quest'ultimo tramò per usurpare il trono, Tiberio fece ritorno a Roma e nel 31 d.C. ordinò l'esecuzione di Seiano. Nonostante le repressioni crescenti durante il suo regno, Tiberio ottenne comunque alcuni risultati positivi: lo Stato godeva di buona salute finanziaria, i confini erano ben protetti e l'autorità centrale risultava ormai consolidata. Alla sua morte nel 37 d.C., Tiberio indicò come eredi i suoi nipoti Gaio (soprannominato Caligola per i calzari militari che portava da bambino) e Tiberio Gemello.

Il senato, sostenuto dal popolo, acclamò imperatore il primo della dinastia giulio-claudia, grazie alla sua discendenza da Germanico, figura che godeva ancora di grande popolarità. Il breve regno di Caligola (37-41) fu segnato da atti di repressione contro i suoi nemici e da un evidente disprezzo verso il senato, dimostrato da episodi passati alla storia, come la famosa nomina del suo cavallo a senatore.  

Nonostante i tratti da sovrano orientale, come la pretesa di farsi dedicare un tempio e ricevere omaggi divini insieme all'obbligo dell'inchino, Caligola fu molto apprezzato dalla plebe grazie ai giochi circensi e alle generose distribuzioni di cibo e denaro. Proprio da qui nasce l'espressione "_panem et circenses_" (pane e circo), a indicare gli strumenti usati per ottenere il consenso delle masse. Tuttavia, il suo regno si concluse tragicamente nel 41, quando fu vittima di una congiura organizzata dai pretoriani, che posero sul trono lo zio Claudio.  

Per la prima volta nella storia di Roma, un imperatore veniva proclamato direttamente dai militari. Claudio, noto per il suo carattere riservato e apparentemente poco adatto alla vita politica, si rivelò invece un buon sovrano. Rafforzò la struttura burocratica affidandola alla segreteria imperiale, dove collaboravano anche alcuni liberti, e avviò il processo di integrazione dei cittadini delle province nel senato romano. Questo processo avrebbe avuto un ulteriore sviluppo con i suoi successori. Tra le imprese in politica estera, si distinse con la conquista della parte meridionale della Britannia (44), dando origine al primo nucleo della città di Londra, allora chiamata _Londinium_.  

La successione al trono fu segnata da intrighi. Claudio ebbe un figlio legittimo, Britannico, dalla prima moglie Messalina, mentre in seconde nozze sposò Agrippina, sua nipote, che aveva già un figlio di nome Nerone. Agrippina complottò per favorire quest'ultimo: fece assassinare Claudio e manipolò il senato affinché esautorasse Britannico. Così, nel 54, Nerone fu proclamato imperatore. A soli diciassette anni governava sotto il controllo della madre e di due influenti figure: Afranio Burro, prefetto del pretorio, e il filosofo Seneca, suo precettore.  

Nerone però non tardò a liberarsi della madre, del giovane Britannico e persino del filosofo Seneca, che fu costretto all'esilio prima di essere condotto al suicidio. Alla morte di Burro, Nerone stabilì attorno a sé un circolo di fedelissimi e assunse poteri assoluti. Durante il suo regno perseguì una politica estera moderatamente efficace, ottenendo un successo contro i Parti e imponendo il protettorato romano sull'Armenia. Nel 64 d.C., gran parte della città di Roma fu devastata da un incendio. Nerone ne approfittò per accusare i cristiani, ordinando persecuzioni che coinvolsero anche gli apostoli Pietro e Paolo, probabilmente martirizzati tra il 66 e il 67 d.C.  

In città si diffuse però l'ipotesi che fosse stato lo stesso Nerone a provocare l'incendio per costruire il grandioso palazzo Domus Aurea. Il crescente disprezzo per il suo governo dispotico, alimentato dalle spese esorbitanti per mantenere la sua sfarzosa corte e dal suo ossessivo amore per l'arte drammatica e i giochi, portò a un aumento dell'ostilità tra senatori e nobili. Negli ultimi anni del regno Nerone riuscì a sventare la congiura dei Pisoni, ma non senza una serie di epurazioni violente che coinvolsero molti aristocratici e letterati illustri come Lucano e Petronio, oltre a Seneca stesso.  

La situazione divenne insostenibile quando Nerone alienò anche l'appoggio dei militari con l'uccisione del generale Corbulone. Amareggiati dalla sua condotta, nel 68 d.C., le truppe stanziate in Lusitania si ribellarono e proclamarono imperatore il loro comandante Galba. Abbandonato da tutti i suoi appoggi politici e militari, Nerone fu infine costretto a suicidarsi.

#note(top)[== *🧩* Dagli accampamenti alle città <senza_numero>

Fin dal I secolo d.C., i Romani costruirono un sistema di fortificazioni, noto come limes, lungo i confini settentrionali per difendersi dalle incursioni delle popolazioni germaniche. Strutture analoghe furono erette a Oriente lungo il fiume Danubio. Questi interventi ebbero un impatto significativo sul piano geografico e demografico.

Molti accampamenti militari (castra) diventarono il nucleo originario di nuove città. Questi insediamenti si caratterizzavano per una pianta generalmente quadrangolare, con un vallo e una fossa che li circondavano, quattro porte di accesso e un sistema di strade interne organizzate attorno a una piazza centrale. Tra i centri urbani nati da accampamenti lungo il Reno e il Danubio si annoverano Colonia e Belgrado.

Un ulteriore conseguenza rilevante fu legata ai soldati che, al termine del servizio lungo le frontiere, si stabilirono nelle aree vicine. Questa migrazione favorì la romanizzazione delle regioni limitrofe e determinò un progressivo calo demografico in Italia.]

== La dinastia Flavia

Nel 69 d.C. l'Impero Romano vide l'avvicendarsi di ben quattro imperatori. Galba fu deposto dai pretoriani e sostituito da Otone; quest'ultimo, a sua volta, venne rovesciato da Vitellio, sostenuto dalle legioni stanziate sul Reno. Nel frattempo, l'esercito inviato in Oriente per sedare la rivolta degli Ebrei proclamò imperatore il proprio comandante, Flavio Vespasiano, dando così origine alla dinastia Flavia.

La politica di Vespasiano si concentrò sul rafforzamento delle finanze imperiali e sulla disciplina militare. Consolidò le frontiere aumentando il numero delle legioni in Siria e in Giudea, e ampliò i territori romani annettendo la Britannia settentrionale. Durante il suo governatorato giunse a termine la lunga guerra contro gli Ebrei, con la distruzione della città di Gerusalemme nel 70 d.C., evento portato a compimento dalle truppe guidate da suo figlio Tito.

Nel 71, Tito tornò a Roma e fu associato al potere dal padre, fino a succedergli al trono alla morte di quest'ultimo. Durante il suo breve regno si distinse per la clemenza del governo (Svetonio lo celebrò come "delizia del genere umano") e per la sua dedizione alle opere pubbliche, culminata con il completamento del Colosseo. Nell'81 fu seguito sul trono dal fratello Domiziano.

Domiziano ampliò i confini imperiali combattendo contro i Catti, una popolazione germanica, conquistando territori oltre il Reno e organizzandoli nelle nuove province della Germania Superiore e Inferiore. Pur non sconfiggendoli definitivamente, affrontò anche i Daci (nell'attuale Romania) guidati dal re Decebalo e consolidò il potere romano in Britannia. 

Sul piano amministrativo riformò la gestione delle province, introducendo un controllo più severo sull'operato dei governatori. Tuttavia, la sua propensione al dispotismo lo rese inviso al Senato e provocò varie congiure contro di lui, culminate nella trama definitiva del 96 d.C. ordita dai prefetti del pretorio e da sua moglie Domizia Longina, che pose fine al suo regno.

#pagebreak()
#set page(fill: accent.sto.lighten(90%))
== In sintesi <senza_numero>

/ Dinastia Giulio-Claudia: Nel 14 d.C., alla morte di Augusto, il potere imperiale passa a Tiberio, suo figlio adottivo. Durante il periodo tra il 14 e il 16 d.C., Germanico, nipote di Tiberio, riporta diverse vittorie contro le tribù germaniche. Nel 26 d.C., Tiberio si ritira nella sua villa sull'isola di Capri, delegando la gestione del governo al prefetto del pretorio, Seiano. Quest'ultimo trama per ottenere il trono, ma nel 31 d.C. Tiberio ritorna a Roma e ordina l'esecuzione di Seiano insieme ai suoi sostenitori. \ Tiberio muore nel 37 d.C. e il Senato proclama imperatore suo nipote Caligola. Sebbene Caligola mostri atteggiamenti da sovrano assolutista, conquista il favore della plebe; tuttavia, la sua impopolarità presso la nobiltà senatoria culmina in una congiura dei pretoriani nel 41 d.C., che lo conducono alla morte. Dopo la sua uccisione, i pretoriani innalzano al trono Claudio, zio di Caligola. \ Durante il regno di Claudio, nel 44 d.C., viene conquistata la parte meridionale della Britannia, dove sorgerà Londra. Nel 54 d.C., Claudio viene assassinato per ordine di sua moglie Agrippina, che garantisce la successione al figlio naturale, Nerone. \ Liberatosi dalla madre e dai suoi tutori, Afranio Burro e Seneca, Nerone conduce un governo caratterizzato da pratiche dispotiche. Nel 64 d.C., un vasto incendio devasta Roma; secondo alcune ipotesi, orchestrato dallo stesso Nerone, il quale attribuisce la colpa ai cristiani. La situazione politica degenera nel 68 d.C., con la rivolta delle legioni in Lusitania che proclamano Galba come imperatore. Nerone, incapace di fronteggiare la crisi, si vede costretto a suicidarsi.

/ Anno dei quattro imperatori: Il 69 d.C. è contrassegnato dall'ascesa e caduta di quattro imperatori nell'arco di pochi mesi. Galba viene deposto dai pretoriani per essere sostituito da Otone, il quale viene rovesciato da Vitellio, sostenuto dalle legioni stanziate lungo il Reno. Nel frattempo, l'esercito inviato in Oriente per sopprimere la ribellione giudaica proclama come nuovo imperatore il proprio comandante, Flavio Vespasiano, che inaugura la dinastia Flavia. Insediatosi a Roma, Vespasiano elimina definitivamente Vitellio consolidando il suo controllo sul potere.

/ Dinastia Flavia: Il regno di Vespasiano si concentra sul rafforzamento dell'esercito e sulla stabilizzazione delle finanze statali. Nel 70 d.C., suo figlio Tito conduce la distruzione di Gerusalemme durante la repressione della rivolta giudaica. Succedendo al padre nel 79 d.C., Tito conclude la costruzione del Colosseo e guida l'impero per un breve periodo. Alla sua morte, nell'81 d.C., è seguito dal fratello Domiziano, durante il cui regno si conducono campagne militari contro popolazioni come i Catti e i Daci. \ Domiziano trova una fine violenta nel 96 d.C., vittima di una congiura ordita dai prefetti del pretorio e da sua stessa moglie.  Il suo assassinio segna il termine della dinastia Flavia e apre una nuova fase della storia imperiale romana.



