#import "../../../template_tufte.typ": *
#show: frame-style(styles.thmbox)

#evidenzia[Negli anni '70 si assiste a una ricerca sperimentale sempre più astratta e sterile, influenzata dallo strutturalismo. Gli anni '80 inaugurano una nuova dimensione edonistica, quella del cosiddetto postmoderno, caratterizzata da una fruizione estetica che sembra dominare anche parte del decennio successivo, gli anni '90. In questo periodo, la separazione tra letteratura e società conduce a una frammentazione caotica, concentrandosi principalmente su aspetti minimi e quotidiani. Un fattore cruciale per il destino della letteratura è il ruolo crescente dei mass media e le pressioni derivanti dal mercato editoriale.]

== Andrea Zanzotto

Andrea Zanzotto (1921), originario di Pieve di Soligo, emerge come una delle personalità poetiche più significative della seconda metà del Novecento. 

La sua produzione poetica rappresenta un tentativo di mascherare la nevrosi, sia individuale che collettiva, attraverso l'uso di una lingua magmatica e coinvolgente, capace di preservare un io poetico ben definito. Dalla sua prima raccolta, _Dietro il paesaggio_ (1951), si sviluppa un percorso letterario ricco e variegato con opere come _Elegia e altri versi_ (1954), _Vocativo_ (1957), _IX Ecloghe_ (1962), _La Beltà_ (1968), il poemetto _Gli sguardi i fatti e senhal_ (1969) e la trilogia composta da _Il Galateo in bosco_ (1978), _Fosfeni_ (1983) e _Idioma_ (1986).

Il cammino poetico di Zanzotto si concentra sulla parola come strumento di comunicazione per chi, come il poeta, si percepisce "eccentrico" rispetto alla vacuità dell'esistenza. Attratto dalla vitalità ma al contempo respinto dall'ostilità del reale, con le _IX Ecloghe_ tenta di recuperare un mondo naturale ideale e pastorale, arricchito dai simboli e dai linguaggi della modernità e della cultura di massa.

Nelle opere successive, caratterizzate da una complessità linguistica ancora più accentuata, emerge l'uso del dialetto nelle raccolte come _Filò_ (1976) e _Mistieròi_ (1979), segno del legame profondo con la terra trevigiana natale. La sua ricerca sulla parola, sul linguaggio e sulla comunicazione prosegue nella maturità con la trilogia dove riemergono forme metriche tradizionali, quali il sonetto, che impongono ordine al caos dei segni indistinti.

In _Fosfeni_, Zanzotto continua a esplorare i recessi della psiche e dei linguaggi, alla ricerca di una parola assoluta, unica via di salvezza contro la dissoluzione della comunicazione indotta dalla società dei mass media.

== La poesia

Il poeta ligure Giovanni Giudici (1924-2011) ha saputo rinnovare alcuni tratti peculiari della poesia novecentesca, valorizzando l'uso dell'ironia e la teatralizzazione dell'io. Il risultato di questa operazione è una leggerezza tanto spietata quanto acuta. Le vicende personali dell'autore, inserite nel contesto della società industriale e caratterizzate da toni crepuscolari con punte di leggerezza quasi giocosa, costituiscono il nucleo tematico delle raccolte _La vita in versi_ (1965), _Autobiologia_ (1969), _O Beatrice_ (1972) e _Il male dei creditori_ (1977). Con _Il ristorante dei morti_ (1981) e _Il lume dei tuoi misteri_ (1984), il tono si fa più riflessivo e lo stile risulta essenziale. In _Salutz_ (1986) il linguaggio diviene più prezioso e ricercato, preludendo alle raccolte successive, tra cui _Fortezza_ (1990) e le prose riflessive di _Andare in Cina a piedi_ (1992).

La poetica di Amelia Rosselli (1930-1996) si distingue per una fusione tra corporeità ed astrazione mentale. La sua poesia coagulava una precisione espressiva in un movimento vibrante di ritmi e suoni. Tra le raccolte principali si annoverano _Variazioni belliche_ (1964), _Serie ospedaliera_ (1969), _Documento_ (1976), _Impromptu_ (1981) e _La libellula_ (1985).

Giovanni Raboni (1932-2004), originario di Milano, si inserisce inizialmente nel solco della cosiddetta Linea Lombarda con le sue prime raccolte, tra cui _Le case della Vetra_ (1966) e _Cadenza d'inganno_ (1975). In queste opere emergono una tensione morale e civile persistente, una profonda inquietudine religiosa e una forte ambientazione meneghina. Nelle raccolte successive, come _Nel grave sogno_ (1982), _Ogni terzo pensiero_ (1993) e _A tanto caro sangue_, la produzione poetica di Raboni si amplia significativamente, superando il limite della catalogazione come semplice poeta lombardo.

Nel solco della Linea Lombarda si colloca anche Tiziano Rossi (1935), il quale, a partire da _La talpa imperfetta_ (1968) fino a opere come _Miele e no_ (1988) e _Il movimento dell'adagio_ (1993), esplora le pieghe del quotidiano alla ricerca di un eroismo tanto silenzioso quanto strenuo, interrogandosi con sguardo laico sulle ragioni che giustificano la nostra presenza nel mondo.

Alda Merini (1931-2009) è stata un'autrice di eccezionale sensibilità, segnata da lunghi periodi di ricovero dovuti a una malattia mentale. Nella sua poesia convergono elementi autobiografici, riflessioni religiose ed espliciti richiami amorosi. Tra le raccolte liriche principali figurano: _La presenza di Orfeo_ (1953), _Nozze romane_ (1955), _La Terra Santa e altre poesie_ (1984), _Vuoto d'amore_ (1991) e _Superba è la notte_ (2000). Di grande rilievo sono anche le prose, come _L'altra verità. Diario di una diversa_ (1986), _Il tormento delle figure_ (1990) e _Ballate non pagate_ (1995).

Vivian Lamarque (1946) ha sviluppato una poetica degli opposti, caratterizzata da una giocosità intrisa di dolore, una crudeltà avvolta nella gentilezza. Il grande poeta Vittorio Sereni descrisse questo approccio parlando di "rovesciamenti come coltellate". Tra le sue numerose pubblicazioni si annoverano _Teresino_ (1981), _Poesie dando del lei_ (1989) e _Una quieta polvere_ (1996). Oltre che poetessa, è anche traduttrice (Prévert, La Fontaine, Baudelaire) e autrice di numerosi libri per bambini, come _Il libro delle ninne-nanne_ (1989), _La bambina che mangiava i lupi_ (1998) e _Unik, storia di un figlio unico_ (1999).

La poesia di Patrizia Valduga (1953), rigorosamente incastonata nell'uso del linguaggio tradizionale, in particolare nella quartina petrarchesca, rielabora e attualizza temi quali l'eros, lo smarrimento dell'anima, il dolore e la sofferenza. Tra le sue opere principali si trovano _Medicamenta_ (1982), _Donna di dolori_ (1991), _Requiem_ (1994) e _Cento quartine e altre storie d'amore_ (1997).

== La narrativa

Paolo Volponi (1924-1994), originario di Urbino, emerge come uno degli scrittori che hanno meglio intuito le contraddizioni profonde e le urgenze della società industriale. Le sue opere affrontano una razionalità nuda, capace però di interrogarsi in modo drammatico sui presagi e le ambizioni utopiche.  

Il rapporto con il mondo industriale si trova al centro di _Memoriale_ (1961), dove la vicenda di un operaio nevrotico diventa spunto per scoprire la carica sovversiva insita nella "diversità" e nella follia, contrapposte alla massificazione del neocapitalismo. Con _La macchina mondiale_ (1965), attraverso il sogno utopico di un contadino che immagina un nuovo sistema tecnologico per riequilibrare il mondo, Volponi manifesta fiducia nella capacità di liberazione dell'essere umano.  

Gli emarginati sono centrali anche in titoli come _Corporale_ (1974) e _Il sipario ducale_ (1975). Nel 1978 firma il romanzo di fantascienza _Il pianeta irritabile_, ambientato in un futuro post-tecnologico. Tornando a temi più personali, con _Il lanciatore di giavellotto_ (1981) approfondisce atmosfere intime. Con _Le mosche del capitale_ (1989) crea un'allegoria grottesca sui limiti dell'ideale democratico nel contesto industriale, mentre _La strada per Roma_ (1991) esplora la separazione dall'adolescenza e dal luogo natale.

Luigi Malerba, pseudonimo di Luigi Bonardi (1927-2008), nato in Emilia e conosciuto anche come sceneggiatore e regista, concepisce la letteratura come un mezzo per deconstruire le ossessioni del mondo moderno. La sua produzione inizia nel solco sperimentalista del Gruppo '63 con opere quali _La scoperta dell'alfabeto_ (1963), _Il serpente_ (1966) e _Salto mortale_ (1968). Nei lavori successivi, pur utilizzando strutture narrative più tradizionali, continua a coltivare l'interesse per l'invenzione linguistica e la satira, pubblicando titoli come _Le rose imperiali_ (1975), _Diario di un sognatore_ (1981), _Il pianeta azzurro_ (1986), _Le galline pensierose_ (1994) e _Le maschere_ (1994).

Giuseppe Pontiggia (1934-2003), originario di Como, è stato un autore di romanzi caratterizzati da una narrazione raffinata e da una meticolosa ricerca linguistica, capaci di colpire per il loro realismo ricco e al tempo stesso intriso di immaginazione. Dopo il suo debutto con _La morte in banca_ (1959), i suoi titoli più celebri includono _L'arte della fuga_ (1968), contraddistinto da un marcato spirito sperimentale; _Il giocatore invisibile_ (1978); _Il raggio d'ombra_ (1983); _La grande sera_ (1989); e _Vite di uomini non illustri_ (1993). Con _Nati due volte_ (2000), ha affrontato con sensibilità il complesso tema della disabilità.

Alberto Bevilacqua (1934-2013), parmense, spicca per la grazia e l'intelligenza nel tratteggiare indagini psicologiche profonde. I suoi romanzi si configurano come un'indagine su sentimenti o caratteri umani. La parte migliore della sua vasta produzione narrativa (_La califfa_, 1964; _Questa specie d'amore_, 1966; _L'occhio del gatto_, 1968; _Una città in amore_, 1970) ruota attorno alla città di Parma, descritta come popolare e passionale, sullo sfondo di lotte operaie, movimenti sindacali e resistenza antifascista. Tra le opere successive si annoverano _Il curioso delle donne_ (1983); _La donna delle meraviglie_ (1984); _I sensi incantati_ (1991); e _Gli anni struggenti_ (2001).

Vincenzo Consolo (1933-2012), nato a Sant'Agata di Militello, è considerato un maestro degli aspetti più tipici della letteratura siciliana: il grottesco, una lingua ricca e stratificata, e la potenza espressiva intrisa di una sensualità barocca. Il suo esordio avviene con il romanzo breve _La ferita dell'aprile_ (1963), scritto in una prosa che mescola memoria e sperimentazione. Rifacendosi a Sciascia per la razionalità lucida e a Gadda per la lezione del plurilinguismo, Consolo ha raggiunto un'importante maturità espressiva con _Il sorriso dell'ignoto marinaio_ (1976). Questo romanzo, scritto in una lingua che combina elementi colti e popolari, ricostruisce eventi della Sicilia del 1860, segnando il fallimento del Risorgimento e perpetuando i temi della violenza e della sopraffazione storica.

Con _Retablo_ (1987), Consolo sviluppa una narrazione su più livelli ambientata in una Sicilia settecentesca e barocca, dove emerge un parallelismo con la società contemporanea, frammentata e disgregata. Tematiche simili si ritrovano nei racconti _Le pietre di Pantalica_ (1988) e nei suoi romanzi successivi come _Nottetempo, casa per casa_ (1992), _L'olivo e l'olivastra_ (1994) e _Di qua dal faro_ (1999).

Più semplice e contenuta è invece la produzione di Gesualdo Bufalino (1920-1996), originario di Comiso. Emerso solo in età avanzata come scrittore, ha raggiunto immediato consenso con il romanzo _Diceria dell'untore_ (1981). Quest'opera ruota attorno a un amore nato in un sanatorio, sullo sfondo della morte, tra angosce, desideri e sensi di colpa, con una struttura narrativa che richiama Proust. In questo contesto, la letteratura e la memoria si presentano come unici mezzi salvifici contro la durezza del reale. Su questa scia si collocano anche altre opere significative come _Museo d'ombre_ (1982); _Argo il cieco ovvero i sogni della memoria_ (1984); _L'uomo invaso_ (1986); e _Le menzogne della notte_ (premio Strega 1988).

Sebastiano Vassalli (1941-2015), originario di Genova, si distingue per una narrativa solida arricchita da un forte spirito polemico e satirico. Ha iniziato la sua carriera all'interno del Gruppo '63 con alcuni testi sperimentali, caratterizzati da una satira mirata a smascherare i luoghi comuni del linguaggio istituzionale.

Tra le sue opere, spiccano romanzi quali _L'arrivo della lozione_ (1976), _Abitare il vento_ (1980), _Mareblu_ (1982) e _La notte della cometa_ (1984), un romanzo-biografia dedicato a Dino Campana. Ha poi esplorato temi legati alla storia italiana con _L'oro del mondo_ (1985), incentrato sul periodo postbellico e sul preludio al boom economico, e _Sangue e suolo_ (1985), che indaga la complessa convivenza tra le comunità italiane e tedesche in Alto Adige. Negli ultimi anni, Vassalli ha orientato la sua ricerca verso il passato, pubblicando romanzi neostorici come _La chimera_ (1990) e _Cuore di pietra_ (1996). Tra le opere più recenti si annovera _Archeologia del presente_ (2001).

Antonio Tabucchi (1943-2012), nativo di Pisa, è noto per il suo interesse verso atmosfere evanescenti e ricche di simbolismo. Prediligendo il romanzo breve, ha dato vita a numerose opere caratterizzate da un realismo semplice ma evocativo, tra cui _Piazza d'Italia_ (1975), _Il gioco del rovescio_ (1981), _Notturno indiano_ (1984) e _Piccoli equivoci senza importanza_ (1985). Altre pubblicazioni includono _L'angelo nero_ (1991) e _Requiem_ (1991). Con il romanzo _Sostiene Pereira_ (1994), Tabucchi ha ottenuto un notevole successo anche a livello internazionale. Nel 2001 è stato pubblicato _Si sta facendo sempre più tardi_, un originale romanzo epistolare.

Pier Vittorio Tondelli (1955-1991), nato in Emilia, è diventato, soprattutto dopo la sua prematura scomparsa, il simbolo della generazione legata ai movimenti giovanili degli anni '70. Dopo il successo dei racconti _Altri libertini_ (1980), ha dato alle stampe _Pao Pao_ (1982), che analizza comportamenti giovanili anarchici e disgregati permeati da un materialismo ingenuo. Con _Rimini_ (1986), Tondelli ha descritto il cinismo della società rampante degli anni '80, attraverso una narrazione frammentaria che mette in luce la solitudine dei personaggi. La sua ultima opera, _Camere separate_ (1989), racconta con intensità drammatica una storia d'amore omosessuale.

Dacia Maraini (1936) si è imposta al pubblico con il romanzo _L'età del malessere_ (1963). Tra le sue opere successive si trovano _Memorie di una ladra_ (1972), _Storia di Piera_ (1980), _La lunga vita di Marianna Ucria_ (1990) e _Bagheria_ (1993), quest'ultimo di taglio autobiografico. Con _Buio_ (1999) e altre opere, Maraini ha spesso affrontato tematiche legate alle difficili realtà delle donne. Oltre alla narrativa, si è dedicata alla poesia (_Dimenticato di dimenticare_, 1982; _Crudeltà all'aria aperta_, 1996), al teatro (_Camille_, 1995) e alla saggistica sul femminismo.

Fruttero & Lucentini ha rappresentato la firma distintiva degli scrittori Carlo Fruttero (1926-2012) e Franco Lucentini (1920-2002). Traduttori, narratori, saggisti e consulenti editoriali di grande rilievo, hanno avuto un ruolo di primo piano nella guida della collana di fantascienza Urania. La loro collaborazione si è espressa in opere originali come commedie (_La cosa in sé_, 1982) e prose satiriche (La prevalenza del cretino, 1985). Spinti da una profonda cultura e curiosità intellettuale, hanno conquistato il successo presso il grande pubblico con romanzi gialli dalla trama articolata: _La donna della domenica_ (1972) e _A che punto è la notte_ (1979). Nel 1989 hanno realizzato La verità sul caso D., completando un romanzo incompiuto di Dickens, mentre nel 1995 hanno presentato un ulteriore esempio di sperimentazione letteraria con La morte di Cicerone.

Susanna Tamaro (1957), dopo aver esordito con _La testa tra le nuvole_ (1989) e _Per voce sola_ (1991), ha raggiunto una straordinaria popolarità grazie a _Va' dove ti porta il cuore_ (1994), un romanzo che unisce racconto familiare e il ritratto emozionante di una donna passionale. Tra i suoi lavori successivi troviamo _Anima Mundi_ (1997) e Il respiro quieto (1996), questo ultimo un libro-intervista. Nel 2001 ha raccolto racconti in Rispondimi, tutti caratterizzati dalla ricerca interiore e spirituale che permea la sua produzione. Non manca anche l'impegno nella letteratura per bambini, con titoli come _Cuore di ciccia_ (1992), _Papirofobia_ (1994) e _Il cerchio magico_ (1994).

Andrea Camilleri (1927-2019), noto sceneggiatore e regista televisivo, ha raggiunto una solida notorietà tardiva attraverso romanzi e racconti intrisi dell'atmosfera siciliana: _Un filo di fumo_ (1980), _La concessione del telefono_ (1998) e _Il re di Girgenti_ (2001). La consacrazione definitiva è arrivata con la celebre serie poliziesca incentrata sul commissario Montalbano. In queste opere Camilleri ha saputo fondere magistralmente l'italiano con il dialetto siciliano, dando vita a una lingua apparentemente fittizia: tra i romanzi più noti della serie si annoverano La forma dell'acqua (1994), _Il cane di terracotta_ (1996) e _L'odore della notte_ (2001).

== In sintesi

Zanzotto Andrea Zanzotto (1921) rappresenta una delle voci poetiche più influenti della seconda metà del Novecento. La sua produzione poetica si configura come un tentativo di celare le nevrosi personali e collettive attraverso una lingua fluida e ricca di suggestioni (Dietro il paesaggio, 1951; IX Ecloghe, 1962; Fosfeni, 1983).  
Giudici Giovanni Giudici (1924) ha saputo rinnovare l'uso dell'ironia e la teatralizzazione dell'individuo, combinando una leggerezza affilata con una profonda sagacia, il tutto espresso in versi limpidi e precisi (La vita in versi, 1965; Salutz, 1986; Fortezza, 1990).  
Volponi Paolo Volponi (1924-1994) si distingue tra gli autori più capaci di cogliere la complessità e l'urgenza intrinseca della società industriale (Memoriale, 1961; La macchina mondiale, 1965; Il sipario ducale, 1975).  
Malerba Luigi Malerba (1927-2008) sfrutta abilmente l'umorismo e l'assurdo per smascherare le ossessioni del mondo moderno: la narrativa diviene un mezzo per sovvertire ciò che appare immutabile, anche quando è dichiaratamente fittizia (Il serpente, 1966; Il pianeta azzurro, 1986).  
Pontiggia Giuseppe Pontiggia (1934-2003) incarna una raffinata ricerca espressiva. Nei suoi romanzi, il realismo si intreccia con uno stile ricco e immaginativo, dando vita a narrazioni che seducono per la profondità e l'inventiva (La morte in banca, 1959; Il giocatore invisibile, 1978; La grande sera, 1989).  