#import "../../../template_normal.typ": *
//#show: frame-style(styles.thmbox)

#evidenzia[Con il termine "feudalesimo" (dal termine "feudo", derivante dal francone _fehu-od_: _fehu_, "bestiame", e _od_, "possesso", per indicare i beni mobili e immobili concessi da un capo ai suoi soldati in cambio dei servigi; latinizzato in _feodum_ o _feudum_, che in un secondo momento identificò sia il bene necessario al sostentamento di una persona subordinata sia la terra concessa in beneficio) si fa riferimento a una tipica forma medievale di organizzazione politica caratterizzata da un potere decentralizzato delegato a uomini fidati del sovrano. Questi godevano di una grande autonomia, tanto che, nell'etica cavalleresca dell'epoca, il sovrano veniva percepito come un _primus inter pares_, ovvero primo tra pari.

Il sistema feudale si consolidò nel periodo carolingio, quando il sovrano iniziò a distribuire regolarmente terre ai suoi soldati, chiamati vassalli, che giuravano fedeltà e rendevano omaggio al loro signore. Successivamente, con il Capitolare di Quierzy dell'877, i feudi maggiori divennero ereditari, inaugurando un processo di secolarizzazione della società feudale. Mentre nel periodo carolingio l'assegnazione di funzioni pubbliche avveniva in modo informale, come atto di generosità personale del sovrano verso il vassallo, nel XII secolo si trovavano ormai due poteri pubblici definiti: da un lato il sovrano e dall'altro il singolo signore feudale, al quale venivano attribuiti funzioni e diritti ereditari. Infine, con la nascita delle prime monarchie nazionali, l'importanza politica dei signori feudali si ridusse progressivamente, poiché i sovrani iniziarono ad affidarsi sempre più a funzionari burocratici professionisti per l'amministrazione dello Stato.]

== Origini del sistema feudale

Le prime manifestazioni del sistema feudale si possono individuare nella regione tra il Reno, la Loira e la Borgogna. Tuttavia, organizzazioni simili al feudalesimo, pur con caratteristiche diverse, erano già presenti in Inghilterra e nella penisola italiana. Già durante il declino dell'Impero romano si riscontravano forme rudimentali di rapporti feudali: i più deboli cercavano protezione da individui più influenti, i quali, a loro volta, necessitavano del supporto e della lealtà degli altri per mantenere la propria posizione. Da questa pratica derivò l'istituto della _commendatio_: un contratto tra protettore e protetto, vincolante per entrambi e con durata vitalizia. I servizi forniti e gli aiuti concessi potevano variare; spesso il potente cedeva al suo subordinato una porzione di terra (in proprietà o più comunemente in usufrutto) affinché quest'ultimo potesse garantirsi sostentamento.

Nel caso delle terre date in usufrutto (denominate _tenure_ nelle aree francofone e _Leihe_ in quelle germaniche), il beneficiario era tenuto a versare un tributo in denaro o, più frequentemente, in natura. La tutela offerta dal benefattore era nota come _mundium_. Tra le popolazioni germaniche era inoltre diffusa l'istituzione del _comitatus_, che indicava il gruppo di soldati che sceglievano volontariamente di combattere per un capo, prestando giuramento di fedeltà personale. I membri del comitato vennero successivamente denominati "vassalli", prendendo origine dal termine celtico _gwas_, utilizzato già nel VI secolo.

#note(top)[== *🧩* La cavalleria <senza_numero>

Fin dall'alto medioevo si formò una casta militare di cavalieri, combattenti che potevano disporre a proprie spese di un cavallo e dell'armatura. Essi avevano il compito di aiutare il principe, a cui erano legati da vincoli di vassallaggio, nella difesa dei deboli. 

Nella Francia del XII sec. fiorì nelle corti dei grandi signori feudali un'etica cavalleresca che esaltava le virtù della lealtà verso il proprio signore e gli altri cavalieri, oltre a valori quali la prodezza (coraggio e capacità di maneggiare le armi), la generosità (intesa come disinteresse per la ricchezza) e la cortesia, cioè la capacità di attenersi a un particolare codice di comportamento verso le dame dell'aristocrazia (ancor oggi per indicare l'atteggiamento cortese verso le donne si usa il termine "cavaliere"). 

Questa stilizzazione dell'ideale cavalleresco si manifestò nella pratica dei tornei (combattimenti simulati, regolati da norme rigorose) e nella fioritura dell'amor cortese in tutte le corti europee. Con l'ascesa delle monarchie nazionali l'appartenenza alla cavalleria diventò segno di un particolare rapporto di benevolenza tra cavaliere e autorità dello Stato, che si traduceva nel conferimento di una decorazione e del titolo di cavaliere (con una accezione mantenuta sino a oggi).]

== Strutture del sistema feudale

L'organizzazione della società basata sulla fedeltà personale fu ampiamente adottata dai sovrani carolingi, rendendo il sistema del vassallaggio una pratica diffusa in tutto l'Occidente. Questo strumento giocò un ruolo centrale nella coesione politica dell'epoca. Attraverso il rito della "immixtio manuum" (commistione delle mani), il vassallo giurava fedeltà al monarca, instaurando un legame bilaterale tra due soggetti socialmente diseguali. Il rapporto veniva formalizzato con un giuramento solenne.

I tre pilastri fondamentali del feudalesimo erano il vassallaggio, il beneficio e l'immunità. Il vassallaggio costituiva un rapporto di subordinazione tra un protettore e un protetto. Questo sistema si diffuse ampiamente tra l'VIII e il IX secolo, prevalentemente per motivi militari, ma anche per esigenze amministrative. La mancanza di un esercito permanente spinse i maestri di palazzo e successivamente i sovrani carolingi a reclutare uomini per combattere durante emergenze e funzionari in grado di gestire un territorio sempre più vasto.

Il vassallo aveva due obblighi principali: l'aiuto e il consiglio. L'aiuto si traduceva principalmente nel servizio militare a cavallo, che solo in rari casi poteva essere sostituito da un pagamento in denaro. In situazioni straordinarie, come il riscatto del signore fatto prigioniero o il finanziamento di un suo viaggio in Terra Santa, il vassallo era tenuto anche a fornire un aiuto monetario. Il consiglio invece rappresentava il dovere di rispondere alla convocazione del signore per esaminare cause giudiziarie o esprimere opinioni su questioni di interesse.

Dal canto suo, il signore aveva l'obbligo di garantire la protezione del vassallo, difenderlo dai suoi nemici e supportarlo nelle cause giuridiche. Questo rapporto di fedeltà era vitalizio, ma poteva essere interrotto qualora uno dei due contraenti non rispettasse i propri doveri, una violazione nota come fellonia. Il beneficio era costituito dalla concessione di un bene materiale (res), solitamente una terra o una carica pubblica.

Le terre concesse provenivano dal patrimonio del sovrano, sebbene spesso fossero confiscate alla Chiesa. Carlo Martello e i suoi successori si impossessarono di numerosi territori ecclesiastici, ma successivamente furono costretti a cambiare strategia, avendo bisogno del sostegno della Chiesa franca. Le concessioni iniziarono a essere regolate attraverso contratti chiamati precarie.

Questo tipo di accordo prevedeva l'assegnazione di un terreno in usufrutto dietro richiesta formulata in una lettera di preghiera (_epistula precaria_), che implicitamente includeva l'obbligo di versare un censo o, in alternativa, prestare un servizio. Da questa prassi derivò l'uso del termine _beneficium_ per designare il bene concesso in usufrutto, termine che in epoca successiva fu sostituito da _feudum_, di origine franca.

Il terzo elemento costitutivo del sistema feudale nel periodo medievale è identificato nell'immunità. Nel contesto del diritto romano, il concetto di _immunitas_ si riferiva all'esenzione dal pagamento di determinate imposte, che potevano essere di natura personale o patrimoniale. Questo privilegio era concesso esclusivamente per particolari tipologie di beni e a specifiche categorie di individui. Tuttavia, già durante le fasi finali dell'Impero Romano, tale esenzione aveva progressivamente perso la sua connotazione meramente fiscale. L'immunità veniva invece associata alla delega di funzioni amministrative ed esattive a soggetti designati.

Questa forma di immunità venne ulteriormente consolidata durante il Medioevo, diventando una caratteristica distintiva del sistema feudale. I proprietari dei feudi, oltre a detenere diritti su terre e risorse, iniziarono a esercitare anche ruoli legati alle funzioni pubbliche. Le relazioni feudali evolsero così in un sistema che assomigliava sempre di più a un'amministrazione politica decentralizzata. Un esempio storicamente significativo fu l'opera di Carlo Magno, il quale assegnò vaste porzioni territoriali, come marche e contee, a marchesi e conti. Questa politica di decentramento mirava a rendere più efficiente la gestione dell'enorme Impero carolingio.

Anche i vescovi e gli abati acquisirono funzioni analoghe nelle loro terre, contribuendo così a estendere il modello feudale alla stessa Chiesa. Con i successori di Carlo Magno, però, questo sistema di decentramento si trasformò gradualmente in un regime di autonomia. I signori locali iniziarono a esercitare libertà sempre maggiori, superando frequentemente i confini stabiliti dall'autorità reale e privilegiando interessi personali o legati al proprio feudo, piuttosto che quelli dell'Impero. L'autorità del sovrano subì un indebolimento progressivo, cedendo spazio al crescente potere dei signori locali.

== L'omaggio e l'investitura

Uno degli atti fondamentali che sanciva il rapporto di sottomissione feudale era definito "omaggio". Derivante dal termine latino _homo_, uomo, questo rito simboleggiava l'accettazione da parte del vassallo di diventare "uomo" subordinato al proprio signore. Il rituale prevedeva la congiunzione delle mani tra i due contraenti, un gesto emblematico che rappresentava la dedizione del vassallo. A questo seguivano il giuramento di fedeltà, solitamente effettuato su testi sacri o reliquie, e spesso anche lo scambio di un bacio.

Nel corso del IX secolo, si verificò una diffusione della pratica di prestare omaggi multipli: molti vassalli riuscirono a ottenere benefici da diversi signori, reindirizzando i rapporti di vassallaggio a proprio vantaggio. Un ulteriore elemento rilevante era rappresentato dall'atto dell'investitura, attraverso il quale veniva formalmente conferito il beneficio o feudo. L'investitura seguiva l'omaggio e il giuramento di fedeltà e implicava la consegna simbolica di un oggetto rappresentativo del beneficio: tra questi potevano figurare uno scettro, una spada, un anello, un frammento di terra o uno stendardo. Nel caso in cui il beneficiario fosse un vescovo, l'oggetto simbolico poteva essere una croce o un pastorale.

Attraverso questa cerimonia, il vassallo acquisiva il diritto di usufruire del feudo, benché la proprietà rimanesse formalmente nelle mani del concedente. Questo sistema sanciva una relazione reciproca che fungeva da fondamento per le dinamiche politiche e sociali dell'epoca feudale.

== Il capitolare di Quierzy: la prima e la seconda età feudale

Il Capitolare di Quierzy, emanato da Carlo il Calvo nell'877, stabilì ufficialmente l'ereditarietà dei feudi maggiori, una pratica già diffusa da tempo. Questa disposizione consentiva ai figli di subentrare ai padri senza perdere i beni immobili, garantendo al contempo ai sovrani un supporto stabile e continuo di uomini al loro servizio. Con il tempo, divennero ereditarie anche le funzioni amministrative connesse alla concessione delle terre.

La possibilità per i vassalli di nominare subordinati all'interno dei propri feudi, detti valvassori (che a loro volta potevano designare i valvassini), diede origine a una vera e propria gerarchia feudale. Con la deposizione di Carlo il Grosso nell'887 da parte di un'assemblea di feudatari, l'Europa entrò in una fase di anarchia e conflitti quotidiani, caratterizzata da lotte per il potere tra feudatari, ribellioni armate dei vassalli e incursioni di cavalieri e briganti.

Di fronte a questa situazione, la Chiesa intervenne con l'istituzione della "tregua di Dio", imponendo la sospensione delle attività belliche in determinati periodi. Le frequenti invasioni da parte di Normanni, Ungari e Saraceni spinsero gran parte della popolazione a cercare protezione presso i castelli dei signori feudali, che divennero così centri vitali per la vita civile ed economica del feudo. Durante i secoli X e XI, definiti come "prima età feudale", l'ereditarietà delle funzioni pubbliche finì per neutralizzare di fatto il controllo del re sui territori formalmente sotto il suo dominio, ma concessi in feudo.

Anche gli imperatori delle dinastie di Sassonia e Franconia, quando attribuivano privilegi o immunità a laici ed ecclesiastici, non facevano altro che ratificare situazioni già consolidate e indipendenti dalla loro volontà. Nel 1037, con la Constitutio de feudis promulgata dall'imperatore Corrado II il Salico, venne sancita l'ereditarietà anche dei feudi minori nel tentativo di ridurre l'influenza dei vassalli maggiori, ormai completamente fuori dal controllo centrale.

Nel XII secolo, anche la Chiesa, con la riforma promossa da Gregorio VII, cercò di affermare l'autorità del Papato su diocesi e abbazie, sottraendole alla consuetudine di considerarle come benefici feudali. Alla prima età feudale seguì, a partire dal XII secolo, il periodo del feudalesimo classico o seconda età feudale. In questa fase, vassallaggio e feudi furono regolati da un sistema completamente formalizzato basato su raccolte sistematiche di consuetudini e leggi feudali.

Questo fenomeno trovò particolare applicazione nei Regni normanni d'Inghilterra e del Sud Italia, nei principati franco-latini d'Oriente, nel Regno di Francia sotto i Capetingi e nei principati tedeschi. Al potere centrale del sovrano si affiancava quello dei singoli feudatari, una dinamica che venne progressivamente contrastata dalle nascenti monarchie nazionali, le quali iniziarono a limitare la formazione di nuovi centri autonomi di potere e a imporre la loro autorità sui potentati feudali esistenti.

#pagebreak()
#set page(fill: main_storia.lighten(90%))
== In sintesi <senza_numero>

/ Sistema feudale: Il sistema feudale ha le sue prime radici nel periodo successivo alla caduta dell'Impero Romano. Tra gli elementi fondamentali che ne hanno favorito l'evoluzione, spiccano le istituzioni della _commendatio_ e del _comitatus_.

/ Feudalesimo nell'era merovingica e carolingia: Nel corso dell'VIII e IX secolo, il vassallaggio si diffonde ampiamente. Sovrani e maestri di palazzo necessitano di uomini per la difesa militare e di funzionari per gestire i loro domini. Per consolidare il potere, i sovrani carolingi sottraggono numerosi terreni alla Chiesa destinandoli come benefici feudali. Carlo Magno utilizza queste terre per affidarle a conti, marchesi, vescovi e abati, con il compito di amministrare e controllare specifici territori dell'Impero. \ Con il capitolare di Quierzy del 877, viene stabilita l'ereditarietà dei feudi maggiori e delle cariche a essi legate. Nel 887, Carlo il Grosso viene deposto da un'assemblea di feudatari, un evento che simboleggia il crescente potere di questa classe.

/ Prima età feudale: In Europa si vive un periodo di anarchia: lotte interne tra feudatari e vassalli per il controllo del potere sono all'ordine del giorno, mentre cavalieri e bande di briganti seminano violenza e saccheggi. Inoltre, le incursioni di Normanni e Saraceni contribuiscono ad alimentare il clima d'insicurezza, spingendo le popolazioni a cercare rifugio nei castelli. Nel 1037, la Constitutio de feudis sancisce l'ereditarietà anche dei feudi minori, consolidando ulteriormente il sistema feudale.

/ Seconda età feudale: Con Papa Gregorio VII si cerca di sottrarre diocesi e abbazie alla sfera dei benefici feudali, riportandole sotto il diretto controllo ecclesiastico. Durante questa fase, vassallaggio e feudo raggiungono una struttura più definita grazie a raccolte sistematiche di leggi e consuetudini. \ Pur continuando a esistere, il potere dei feudatari viene progressivamente limitato dall'affermazione delle monarchie nazionali. Questi nuovi stati centralizzati impediscono la nascita di ulteriori nuclei autonomi e rafforzano il controllo sui centri di potere già esistenti.