#import "../../../template_tufte.typ": *
#show: frame-style(styles.thmbox)

#evidenzia[L'economia dell'età feudale era prevalentemente di natura rurale e trovava il suo fulcro organizzativo nelle ville, unità agrarie costituite da una pluralità di poderi confinanti. Ciascuna villa era amministrata da un proprietario che gestiva direttamente una porzione di terra, avvalendosi dell'operato dei servi, mentre la rimanente parte veniva concessa a dei coloni che corrispondevano un affitto in natura. I contadini legati alla terra che lavoravano non avevano la possibilità di abbandonarla, condizione che si perpetuava di generazione in generazione. Per questa ragione si consolidò l'appellativo di "servi della gleba", indicando una subordinazione che dipendeva direttamente dal possesso e dalla coltivazione della terra.

Tra la fine del X secolo e l'inizio dell'XI, la suddivisione dei ruoli sociali fu oggetto di una articolata riflessione dottrinale. Le funzioni specifiche delle tre principali categorie sociali—ecclesiastici, signori laici e contadini—vennero interpretate come espressione delle differenze naturali fra gli individui, già individuate dai padri della Chiesa nel concetto tripartito di uomini pneumatici (spirituali), psichici (dominati da inclinazioni dell'anima) e ilici (soggetti principalmente agli impulsi corporei).

A partire dall'anno Mille, si registrò un generale risveglio culturale e socio-economico. L'intensificazione dei traffici commerciali acquisì particolare rilievo, soprattutto in Italia, grazie al ruolo giocato dalle repubbliche marinare. Contestualmente, si assistette a un trasferimento del potere dalle mani della nobiltà a quelle della crescente classe media. Durante l'età comunale, i comuni investirono ingenti somme per affrancare i servi residenti, contribuendo a indebolire il sistema latifondistico e favorendo la crescita delle popolazioni urbane.

Nelle zone rurali si avviarono significative opere di bonifica e dissodamento, segnando l'inizio del declino delle strutture feudali e l'emergere di nuovi ceti sociali. La borghesia—composta da giuristi, mercanti, medici e piccoli artigiani—cominciò a partecipare attivamente alla vita politica. Il trend demografico fu caratterizzato da un continuo incremento per tre secoli, dal 1000 al 1300, interrotto bruscamente dall'epidemia di peste del 1346 e successivamente dalla Guerra dei Cento Anni.]

== Economia e società feudali

La grande proprietà fondiaria costituiva il presupposto fondamentale del sistema feudale e rappresentava la base dell'organizzazione economica. Le ville, pilastri di tale economia, si articolavano in due parti distintive: la parte dominica, gestita direttamente dal proprietario (dal termine latino *dominus*, "signore"), e la parte massaricia, composta dai mansi. Questi ultimi erano appezzamenti di terreno contenenti un'abitazione, un orto e aree coltivabili; talvolta erano incluse anche vigne. I mansi erano lavorati da servi o uomini liberi che dovevano corrispondere un canone al padrone. Inoltre, in determinati periodi dell'anno particolarmente cruciali—come l'aratura, la semina o la vendemmia—erano vincolati a prestare lavoro gratuito nella parte dominica, formando quelle prestazioni obbligatorie note come *corvées*.

Le mansioni agricole non esaurivano gli obblighi dei contadini. Essi dovevano partecipare alla costruzione e manutenzione di infrastrutture quali ponti e strade, nonché edifici. Le donne erano impegnate nella filatura e tessitura al servizio del signore. La parte dominica della villa ospitava la *curtis*, un'area recintata spesso fortificata, che includeva l'abitazione del *dominus*, un frutteto e un orto, oltre a strutture dedicate a vari scopi produttivi come cucine, forni e frantoi. In questo spazio erano inoltre presenti magazzini e dormitori destinati ai servi impegnati costantemente nelle attività legate alla parte dominica. 

Spesso le ville raggiungevano dimensioni significativamente grandi, con una parte dedicata alle superfici coltivabili, mentre boschi e pascoli coprivano aree estese. Sebbene vengano generalmente considerate autosufficienti, nel IX e X secolo vi furono numerose fiere e mercati che favorivano il commercio tra diverse ville. Questo sistema economico era ulteriormente sostenuto dal fatto che alcuni signori possedevano più ville, aumentando le possibilità di scambio.

Anche i centri urbani erano piuttosto sviluppati e non si limitavano a ospitare abitazioni, officine e orti, ma includevano anche campi circostanti. Tra i più rilevanti si possono citare Milano, Tours, Arles, Metz, Parigi e Aquisgrana.

== Le tecniche agricole

L'aratro costituiva lo strumento fondamentale per la lavorazione dei terreni. Nei territori argillosi e pesanti del nord Europa si utilizzava un modello avanzato dotato di versoio, che permetteva di rivoltare la terra facilitando l'aratura. Per ottimizzare il lavoro, i campi venivano disposti in forma allungata, riducendo così il numero di percorsi necessari per completare l'operazione e le manovre successive.

La resa dei terreni era migliorata grazie all'adozione di sistemi di rotazione biennale e triennale. Con la rotazione biennale, il terreno veniva suddiviso in due parti: una coltivata a cereali e l'altra lasciata a maggese, ma comunque arata per consentire al suolo di rigenerarsi. L'anno successivo le due porzioni venivano invertite. Nel sistema triennale, invece, il terreno era diviso in tre sezioni: una destinata ai cereali invernali (segale e frumento), una ai cereali primaverili (avena e orzo) e una terza semplicemente arata. Questa tecnica garantiva un miglior sfruttamento delle risorse agricole, oltre a fornire ampie quantità di avena utili per alimentare i cavalli, preferiti ai buoi per la loro maggiore velocità nel traino dell'aratro. Durante questo periodo si diffusero anche la ferratura degli zoccoli dei cavalli e l'utilizzo su larga scala dei mulini ad acqua.

== La dottrina dei tre ordini sociali

Tra la fine del X e l'inizio dell'XI secolo emerse la dottrina dei tre ordini, che regolava la suddivisione della società feudale. Tale dottrina si ricollegava agli insegnamenti dei Padri della Chiesa, a loro volta influenzati da Platone nella "Repubblica", dove si analizzava l'analogia tra organizzazione sociale e divisione dell'anima nelle sue parti: egemonica, irascibile e concupiscibile. L'anima contempla e governa nella sua parte superiore, è volitiva e guerriera nella media, e segue le inclinazioni corporee nella parte inferiore, che deve essere subordinata alle prime.

Nel Medioevo, il primo ordine corrispondeva alla casta degli *oratores*, composta da monaci e sacerdoti dediti alla contemplazione, alla preghiera e alla trasmissione degli insegnamenti. Vescovi, abati ed ecclesiastici in generale godevano del diritto di sostentarsi grazie alle rendite delle loro proprietà. Il secondo ordine era costituito dai signori laici, detti *bellatores* per via del loro compito principale: la guerra. 

La loro principale occupazione era volta al mantenimento e alla tutela dell'ordine e della giustizia, sia a livello interno che esterno. In particolare, si dedicavano alla guerra, dalla quale derivavano consistenti bottini che andavano ad aggiungersi ai proventi dei loro vasti latifondi. Inoltre, praticavano attività quali la caccia, i tornei e altre pratiche conformi agli ideali cavallereschi propri della classe nobiliare.

Il terzo ordine, quello dei laboratores, si distingueva per l'impegno nel lavoro manuale, attraverso il quale garantivano il sostentamento sia per sé stessi che per i loro servitori. La loro partecipazione alla società tradizionale avveniva esclusivamente in forma indiretta, in quanto le loro limitate possibilità intellettuali non consentivano un accesso a conoscenze di livello superiore.

Questa dottrina venne diffusa principalmente da alcuni vescovi francesi nel tentativo di mitigare la disgregazione sociale dell'XI secolo. Essi richiamavano i membri dei diversi ordini sociali al principio dell'origine divina della suddivisione sociale, nonostante le imperfezioni proprie della natura umana e la confusione dei tempi impedissero talvolta una perfetta corrispondenza tra le funzioni ricoperte e il ruolo attribuito.

== La rinascita dell'anno mille

L'Europa dei secoli X e XI fu caratterizzata da una significativa espansione economica, alimentata da due fattori principali: l'aumento demografico e la cosiddetta "rivoluzione agraria". Sebbene i dati siano incerti, si stima che la popolazione registrò un incremento di circa trenta milioni di individui. Tale crescita, abbastanza costante per tre secoli, ebbe una drammatica interruzione con l'epidemia di peste che investì l'Europa tra il 1346 e il 1350.

Uno degli indicatori più evidenti dell'espansione demografica fu rappresentato dall'intensificazione delle operazioni di disboscamento e dal corrispondente ampliamento delle superfici adibite all'agricoltura. Numerosi documenti attestano tale trasformazione: dagli accordi di colonizzazione di nuove terre alle mappe di villaggi e terreni dissodati, dalle nuove imposte decimali clericali al sorgere di borghi e città, o all'ampliamento delle fortificazioni esistenti.

Le condizioni che favorirono l'incremento demografico furono molteplici: il miglioramento delle tecniche agricole, che garantì una maggiore disponibilità alimentare; la riduzione del tasso di mortalità infantile; e un progressivo aumento della durata della vita. A ciò si aggiunse il venir meno delle invasioni da parte di Normanni, Ungari e Saraceni, unitamente a un miglioramento delle condizioni climatiche che contribuì significativamente ad elevare la qualità della vita. Boschi e paludi furono convertiti in terre coltivabili grazie all'attività dei monaci e dei signori terrieri, mentre i contadini ampliarono i loro possedimenti agricoli.

Di particolare rilevanza fu l'opera di colonizzazione e dissodamento nell'Europa centro-orientale, dove popolazioni tedesche si insediarono nei territori a est del fiume Elba, fondando numerosi nuclei urbani come Lubecca e Norimberga. In questo contesto, gli avanzamenti tecnologici in ambito agricolo giocarono un ruolo cruciale. Tra le innovazioni si annoverano l'impiego dell'aratro a versoio, la sostituzione dei buoi con cavalli per il traino grazie alla ferratura degli zoccoli, la diffusione della rotazione triennale delle colture e l'uso sistematico dei mulini ad acqua. Questi sviluppi determinarono un sensibile incremento della produzione agricola, assicurando importanti benefici economici e sociali.

== La rinascita delle città

Nel periodo tardo-antico e nei primi secoli del Medioevo, le città avevano progressivamente perso il ruolo di fulcro politico e sociale che avevano ricoperto durante l'età classica. Tuttavia, a partire dall'XI secolo, i centri urbani conobbero una significativa rinascita, tornando ad essere popolosi e assumendo una posizione centrale nella vita economica. Le città medievali erano generalmente delimitate da mura che separavano lo spazio urbano dalle aree rurali, distinguendo simbolicamente i *cives* (cittadini civilizzati) dai *rustici* (abitanti delle campagne considerati rozzi). 

Ciononostante, la comunicazione tra città e campagna risultava molto vivace: le aree rurali fornivano prodotti agricoli e generi alimentari, mentre dalle città si diffondevano manufatti e beni artigianali. L'economia urbana era sostenuta principalmente dall'attività artigianale e mercantile, che costituivano il nucleo centrale della produzione e dello scambio. Parallelamente, si osservava un marcato incremento demografico nei centri urbani, alimentato dall'afflusso di contadini, artigiani e membri dell'aristocrazia rurale attratti dalle opportunità offerte dalle città.

Questo dinamismo economico si tradusse in un'intensificazione delle relazioni commerciali: i beni circolavano non solo in Europa, ma anche tra Africa e Asia orientale. In Italia, il fenomeno della rinascita cittadina ebbe luogo in tempi più precoci rispetto ad altre regioni d'Europa. Le cosiddette città marinare – Amalfi, Pisa, Genova e Venezia – si affermarono come protagoniste di un vasto impero commerciale. Venezia, in particolare, ottenne nel 1082 privilegi significativi dall'Impero Bizantino, quali l'esenzione fiscale per il commercio in territorio bizantino, favorendo così il suo predominio economico.

Le principali rotte fluviali del Po e dell'Adige rappresentavano vie fondamentali per il commercio interno dei veneziani, permettendo loro di connettere l'entroterra con il mercato internazionale. Le navi veneziane esportavano beni industriali, schiavi e legname proveniente dalle regioni slave, mentre importavano spezie e tessuti di lusso dall'Oriente.

== L'età comunale e signorile

Lo sviluppo economico urbano promosse la formazione di nuovi gruppi sociali, soprattutto nei centri cittadini. I cosiddetti borghesi – termine derivato da "borgo", ovvero "città" – erano rappresentati da mercanti, banchieri, artigiani, medici e giuristi che iniziarono a svolgere un ruolo sempre più rilevante nella società. Si diffuse l'usanza di organizzare tali figure professionali in corporazioni dette "arti", strutture preposte a regolare le attività economiche.

Le corporazioni esercitavano funzioni di controllo e regolamentazione attraverso una serie di prerogative: stabilivano i salari massimi, disciplinavano l'acquisto delle materie prime, fissavano i prezzi dei beni e determinavano la durata della giornata lavorativa. Nei comuni medievali emergono distinzioni tra piccoli mercanti, operanti esclusivamente nell'ambito cittadino, e grandi mercanti che intrattenevano relazioni commerciali internazionali grazie a ingenti investimenti.

L'espansione del commercio influenzò anche la vita rurale: il sistema economico tradizionale della *villa* iniziò a dissolversi, provocando un frazionamento delle proprietà terriere. Molti borghesi investirono i propri capitali diventando nuovi proprietari agricoli, mentre l'innovazione tecnologica nel settore agricolo subì un rallentamento. Inoltre, l'affrancamento di numerosi servi della gleba rappresentò un ulteriore colpo al sistema latifondista tradizionale; questi ex-servi abbandonarono le campagne per stabilirsi nelle città contribuendo alla loro crescita demografica ed economica.

Le nuove attività lavorative che si stavano diffondendo nelle città ebbero un impatto significativo sulla cultura e sull'istruzione. I mercanti e coloro che svolgevano attività commerciali necessitavano di apprendere tecniche di calcolo, redigere lettere commerciali e predisporre bilanci. Oltre alla tradizionale istruzione che dava accesso agli studi universitari, furono organizzati corsi a carattere tecnico-professionale. Gli studenti completavano poi la loro formazione come apprendisti presso botteghe già consolidate.

L'espansione degli scambi commerciali richiedeva una gestione sempre più efficiente. Fu in questo contesto che nacquero i primi libri contabili e nuove modalità di raccolta dei capitali. Tra le forme di prestito più diffuse vi erano la commenda e il prestito marittimo. Nel caso della commenda, il finanziatore investiva il proprio capitale e partecipava ai guadagni; nel prestito marittimo, invece, il mercante che intraprendeva un viaggio in mare riceveva un prestito da restituire al ritorno con un interesse del 20-25%.

A partire dal XIII secolo cominciarono a emergere le prime strutture societarie, come le compagnie a responsabilità illimitata, nelle quali ciascun socio contribuiva con una quota e partecipava ai profitti proporzionalmente. Parallelamente si svilupparono in modo significativo le attività bancarie e le loro tecniche. Le transazioni di “giro”, che permettevano al banchiere di trasferire denaro tra i clienti, e le cambiale-tratta, tramite cui si richiedeva tramite lettera a una banca di effettuare un pagamento a una persona specifica (il portatore), favorirono una migliore organizzazione finanziaria e stimolarono in maniera considerevole l'espansione economica.

== Approfondimento: iI castello

Durante le incursioni di Ungari, Saraceni e Vichinghi, la conformazione territoriale di molte zone dell'Occidente subì profondi cambiamenti. Si rese necessario creare luoghi di difesa dove la popolazione potesse trovare protezione. I grandi proprietari terrieri fecero costruire fortezze e castelli che, una volta riconosciuti dai sovrani, acquisirono carattere ereditario. Dopo la fine delle scorrerie straniere, il castello divenne simbolo di potere e strumento di dominio, permettendo a molte dinastie locali di affermarsi.

Se in origine i castelli accoglievano anche parte della popolazione, successivamente divennero residenze esclusive dei signori e delle loro famiglie. Questi luoghi divennero anche centri di incontro con altre famiglie nobili o cavalieri, favorendo la nascita di relazioni di amicizia o alleanze matrimoniali.

Il fenomeno dell'incastellamento si diffuse particolarmente in Spagna, al punto che un'intera regione prese il nome di Castiglia proprio grazie alla grande proliferazione dei castelli. Questi edifici venivano spesso costruiti in aree isolate che però garantivano il controllo su vallate e vie di comunicazione. Intorno ai castelli sorsero successivamente borghi e mercati, che costituirono i nuclei originari di nuovi insediamenti urbani.

== Approfondimento: le corporazioni

Nel XIII secolo, le corporazioni, note come "arti", svolsero un ruolo cruciale offrendo competenze tecniche e strutture organizzative per il progresso economico dei comuni italiani. A Firenze, in particolare, raggiunsero il loro apice, influenzando in modo decisivo l'evoluzione politica e istituzionale della città.

In tutte le città si distingueva chiaramente tra le "arti maggiori", ovvero le corporazioni più influenti e ricche, e le "arti minori", che raccoglievano lavoratori di settori economici meno rilevanti e non avevano un reale peso politico. Anche chi esercitava le cosiddette "arti liberali" – come medici, notai, maestri e giudici – formò corporazioni che divennero protagoniste della vita politica comunale.

Il sistema corporativo entrò in crisi nel XVIII secolo, con l'avvento della rivoluzione industriale e l'aumento della popolazione, che resero insostenibile il mantenimento dei regimi di monopolio sul lavoro e sulla produzione, fino ad allora alla base della loro forza ed efficacia.

// nessun riepilogo