#import "../../../template_tufte.typ": *
#show: frame-style(styles.thmbox)

#evidenzia[Alessandro Manzoni rappresenta una delle figure più rilevanti del Romanticismo italiano. La sua opera sancisce l'ingresso della letteratura italiana nel grande realismo romantico europeo, incarnando i valori di coesione nazionale e gli ideali del Risorgimento. Con la sua visione innovativa, Manzoni ha liberato la letteratura moderna dalla rigidità del classicismo e dall'indifferenza verso la dimensione storica, promuovendo un impegno morale e sociale che le attribuisce anche una funzione educativa.

I Promessi Sposi, sotto questo profilo, si distinguono come un'opera di straordinaria novità. La peculiarità principale del romanzo consiste nel suo carattere popolare, nell'ampio respiro narrativo e nella raffinata complessità linguistica, che lo rendono un capolavoro senza tempo.]

== La vita e le opere

Manzoni nasce a Milano nel 1785. Giulia, la madre di Alessandro Manzoni, era moglie del vecchio conte Pietro e figlia dell'illuminista Cesare Beccaria. È probabile che il padre naturale fosse Giovanni Verri, fratello dei più noti Pietro e Alessandro Verri. A partire dai sei anni, fu inserito in vari collegi: inizialmente a Merate e Lugano, poi a Milano presso il Collegio dei Nobili gestito dai Barnabiti.

Questa esperienza educativa, sebbene caratterizzata da rigidità disciplinare e da una marcata enfasi retorica, gli lasciò un ricordo poco piacevole. Tuttavia, tale formazione lo avvicinò agli autori classici e non ostacolò l'accesso alle idee emergenti dell'epoca. Durante gli anni di collegio, Manzoni lesse scrittori moderni come Alfieri, Parini e Monti, oltre a influenti pensatori francesi quali Voltaire, Jean-Jacques Rousseau, Claude-Adrien Helvétius e Condorcet.

In seguito, grazie all'influenza degli esuli napoletani Vincenzo Cuoco e Francesco Lomonaco, riuscì a superare l'astrattezza dell'Illuminismo, sviluppando una sensibilità più concreta verso la storia. Dopo aver trascorso un breve periodo convivendo col padre, nel 1805 si trasferì a Parigi per raggiungere sua madre e il suo compagno, il conte Carlo Imbonati, che però morì improvvisamente prima del suo arrivo.

A Parigi, Manzoni frequentò il salotto intellettuale della vedova Condorcet, dove conobbe Claude Fauriel, convivente della padrona di casa e studioso con il quale instaurò un rapporto di profonda amicizia. Questo ambiente di confronto con gli idéologues — intellettuali libertari e socialmente impegnati, prevalentemente legati al sensismo ma aperti ad approcci spiritualisti — contribuì a affinare in lui un forte senso di rigore morale e intellettuale.

Nel 1808 si unì in matrimonio con rito calvinista a Enrichetta Blondel, figlia di un banchiere di origini ginevrine. La relazione con la moglie divenne fondamentale nel percorso graduale di conversione religiosa che culminò nel matrimonio cattolico celebrato nel 1810. Questo cambiamento fu preceduto dal "miracolo di San Rocco", episodio durante il quale il trepido Alessandro invocò Dio per ritrovare la moglie persa nella folla parigina.

Stabilitosi in Milano, Manzoni condusse una vita riservata, dedicandosi a letture filosofiche e religiose con piena partecipazione emotiva ai dibattiti letterari e agli eventi storici che segnarono l'Italia. Dal 1816, tali dibattiti assunsero un carattere particolarmente acceso, soprattutto per la contrapposizione tra romantici e classicisti, verso i quali Manzoni dimostrò una spiccata simpatia. La conversione religiosa segnò anche un distacco dalle forme classiciste delle sue prime poesie, favorendo l'elaborazione ritmica dei suoi primi _Inni sacri_, iniziati nel 1812 e pubblicati nel 1815 con l'aggiunta de _La Pentecoste_ nel 1822.

Il suo impegno letterario si concretizzò poi nel tentativo di una tragedia ispirata ai principi romantici con _Il conte di Carmagnola_ (1820), caratterizzato da un soggetto storico che infrangeva le convenzioni classiche delle unità di tempo, luogo e azione. Parallelamente, con le _Osservazioni sulla morale cattolica_ (1819), Manzoni contrastò le posizioni anticlericali sostenute dai neoghibellini.

Nel 1819 tornò a Parigi dove ebbe modo di frequentare lo storico Jules Michelet Thierry. Da questi assimilò l'importanza di una storiografia centrata sulle masse e alcuni concetti riguardanti l'origine delle classi sociali che trovarono espressione nella tragedia _Adelchi_ (1822).

Nel 1820, Manzoni fece ritorno a Milano, conducendo una vita riservata e laboriosa, contraddistinta da pochi viaggi. Questi anni furono caratterizzati da un'alternanza tra un sereno humor e periodi di profonde crisi nervose. Nel 1821 compose due celebri odi civili: "Marzo 1821", dedicata ai moti liberali, pubblicata solo nel 1848, e "Il cinque maggio", ispirata dalla morte di Napoleone. Fu un periodo prolifico di sperimentazione artistica, durante il quale cercò febbrilmente di individuare il modo migliore per esprimere la vastità dei suoi interessi, rendendoli accessibili a un pubblico più ampio.

Questa tensione creativa lo portò al romanzo. Tra il 1821 e il 1823 scrisse "Fermo e Lucia", che venne poi sottoposto a una radicale revisione strutturale e stilistica. Il romanzo fu infine pubblicato a Milano tra il 1825 e il 1827 con il titolo "I promessi sposi". Dopo un soggiorno a Firenze nel 1827, Manzoni apportò ulteriori perfezionamenti linguistici al testo, che raggiunse la sua forma definitiva nella versione a dispense illustrate pubblicata a Milano tra il 1840 e il 1842.

Con lo scemare dell'impeto creativo, Manzoni si dedicò prevalentemente alla riflessione su problemi di teoria estetica e linguistica, oltre che a studi storiografici. Tra questi vi sono il "Discorso sopra alcuni punti della storia longobardica in Italia" del 1822, che ebbe funzione preparatoria per la tragedia "Adelchi", e le ricerche legate al romanzo "I promessi sposi", da cui scaturì l'indagine sul processo agli untori narrato ne "La colonna infame", pubblicata come appendice al romanzo nel 1842.

Tornò a riflettere sulle questioni estetiche con scritti come il discorso "Del romanzo storico e, in genere, de' componimenti misti di storia e d'invenzione" (redatto attorno al 1830 e pubblicato nel 1845) e il dialogo "Dell'invenzione" (1850), influenzato dalle idee del filosofo e amico Antonio Rosmini. Parallelamente approfondì le sue meditazioni linguistiche, che avrebbero dovuto confluire nel volume organico "Della lingua italiana", rimasto però incompiuto. Tuttavia, alcuni suoi testi, come la "Lettera a Carena" del 1846, la relazione al ministro sull'unità della lingua e altri scritti del 1868, testimoniano il suo impegno per la causa risorgimentale dal punto di vista linguistico.

=== La vita pubblica e gli ultimi anni

Manzoni trascorse prevalentemente gli ultimi anni della sua vita nell'ambito privato, segnato da numerosi lutti. La perdita di Enrichetta Blondel, provata da dieci maternità, lo spinse a scrivere il frammento "Il Natale del 1833", che insieme all'incompiuto "Ognissanti" e ai pochi versi d'occasione rappresenta l'ultimo contributo poetico dopo la svolta narrativa. Sei degli otto figli sopravvissuti, così come la sua seconda moglie Teresa Stampa (sposata nel 1840), morirono prima di lui. Nonostante queste sofferenze, la fede di Manzoni rimase salda, così come il suo interesse per le vicende politiche dell'Italia. Ne sono testimonianza il rifiuto di un'onorificenza austriaca nel 1838 e la firma dell'appello milanese rivolto a Carlo Alberto nel 1848.

Nel 1859 ricevette la visita di Garibaldi e nel 1861, in qualità di senatore del Regno, votò in favore di Roma capitale. Nel 1872 accettò la nomina a cittadino onorario di Roma nonostante l'opposizione del papa al nuovo Stato italiano. La sua morte, avvenuta a Milano nel 1873, fu accompagnata da solenni onoranze e ispirò la composizione della "Messa da Requiem" di Giuseppe Verdi.

== La produzione poetica

Le poesie giovanili di Alessandro Manzoni, antecedenti agli _Inni Sacri_, vennero dallo stesso autore rifiutate, poiché prese le distanze dai temi e dalle forme del neoclassicismo, percepite come estranee ai valori cristiani riscoperti. Tuttavia, nelle rime giovanili emerge già un'inclinazione seria e riflessiva, evidente fin dalle terzine del _Trionfo della libertà_ (1801), dove si riscontra un entusiasmo giacobino giovanile e spontaneo.

Nei versi sciolti de _L'Adda_ (1803), pur dedicati a Vincenzo Monti, Manzoni celebra in realtà Giuseppe Parini, figura di spicco della satira moralistica. Nel carme _In morte di Carlo Imbonati_ (1805-06), la figura del defunto suggerisce al giovane poeta l'esempio di Parini, Alfieri e Omero, considerati custodi di una poesia capace non solo di eternare il ricordo, ma anche di educare alla virtù.

La svolta decisiva si intravede nel progetto incompiuto di comporre dodici Inni Sacri che scandiscano l'anno liturgico, celebrando il perpetuo ritorno della verità divina. Nei cinque inni completati (_La Resurrezione_, _Il nome di Maria_, _Il Natale_, _La Passione_, _La Pentecoste_), Manzoni rinnova sia la materia che la forma: la parola diviene preghiera e si distacca dall'usura delle convenzioni letterarie. Si allontana dallo stile melodico di Petrarca e Tasso, attiva reminiscenze bibliche e adotta un linguaggio al contempo drammatico, sublime e colloquiale.

Lo stile austero e denso degli Inni Sacri, ricco di riprese interne ed echi, torna nelle odi civili, creando un parallelo tra riscatto nazionale e palingenesi religiosa a livello sonoro e ritmico. In _Marzo 1821_, l'invocazione severa a un Dio biblico e guerriero si smorza nel tono riflessivo e nella dedica al poeta tedesco Theodor Körner, caduto per la libertà della sua patria. Invece, ne _Il cinque maggio_, la passione politica lascia spazio a una profonda meditazione religiosa: dinanzi alla morte di Napoleone, Manzoni rinvia ai posteri il giudizio storico e affida alla misericordia divina il giudizio morale.

== Le tragedie

Nel cimentarsi con il genere teatrale, Manzoni avvertì la necessità di rispondere alle riserve espresse dai moralisti, religiosi o laici, nei confronti del dramma. Difese la funzione educativa della tragedia e proclamò la libertà dalle rigide "regole" classicistiche, posizioni che espresse nel 1820 nella _Lettera a M. Chauvet sull'unità di tempo e di luogo nella tragedia_ e nella _Prefazione al Carmagnola_. I temi storici scelti alludono indirettamente alla divisione e sottomissione dell'Italia contemporanea: le guerre fra gli Stati italiani ne _Il Conte di Carmagnola_ e la dominazione straniera in _Adelchi_.

La prima tragedia, _Il Conte di Carmagnola_, è segnata da un radicale pessimismo, privo di prospettive provvidenziali. Il protagonista, ex condottiero dei Visconti di Milano, passa al servizio della Repubblica di Venezia; dopo aver sconfitto i milanesi a Maclodio, suscita sospetti a causa della clemenza dimostrata verso i vinti. Ingannato dalla Serenissima, viene richiamato a Venezia e condannato a morte. La sua vicenda culmina in un tormento interiore che lo conduce dall'odio al perdono e alla fede. Se il Conte è il martire della tragedia, il vero personaggio tragico è il senatore Marco, lacerato tra l'amicizia per il Carmagnola e l'obbedienza alla ragion di stato.

L'opera _Adelchi_, anch'essa strutturata in cinque atti e composta in versi, si distingue per la sua maggiore complessità e coralità rispetto alle altre opere manzoniane. Essa narra gli eventi successivi al ripudio, da parte di Carlo Magno, della moglie Ermengarda, figlia del re longobardo Desiderio e sorella dell'eroe eponimo Adelchi. Carlo, chiamato in Italia su richiesta del pontefice, sorprende l'esercito longobardo e lo sconfigge. In una drammatica successione si consumano il tradimento di diversi duchi longobardi, l'agonia di Ermengarda, innocente e profondamente infelice, la rovina del regno di Desiderio e la morte eroica di Adelchi.  

Adelchi incarna l'ideale dell'eroe solitario e virtuoso, impegnato a difendere la sua stirpe "colpevole" fino all'estremo. Tuttavia, alla logica della politica contrappone i principi della giustizia e della pietà. Sia Adelchi sia Ermengarda pagano con la loro tragica sorte la superiore nobiltà d'animo che li caratterizza. Entrambi affrontano l'approssimarsi dell'ora fatale come un momento bramato di pace, interpretando la sofferenza terrena come condizione per il riscatto spirituale davanti al Salvatore. 

== I promessi sposi

La necessità di individuare un mezzo espressivo capace di affrontare efficacemente tematiche complesse spinge Manzoni a passare dal teatro al romanzo, un genere che aveva trovato nuova fortuna grazie alle narrazioni storico-romanzesche dello scrittore scozzese Walter Scott.  

=== La redazione

Prima di iniziare la stesura del romanzo, Manzoni avvia un approfondito studio della Lombardia del XVII secolo. Egli si basa sulla storiografia dell'epoca, come quella di Giuseppe Ripamonti e Alessandro Tadino, nonché su testi economici e giuridici moderni, tra cui quelli di Melchiorre Gioia e Pietro Verri. Inoltre, attinge a fonti documentarie originali, come le raccolte di gride pubbliche, che verranno abilmente integrate nel romanzo attraverso affascinanti pastiches stilistici.  

Nel 1823 Manzoni conclude _Fermo e Lucia_, ma decide di accantonarlo insoddisfatto dalla lingua utilizzata. La versione originaria presenta uno stile che mescola forme letterarie tratte dal vocabolario della Crusca con elementi del linguaggio parlato, influenzato dall'uso personale del milanese e del francese. Questa scrittura risulta abbondante di lombardismi, gallicismi, latinismi e arcaismi, venendo percepita come "goffa e artificiosa".  

Nel marzo 1824 Manzoni riprende il lavoro sull'opera, apportando significative modifiche sia alla trama che allo stile. Le parti più marcatamente romantiche, come il racconto oscuro della Monaca di Monza e il tragico epilogo di don Rodrigo, vengono ridotte. La lingua subisce un processo di affinamento, abbandonando l'astrattezza artificiosa in favore della parlata toscana contemporanea. Lo stile è inoltre moderato da una sottile ironia e ricondotto entro parametri classici. Ciononostante, la redazione dei _Promessi sposi_ compiuta nel biennio 1825-1827 non soddisfa pienamente l'autore, che intraprende un viaggio a Firenze per immergersi nella parlata locale al fine di “sciacquare i panni in Arno”.  

La revisione finale del romanzo prende forma nella redazione “quarantana” (1840-1842). In essa Manzoni trova una soluzione innovativa al dilemma linguistico tra il toscano letterario "morto" della tradizione scritta e i dialetti popolari municipali della conversazione. Egli individua una geniale mediazione nel fiorentino parlato dalla borghesia colta, fornendo così alla nascente Italia un solido fondamento linguistico per il suo idioma nazional-popolare.   

== La tematica

Manzoni decide di dedicarsi al genere del romanzo spinto da profonde esigenze estetiche ed etiche: l'arte deve avere come oggetto la verità, come scopo l'utilità e, per raggiungerlo, utilizzare come mezzo l'interesse. 

Già nella poesia, Manzoni aveva mostrato una predilezione per il "vero", rifuggendo gli abbandoni fantastici o le evasioni idilliache. Anche le sue due tragedie avevano finalità educative, ma queste risultavano in parte inefficaci a causa del carattere elitario dei personaggi e dello stile, inadatti ai lettori comuni cui lo scrittore intende ora rivolgersi. Nel romanzo, Manzoni opta per raccontare non le imprese dei grandi personaggi, ma le vicende oscure delle masse anonime, ricostruendo la loro quotidianità. È così che due umili popolani diventano protagonisti.

Un intreccio "inventato" ma plausibile si innesta su un ben delineato sfondo storico — il malgoverno spagnolo, la peste, la guerra — popolato da figure reali come il cardinal Borromeo, la Monaca di Monza e l'Innominato, oltre ad archetipi sociali come bravi prepotenti, preti impauriti, cappuccini valorosi, politici intriganti e folle in tumulto. La narrazione ruota attorno all'amore contrastato tra un artigiano e un'operaia, ostacolati da un piccolo tiranno locale. La vicenda troverà il suo esito positivo grazie alla "conversione" di un potente bandito e ad alcuni accadimenti "provvidenziali".

La trama segue uno schema narrativo semplice (amore ostacolato, superamento delle difficoltà con interventi di antagonisti e alleati, conclusione lieta) e si arricchisce di profonde digressioni psicologiche e morali, riflessioni storiche ed esistenziali. Tutto ciò è espresso con uno stile magistrale capace di alternare descrizioni precise, dialoghi vivaci, sottile ironia e accenti di tragico o lirico.

Manzoni sceglie il Seicento come ambientazione per una motivazione precisa: quel secolo rappresenta per lui il simbolo delle sue critiche più aspre — contro il formalismo, l'ostentazione scenografica, la prepotenza, l'erudizione sterile, l'ipocrisia dei potenti sia civili che religiosi e contro l'ignoranza diffusa. Attraverso una prospettiva illuminata dalla ragione illuministica e dalla morale cattolica, Manzoni demistifica questa oscurità. Il Seicento gli appare come l'epoca dei più gravi oltraggi ai valori dello spirito e dell'intelligenza, ma è anche una cornice che permette di esaltare la possibilità individuale di scegliere responsabilmente la giustizia e la salvezza.

Il romanzo è stato spesso interpretato come un'epopea della Provvidenza e criticato per una presunta accettazione passiva del male. In realtà, pur ponendo al centro della narrazione l'intervento divino nel mondo umano, Manzoni non lo utilizza per eliminare dolori e ingiustizie; il miracolo della Provvidenza si compie invece nel segreto dell'anima, rendendo più tollerabili le sofferenze che accompagnano la vita terrena.

== I saggi

La complessa relazione tra verità storica e invenzione rappresenta il fulcro del Discorso sul romanzo storico, in cui Alessandro Manzoni analizza le contraddizioni teoriche di un genere che mescola queste due dimensioni. Sebbene sembri mettere in discussione il fondamento stesso del suo romanzo, Manzoni intende in realtà criticare gli eccessi avventurosi che caratterizzavano i romanzi storici dell'epoca. Nel ricondurre l'inventiva dello scrittore a idee preesistenti, che vengono più ritrovate che create, riconcilia implicitamente il metodo storiografico con la scrittura letteraria, accomunandoli entrambi alla dipendenza da una realtà superiore e divina.

Nel Manzoni storiografo si intrecciano rigorosamente l'approccio razionalista, l'amore per la patria e l'adesione ai principi cristiani. Un esempio significativo è l'opera Storia della colonna infame, che può essere vista come un'inchiesta e al contempo un'accusa appassionata. Qui, Manzoni applica un rigore metodologico e un profondo senso morale: dimostra come i giudici fossero ben consapevoli dell'ingiustizia della loro condanna degli untori, respingendo l'idea illuminista secondo cui il crimine fosse semplicemente frutto della "barbarie" dell'epoca. A suo avviso, utilizzando ragione e coscienza, quei tragici errori sarebbero stati evitabili.

Lo stesso spirito sociale e nazionale permea anche la riflessione manzoniana sulla lingua, testimoniata da opere e lettere fondamentali come la missiva a G. Carena del 1846 o la relazione per il ministro Broglio sull'Unità della lingua italiana. Qui si inseriscono anche i documenti del 1868, tra cui la Lettera intorno al libro "De vulgari eloquio" di Dante Alighieri e la Lettera intorno al Vocabolario. Le linee guida del pensiero linguistico di Manzoni risiedono nella valorizzazione dell'"uso" come criterio essenziale per selezionare parole e costruzioni, nonché nella proposta di un idioma comune comprensibile da tutt'Italia. Questa visione rappresentava un equilibrio tra l'uso dialettale e il toscano letterario, servendosi dell'esempio maturato nei Promessi sposi.

== In sintesi

La vita: Dopo gli studi presso un collegio a Milano, Alessandro Manzoni si trasferisce a Parigi nel 1805, dove frequenta ambienti intellettuali di rilievo. Nel 1810 si converte al cattolicesimo e sposa Enrichetta Blondel, con cui avrà dieci figli. Tornato a Milano, si avvicina ai romantici opponendosi ai classicisti. Trascorre gran parte della vita tra Milano e Brusuglio, dedicandosi agli studi. Rimasto vedovo nel 1840, contrae un secondo matrimonio con Teresa Stampa. Nel 1861 diventa senatore del Regno d'Italia e sostiene Roma capitale, nonostante il dissenso papale.

Opere poetiche: Gli _Inni sacri_ (1815) e le odi civili _Marzo 1821_ e _Il cinque maggio_ (1821) si distinguono per uno "stile petroso", lontano dai modelli petrarcheschi e ricco di riferimenti biblici.

Le tragedie: Ne _Il conte di Carmagnola_ (1820) prevale un profondo pessimismo, mentre l'_Adelchi_ (1822) mette in contrasto le motivazioni della giustizia e della pietà con quelle della politica.

"I promessi sposi": La prima versione del romanzo, intitolata _Fermo e Lucia_ (1821-1823), evolve nelle successive edizioni del 1827 e del 1842. Con quest'opera, Manzoni intende creare un grande romanzo rivolto al popolo, racchiudendo in esso tutta la sua poetica.

La poetica: La letteratura deve ricercare il "vero" e il "reale", con l'obiettivo di educare tutte le classi sociali. Per Manzoni, il cattolicesimo rappresenta uno strumento per proporre in chiave romantica una visione nazionale e morale della letteratura. La lingua, frutto della mediazione tra dialetto e toscano letterario, è l'elemento centrale per una comunicazione efficace su scala nazionale.

