Il passaggio tra Ottocento e Novecento fu un periodo ricco di fermenti, iniziative, tensioni e contrasti, pur mantenendo una certa continuità con il passato.

Sull'onda del rinnovamento portato dalla rinascita celtica, emerse una figura di primo piano nella poesia del secolo: W.B. Yeats. In ambito poetico, si verificò un netto cambiamento con l'arrivo di T.S. Eliot, il quale segnò il corso della poesia moderna introducendo il "metodo mitico" e una frammentazione stilistica innovativa. Il suo influsso si fece particolarmente sentire tra i poeti degli anni Trenta, che esplorarono apertamente temi di impegno sociale e politico, adottando un tono sobrio e distaccato ispirato proprio a Eliot.

Negli anni Quaranta, vi fu una più marcata opposizione al freddo intellettualismo dominante, portata avanti dai cosiddetti "poeti apocalittici", tra i quali R. Graves e D. Thomas rappresentarono figure guida. Dall'intensità espressiva di questa corrente nacque il "Movement" nel 1957, che si pose come simbolo di una poesia rigorosa, misurata e profondamente radicata nella tradizione britannica, rifacendosi al modello di Pope.

Per quanto riguarda il romanzo, è possibile individuare un filo di continuità tra autori come Thomas Hardy e D.H. Lawrence, così come tra i naturalisti e scrittori quali J. Galsworthy e H.G. Wells. Tuttavia, con J. Joyce si verificò una rottura decisiva: la sua opera influenzò in modo cruciale l'evoluzione del romanzo, esercitando su questo genere un impatto tanto significativo quanto quello di Eliot sulla poesia.

Nella narrativa del secondo dopoguerra si assistette a un consolidamento dello sperimentalismo, che raggiunse le più complesse astrazioni metafisiche e linguistiche nell'opera di S. Beckett, in diretto dialogo con l'eredità joyciana. Contemporaneamente, le scrittrici giocarono un ruolo importante nella ridefinizione della narrativa recente, affrontando con originalità il tema della condizione femminile in una società in trasformazione. Tra queste spiccano M. Spark, D. Lessing, M. Drabble, A. Carter ed E. O'Brien.

Un significativo rilancio ha interessato anche il dramma nel secondo dopoguerra. Autori come J. Osborne, S. Beckett, H. Pinter, J. Arden e A. Wesker hanno sperimentato diverse forme teatrali: dal dramma sociale a quello della protesta esistenziale, passando per il teatro domestico caratterizzato da assenza e silenzio. In ogni caso, queste opere condividono una grande padronanza tecnica e artistica del mezzo teatrale. 
