#import "../../../template/_global/template.typ": *
#import "../../../template/_global/config.typ": *

#intro[A completare l'eccezionale triade trecentesca dei grandi padri fondatori della letteratura italiana troviamo Giovanni Boccaccio. Considerato il più grande narratore del nostro panorama letterario, il suo capolavoro, il _Decameron_, rappresenta una visione monumentale della vita con tutte le sue sfumature, dalle luci alle ombre. Questo straordinario affresco umano, definito quasi una "commedia umana," pone al centro l'azione dell'uomo nel mondo, privilegiando una dimensione terrena rispetto alla prospettiva dell'eterno. L'opera di Boccaccio costituisce un ponte fondamentale tra il Medioevo e il primo Rinascimento, grazie a una prosa estremamente versatile, in grado di spaziare da costruzioni solenni ricche di subordinate fino a una narrazione asciutta e incisiva. Per secoli, la sua scrittura rimarrà un modello insuperabile.]

== La vita e le opere

Giovanni Boccaccio nacque nel 1313 a Firenze, figlio illegittimo di ser Boccaccino di Chellino, un ricco uomo d'affari originario di Certaldo. Fin da giovane fu indirizzato dal padre alla carriera finanziaria e nel 1327 fu condotto con lui a Napoli, dove ser Boccaccino lavorava come procuratore presso la banca dei Bardi, principale finanziatrice del re Roberto d'Angiò. L'esperienza napoletana fu cruciale per la formazione culturale del giovane Boccaccio. Accanto ai doveri legati alla pratica bancaria, egli ebbe l'occasione di frequentare i circoli aristocratici della città e la sontuosa corte angioina.

Nel 1334, Boccaccio compose la _Caccia di Diana_, poemetto allegorico-mitologico in terza rima composto da 18 canti, nei quali si celebrano le bellezze dell'aristocrazia napoletana. Con il _Filocolo_ (1336-38?), romanzo in prosa che racconta una romantica e avventurosa vicenda d'amore, emerge un primo esempio consistente della sua spinta creativa. Qui compare per la prima volta Fiammetta (Maria d'Aquino, figlia illegittima di re Roberto d'Angiò), figura ispiratrice e destinataria delle sue opere che sarà centrale nella sua autobiografia sentimentale ideale. Tra il 1335 e il 1339 iniziò la stesura del _Filostrato_, poema in ottave che narra le vicende amorose e tradite di Troilo e Criseida. Successivamente, tra il 1339 e il 1341, Boccaccio compose il più elaborato _Teseida delle nozze d'Emilia_, un poema epico-amoroso in 12 canti in ottave, ambientato tra i conflitti leggendari di Teseo e le Amazzoni.

== Il ritorno a Firenze e le opere della maturità

Tra il 1340 e il 1341, Boccaccio fece ritorno a Firenze. Gli anni successivi al rimpatrio furono particolarmente prolifici per lo scrittore, ormai avviato verso la piena maturità letteraria. Tra le sue opere di questo periodo spiccano la _Comedia delle ninfe fiorentine_ (1341-42), un'opera che alterna poesia e prosa e narra l'elevazione spirituale verso l'amore di Ameto, pastore rozzo e ingenuo, guidato da sette ninfe. Analoghi temi di crescita interiore emergono nell'_Amorosa visione_ (1342-43), poema allegorico composto da 50 canti in terzine, ispirato ai modelli danteschi e arricchito da reminiscenze ovidiane. Invece, con l'_Elegia di madonna Fiammetta_ (1343-44), Boccaccio si concentra su una storia d'amore tormentata ambientata nella Napoli contemporanea e raccontata in prima persona dalla protagonista. Qui emerge un raffinato gioco narrativo che intreccia il realismo con la mitologia classica, offrendo una visione vibrante della realtà e dell'immaginazione.

Il punto culminante della produzione precedente al _Decameron_ è rappresentato dal poema in ottave _Ninfale fiesolano_ (1344-46?), che, partendo dalla tragica vicenda amorosa tra il pastore Africo e la ninfa Mensola, giunge a celebrare le leggendarie origini di Fiesole e Firenze. In questo testo, Boccaccio alterna con maestria il realismo della tradizione letteraria popolare e il tono elevato della poesia lirica.

Nel corso dell'epidemia di peste del 1348 perse il padre, oltre a numerosi amici e conoscenti. Subito dopo, tra il 1349 e il 1353, compose il suo capolavoro, la raccolta di novelle _Decameron_. Sul finire dello stesso decennio nacque Violante, figlia illegittima come gli altri suoi figli, alla quale dedicò affettuosi ricordi nelle epistole e nell'egloga XIV. Gli anni '50 e '60 furono particolarmente intensi per Boccaccio, impegnato non solo in incarichi pubblici e missioni diplomatiche, ma anche nello studio, nella scrittura e nelle frequentazioni con amici intellettuali. Di rilevante importanza è l'incontro avvenuto nel 1350 con Petrarca, che diede origine a una profonda amicizia.

In questo periodo si collocano le opere umanistiche in latino che contribuirono significativamente alla sua fama in Europa. Tra queste spicca la _Genealogia degli dei gentili_ (_Genealogia deorum gentilium_), un ambizioso repertorio dei miti antichi reinterpretati come strumenti per trasmettere verità morali e religiose, culminando in una fervida difesa della poesia. Altro lavoro di rilievo è il _Monti, selve, laghi, fiumi, stagni o paludi e nomi del mare_ (_De montibus…_), un vero e proprio compendio di conoscenze geografiche classiche e medievali. Il tema moralistico, che analizza la caduta del favorito dalla sorte a causa di superbia e stoltezza, resta invece centrale nell'opera _Delle sventure degli uomini illustri_ (_De casibus virorum illustrium_), una raccolta di profili biografici che va da Adamo a Giovanni il Buono, re di Francia. Complementare, sebbene differente nello spirito, è lo scritto _Delle donne illustri_ (_De mulieribus claris_). Nel 1367 pubblicò le sedici egloghe del _Bucolicum carmen_, un'opera ispirata sia da Virgilio che da Petrarca.

=== Gli ultimi anni

La composizione del _Corbaccio_, un libello in prosa volgare caratterizzato da una forte vena misogina, sembra collocarsi intorno al 1354-55. Scosso da una lettera del beato Pietro Petroni, che lo esortava ad abbandonare la poesia per riflettere sulla morte imminente, trovò però nella rassicurazione di Petrarca l'incoraggiamento a continuare gli studi a lui tanto cari. In questo periodo si datano anche l'_Epistola consolatoria_ a Pino de' Rossi (1361) e probabilmente la _Vita di san Pier Damiani_ (_Vita sanctissimi patris Petri Damiani heremite_). Nel 1365 fu inviato a svolgere una missione diplomatica presso la corte papale di Avignone. Boccaccio nutrì una profonda ammirazione per Dante e nel 1351 aveva già scritto un _Trattatello in laude di Dante_. Per questo motivo fu invitato dal Comune di Firenze a tenere pubbliche letture della Commedia: iniziate nell'ottobre del 1373, le esposizioni (_Esposizioni sulla Commedia di Dante_) vennero interrotte all'inizio del 1374, quando Boccaccio, ormai ammalato, fece ritorno a Certaldo. Qui si spense il 21 dicembre 1375.

== Il _Decameron_

Redatto negli anni immediatamente successivi alla peste del 1348, tra il 1349 e il 1353, il _Decameron_ porta con sé le tracce indelebili di quell'evento luttuoso. È proprio per sfuggire all'epidemia e al degrado morale che ha investito la vita fiorentina che i dieci giovani protagonisti della cornice narrativa (Pampinea, Filomena, Elissa, Neifile, Emilia, Lauretta, Fiammetta, Panfilo, Filostrato e Dioneo) decidono, in seguito a un incontro casuale nella chiesa di Santa Maria Novella, di ritirarsi in campagna. Nella loro villa, immersi in un regime di piacevole vita comunitaria che combina momenti di gioco, danza ed escursioni, trovano anche occasione di dedicarsi alla narrazione di novelle. Questi racconti, il cui tema viene stabilito ogni giorno dal re o dalla regina designati a turno, si distribuiscono su un arco di dieci giornate (da cui il titolo dell'opera), per un totale di cento novelle. A queste si aggiungono dieci canzoni da ballo, cantate a chiusura di ogni giornata dai giovani della brigata.

Ricca e variegata è la gamma delle fonti a cui attinge Boccaccio, spesso reinterpretandole liberamente o trasformandole in parodie. Nel _Decameron_ è celebrata con grande sapienza artistica la borghesia mercantile emersa nell'Italia del Duecento e Trecento, una classe che l'autore osserva con ammirazione nei suoi tentativi di elevarsi attraverso gli ideali cortesi. Emblema eccelso di quest'umanità è messer Torello da Pavia che, pur essendo un semplice cittadino e non un nobile, si distingue per la sua straordinaria eleganza d'animo e modi, qualità che emergono nella sua gara di cortesia con il Saladino, sultano del Cairo.

=== Una "Umana commedia"

Un'osservazione condivisa da generazioni di lettori è che il _Decameron_ rappresenti un progetto narrativo di insolita ambizione. Di certo Boccaccio, concependo l'opera come un affresco grandioso della vita umana in tutti i suoi aspetti – luci ed ombre, emozioni e riflessioni morali, meraviglia e introspezione psicologica – si ispirò al grande modello della _Commedia_ dantesca. La sua creazione può essere definita una "commedia umana", poiché l'attenzione si concentra esclusivamente sugli atti dell'uomo nel mondo e per il mondo, lasciando da parte la prospettiva dell'eterno.

Il realismo dell'opera si manifesta soprattutto nella scelta di narrare vicende collocate nel presente, ambientate in luoghi ben identificabili e popolate anche da personaggi che appartengono ai ceti sociali più bassi, non necessariamente con intenti umoristici. Boccaccio elabora così una poetica che abbandona l'erudizione ostentata e il gusto per la mitologia, rinuncia alle allegorie complesse e si fa promotore dei diritti del piacere sessuale. L'autore esalta inoltre le risorse pragmatiche dell'individuo e valorizza l'azione umana per se stessa. Se è vero che sul _Decameron_ gravano ancora significative influenze medievali, è altrettanto evidente come esso rappresenti un anticipatore vivido e travolgente della grande stagione del pensiero e della letteratura rinascimentale.

#pagebreak()
#set page(fill: accent.ita.lighten(90%))
== In sintesi <senza_numero>

/ Vita: Giovanni Boccaccio nacque nel 1313 a Firenze, figlio illegittimo di un facoltoso mercante. La sua formazione si svolse prevalentemente a Napoli, città in cui ebbe modo di frequentare gli ambienti aristocratici e la corte di Roberto d'Angiò, dove produsse le sue prime opere letterarie. Nel 1340-41 fece ritorno a Firenze, dove si dedicò a importanti incarichi pubblici e diplomatici, nonché alla stesura delle opere della sua piena maturità letteraria. Morì nel 1375 a Certaldo.  

/ Periodo napoletano: Tra le opere giovanili si distinguono il _Filocolo_ (1336-38?), un romanzo sentimentale in prosa, il _Filostrato_ (1335 o 1339), poema narrativo in ottave che narra dell'amore tradito di Troiolo per Criseida, e il _Teseida delle nozze d'Emilia_ (1339-41?), un poema composto da dodici canti in ottave che prende spunto dalle imprese eroiche di Teseo e delle Amazzoni.  

/ Periodo fiorentino: Tra le opere prodotte dopo il ritorno a Firenze si annoverano _Amorosa visione_ (1342-43), poema allegorico composto da cinquanta canti in terzine, strutturato secondo modelli danteschi e arricchito da reminiscenze ovidiane. L'_Elegia di madonna Fiammetta_ (1343-44), invece, narra in forma soggettiva la travagliata vicenda amorosa vissuta dalla protagonista. Il _Ninfale fiesolano_ (1344-46?) è un poema in ottave che racconta i tragici amori tra il pastore Africo e la ninfa Mensola, per approdare alla celebrazione delle origini leggendarie di Fiesole e Firenze; si tratta dell'opera più compiuta prima della composizione del _Decameron_.  

/ Il _Decameron_: Considerato il capolavoro boccacciano, il _Decameron_ consiste in una raccolta di cento novelle racchiuse all'interno di una "cornice" narrativa, scritta tra il 1349 e il 1353. La caratteristica distintiva dell'opera risiede nel suo realismo, volto a rappresentare una comunità umana autentica, dotata però di una nobile dignità. Il _Decameron_ si configura così come una straordinaria rappresentazione della commedia umana.  