#import "../../../template/_global/template.typ": *
#import "../../../template/_global/config.typ": *

#intro[La produzione poetica del Trecento mostra segni di stasi, stretta tra l'esaurimento creativo dello stilnovismo e l'imponente influenza di Petrarca, del quale però non si coglie ancora appieno la radicale innovazione. In questo contesto, la lirica raggiunge risultati minori rispetto ad altri generi, come la novellistica, che si dimostra più feconda e vivace. I _Trecentonovelle_ di Franco Sacchetti, modellate sul paradigma boccacciano, rappresentano una testimonianza significativa di questa tradizione narrativa, destinata a durare nel tempo.]

== La lirica
#note(bottom)[== *🧩* La letteratura franco-italiana <senza_numero>

La letteratura franco-italiana, talvolta definita anche francoveneta, rappresenta un corpus di opere, per lo più di carattere cavalleresco, composte tra il XIII e l'inizio del XIV secolo nella regione della bassa valle del Po. Questi testi furono scritti in una lingua che gli autori consideravano francese, ma che in realtà costituisce un'interessante commistione fra elementi linguistici italiani e francesi. Un tratto distintivo di questa produzione letteraria risiede nella sintesi tra due grandi tradizioni culturali della Francia medievale: quella epico-carolingia e quella amorosa di origine bretone. \ Tra le opere più significative di questo filone si annovera un ciclo di poemi carolingi, che comprende, ad esempio, narrazioni su Buona d'Antona, su Berta, madre di Carlomagno, sulla giovinezza di Carlomagno stesso e sugli amori tra Milone e Berta, sorella dell'imperatore. È probabile che tali componimenti siano stati creati da un unico autore. Altro esempio rilevante è l'_Entrée de Spagne_, un poema composto da un autore padovano e successivamente portato a compimento nel XIV secolo da Niccolò da Verona con la stesura della _Prise de Pampelune_.]
Con il superamento delle forme stilnoviste, già preannunciato dalle scelte tematiche e stilistiche della _Commedia_ dantesca, la poesia del Trecento fatica a sviluppare nuovi orizzonti espressivi. L'esperienza del Petrarca, nonostante la sua qualità innovativa nell'uso del volgare, rimane spesso incompresa dagli epigoni del periodo. Un esempio emblematico di questa limitazione è rappresentato da Sennuccio del Bene (1275-1349), la cui produzione non riesce a interpretare pienamente le novità introdotte dai fondatori dello stilnovismo. 

Matteo Frescobaldi (1300-1348) tenta una ripresa dello stilnovismo in chiave più semplice, benché prevedibile. Giovanni Quirini emerge come valido divulgatore del pensiero dantesco e del dolce stil novo, mentre Antonio Beccari (1315-1371) si distingue per una sintesi originale tra motivi danteschi e elementi della tradizione giullaresca. Tuttavia, dalla seconda metà del secolo prevale una tendenza imitativa più superficiale e libresca.

Contemporaneamente, nel corso del Trecento continua la tradizione dei rimatori appartenenti alla corrente realista, segnata da una transizione dal realismo disordinato e ribelle del Duecento a un approccio più ordinato e borghese della vita quotidiana. Questo "nuovo realismo" incorpora esigenze moralistiche e religiose, spesso espresse attraverso un vivace cronachismo. Una figura centrale in questo ambito è Antonio Pucci (1310-1388), autore prolifico che ha lasciato opere significative quali il _Centiloquio_, _Le proprietà di Mercato Vecchio_, _La guerra di Pisa_ e vari cantari cavallereschi, fra cui _Apollonio di Tiro_, _La Madonna Lionessa_ e _La Reina d'Oriente_.

== La novellistica e Sacchetti

Nel panorama novellistico del Trecento emerge con forza Giovanni Sercambi (1347-1424), originario di Lucca, noto per il _Novelliero_, una raccolta di 155 novelle composte tra il 1374 e il 1385 sul modello boccacciano. L'opera si caratterizza per un linguaggio vivace, ricco di inflessioni dialettali e accenti colloquiali. Attraverso una narrazione variegata che include temi spregiudicati e scurrili, anticipa il gusto della facezia tipico del Quattrocento. Della sua produzione civile va ricordata anche la _Croniche delle cose di Lucca dal 1164 al 1424_, un resoconto storico pubblicato solo postumo nel 1892.

=== Franco Sacchetti

Nato in una famiglia di mercanti fiorentini, Franco Sacchetti (circa 1330-1400) è unanimemente considerato il secondo grande narratore del Trecento dopo Giovanni Boccaccio. La sua biografia si intreccia con le vicende economiche e politiche della Firenze del secolo XIV: operò come mercante e partecipò attivamente alla vita politica cittadina. Tuttavia, l'epidemia di peste del 1374 segnò per lui un momento di profonda crisi morale, ulteriormente aggravata da due eventi drammatici: il tumulto dei Ciompi del 1378, che mise in discussione la sua visione moderatamente conservatrice, e la condanna per alto tradimento inflitta al fratello Giannozzo nel 1379.  

La prima opera poetica di Sacchetti, _La battaglia delle belle donne di Firenze con le vecchie_ (1563), un poemetto in ottave, fu composta in occasione del matrimonio di Maria Felice Strozzi. Seguendo il modello della _Caccia di Diana_ di Boccaccio, Sacchetti affronta il tema ludico del contrasto tra la bellezza della giovinezza e la decadenza della vecchiaia, inserendolo tuttavia in una struttura popolareggiante rappresentata dai quattro cantari, reinterpretati in chiave maliziosa. Alla medesima fase produttiva, risalente agli anni Sessanta del Trecento, appartiene anche il _Libro delle rime_, raccolta poetica che testimonia la varietà stilistica del suo autore, spaziando tra il linguaggio cortese e quello comico. In particolare, le poesie per musica (madrigali, cacce e ballate) si distinguono per la sperimentazione di ritmi vivaci e melodiosi, capaci di generare piacevoli bozzetti poetici. Tuttavia, le liriche più tarde della raccolta riflettono un mutamento di tonalità: abbandonano il registro leggero precedente per assumere un approccio pedagogico più serio, caratteristico anche delle opere in prosa dell'autore maturo.

L'intento etico diviene esplicito nel capolavoro di Sacchetti, _Il Trecentonovelle_, una raccolta iniziata intorno al 1392 e completata nel 1396-97, di cui sono pervenute 223 novelle. Benché ispirata al _Decameron_ di Boccaccio, questa non presenta una struttura cornice e adotta piuttosto un tono colloquiale e familiare. Tale scelta narrativa conferisce all'opera un carattere di libero vagabondare della memoria. Il linguaggio impiegato dall'autore si distingue per la semplicità spontanea: rifiuta i preziosismi letterari a favore di un registro quotidiano, elevando la parlata comune a dignità artistica. Ogni novella rappresenta un'affascinante istantanea della vita borghese e popolare dell'epoca, in cui i personaggi vengono descritti con vivace realismo comico. Il fine ultimo dell'opera è didattico ed esemplare: ciascun racconto culmina in una riflessione morale finalizzata a suggerire insegnamenti pratici e ammonimenti etici.

#pagebreak()
#set page(fill: accent.ita.lighten(90%))
== In sintesi <senza_numero>

/ Lirica:  La poesia lirica del periodo si concentra essenzialmente sull'imitazione dello stilnovo. Tra gli autori principali troviamo Sennuccio del Bene, lucido continuatore di quella tradizione; Matteo Frescobaldi, che adotta uno stilnovismo semplice, sebbene a tratti prevedibile; e Antonio Beccari, il quale combina elementi danteschi con motivi provenienti dalla tradizione giullaresca. Nei rimatori realisti, il disordine ribelle del realismo duecentesco evolve in una visione più ordinata e borghese della vita, accompagnata da una certa inclinazione moralistica, come nel caso di Antonio Pucci.

/ Novellistica:  Giovanni Sercambi, autore del _Novelliero_, si distingue per la vivacità dell'espressione e l'uso di una lingua colorita e colloquiale. Franco Sacchetti invece, con il _Trecentonovelle_, mostra un equilibrio narrativo e una capacità descrittiva piena di dinamismo, affiancata da un "buon senso" moralistico e borghese, in netto contrasto con gli approcci più liberi di Boccaccio.