#import "../../template_normal.typ": *
//#show: frame-style(styles.thmbox)

#evidenzia[La postmodernità è un concetto introdotto da Jean-François Lyotard in ambito filosofico per descrivere il declino delle forme universalistiche di interpretazione e legittimazione che hanno dominato lo sviluppo della società occidentale sin dal XVII secolo.

Il postmoderno mette in evidenza l'esistenza di una pluralità di giochi linguistici, reciprocamente alternativi e incommensurabili. Ciascuno di questi è in grado di garantire, al proprio interno, le condizioni necessarie alla propria perpetuazione, ma nessuno riesce a rivendicare quell'universalità che costituiva il tratto distintivo dei discorsi dell'età moderna. Di conseguenza, emerge l'impossibilità di fondare in modo non contingente categorie quali giustizia, verità e morale, che finiscono per essere sostituite da criteri operativi applicabili esclusivamente su scala locale e in contesti specifici.]

== Tratti filosofici della postmodernità

Il termine "postmodernità" o "postmoderno" è stato utilizzato in numerosi ambiti disciplinari, tra cui architettura, letteratura, arte, sociologia e filosofia, con significati diversi. Dal punto di vista filosofico, il concetto ha ottenuto particolare risonanza grazie al saggio di J.-F. Lyotard _La condizione postmoderna_ (1979) e si è diffuso principalmente durante gli anni Ottanta del XX secolo.

Secondo Lyotard, il postmoderno - pur evocando una periodizzazione storica - non descrive propriamente una fase successiva all'età moderna, bensì una condizione che è già parte integrante della modernità stessa. Tra moderno e postmoderno non esiste una netta discontinuità, bensì un legame complesso; il secondo sembra essere già intrinsecamente contenuto nel primo.

La condizione postmoderna si caratterizza per il progressivo declino dei cosiddetti "grandi racconti" dell'età moderna (illuminismo, idealismo, marxismo), i quali proponevano illusoriamente una visione unitaria della realtà capace di stabilire un ponte tra estetica, etica e teoria. Questi "grandi racconti", incluso quello del capitalismo, perdono credibilità, e il progetto di emancipazione universale dell'umanità – basato su ideali come maggiore libertà, uguaglianza, razionalità e ricchezza – viene smantellato. Il sapere, nel contempo, si distacca dalla sua tradizionale funzione formativa umanistica per essere ridotto a oggetto di scambio e informazione sotto l'influenza dell'informatica e dei mass-media.

Jürgen Habermas, nel suo saggio _Il discorso filosofico della modernità_ (1985), ha criticato questa visione postmoderna considerandola una forma di neoconservatorismo. Egli sostiene la necessità di recuperare il progetto moderno illuminista e di riaffermare l'unità del sapere come base della cultura e della società.

== Jean-François Lyotard

Jean-François Lyotard (Versailles 1924 - Parigi 1998), celebre filosofo francese e docente di filosofia presso l'Università di Paris VIII-Vincennes, nonché successivamente negli Stati Uniti, ha sviluppato nelle sue prime riflessioni un approccio che individua uno spazio alternativo rispetto al discorso tradizionale, considerandolo irriducibile ai parametri linguistici. 

Nel suo lavoro _Discorso, figura_ (1971), attraverso un'analisi degli sviluppi artistici e delle teorie dell'arte a partire dal Quattrocento, Lyotard ha messo in discussione il primato che la tradizione filosofica occidentale ha storicamente assegnato al discorso, evidenziando come esso venga sovvertito dal "figurale". Quest'ultimo, che comprende elementi quali l'immagine, il corpo e le pulsioni, risulta estraneo alla traduzione linguistica e non può essere incorporato in schemi comunicativi convenzionali. 

Questa prospettiva è stata ulteriormente approfondita in _Economia libidinale_ (1974), dove il filosofo, oltre a integrare le fondamenta della psicoanalisi freudiana, ha intrapreso un dialogo critico con il pensiero marxiano. Lyotard propone una visione emancipativa non concentrata sulla protesta contro lo sfruttamento del capitalismo, bensì orientata a svelare la dimensione pulsionale che si cela dietro di esso, valorizzando il desiderio come forza affermativa e creativa.

Con _La condizione postmoderna_ (1979), noto come manifesto del pensiero postmoderno, Lyotard supera le precedenti posizioni definendole una "metafisica romantica del desiderio". L'opera identifica l'era postmoderna come un'epoca caratterizzata dalla dissoluzione dei grandi "meta-racconti" o "meta-narrazioni" (illuminismo, idealismo e storicismo marxista), sostituiti da una pluralità di linguaggi irriducibili e incommensurabili tra loro. Questo segna l'inizio di una nuova fase del pensiero di Lyotard, che non indulge nella nostalgia per un'unità perduta, ma abbraccia la diversificazione, la pluralità e l'instabilità come dimensioni costitutive della realtà.

In questa seconda fase, il filosofo torna a riflettere sul discorso, interpretandolo come un'aggregazione di famiglie di frasi eterogenee (descrittive, prescrittive, ecc.) e orienta il suo interesse verso questioni etiche. In _Il dissidio_ (1983), considerata la sua opera filosofica più completa, Lyotard promuove il ricorso a una razionalità "paralogica", "paratattica" e "trasversale", capace di escludere subordinazione e gerarchia per adeguarsi ai diversi contesti di applicazione. Tale approccio riflette una relativizzazione del sapere che si richiama, tra gli altri, ad Aristotele. Lyotard riconosce nel pensatore greco il primo autore ad aver esplicitamente distinto le scienze in base alle loro finalità, alla struttura degli oggetti e alle forme di ragionamento proprie a ciascuna disciplina.

Nella sua riflessione etica, Lyotard rivaluta alcuni aspetti dell'etica aristotelica e rielabora il modello kantiano del giudizio riflettente, nell'intento di definire un criterio di giustizia che possa prescindere da enunciati universali o univocamente veri.

== Gianni Vattimo

In Italia, uno dei principali interpreti del pensiero postmoderno è stato Gianni Vattimo (Torino, 1936), allievo di Luigi Pareyson. La sua attività filosofica si è caratterizzata come un'elaborazione dell'eredità critica alla metafisica inaugurata da Friedrich Nietzsche e ulteriormente sviluppata da Martin Heidegger. Vattimo ha svolto anche un ruolo di divulgatore dell'ermeneutica di Hans-Georg Gadamer, introducendola nel panorama filosofico italiano, in particolare attraverso la curatela della traduzione dell'opera fondamentale _Verità e metodo_.

Nel corso della sua carriera accademica, Vattimo ha insegnato estetica e filosofia teoretica presso l'Università di Torino. Tra i suoi primi lavori si annoverano _Essere storia e linguaggio in Heidegger_ (1963), _Il soggetto e la maschera_ (1974), _Le avventure della differenza_ (1980) e _Al di là del soggetto_ (1981). Tuttavia, una svolta significativa nel suo pensiero è rappresentata dalla raccolta _Il pensiero debole_, pubblicata con l'apporto di Pier Aldo Rovatti nel 1983. In tale contesto, Vattimo ha articolato una concezione filosofica che invita a un ripensamento radicale della verità, intesa non come corrispondenza tra pensiero e realtà, bensì come interpretazione. Il "pensiero debole" propone una filosofia che rinuncia al suo tradizionale ruolo fondativo e abbraccia una visione della verità come storicamente situata e inevitabilmente frammentata.

Questa corrente filosofica ha attratto numerosi pensatori italiani, tra cui Rovatti, Gargani e Ferraris, configurandosi come uno strumento teorico per approfondire la "crisi della ragione" che attraversa gran parte della filosofia contemporanea post-nietzschiana e post-heideggeriana. Alla luce di questa prospettiva, Vattimo ha elaborato una "ontologia debole" o "ontologia del declino," che concepisce l'essere sotto il segno della transitorietà e della mortalità, intese come caratteristiche essenziali dell'esistere. Secondo questa visione, l'essere deve essere interpretato non attraverso modelli logici o metafisici, bensì riconoscendo la sua caducità e rammemorando le tappe che ne segnano il declino storico e ontologico. La filosofia viene quindi proposta come un esercizio di pietas, volto a preservare la memoria dell'essere nella sua finitudine.

Uno dei testi fondamentali di Vattimo, _La fine della modernità_ (1985), ha avuto vasta fortuna e influenza, consolidando le basi teoriche del "pensiero debole." In questa opera, l'autore riflette sui tratti distintivi del postmoderno, quali la frammentazione del reale, la pluralità dei giochi linguistici e delle forme del sapere, nonché le contaminazioni tra i generi e le differenze culturali. Vattimo invita ad accogliere con atteggiamento permissivo e sereno l'effimericità e l'instabilità del divenire delle cose, promuovendo un approccio distante da aspirazioni nostalgiche verso unità e valori ormai irrimediabilmente entrati in crisi.

In tale contesto, egli articola la possibilità di quello che definisce un "nichilismo gaio," ispirato al concetto nietzschiano della "gaia scienza." Questo nichilismo si caratterizza per una consapevole accettazione della finitezza e del divenire, senza ricercare vanamente una ricomposizione di unità perdute o un recupero di ideali ormai tramontati. Attraverso questa prospettiva, il nichilismo postmoderno di Vattimo si configura come uno slancio positivo verso un modo di pensare che abbraccia la mortalità dell'essere come occasione per nuove aperture interpretative e dialogiche.
#pagebreak()
#set page(fill: main_umane.lighten(90%))
== In sintesi <senza_numero>

/ Postmoderno: Il concetto di postmodernità identifica una fase del pensiero sviluppatasi negli anni Ottanta del Novecento, che ha coinvolto diversi ambiti, quali quello letterario, architettonico, filosofico e sociologico. Tale paradigma si distingue per un rapporto complesso con la modernità, caratterizzato dall'emergere di una molteplicità di forme di sapere e da una varietà di giochi linguistici, ciascuno dei quali si configura come alternativo e incommensurabile rispetto agli altri. Nessuna di queste forme, tuttavia, possiede un valore universale. La società postmoderna appare quindi frammentata, strutturata su valori contingenti e orientata esclusivamente a criteri di operatività pratica.

/ Lyotard: Jean-François Lyotard, con la pubblicazione de _La condizione postmoderna_ (1979), ha dato vita a quello che è considerato il manifesto teorico del pensiero postmoderno. Lyotard individua nell'età postmoderna il progressivo cedimento delle grandi "meta-narrazioni" dominanti della modernità — illuminismo, idealismo e storicismo marxista — che avevano agito come strutture coesive e interpretative dell'esperienza umana. Egli sostiene che la filosofia contemporanea debba adattarsi alla diversificazione, alla pluralità e all'instabilità, riconoscendole come aspetti fondamentali e irrinunciabili del reale. Con _Il dissidio_ (1983), Lyotard propone una razionalità alternativa, non subordinante né gerarchizzante, che si dimostri adeguata ai vari ambiti funzionali e alle loro specificità.

/ Vattimo: Voce autorevole del pensiero postmoderno in Italia, Gianni Vattimo si è collocato nel solco della critica alla metafisica inaugurata da Friedrich Nietzsche e sviluppata da Martin Heidegger. Insieme a Pier Aldo Rovatti, con la raccolta _Il pensiero debole_ (1983), Vattimo ha riformulato la filosofia come "pensiero debole", invitandola ad abbracciare la perdita del proprio ruolo fondativo per orientarsi verso un esercizio interpretativo. Da questa prospettiva, attorno alla quale si è costituita una vera e propria corrente filosofica, il pensiero "debole" prende coscienza della mortalità dell'essere e ne ricostruisce i momenti principali del declino. Con _La fine della modernità_ (1985), Vattimo ha sottolineato la frammentazione e la pluralità della realtà contemporanea, valorizzando l'accettazione dell'instabilità e della fugacità dei fenomeni e dei valori. Egli ha così delineato l'idea di un "nichilismo gaio", che contempla con serenità la finitudine del senso e accoglie senza nostalgia la perdita di assolutezza, unità e universalità.

