#import "../../../template/_global/template.typ": *
#import "../../../template/_global/config.typ": *

#intro[Giacomo Leopardi emerge come il massimo interprete poetico dell'Ottocento e uno dei fondatori della poesia italiana moderna. La sua unicità, spiccata anche nel panorama culturale internazionale, risiede nella capacità di innovare profondamente pur rifiutando il romanticismo e puntando a una continuità con la tradizione classica. Il tutto si colloca all'interno di una visione caratterizzata dal drammatico pessimismo cosmico. Il suo classicismo, tuttavia, non ha nulla della sterile rigidità di molti neoclassici italiani. La grandezza di Leopardi si può riassumere in una formula essenziale: concepire la poesia come uno strumento elevato per indagare l'esistenza e perseguire la verità.]

== I primi anni
#note(bottom)[== *🧩* Canzone leopardiana <senza_numero> 

La canzone leopardiana si caratterizza per l'adozione di un "nuovo metro", definito come "canzone libera". Questo schema si distacca dalle rigide strutture della canzone petrarchesca, permettendo una varietà nella composizione delle strofe, con una libera alternanza di endecasillabi e settenari e una distribuzione delle rime estremamente flessibile. 

Pur trasformando la tradizione classica, questa modalità non la rinnega, ma anzi la reinventa per integrarsi armoniosamente con parti liriche, meditazioni e riflessioni gnomiche. Anche il linguaggio adotta una combinazione di termini colti e quotidiani, il cui accostamento riesce a evocare in maniera più intensa emozioni profonde e spunti di riflessione.]
Nato a Recanati nel 1798 in una famiglia della nobiltà clericale provinciale, Leopardi crebbe sotto l'influenza del padre Monaldo, un erudito bibliofilo con idee reazionarie, e della madre Adelaide Antici, una donna severa e religiosa fino al fanatismo. Primogenito di dieci figli (dei quali solo cinque sopravvissero), Giacomo mantenne un legame affettuosissimo con il fratello Carlo e la sorella Paolina. La sua educazione fu affidata al gesuita Giuseppe Torres e all'abate Sebastiano Sanchini, ma fu soprattutto autodidatta. La vasta biblioteca paterna alimentò il fervore delle sue ricerche fin dalla giovinezza. Nel 1809 scrisse il suo primo componimento poetico, il sonetto La morte di Ettore, seguito da altre poesie in italiano e latino, traduzioni da Orazio, dissertazioni di carattere filosofico e due tragedie.

Nel luglio del 1812, Giacomo Leopardi intraprese sette anni di studio intenso e appassionato che ebbero ripercussioni negative sulle sue già fragili condizioni di salute. Durante questo periodo, si dedicò all'apprendimento autodidatta del greco e dell'ebraico, svolse lavori filologici straordinari e scrisse opere di rilievo come la _Storia dell'astronomia_ (1813) e il _Saggio sopra gli errori popolari degli antichi_ (1815). Quest'ultimo spicca per le riflessioni sugli stupori infantili, i sogni e gli incubi, la quiete delle ore meridiane, così come per il terrore dei fulmini e delle tempeste.

All'indomani della sconfitta di Gioacchino Murat a Tolentino, scrisse con toni patriottici e antifrancesi _Agl'Italiani. Orazione per la liberazione del Piceno_ (1815). In parallelo continuava la propria attività poetica, componendo nel 1816 opere come l'_Inno a Nettuno_ (spacciato come traduzione da un originale greco), le _Odae adespotae_ (in greco e latino) e l'idillio funebre _Le rimembranze_. Di particolare rilievo furono anche le traduzioni di testi classici: gli _Idilli_ di Mosco e la _Batracomiomachia_ attribuita a Omero nel 1815, il primo libro dell'_Odissea_ e il secondo dell'_Eneide_ nel 1816, e la _Titanomachia_ di Esiodo nel 1817.

== La conversione letteraria

Lo studio approfondito di queste opere segnò una svolta decisiva nella vita di Leopardi, portandolo alla sua "conversione letteraria", ovvero alla scoperta della vocazione poetica emersa tra il 1815 e il 1816. Questo cambiamento fu frutto di profondi conflitti interiori alimentati dalle sue esperienze culturali e personali. Da un lato, l'aggravarsi della sua malattia e l'angoscia per la morte imminente, insieme al tormento per una giovinezza sfiorita prematuramente, trovarono espressione nella cantica _Appressamento della morte_ (1816). Dall'altro lato, cresceva in lui un profondo desiderio di libertà e evasione dalla "prigionia" di Recanati.

Nel 1816, Leopardi cercò di inserirsi nel dibattito tra classicisti e romantici con una _Lettera_, rimasta inedita, contestando le idee di Madame de Staël sul rinnovamento della letteratura italiana tramite l'influenza degli autori stranieri. L'anno successivo iniziò a corrispondere con Pietro Giordani, figura eminente del classicismo liberale, che fu il primo a riconoscere il talento straordinario del giovane Leopardi. Sempre nel 1817, il poeta visse un'intensa esperienza sentimentale: si innamorò improvvisamente della cugina ventiseienne di Monaldo, Geltrude Cassi Lazzari, durante una visita a Recanati. Questo amore lo ispirò nella composizione dell'_Elegia I_ (_Il primo amore_), dell'_Elegia II_ e del _Diario del primo amore_, dove analizzò con una prosa limpida e vivace le fasi e gli effetti di quell'innamoramento.

=== Lo _Zibaldone_

Il 1817 rappresenta un anno cruciale anche per l'inizio della stesura dello _Zibaldone_, cui Leopardi dedicò numerosi appunti tra luglio e agosto. Quest'opera monumentale si sviluppò fino al 4 dicembre 1832, raggiungendo l'impressionante mole di 4526 pagine manoscritte. Lo _Zibaldone_ è un vero e proprio laboratorio intellettuale dove si alternano riflessioni filosofiche, bozzetti poetici, appunti introspettivi fulminei e approfondimenti sui meccanismi della memoria, dei sensi e delle emozioni. Vi si trovano dissertazioni sui rapporti tra individuo e società, considerazioni filologiche e analisi delle lingue e letterature antiche e moderne.

Sono famose le riflessioni approfondite sulla percezione dei suoni e sulla visione di spazi e oggetti che evocano l'infinito, così come quelle sulla noia, la malinconia, il riso, la giovinezza e l'amore, temi che troveranno espressione poetica nei _Canti_. L'opera fu pubblicata per la prima volta tra il 1898 e il 1900 con il titolo _Pensieri di varia filosofia e di bella letteratura_; tuttavia, già dal 1845 erano noti i 111 _Pensieri_, che Leopardi aveva personalmente predisposto per la stampa, traendoli in gran parte dallo _Zibaldone_.

== La conversione filosofica

La crisi personale di Leopardi raggiunse il culmine nel 1819, periodo in cui, oltre alle sofferenze già presenti, si aggiunse una malattia agli occhi che gli impose di abbandonare persino la lettura. Nel luglio dello stesso anno, un tentativo di fuga dalla casa paterna, con l'intenzione di recarsi a Roma, fu prontamente scoperto e bloccato da suo padre Monaldo.

Nel frattempo, il senso di inquietudine e lo scetticismo filosofico si acuirono, portandolo a una profonda consapevolezza del nulla. Scrive nello _Zibaldone_: "Io era spaventato nel trovarmi in mezzo al nulla, un nulla io medesimo. Io mi sentiva come soffocare, considerando e sentendo che tutto è nulla, solido nulla". L'idea che la realtà sia costituita dal nulla e che questo nulla abbia una consistenza "solida", corporea, è uno dei tragici paradossi fondamentali del pensiero leopardiano. Questo pensiero dà origine a una serie di altri paradossi: il mistero doloroso racchiuso nel nulla rappresenta un interrogativo titanico che la natura dissemina in frammenti, coinvolgendo ogni aspetto dell'esistenza umana. 

Dal "mirabile e spaventoso" arcano custodito nel nulla nasce il bisogno disperato delle "illusioni", anch'esse percepite come corporee: piaceri "vani" ma al tempo stesso "solidi". In questo contesto dominato dal "nulla", Leopardi affrontò con spirito solitario i grandi temi che avevano animato il pensiero del Settecento e che riemergevano, in forme diverse, nel dibattito romantico. Meditando intensamente, mise a fuoco una serie di contrapposizioni. La prima è quella tra natura e ragione, un'antitesi mutuata da J.-J. Rousseau: mentre la natura tende alla felicità, la ragione la distrugge; la natura è il regno delle illusioni, della poesia e del "bello", mentre la ragione, portatrice di verità, inaridisce l'animo e spezza i sogni.

Questo dualismo tra poesia e filosofia si traduce nel contrasto tra "poesia di immaginazione" e "poesia sentimentale". Per Leopardi la vera poesia è solo quella che nasce dalla fantasia creatrice di miti; tuttavia, gli uomini moderni, intrappolati nella realtà del "vero arido", riescono a produrre soltanto poesia sentimentale, una forma che si avvicina più alla filosofia. La consapevolezza dell'inevitabilità di una poesia profondamente influenzata dal pensiero avvicinava Leopardi ad alcune posizioni del movimento romantico, pur mantenendo sostanziali differenze e irreconciliabili divergenze.

Nel _Discorso di un italiano intorno alla poesia romantica_ (composto a partire dal 1818), Leopardi accettava i presupposti critici della scuola romantica, come il rifiuto dell'imitazione degli antichi e l'abuso della mitologia. Tuttavia, tra i principi costruttivi condivideva soltanto l'interesse per il "patetico", interpretandolo non come una possibilità creativa ma come una dolorosa necessità: un abbandono sofferto della fantasia senza adeguato compenso emotivo o estetico.

== I primi _Canti_

Constatando il vuoto universale, la poesia di Leopardi si sviluppava sotto il segno della precarietà, come paradosso, sfida e tentazione: nasceva proprio nel momento in cui il poeta aveva sancito la fine della poesia stessa. Dopo il fallimento di alcuni esperimenti romantici, la vera voce poetica leopardiana prese forma e si articolò su due piani distinti: le nove canzoni (1818-1822) e i cinque idilli (1819-1821), che costituirono il nucleo iniziale di quello che sarebbe diventato il _Libro dei Canti_. Questo "libro", frutto di pubblicazioni parziali e continue modifiche di lessico e stile, si consolidò attraverso tre tappe fondamentali: l'edizione Piatti (Firenze, 1831) con 23 liriche; l'edizione Starita (Napoli, 1835) con 39 liriche; e l'edizione postuma Le Monnier (Firenze, 1845) con 41 poesie.

== Le _Canzoni_

Fra le nove canzoni leopardiane, le prime cinque risentono in parte dell'influenza esercitata da Giordani, che proponeva una poesia come "magistero civile" ispirato ai modelli classici, ma riflettono anche l'anelito del poeta verso azioni eroiche e ideali, manifestato più volte nelle lettere e nello _Zibaldone_. _All'Italia_ e _Sopra il monumento di Dante_, scritte nel 1818, trattano temi patriottici e mettono a confronto un passato glorioso con un presente umiliato dalla schiavitù e dalla viltà.

La canzone _Ad Angelo Mai_ (1820), inizialmente concepita come un'esortazione alla riscossa morale e civile, si evolve in una riflessione più ampia: la decadenza del presente diventa simbolo della condizione universale dell'umanità, che ha perso le illusioni di un felice stato naturale precipitando in un'epoca dominata dalla dolorosa consapevolezza del "vero". Quest'ultima genera noia e senso di vuoto esistenziale.

Questo pessimismo radicale trova conferma in _Le nozze della sorella Paolina_ (1821), dove Leopardi, privo ormai di speranze per un riscatto del presente, esalta la virtù come valore assoluto e stoico. Analogamente, in _A un vincitore nel pallone_ (1821), si celebrano l'agonismo e il rischio come ultimi baluardi contro un'esistenza priva di significato. La conclusione sconvolgente ("Nostra vita a che val? Solo a spregiarla") segna il passaggio alle due grandi allegorie dell'infelicità umana: _Bruto minore_ (1821) e _L'ultimo canto di Saffo_ (1822), dove ormai la natura assume il ruolo di matrigna crudele piuttosto che di madre benevola.

In _Bruto minore_, il protagonista, morente, demolisce il mito della virtù e attraverso il suicidio si erge titanicamente contro la divinità, sfidandola con parole cariche di rabbia. Saffo, invece, figura tragica disprezzata perché privata della bellezza dalla natura stessa, si abbandona anch'essa al suicidio. Tuttavia, la protesta di Saffo assume toni elegiaci e profondamente struggenti, diversamente da quelli di Bruto. Completano il percorso poetico leopardiano del 1822 _Alla primavera_ e _Inno ai patriarchi_, che segnano un duplice commiato: dalla mitologia classica pagana e da quella biblica. 

=== Gli idilli

Gli idilli autentici, definiti da Leopardi come "esprimenti, situazioni, affezioni, avventure storiche del mio animo", si riducono a cinque componimenti chiave: _L'infinito_ (1819), _Alla luna_ (1819), _La sera del dì di festa_ (1820), _Il sogno_ (1820-21) e _La vita solitaria_ (1821). In contrapposizione alle canzoni, le "situazioni idilliche" si sviluppano interamente nel soggetto, configurandosi come frammenti della "storia di un'anima" vissuti in uno spazio circoscritto e in un momento definito. Questi momenti vengono costantemente reinterpretati dalla memoria e posti in relazione con altre esperienze interiori già vissute.

Il cambiamento si avverte anche nello stile: alla complessa sintassi delle canzoni, arricchita da un vocabolario ricco di arcaismi e latinismi, subentra un linguaggio più semplice e limpido. Questo conserva tuttavia un raffinato equilibrio tra termini rari e parole quotidiane, mantenendo una tonalità profondamente poetica. Tra i capolavori spiccano _L'infinito_ e _Alla luna_, entrambi componimenti brevi ma straordinariamente intensi: il primo evoca la vertigine dell'infinito suggerita per contrasto da elementi finiti, mentre il secondo celebra la dolcezza della memoria in un intimo dialogo col satellite, elevato a simbolo di rimembranza sublime.

== Il silenzio poetico

Nel periodo compreso tra il 1822 e il 1828, Leopardi sperimentò un lungo silenzio poetico, interrotto soltanto da due componimenti: la canzone _Alla sua donna_ (1823), un congedo dall'ideale femminile irraggiungibile che incarna la poesia stessa in fuga, e l'epistola _Al conte Carlo Pepoli_ (1826). Quest'ultima è una raffinata opera in cui il tono si alterna tra oraziano e pariniano, segnando simbolicamente la conclusione di una fase creativa che il poeta considerava ormai chiusa. Il componimento si chiude con l'ammissione di Leopardi di abbandonare il campo poetico per dedicarsi agli studi dell'"acerbo vero".

Nonostante il silenzio letterario, quegli anni furono ricchi di esperienze importanti. Nel novembre 1822 Leopardi si trasferì a Roma presso lo zio Carlo Antici, ma rimase profondamente deluso sia dalla città che dal suo ambiente erudito-archeologico. Solo la visita alla modesta tomba del Tasso gli regalò un momento di intensa commozione. Tornato a Recanati nel 1823, ripartì nel 1825 per accettare l'incarico di curare un'edizione delle opere di Cicerone per l'editore milanese Antonio Fortunato Stella. Successivamente soggiornò a Bologna, Firenze (dove frequentò il Gabinetto Vieusseux e il circolo dei liberali toscani) e Pisa, città che gli offrì uno dei periodi più piacevoli e salutari.

== Le _Operette morali_

Leopardi compose quasi tutte le _Operette morali_ tra il 1824 e il 1827, facendo emergere tematiche centrali che ne attraversano il tessuto narrativo. Tra queste spiccano il tema dell'illusione e della felicità irraggiungibile, come illustrato nel _Dialogo di un Folletto e di uno Gnomo_; quello della natura e del piacere, affrontato nel _Dialogo della Natura e di un'Anima_ e nel _Dialogo della Natura e di un Islandese_. Inoltre, Leopardi si concentra sulla noia, considerata peggiore del dolore, come nel _Dialogo di Torquato Tasso e del suo Genio familiare_ o nel _Dialogo di Cristoforo Colombo e di Pietro Gutierrez_. Infine, emerge anche una riflessione più generale sulla responsabilità dell'individuo verso se stesso e la società, ben rappresentata nel _Dialogo di Federico Ruysch e delle sue mummie_.

Le opere successive, scritte nel 1832, come il _Dialogo di un venditore d'almanacchi e di un passeggere_ e il _Dialogo di Tristano e di un amico_, introducono nuove prospettive. In queste prose si affaccia una visione della vita più pacata, ma allo stesso tempo più eroica. Le _Operette morali_ rappresentano una sintesi tra filosofia e poesia: le idee e i ragionamenti si trasformano in immagini vivide e allegorie grazie a una prosa accuratamente elaborata. Leopardi riesce così a rinnovare i modelli antichi — soprattutto i dialoghi di Luciano — con una «leggerezza apparente», arricchendoli di soluzioni originali e dinamiche che alternano meditazione e ironia, passaggi lirici ed intensi scambi dialettici.

== I _grandi Idilli_

Durante il suo soggiorno a Pisa, nell'aprile del 1828, Leopardi scrisse alla sorella Paolina comunicandole la propria riscoperta dell'ispirazione poetica: "Dopo due anni, ho fatto dei versi quest'Aprile; ma versi veramente all'antica, e con quel mio cuore d'una volta". I versi in questione erano _Il risorgimento_ e _A Silvia_. A questi seguirono altri canti memorabili, tra cui _Il passero solitario_, _Le ricordanze_, _La quiete dopo la tempesta_, _Il sabato del villaggio_ e il _Canto notturno di un pastore errante dell'Asia_, composti tra il 1829 e il 1830 durante il ritorno forzato del poeta a Recanati. Leopardi fu costretto a tornare nel novembre del 1828 a causa della sospensione dell'assegno dello Stella e del peggioramento delle sue condizioni di salute.

In questo periodo trascorse quasi un anno e mezzo immerso in una malinconia che definì "oramai poco men che pazzia". Fu proprio in questo contesto di profonda disperazione che nacquero gran parte dei cosiddetti "grandi idilli". La loro composizione fu accompagnata da un importante approfondimento teorico sulla poesia intesa come pura lirica, slegata dall'imitazione, dalle regole precostituite e da fini pratici. È proprio durante questa fase che la denominazione "canto" si afferma: _Canti_ sarà il titolo dell'edizione del 1831, ufficializzato nella raccolta del 1835. Questo titolo segnava una rottura con i precedenti della letteratura italiana, eliminando ogni riferimento a "generi" o "sottogeneri" in favore della celebrazione della poesia nella sua forma più pura.

_Il risorgimento_ costituisce una particolare celebrazione della "rinascita del cuore", espressa attraverso strofe metastasiane. Diverso il tono nei canti successivi: _A Silvia_ è un tributo alla giovinezza perduta e mai vissuta pienamente; _Le ricordanze_, invece, nasce dalla memoria nostalgica di un mondo e di un'età colmi di fantasie e illusioni. Nel _Canto notturno di un pastore errante dell'Asia_, Leopardi riflette sul mistero della natura e dell'esistenza.

Il dittico costituito da _Il sabato del villaggio_ e _La quiete dopo la tempesta_ rappresenta gli "apologhi del borgo," accomunati per stile e tematiche al _Passero solitario_. In quest'ultima composizione, la "rimembranza" emerge come tema dominante nella visione limpida e quasi "mitica" del villaggio e della casa paterna. Il paesaggio e la memoria si trasformano in luoghi e figure favolistiche, capaci di condensare una struggente nostalgia per i sogni e le fantasie dell'infanzia, affiorando come frammenti di una poetica che idealizza la semplicità del passato.

Nel _Canto notturno di un pastore errante dell'Asia_, la riflessione filosofica e la liricità si ampliano verso orizzonti più vasti. Qui, lo spazio circoscritto del borgo lascia il posto a un ambiente desertico, sconfinato e ignoto. La voce del poeta si trasfigura in quella del pastore errante, figura enigmatica che interroga la luna con una serie di domande incalzanti sul senso dell'esistenza, sulla origine della vita e sull'essenza dell'universo, delineando così una meditazione che trascende il tempo e lo spazio.

== La nuova poetica e gli ultimi canti

Nel 1830, accettando un prestito dagli amici fiorentini, Leopardi abbandonò definitivamente Recanati. Stabilitosi a Firenze, riallacciò vecchi legami e ne creò di nuovi, tra cui l'amicizia con Antonio Ranieri, esule napoletano che divenne suo inseparabile sodale negli ultimi anni, e il rapporto tormentato con Fanny Targioni Tozzetti, da cui nacque una violenta e sfortunata passione amorosa. Dal 1833 Leopardi trascorse gli ultimi anni della sua vita a Napoli, sempre più segnato dalla malattia, fino alla morte avvenuta il 14 giugno 1837.

L'ultima fase della vita del poeta è contraddistinta da un netto rifiuto della sua precedente condizione di solitudine, a metà fra il malinconico abbandono e l'ostile distacco. Di fronte al decadimento fisico, Leopardi manifestò una crescente necessità di affermazione personale attraverso la sua filosofia, definita "disperata ma vera," antagonista rispetto alle visioni ottimistiche dell'esistenza. Questa tensione intellettuale si tradusse in un marcato disprezzo per le correnti spiritualistiche contemporanee e in una pungente critica all'entusiasmo ingenuo dei liberali, espressa in testi come la _Palinodia al marchese Gino Capponi_ (1835), la satira _I nuovi credenti_ e il poemetto _Paralipomeni della Batracomiomachia_, tutti appartenenti al medesimo periodo.

Di particolare rilevanza sono gli ultimi canti di Leopardi, inseriti nel cosiddetto "ciclo di Aspasia," composti tra il 1832 e il 1835. Questi testi, ispirati dall'amore non corrisposto per Fanny Targioni Tozzetti, rappresentano una sofferenza vissuta non solo con i sensi ma anche con l'anima. Tra questi spiccano le due canzoni "sepolcrali," _Sopra un bassorilievo antico sepolcrale_ e _Sopra il ritratto di una bella donna_ (1834-35), improntate a una meditazione sulla morte pervasa da profonda pietas e da una dolorosa ma rigorosa riflessione.

Il "ciclo di Aspasia" offre una narrazione completa dell'amore negato: dalla sua fase "positiva" (_Il pensiero dominante_, _Consalvo_, _Amore e Morte_) alla fase "negativa" che rivela l'inganno (_A se stesso_, _Aspasia_). Questo percorso poetico è sorretto dall'inscindibile legame tra ideologia e canto, laddove alla rappresentazione degli eventi si associa costantemente uno sguardo razionale che analizza la loro essenza.

_Il tramonto della luna_ celebra la fine dell'"inganno idillico". Il paesaggio lunare viene evocato con la delicatezza delle parole un tempo usate, ma solo come "quadro di paragone", per sottolinearne il contrasto simmetrico con la "vita mortal". Quest'ultima, a differenza delle "collinette e piagge", non si tingerà "d'altra aurora" quando sopraggiunge la notte, ovvero la vecchiaia.

La chiusura del "libro" (escludendo _Imitazione_, _Scherzo_ e i cinque _Frammenti_, che formano una sorta di appendice) è affidata alla Ginestra, una poesia dall'ampia e maestosa orchestrazione. Lontana dall'essere un semplice commiato, essa riprende temi antichi, ora riletti e riformulati con nuove sensibilità ideologiche e stilistiche. Il paesaggio desertico e vulcanico, costellato di rovine, diventa lo scenario centrale, un terreno devastato che contrasta l'incantevole spettacolo delle stelle, fiammeggianti "in un purissimo azzurro" e riflesse nel mare.

Riemerge anche la critica al "secol superbo e sciocco", che si illude nelle "magnifiche sorti e progressive", ignorando l'ineluttabile ferocia della natura distruttrice. Tuttavia, questa polemica si spoglia di ogni asprezza animosa: il titanismo leopardiano si fonde ora con la pietà, trasformandosi in un messaggio di fratellanza tra gli uomini, legati da un comune destino di infelicità.

== I giudizi su Leopardi

Leopardi non fu pienamente apprezzato dai suoi contemporanei, a eccezione di pochi (come Pietro Giordani, Vincenzo Gioberti e Carlo Tenca), a causa della sua distanza sia dai classicisti sia dai romantici. Successivamente, venne celebrato (da Francesco De Sanctis e Benedetto Croce) soprattutto come grande poeta lirico, il "poeta degli idilli". Nei primi decenni del Novecento si sviluppò una predilezione per il Leopardi prosatore, mentre durante il periodo della "poesia pura" e dell'ermetismo furono esplorati, attraverso prospettive e metodi diversi, i valori musicali ed evocativi della sua scrittura poetica (Giuseppe De Robertis e Giuseppe Ungaretti).

Parallelamente, emerse l'importanza del pensiero laico e progressista di Leopardi. In tempi più recenti, si è posto l'accento su Leopardi filosofo: sul suo nichilismo, collocandolo in relazione con le correnti irrazionalistiche e del pensiero "negativo" dell'Occidente, da Schopenhauer a Nietzsche fino a Benjamin, i quali hanno dedicato riflessioni significative al poeta di Recanati.

#pagebreak()
#set page(fill: accent.ita.lighten(90%))
== In sintesi <senza_numero>

/ Vita:  Poeta e filologo autodidatta e precoce, Giacomo Leopardi trascorse gran parte della sua esistenza nella sua città natale, Recanati, tormentato da gravi problemi di salute. Nonostante ciò, fece brevi soggiorni a Roma, Milano, Firenze, Pisa e Bologna, per poi stabilirsi definitivamente a Napoli, dove trovò la morte.  

/ Filosofia:  Leopardi concepì la realtà come un "solido nulla", in cui la materia genera dolore e la natura rappresenta l'incarnazione enigmatica del nulla stesso. La sua visione filosofica rigetta approcci spiritualistici e ottimistici, ponendo l'esistenza sotto il segno di una radicale negazione.  

/ Opere in prosa:  Il celebre _Zibaldone_, che raccoglie riflessioni e annotazioni scritte tra il 1817 e il 1832, costituisce un poderoso laboratorio di introspezione. Le _Operette morali_, invece, si presentano come un capolavoro di ironia e lucidità filosofica.  

/ Opere poetiche:  Ne _I Canti_, pubblicati in edizioni successive nel 1831 e 1835, e infine postumi nel 1845, Leopardi riunisce diversi nuclei poetici. Tra questi si annoverano le prime nove canzoni (es. _Ad Angelo Mai_, _Le nozze della sorella Paolina_, _A un vincitore nel pallone_, _Bruto minore_, _Ultimo canto di Saffo_, 1818-1822) e i piccoli idilli (tra cui spiccano _L'infinito_ e _Alla luna_, 1819-1821). Seguono i grandi idilli (es. _Il risorgimento_, _A Silvia_, _Il passero solitario_, 1828-1829), nonché il cosiddetto "ciclo di Aspasia" (_Il pensiero dominante_, _A se stesso_, _Aspasia_, 1832-1835). Infine, troviamo _Il tramonto della luna_ e il coro de _La Ginestra_.  

/ Poetica:  La poesia leopardiana mette al centro il dolore umano, offrendo come unica risposta il riconoscimento sincero della verità personale. La letteratura diventa così esperienza di memoria struggente, critica verso l'ottimismo e aperta alla ricerca di una consolazione filosofica.  