#import "../../../template_normal.typ": *
//#show: frame-style(styles.thmbox)

#evidenzia[La letteratura latina prende avvio intorno alla metà del III secolo a.C., con una data simbolica indicata dagli stessi Romani: il 240 a.C., anno in cui venne rappresentata per la prima volta un'opera teatrale attribuita a Livio Andronico, probabilmente una tragedia. Sin dalle sue origini, questa letteratura risente profondamente dell'influenza della tradizione greca, instaurando con essa un rapporto costante e dialettico. Nel corso di cinque secoli, Roma conquista l'Italia centrale e meridionale, definisce la propria identità culturale, istituisce un sistema giuridico e organizza le sue istituzioni politiche e religiose. Tuttavia, nel medesimo periodo non produce opere letterarie di rilievo, nonostante i suoi frequenti contatti con la fiorente cultura ellenistica della Magna Grecia.

Esisteva, però, una produzione anonima tramandata oralmente, che aveva prevalentemente scopi pratici o occasionali e che può essere definita come preletteraria. Questa si manifestava attraverso forme poetiche rudimentali, prive di un autentico intento letterario e caratterizzate da un latino arcaico e primitivo. I documenti superstiti di questa fase primaria sono molto scarsi e rivestono maggiore interesse dal punto di vista della storia culturale e linguistica piuttosto che letteraria. Ciononostante, tali testimonianze hanno esercitato una certa influenza sui successivi sviluppi della letteratura latina, in particolare per quanto riguarda il teatro, l'oratoria e la storiografia.]

== Le iscrizioni

I documenti epigrafici giunti fino a noi, estremamente rari, si presentano spesso di difficile interpretazione a causa della complessità linguistica che li caratterizza. Tuttavia, essi attestano che già nella Roma arcaica del VI secolo a.C. la scrittura era un mezzo largamente diffuso tanto per usi pubblici quanto privati, specialmente tra i ceti dominanti e la classe sacerdotale. Si trattava, nello specifico, di un sistema alfabetico derivato dalla tradizione greca, introdotto attraverso le città della Magna Grecia.

Particolarmente enigmatica risulta l'iscrizione del cosiddetto _Lapis Niger_, risalente ai secoli VII-VI a.C., resa ancor più oscura dalla frammentarietà del testo. Questa iscrizione fu incisa su un cippo parallelepipedo rinvenuto nel Foro Romano verso la fine del XIX secolo, al di sotto di una pavimentazione in marmo nero. Secondo la tradizione, tale luogo corrisponderebbe alla tomba di Romolo. Il testo riporta prescrizioni di carattere religioso finalizzate all'interdizione dell'accesso a un'area sacra; vi si fa inoltre menzione di un _rex_, probabilmente una figura sacerdotale. L'iscrizione è redatta in caratteri greci e segue lo stile bustrofedico, in cui le righe si alternano da destra a sinistra e da sinistra a destra, con lettere opportunamente orientate in base alla direzione della scrittura.

Sempre attribuibile allo stesso periodo e altrettanto complessa da interpretare è l'iscrizione presente sul cosiddetto Vaso di Dueno, un piccolo recipiente in terracotta, forse destinato a riti sacrificali o utilizzato come contenitore di cosmetici. Questo reperto fu ritrovato tra il Quirinale e il Viminale e presenta una scrittura che procede da destra a sinistra, senza separazione tra le singole parole. Sebbene il significato rimanga incerto, sembrerebbe alludere alla destinazione votiva dell'oggetto o, in alternativa, al dono di una fanciulla per il proprio amato. Nonostante ciò, l'unico dato ricavabile – peraltro discutibile – è che l'opera potrebbe esser stata realizzata da un certo Dueno.

Di più semplice comprensione è invece l'iscrizione sulla cosiddetta Cista Ficoroni, databile a un'epoca considerevolmente più recente. Questo testo, inciso su un cofanetto cilindrico in bronzo ritrovato a Preneste (l'odierna Palestrina), recita: "Dindia Malconia mi donò alla figlia; Novio Plauzio mi fece a Roma". Invece, critiche accese e dubbi persistono sull'autenticità dell'iscrizione riportata sulla Fibula Praenestina, considerata il primo documento in lingua latina giunto sino a noi. Rinvenuta anch'essa in una tomba di Preneste, si tratta di una fibbia in oro risalente al VI secolo a.C., sulla quale compaiono i nomi dell'orafo o del donatore e del destinatario: "Manio mi fece per Numerio". La scrittura segue uno schema da destra a sinistra ed è realizzata con caratteri greci, senza alcun intervallo tra le parole.  

#note(top)[== *🧩* Il verso saturnio <senza_numero>

Il verso saturnio, unica forma metrica impiegata nella poesia latina arcaica, deve il proprio nome al dio Saturno, il quale, secondo la tradizione mitologica, si rifugiò nel Lazio dopo essere stato scacciato dal cielo; è altresì noto come _faunio_, in onore del dio Fauno, figura autoctona e considerata l'ipotetico inventore di questo metro. Il poeta Ennio testimonia che gli antichi compositori di canti utilizzavano i saturni e che tale verso era adoperato da vati e fauni, forse facendo riferimento al suo ruolo nei canti religiosi e rurali della tradizione primitiva. 

Il saturnio si caratterizza per una struttura altamente fluida e imprevedibile, al punto che gli studiosi non concordano sulla sua effettiva natura. Esso potrebbe basarsi su un ritmo quantitativo, ossia costruito secondo una sequenza precisa di sillabe lunghe e brevi; su un ritmo accentuativo, derivante dall'alternanza di sillabe toniche e atone; o ancora su una combinazione di entrambi questi elementi. Questa difficoltà nell'identificazione deriva anche dal fatto che tra i pochi esempi rimasti -- circa duecento versi distribuiti tra fonti epigrafiche e letterarie -- non si riscontra alcuna regolarità strutturale. È plausibile che nelle prime fasi della sua evoluzione il saturnio avesse un ritmo accentuativo, radicato nella tradizione indoeuropea, per poi assumere progressivamente una forma quantitativa, più adeguata alle caratteristiche della lingua latina e alle esigenze della poesia letteraria. 

Già nel I secolo d.C., Cesio Basso, grammatico latino, sosteneva la natura quantitativa del saturnio, descrivendolo come composto da due membri metrici o _cola_: il primo costituito da un dimetro giambico catalettico e il secondo da un itifallico o da una tripodia trocaica. Tuttavia, egli stesso riconosceva di aver trovato un solo esempio che rispondesse a questa descrizione.  

Pur essendo ampiamente utilizzato nei secoli della prima fase della letteratura latina, il saturnio conobbe una progressiva decadenza; fu infatti adottato dai primi poeti come Livio Andronico e Nevio, ma venne successivamente soppiantato dall'esametro d'origine greca. Il motivo di questo cambiamento può essere ricondotto all'eccessiva irregolarità del saturnio, giudicata inadeguata rispetto ai gusti sempre più sofisticati degli autori dell'età classica.]

=== Le tombe degli Scipioni

Le iscrizioni sepolcrali incise sui sarcofaghi della potente famiglia degli Scipioni, situati fuori Porta Capena lungo la via Appia, sono di notevole interesse documentario. Questi reperti rappresentano la più antica testimonianza diretta del verso saturnio e dimostrano una buona conoscenza delle epigrafi funerarie di tradizione greca. 

L'epitaffio dedicato a Lucio Cornelio Scipione Barbato, console nel 298 a.C., è una revisione posteriore al 200 a.C., come attestano le caratteristiche linguistiche; invece, quello dedicato al figlio omonimo è sicuramente più antico. In esso si legge: "Molti Romani concordano che solo questo uomo / fu il migliore tra gli onesti / Lucio Scipione, figlio di Barbato. / Egli ricoprì le cariche di console, censore ed edile presso di voi. / Conquistò la Corsica e la città di Aleria / e consacrò un tempio alle Tempeste come gesto di devozione".

== La prosa: diritto, cronaca e oratoria

Nei secoli iniziali, pur non essendo di carattere strettamente letterario, la prosa contribuì in modo significativo all'evoluzione linguistica, creando un terreno favorevole per lo sviluppo della letteratura.

=== Il diritto

Molti documenti di rilevanza storica sono purtroppo andati perduti. Questo è il caso dei trattati (_foedera_) che regolavano accordi di alleanza, pace e commercio con i popoli con cui i Romani intrattenevano rapporti, come il trattato commerciale con Cartagine del 509 a.C. o il patto stipulato con la Lega italica nel 493 a.C. Gli storici romani si limitano a fornire un elenco sommario di tali trattati, senza approfondire i contenuti degli accordi né i principi su cui si fondava il diritto internazionale primitivo.

Per quanto riguarda le _leges regiae_ (leggi regie), attribuite dalla tradizione a Romolo e agli altri re di Roma, ciò che resta sono solo frammenti riportati da giuristi vissuti in epoche successive. Non si trattava di leggi scritte, ma di norme tramandate oralmente tra i membri dell'élite dominante. Queste leggi si basavano probabilmente su consuetudini legate a rituali religiosi e norme di diritto privato. Sempre secondo la tradizione, tali norme sarebbero state raccolte in un codice chiamato _Ius civile Papirianum_ dal pontefice Sesto Papirio durante il regno di Tarquinio il Superbo.

Le _Leggi delle XII Tavole_ rappresentano un contributo di fondamentale importanza, sia dal punto di vista storico che giuridico, in quanto costituiscono la prima espressione scritta del diritto romano. Tito Livio le descrisse secoli più tardi come la "fonte di ogni diritto pubblico e privato". Durante l'età di Cicerone, esse venivano ancora utilizzate come autorevole testo scolastico. La loro redazione fu il risultato delle pressanti richieste della plebe che, per ottenere una maggiore certezza del diritto, spinse per la creazione di norme scritte. Tali leggi furono elaborate da una commissione di dieci magistrati, i decemviri _legibus scribundis_, tra il 451 e il 450 a.C., e incise su dodici tavole di bronzo esposte nel Foro Romano.

Oltre all'inestimabile valore giuridico, le XII Tavole rivestono una rilevanza significativa anche sul piano letterario: benché non siano pervenute nel loro testo originale ma in versioni successive, con modifiche occasionali di termini, esse rappresentano il primo esempio di prosa strutturata dell'epoca arcaica. Stilisticamente sono caratterizzate da una scrittura concisa ed essenziale. 

Tra gli esempi tramandatici possiamo citare il principio secondo cui, "se un ladro ruba di notte e il derubato lo uccide, tale uccisione è da considerarsi legittima". Un'altra norma stabilisce che "in relazione agli stranieri vale il diritto di rivendicazione", mentre un'altra recita: "se un padre vende per tre volte il figlio, il figlio sia affrancato dalla patria potestà".

Pur risentendo di possibili influenze greche, le XII Tavole riflettono in maniera pregnante le consuetudini del popolo romano e il suo spiccato pragmatismo. Sebbene esse non costituiscano un sistema organico capace di abbracciare l'intero diritto pubblico e privato, rappresentano un progresso significativo verso l'uguaglianza giuridica dei cittadini romani. La codificazione scritta del diritto segnò una conquista cruciale per la plebe, poiché contrastava la gestione arbitraria tipica delle élite dominanti, che detenevano fino ad allora il monopolio del sapere giuridico attraverso la tradizione orale.

=== La cronaca

Un altro elemento centrale nella società romana erano i "fasti", veri e propri registri civici compilati dai pontefici. Essi indicavano i giorni dell'anno in cui era possibile svolgere attività pubbliche (_fasti_) e quelli in cui tale pratica era proibita per motivi religiosi (_nefasti_). Inoltre, documentavano cerimonie, mercati, fenomeni naturali e astronomici, così come eventi straordinari. Il termine _fasti_ venne poi utilizzato per designare anche gli elenchi ufficiali dei magistrati annuali, degli atti pubblici e delle imprese militari (come i _fasti consulares_, _fasti pontificales_ e _fasti triumphales_).

Successivamente, il collegio dei pontefici pose in essere un'importante iniziativa memorialistica: ogni anno veniva registrato sulla _Tabula Dealbata_, esposta nella Regia – sede del pontefice massimo e del rex sacrorum –, non solo l'elenco dei magistrati in carica, ma anche gli eventi salienti di natura civile, religiosa, commerciale e militare. Tali annotazioni, conosciute complessivamente come _annales_, costituivano una cronaca essenziale della storia romana.

Nel II secolo a.C., per iniziativa del pontefice Publio Muzio Scevola, questi _annales_ furono raccolti e organizzati in ottanta volumi con il titolo di _Annales Maximi_. Tuttavia, gran parte delle informazioni precedenti al 390 a.C. era andata perduta a seguito di un devastante incendio, lasciando scarse testimonianze sui primi secoli della storia di Roma. Parallelamente, gli alti magistrati romani – come consoli, questori e censori – redigevano resoconti personali delle loro attività mediante i cosiddetti _commentarii_, annotazioni private che potevano essere successivamente depositate presso il collegio dei pontefici e divenire così pubbliche. In modo analogo, anche i vari collegi sacerdotali conservavano i loro atti nei _Libri pontificum_, nei _Libri augurum_ e nei _Libri saliorum_.

=== L'oratoria e Appio Claudio Cieco
//
Fin dalle origini della Repubblica, l'oratoria ricoprì un ruolo di primaria importanza, poiché l'arte di parlare e persuadere garantiva fama, successo e potere, elementi essenziali per intraprendere una carriera politica. Questa disciplina, perfettamente in linea con la natura pragmatica del popolo romano, era considerata l'unica occupazione intellettuale adeguata a un cittadino appartenente alle classi più elevate. Non si conosce nulla degli oratori precedenti ad Appio Claudio Cieco, il primo del quale abbiamo testimonianze storiche certe.

Appio Claudio Cieco, patrizio vissuto tra il IV e il III secolo a.C., si dimostrò particolarmente sensibile ai problemi sociali del suo tempo. Nel 312 a.C., durante il suo incarico di censore, introdusse in Senato nuovi uomini, includendo persino i figli di ex schiavi. A lui si deve la costruzione del primo acquedotto romano, l'_Aqua Appia_, e l'avvio dei lavori per la via Appia, la celebre _regina viarum_, la prima grande strada militare che collegava Roma a Capua. Fu console nel 307 e nel 296 a.C., partecipando alle guerre sannitiche. Nonostante l'età avanzata e la cecità, nel 280 a.C. indirizzò al Senato un celebre discorso che convinse i senatori a rifiutare le condizioni di pace offerte da Pirro, re dell'Epiro. Questo discorso, considerato il primo intervento ufficiale pubblicato a Roma, fu citato anche da Cicerone.

Appio Claudio fu autore del _Carmen de moribus_, una raccolta di massime morali in versi saturni. Di essa sono rimaste solo tre frasi, tra cui la famosa "Ognuno è artefice del proprio destino", la più conosciuta. Non è chiaro se i suoi scritti risentissero già dell'influenza della cultura greca. Si interessò anche al diritto, facendo raccogliere e pubblicare dal suo segretario, Gneo Flavio, il cosiddetto _Ius Flavianum_, la prima opera latina sui procedimenti giudiziari. La tradizione gli attribuisce inoltre una riforma ortografica che vide l'introduzione della consonante r intervocalica al posto della s e l'eliminazione della lettera z.

== La poesia: i carmina

Nella fase preletteraria della cultura romana, la poesia si limitava a espressioni di carattere pratico e occasionale, celebrando i sentimenti più profondi della vita spirituale, religiosa e civile attraverso componimenti chiamati carmina (dal verbo _cano_: canto), solitamente realizzati in versi saturni. In ambito letterario, il termine è utilizzato per indicare opere poetiche di una certa estensione; tuttavia, nell'antichità il _carmen_ non si riferiva esclusivamente a composizioni cantate o in versi, ma comprendeva anche tutto ciò che aveva un'aura di solennità e si distingueva dal linguaggio ordinario. Rientravano in questa categoria non solo poesie, ma anche preghiere, filastrocche infantili, formule magiche, leggi, profezie, incantesimi, lamenti funebri e persino giuramenti.

I carmina erano caratterizzati da contenuti semplici e uno stile piuttosto grezzo, nonostante i tentativi di adottare un tono espressivo più elevato. Gli strumenti tecnici a disposizione erano limitati: si basavano su rime, allitterazioni, assonanze, figure etimologiche e simmetrie. Inoltre, il ritmo monotono e cadenzato di queste composizioni facilitava la memorizzazione da parte degli ascoltatori.
//
=== I carmina religiosi

I carmina religiosi rappresentano una testimonianza significativa dei più antichi canti della poesia religiosa romana, risalenti al VI secolo a.C. Tra questi si annovera il _Carmen Saliare_, strettamente connesso ai rituali magico-religiosi dei Salii. Considerato uno dei primi testi della tradizione letteraria romana ad essere giunto sino a noi, esso ci è noto solo attraverso pochi frammenti, spesso oscuri e di difficile interpretazione, che sono stati tramandati grazie agli studi degli eruditi latini.

Ogni anno, nel mese di marzo e di ottobre, i sacerdoti dei Salii – dodici ministri del culto di Marte, il dio della guerra – si riunivano in processione per celebrare rispettivamente l'apertura e la chiusura della stagione guerresca. Il nome stesso dei sacerdoti, derivante dal verbo "salio" (da _salio_: saltare), rievoca la loro caratteristica attività rituale: vestiti con abiti da antichi guerrieri, attraversavano i luoghi più significativi della città di Roma intonando invocazioni agli dèi. Durante il rito, danzavano e battevano il suolo con passi ritmati in tempo ternario, percuotendo con bastoni gli _ancilia_, dodici scudi sacri di bronzo. La tradizione attribuisce l'istituzione del collegio dei Salii a Numa Pompilio, secondo re di Roma, il quale avrebbe ordinato loro di custodire l'ancile, uno scudo sacro caduto miracolosamente dal cielo come segno divino a protezione della città. Per garantirne la conservazione, furono realizzati altri undici scudi identici al primo, opera del mitico fabbro Mamurio Veturio.

Di tutt'altra natura e di gran lunga meglio conservato è il _Carmen Arvale_, anch'esso risalente al VI secolo. Questo testo ci è giunto in forma completa e affidabile poiché veniva tramandato accuratamente di generazione in generazione. Il Carmen Arvale era un canto propiziatorio volto a invocare la fertilità dei campi da parte delle divinità a cui era dedicato. La sua trascrizione più nota compare su frammenti di un epigrafe datata al 218 d.C., appartenente agli _Acta fratrum Arvalium_, ovvero gli atti ufficiali con cui i membri del collegio sacerdotale registravano le proprie attività.

Quest'inno cerimoniale costituiva il culmine della processione celebrata durante la festa degli _Ambarvalia_, che cadeva nel mese di maggio. Composto in versi saturni, il carme prevedeva la ripetizione triplice di ogni stanza, eccetto per l'ultima che veniva intonata cinque volte. Nonostante la sua struttura sia stata preservata, il significato del testo rimane enigmatico. Esso si rivolgeva ai Lari, a Marte e ai Semoni affinché difendessero i campi agricoli (_arva_) da pestilenze e calamità. 

L'esecuzione dell'inno avveniva nell'ambito del rito di purificazione dei campi e in altre importanti celebrazioni religiose ad opera dei _fratres Arvales_. Si trattava di un collegio composto da dodici sacerdoti patrizi votati al culto della dea Dia, figura associata alla terra fecondatrice e considerata un simbolo della rigenerazione agricola. Secondo la tradizione mitologica romana, tale collegio sarebbe stato istituito dal leggendario fondatore di Roma, Romolo. 
//
=== I carmina profani

Tra gli aspetti legati alla sfera privata e profana della cultura romana, spiccano i _carmina convivalia_, canti che, come testimonia Cicerone, venivano intonati durante i banchetti degli antenati. Era consuetudine che gli invitati, accompagnati dal suono del flauto, cantassero a turno le gesta e le virtù di uomini illustri. Questi banchetti, noti come _convivia_, erano occasioni di ritrovo per le classi più elevate, che si riunivano quasi quotidianamente, spesso nell'ambito di relazioni politiche. In tali momenti, la poesia, la musica e la danza giocavano un ruolo cruciale. I carmina, probabilmente composti in versi saturni, celebravano le imprese gloriose degli antenati illustri. Tuttavia, nessun frammento di questi componimenti è giunto fino a noi e nulla si conosce degli eroi così celebrati.

Un'altra forma di canto breve in versi saturni erano i _carmina triumphalia_. Questi erano improvvisati dai soldati durante le cerimonie trionfali in onore dei generali vittoriosi. Diversamente dal carattere solenne e celebrativo che il termine potrebbe suggerire, si trattava spesso di espressioni rustiche e popolari, nelle quali le lodi al vincitore si alternavano a battute taglienti, rozze e talvolta licenziose.

Completamente differenti dai canti trionfali erano invece le _neniae_, ovvero le lamentazioni funebri in versi, eseguite durante i funerali per rendere omaggio al defunto. In epoche antiche, esse erano intonate da un parente stretto del defunto, mentre in seguito il compito passò alle _praeficae_, donne appositamente ingaggiate per questo scopo. Probabilmente le _neniae_ includevano una parte d'improvvisazione guidata da uno schema fisso. I funerali delle figure di spicco di Roma assumevano spesso un carattere pubblico e solenne: consistevano in un corteo imponente che coinvolgeva parenti, amici e persino gli antenati, rappresentati da individui che indossavano maschere di cera. Giunti al Foro, un figlio del defunto o un parente stretto oppure un amico pronunciava una _laudatio funebris_, discorso commemorativo che esaltava le virtù e le imprese del caro scomparso.

== Il teatro

Fescennino, satura e atellana rappresentano le prime espressioni preletterarie del teatro romano. Queste forme artistiche erano tutte in versi e di natura popolare.

=== Il fescennino

Il fescennino era una tipica manifestazione del mondo rurale: consisteva in uno scambio vivace di battute licenziose, espresse in versi semplici e spesso improvvisati. Questi canti venivano eseguiti dai contadini durante cerimonie legate al raccolto o durante le feste dei _Liberalia_, in onore del dio della fecondità. Si ritiene che il termine fescennino derivi dal nome della cittadina falisca di Fescennium, situata nell'Etruria meridionale.

Questo tipo di canto rappresenta una forma embrionale di rappresentazione teatrale: non solo per il suo carattere dialogico, ma anche perché chi lo intonava usava indossare maschere grottesche fatte con cortecce d'albero, dette personae. Successivamente, i fescennini si diffusero anche nelle città e venivano eseguiti in occasione delle feste nuziali. Tuttavia, a causa dei loro contenuti diffamatori e spesso offensivi, furono regolamentati dalle XII Tavole.

=== La satura

Gli attori, chiamati _histriones_, arrivarono dall'Etruria e, secondo Tito Livio, furono loro a inaugurare i primi _ludi scaenici_ nel 364 a.C. Durante cerimonie organizzate per placare la collera degli dèi e porre fine a una grave epidemia, venne messo in scena uno spettacolo in cui gli artisti eseguivano danze al ritmo del flauto. I Romani, in seguito, arricchirono queste esibizioni introducendo il canto e la recitazione con versi di tipo fescennino. Da questa evoluzione nacque la satura, una rappresentazione drammatica più articolata della quale, però, non è rimasta nessuna testimonianza concreta.

Il termine satura deriva da _satur lanx_, ovvero un piatto colmo di diverse pietanze, un'immagine che ben rappresenta i vari elementi che costituivano questa forma di spettacolo. Solitamente la satura si concludeva con un _exodium_, un momento finale in cui un attore, chiamato _exodiarius_, eseguiva un canto comico accompagnandolo con espressioni mimiche allo scopo di intrattenere il pubblico.

=== L'atellana

Di ben maggiore rilevanza nella storia del teatro romano fu la comparsa, verso la fine del IV secolo a.C., dell'atellana (_fabula atellana_), una farsa di origine osca il cui nome deriva da Atella, una piccola città della Campania. In queste rappresentazioni gli attori indossavano maschere che li trasformavano in caratteri facilmente riconoscibili dal pubblico, grazie al loro modo di pensare, agire e parlare, così come al loro abbigliamento. La recitazione era basata sull'improvvisazione attorno a un canovaccio rudimentale e trattava temi di natura burlesca e spesso grossolana, utilizzando un linguaggio semplice, popolare e talvolta osceno.

I personaggi principali dell'atellana erano quattro ruoli fissi: _Pappus_, l'anziano rimbambito, avaro e lussurioso, invariabilmente ingannato dall'amante e dal figlio; _Maccus_, il credulone con orecchie d'asino, spesso vittima delle astuzie altrui; _Bucco_, servo spaccone, logorroico e goloso; e _Dossennus_, il vecchio astuto e gobbo, sagace ma anche cinico, parassita amante dei banchetti.

Si ritiene che il metro utilizzato fosse il _versus quadratus_, formato da due unità metriche ciascuna di due piedi. L'atellana godette di grande popolarità e continuò a essere rappresentata come forma di _exodium_ persino quando Livio Andronico introdusse a Roma il teatro modellato su esempi greci. Nel I secolo a.C., questa forma teatrale acquisì un impianto letterario grazie a Pomponio e Novio, che abbandonarono l'improvvisazione in favore di testi completamente scritti.

#pagebreak()
#set page(fill: main_letteratura.lighten(90%))
== In sintesi <senza_numero>

/ Primi secoli (VIII-VII sec. a.C.): Nei primi secoli della sua storia, Roma non possiede ancora una produzione letteraria definita. La cultura è trasmessa oralmente e le opere sono anonime, senza testimonianze specifiche di carattere letterario.

/ Iscrizioni: I primi documenti in lingua latina giunti fino a noi sono epigrafi di difficile interpretazione, come il Lapis Niger (VII-VI sec. a.C.), il Vaso di Dueno (VII-VI sec. a.C.), la Cista Ficoroni e le iscrizioni sulle tombe della famiglia degli Scipioni (III sec. a.C.). Questi documenti rivestono un interesse particolare in quanto prime testimonianze dirette del verso saturnio.

/ Prosa:Le Leggi delle XII Tavole rappresentano una conquista fondamentale per la plebe, garantendo certezza giuridica. Al contempo, esse assumono un valore preletterario, costituendo uno dei primi esempi di prosa organizzata. \ La pratica di redigere annualmente gli Annales, poi raccolti in 80 libri sotto il titolo di Annales Maximi, offre una cronaca storica completa del popolo romano, tracciandone le vicende attraverso i secoli. \ Tra le attività intellettuali, l'oratoria emerge come la più prestigiosa per un patrizio, essenziale per il successo politico e sociale. Appio Claudio Cieco (IV sec. a.C.) è ricordato come il primo oratore romano di cui si abbia notizia: la sua celebre orazione al Senato contro la pace con Pirro (280 a.C.) fu tramandata e letta ancora ai tempi di Cicerone.

/ Poesia: Il verso più antico della tradizione romana è il saturnio. Il primo genere poetico noto è il _carmen_, che include i più antichi inni religiosi, come il Carmen Saliare e il Carmen Arvale. Il Carmen Saliare era recitato dai sacerdoti Salii in occasione dei riti primaverili e autunnali per segnare l'apertura e la chiusura del periodo bellico; il Carmen Arvale, invece, veniva cantato dai sacerdoti Arvali per invocare la fertilità delle terre. Esistono anche composizioni di carattere profano, come i carmina _convivalia_, i canti trionfali e le _neniae_.

/ Origini del teatro: Le prime forme di poesia teatrale includono i versi fescennini, scambi di battute licenziose tra contadini durante le feste. Inoltre, la satura, di origine etrusca, introduce una rappresentazione più complessa con elementi di canto, recitazione, danza e gestualità mimica. Tuttavia, la tradizione teatrale più significativa è rappresentata dall'atellana, una farsa di origine osca basata su canovacci e interpretata da maschere fisse come _Pappus, Maccus, Bucco e Dossennus_.

