#import "../../../template_normal.typ": *
//#show: frame-style(styles.thmbox)

#evidenzia[Un maggior orientamento verso l'intervento concreto sulla realtà politica e sociale portò gli illuministi lombardi a impegnarsi attivamente nell'amministrazione pubblica. Essi sostennero con convinzione il riformismo illuminato promosso dagli Asburgo, che però rallentò il proprio slancio a partire dagli anni Settanta. In questo stesso periodo si affermarono i modelli neoclassici, con Giuseppe Parini come massimo interprete. Parini incarnò l'equilibrio tra ragione e grazia, bellezza e dignità morale.]

== I fratelli Verri
#note(bottom)[== *🧩* Casanova, l'ultimo libertino <senza_numero> 

Durante il Seicento, il libertinismo si era affermato come un fenomeno di laicismo estremo e di ribellione alle convenzioni sociali. Tuttavia, con l'Illuminismo, si radicalizza ulteriormente, assumendo tratti di un cinismo spietato e di una celebrazione volontaristica del controllo di sé sugli altri, spesso mascherata da un'esteriorità erotica. In questa prospettiva, l'opera del marchese Donatien-Alphonse-François de Sade (1740-1814) rappresenta un esempio paradigmatico. \ In Italia, il libertinismo appare meno originale: trae ispirazione dal modello cinquecentesco di Pietro Aretino e si manifesta principalmente attraverso figure di avventurieri. Tra questi emerge Giacomo Casanova (1725-1798) che, con la stesura dell'Histoire de ma vie (Storia della mia vita, 1790-98), offre l'esempio più rappresentativo del libertinismo italiano. Non si tratta di un'opera di ribellione ideologica, ma piuttosto di una sintesi tra una narrazione vivace e al tempo stesso glaciale, alimentata da curiosità, scherzi e racconti erotici ripetuti in modo ossessivo, quasi privi ormai di autentico desiderio, all'interno di una cornice morale fortemente influenzata da un nichilismo disincantato.]
Il milanese Pietro Verri (1728-1797), insieme al fratello Alessandro, fu il fondatore dell'Accademia dei Pugni (1761), polo centrale dell'illuminismo lombardo. Da questa esperienza nacque nel 1764 la rivista _Il Caffè_, che rappresentò un punto nevralgico per le migliori riflessioni del riformismo illuminista italiano. Dopo la chiusura della rivista nel 1766, Verri intraprese un percorso nell'amministrazione pubblica austriaca, da cui venne però estromesso nel 1786 a causa di un irrimediabile conflitto con Giuseppe II.

L'ampia produzione di Verri si ispira ai principi illuministi, secondo i quali la cultura e il sapere devono mirare all'"utile" combattendo i "pregiudizi". Scienza e intellettualità trovano senso nella misura in cui favoriscono un rinnovamento morale, civile ed economico della società. Il motto "Cose e non parole" espresso da _Il Caffè_ riflette appieno questo orientamento: l'illuminismo lombardo si affranca decisamente dai retaggi classicistici per promuovere una cultura impegnata nelle battaglie civili.

Tra le opere di Pietro Verri spiccano i saggi economici: _Elementi del commercio_ (1760) e il _Dialogo sul disordine delle monete nello stato di Milano_ (1804, pubblicato postumo). La sua opera più importante è il trattato _Meditazioni sull'economia politica_ (1771). Degna di nota è anche la sua attenzione ai temi sociali, evidente nel riesame del processo degli untori durante la peste del 1630 a Milano, da cui nacque il celebre scritto _Le osservazioni sulla tortura_ (1777, pubblicato postumo nel 1804). Nel 1777 iniziò la stesura della _Storia di Milano_ (1783-98), un esempio insigne di storiografia illuminista. Tra le opere filosofiche figurano le _Meditazioni sulla felicità_ (1763) e il _Discorso sull'indole del piacere e del dolore_ (1773). 

Di particolare interesse è l'opera scritta in occasione della nascita della figlia Teresa, _Ricordi a mia figlia_ (1777), una delle prime opere letterarie destinate a una bambina, in cui Verri propone un modello educativo basato sull'affetto e la cura piuttosto che sulla severità.

Alessandro Verri (1741-1816) fu anch'egli protagonista dell'Accademia dei Pugni e de _Il Caffè_ insieme al fratello Pietro. Il documento _Rinunzia avanti notaio degli autori del presente foglio periodico al vocabolario della Crusca_ (1764-65) rappresenta una decisa opposizione al classicismo e al purismo linguistico, ottenendo ampia risonanza. 

Tra il 1761 e il 1766 lavorò al _Saggio sulla storia d'Italia_, rimasto però inedito. Successivamente si recò con l'amico Beccaria a Parigi e Londra; il carteggio intrattenuto con il fratello Pietro durante quel periodo costituisce una preziosa testimonianza della vita culturale italiana del tardo Settecento. Tornato in Italia, si stabilì definitivamente a Roma, dove abbracciò il neoclassicismo e sviluppò un cambiamento ideologico-politico avvicinandosi a posizioni papaline di stampo reazionario.

Tra le sue traduzioni si segnalano l'_Amleto_ (1768) e l'_Otello_ (1777) di Shakespeare; inoltre, compose due tragedie, _Pantea_ e _La congiura di Milano_, pubblicate nel volume _Tentativi drammatici_ (1779). Tuttavia, sono i suoi romanzi a riscuotere maggiore rilievo: _Le avventure di Saffo_ (1782), le _Notti romane_ (1792) e la _Vita di Erostrato_ (1815). Questi ultimi riflettono un neoclassicismo intrecciato ad atmosfere pre-romantiche.

Cesare Beccaria (1738-1794), anch'egli di origine milanese, è ampiamente riconosciuto come uno dei principali protagonisti dell'Illuminismo italiano. Intimo amico di Giuseppe Parini e dei fratelli Pietro e Alessandro Verri, con i quali partecipò attivamente alle iniziative culturali dell'Accademia dei Pugni e del periodico _Il Caffè_, Beccaria si distinse per il suo entusiasmo verso le opere dei grandi pensatori francesi del tempo, tra cui Montesquieu, d'Alembert, Diderot e, in particolare, Rousseau.

Il celebre trattato Dei delitti e delle pene (1764) rappresenta il contributo più innovativo ed emblematico dell'Illuminismo italiano. In questa opera, Beccaria sviluppa una critica incisiva nei confronti di un sistema giudiziario caratterizzato da irrazionalità; condanna fermamente la pena di morte e la tortura, considerate pratiche proprie di uno Stato arretrato e barbarico, e propone l'adozione di pene più umane. Il trattato si focalizza soprattutto sulla costruzione di uno Stato razionale e laico, nel quale la dignità umana sia garantita e preservata. Egli afferma che non vi può essere libertà laddove le leggi consentano che un individuo perda la sua condizione di persona per essere ridotto a mero oggetto.

Oltre al trattato più conosciuto, Beccaria ci ha lasciato altre opere significative: Ricerche intorno alla natura dello stile (1770) ed Elementi di economia pubblica, pubblicati postumi. Questi testi rappresentano il frutto della sua attività accademica presso le Scuole Palatine di Milano, dove insegnò con grande impegno.

== Giuseppe Parini

Giuseppe Parini (1729-1799), nato a Bosisio (oggi denominato Bosisio Parini) vicino a Lecco, è considerato il modello esemplare di poeta classicista, capace di armonizzare ragione e grazia, bellezza e dignità morale. Entrato al servizio come precettore presso la famiglia dei duchi Serbelloni, poté dedicarsi alla poesia e agli studi letterari, sostenuto dall'Accademia dei Trasformati, un'istituzione illuministica a cui fu ammesso nel 1753. Durante questo periodo lesse diverse opere satiriche, tra cui Dialogo sopra la nobiltà (1757), Dialogo sopra le caricature (1759), Lettere del conte N. N. a una falsa divota (1761), oltre all'importante Discorso sopra la poesia (1761), dove combinava i principi dell'estetica sensistica con un raffinato gusto classicista.

Con lo stesso spirito innovativo, Parini pubblicò le prime Odi a tema civile, tra cui La vita rustica (1757), La salubrità dell'aria (1759) e La impostura (1761). Tuttavia, nel 1762 fu licenziato dai Serbelloni per essersi schierato in difesa di una cameriera maltrattata. Successivamente fu accolto nella casa del conte Giuseppe Maria Imbonati, aristocratico illuminista, presso il quale scrisse L'educazione (1764) come guida didattica per il figlio Carlo.

Durante questo periodo emerse il capolavoro letterario di Parini: Il giorno, un poema satirico composto da due parti principali, Il Mattino (1763) e Il Mezzogiorno (1765). L'opera riscosse un successo tale da attirare l'attenzione dei riformatori vicini al governo di Maria Teresa d'Asburgo. Tra questi, il conte Firmian gli affidò la direzione della _Gazzetta di Milano_ nel 1769 e in seguito lo nominò professore di lettere presso il Regio Ginnasio di Brera nel 1773.

Parini compose un'opera teatrale di modesta qualità, _Ascanio in Alba_ (1771), musicata da Mozart. Si dedicò inoltre alla stesura di testi didattici, come _Sui principi generali delle belle lettere applicati alle belle arti_ (1773-75), nonché a scritti sulla riforma scolastica, come _Sul decadimento delle belle lettere e delle belle arti_ (1773). Tuttavia, fu soprattutto la produzione poetica ad assorbire maggiormente le sue energie, con un vasto corpus di opere spesso legate a circostanze specifiche. Di particolare valore è una serie di nuove _Odi_ (1791), caratterizzate da un contenuto sociale e morale, tra cui spiccano: _L'innesto del vaiolo_ (1765), _Il bisogno_ (1766), _Le nozze_ (1777), _La laurea_ (1777), _La caduta_ (1785), _La recita dei versi_ (1786), _Il pericolo_ (1787), _La magistratura_ (1788), _Il dono_ (1790) e _La gratitudine_ (1791).

Nel frattempo, seppur con lentezza, proseguì la scrittura delle parti mancanti de _Il giorno_, ovvero _Il vespro_ e _La notte_. Questi componimenti, però, rimasero largamente incompiuti. È probabile che la poesia satirica fosse ormai distante sia dal gusto del poeta, attratto dal neoclassicismo, come testimoniano composizioni quali _A Nice_ (1793) e _Alla Musa_ (1795), sia dalla sensibilità dell'epoca, fortemente influenzata dagli eventi della rivoluzione francese. Parini espresse un giudizio severo su questi eventi, come evidenziato in componimenti come _A Silvia. Sul vestire alla ghigliottina_ (1795). Morì nel 1799.

=== _Il giorno_

L'intero poemetto fu pubblicato solo nel 1801, grazie a Francesco Reina. La struttura dell'opera ruota attorno alla descrizione dettagliata della giornata di un "giovin signore", accompagnata dai consigli dell'autore, che si presenta come "precettor d'amabil rito". Lo scopo è quello di istruire il giovane affinché possa sempre distinguersi e onorare il proprio rango. La narrazione inizia con il risveglio del protagonista, nel tardo mattino, seguito dalle rituali operazioni necessarie a prepararsi per la giornata: la colazione, la vestizione e l'incipriatura.

Segue il _Mezzogiorno_, momento in cui il "giovin signore" prende parte a un sontuoso banchetto, durante il quale incontra la dama di cui è cicisbeo. Durante il pranzo, chiamato "i desinari illustri", Parini coglie l'occasione per descrivere alcune figure particolari, come il mangione e il vegetariano. Da qui nasce l'episodio della "vergine cuccia", uno dei passaggi più celebri dell'opera.

Nel _Vespro_, l'autore riflette sui rapporti di falsa amicizia basati esclusivamente su convenzioni sociali. Nella Notte, invece, il contrasto tra le tenebre degli spazi esterni e lo sfavillio dei saloni nobiliari serve a sottolineare l'inesorabile disfacimento della nobiltà. L'eleganza rococò appare ormai sradicata: la morte e un senso di terrore spettrale offuscano l'esistenza vuota dell'aristocrazia.

L'ironia costante impiegata da Parini vivifica questa materia e crea un poema didascalico dai contenuti paradossali. Il precettore, fingendo di impartire insegnamenti utili al suo discepolo per perpetuare la propria vita frivola, demolisce spietatamente l'immagine che la classe nobiliare ha di sé stessa, mettendone in luce tutta la vanagloria e l'assurdità. La dilatazione dei tempi e dei gesti descritti contribuisce a evidenziare l'inconsistenza dei rituali e delle parole della nobiltà, provocando una potente reazione morale nel lettore.

#pagebreak()
#set page(fill: main_letteratura.lighten(90%))
== In sintesi <senza_numero>

/ _Il Caffè_ e gli illuministi lombardi: Il motto "Cose e non parole" riflette l'approccio pratico e concreto del _Caffè_, simbolo degli illuministi lombardi che abbandonarono ogni residuo arcadico per promuovere una cultura impegnata nelle battaglie civili. Tra i principali protagonisti: Alessandro e Pietro Verri, autori delle _Osservazioni sulla tortura_ (1777), e Cesare Beccaria, noto per il trattato _Dei delitti e delle pene_ (1764).

/ Giuseppe Parini: Parini incarna il modello del poeta classicista, capace di armonizzare ragione e grazia, bellezza e dignità morale. La sua poetica si basa sull'equilibrio tra la compostezza classica e un profondo senso di responsabilità civile. Tra le opere principali figurano le _Odi_, raccolte in volume nel 1791, e alcune composizioni vicine al gusto neoclassico (_Il messaggio_, 1793; _A Nice_, 1793; _Alla Musa_, 1795). Il suo capolavoro è il poemetto storico _Il giorno_, composto da _Mattino_ (1763) e _Mezzogiorno_ (1765), mentre le ulteriori due sezioni, _Vespro_ e _Notte_, rimasero incompiute.