#import "../../../template_normal.typ": *
//#show: frame-style(styles.thmbox)

#evidenzia[Il romanticismo si affermò lungo tutto il XIX secolo, caratterizzandosi come una delle manifestazioni culturali più rappresentative dell'epoca. Benché spesso venga interpretato come una reazione radicale alla razionalità illuminista, esso non si limita a una mera opposizione. Il romanticismo si distingue infatti per la valorizzazione della passione, dell'irrazionalità e dell'indicibile, senza tuttavia perdere la continuità con l'indagine illuminista sul "moderno". Tale sviluppo sembra incarnare una maturazione culturale che si manifesta attraverso un'antinomia: da un lato, trasgressione e novità radicali; dall'altro, persistenza di alcuni elementi del passato. 

La varietà di orientamenti che il romanticismo raccoglie e integra lungo il XIX secolo riflette questa complessità. Si va dall'esaltazione di un individualismo libertario alla proposizione di uno spirito di conservazione più introverso, spesso incline a posizioni reazionarie. In Italia, la dialettica romantica trovò ampio spazio nelle riviste _Il Conciliatore_ e _L'Antologia_, con figure di spicco quali Giovanni Berchet e Silvio Pellico. Da questo movimento trassero linfa anche le eccellenti opere poetiche dialettali di autori come Carlo Porta, in ambito milanese, e Gioacchino Belli, rappresentante della tradizione romana.]

== L'idea romantica

L'essenza del romanticismo trae origine dal termine inglese _romantic_, inizialmente associato al significato negativo di "romanzesco", "fantasioso" o "irreale", derivato a sua volta da "romance", termine che designava i romanzi medievali e i poemi cavallereschi italiani. La parola acquisì un nuovo significato alla fine del XVIII secolo sul continente europeo, diventando sinonimo di "pittoresco". Fu però lo scrittore tedesco Johann Gottfried Herder a utilizzare per primo il termine per identificare la poesia "moderna", caratterizzata da tratti popolari e sentimentali, in contrasto con la poesia "antica", ovvero quella classica.

I principi fondamentali che formano l'ossatura del romanticismo comprendono l'individualismo, il legame con il popolo, l'armonia con la natura, il profondo interesse per la storia, l'amore assoluto e il senso di squilibrio dell'io tra dimensione fiabesca e realtà quotidiana. L'espressione dell'io diviene centrale: l'arte e il linguaggio non sono concepiti come meri strumenti di conoscenza razionale, ma come manifestazioni istintive della libertà individuale, strettamente intrecciate allo spirito collettivo e all'identità profonda del popolo. Il rifiuto del meccanicismo illuminista trova giustificazione nel fatto che la natura, per i romantici, incarna il segreto stesso dell'energia vitale, una forza spirituale che si manifesta attraverso simbolismi e analogie.

Anche la concezione romantica della storia si discosta dalle interpretazioni lineari: essa è percepita come un processo dinamico e rivoluzionario, caratterizzato da fratture, superamenti, sintesi e crisi. Sul piano emotivo, il romanticismo conferisce al sentimento una dimensione drammatica perpetua; l'amore diventa un'esperienza estrema che si connota ironicamente attraverso il frammento e l'incompiutezza. Il senso di squilibrio dell'io rispetto ai limiti imposti dal tempo e dalla realtà pone il soggetto in una condizione intrinsecamente drammatica: tale condizione può sublimarsi in due direzioni opposte. Da un lato si orienta verso l'immaginario fiabesco, tramite l'esplorazione delle tradizioni popolari, degli stati onirici e del culto del Medioevo o dell'esotico; dall'altro lato può invece cristallizzarsi nella quotidianità, in una prospettiva realistica esasperata e assoluta.

#note(bottom)[== *🧩* Il romanticismo europeo <senza_numero>

In Germania, il romanticismo trova le sue radici nel rapporto drammatico con l'eredità del mondo antico. Il preromanticismo tedesco rappresenta già una forma di ribellione artistica, basata sulla libertà espressiva del genio creativo e sul suo tragico senso di impotenza nell'arte. Il capolavoro _I dolori del giovane Werther_ (1774) di Johann Wolfgang Goethe è uno degli esempi più emblematici di questa tragicità, incarnando il destino tormentato del nuovo eroe moderno. Tuttavia, tali istanze artistiche si consolidarono pienamente nel romanticismo solo quando l'impeto ribelle si trasformò in un impegno costruttivo e originale. L'opera di Goethe trovò un complemento nella produzione teatrale di Friedrich Schiller, il quale, con il saggio _Sulla poesia ingenua e sentimentale_ (1795), distinse tra la poesia "ingenua" degli antichi e quella "sentimentale" dei moderni, più riflessiva, critica e indefinita. Questa distinzione costituì uno dei fondamenti del romanticismo europeo, sviluppatosi grazie al contributo del cosiddetto gruppo di Jena e della rivista _Athenäum_ (1798-1800), cui collaborarono figure come Friedrich e August Wilhelm Schlegel, Ludwig Tieck e Novalis.

In Inghilterra, il romanticismo si consolidò con le opere straordinarie di William Wordsworth e Samuel Taylor Coleridge, coautori delle _Ballate liriche_ (1798). A loro si aggiunsero le raccolte poetiche di John Keats e Percy Bysshe Shelley, insieme all'influenza carismatica di George Gordon Byron, considerato un vero e proprio mito vivente. Questo movimento romantico britannico non fu solo un'espressione di ribellione e di riflessione sul dramma individuale, ma anche un'esplorazione poetica della natura in chiave sentimentale, un tratto evidente nei romanzi storici di Walter Scott.

In Francia, un atteggiamento antilluministico era già emerso negli scritti di François-René de Chateaubriand durante il periodo della Rivoluzione e dell'età napoleonica. Tuttavia, il romanticismo si strutturò come movimento organico grazie al trattato _Sulla Germania_ (1813), scritto da Madame de Staël tre anni prima della sua pubblicazione. Con la Restaurazione si affermò lo stile lussuoso della prosa di Chateaubriand, ma fu con la rivoluzione di luglio che il romanticismo francese assunse connotazioni più liberali e democratiche. Autori come Alfred de Vigny, Victor Hugo, Alfred de Musset e Gérard de Nerval diedero vita a una nuova declinazione del romanticismo. Questo movimento cercava codici espressivi innovativi, esplorando temi come il notturno, la malattia, il realismo e visioni esotiche e profondamente sentimentali.]

== Il romanticismo italiano

Il romanticismo italiano si distingue per un approccio più cauto e misurato rispetto ai corrispettivi movimenti in Germania e Inghilterra. Non rappresentò mai una vera rottura con la tradizione; al contrario, in alcuni casi fu una preziosa opportunità per sperimentare formule nuove, che fossero comunque rispettose della tradizione letteraria umanistica. La negazione di ogni forma di estremismo rese il dibattito meno vivace rispetto ad altri Paesi, ma non meno rilevante, specialmente riguardo argomenti cruciali come la ricerca di un linguaggio "popolare", lontano dalle astrattezze accademiche, o la necessità di una letteratura nazionale che contribuisse in modo concreto al progresso collettivo.

=== Origini e prima generazione romantica

Il romanticismo italiano prese forma nei dibattiti pubblici animati dalle riviste letterarie. Quando la _Biblioteca italiana_, diretta da Giuseppe Acerbi, inaugurò il suo primo numero con l'articolo di Madame de Staël _Sulla maniera e l'utilità delle traduzioni_, si aprì immediatamente una vivace polemica tra classicisti e romantici. Pur adottando un'impostazione classicista, la rivista non fu mai rigidamente dogmatica.

La polemica, tuttavia, si concentrò su questioni relativamente marginali, come l'uso della mitologia classica, i rapporti con le letterature straniere e il rispetto delle unità drammatiche basate sul modello aristotelico. Alcuni esponenti del classicismo, tra cui Pietro Giordani, mantennero una certa apertura verso le idee romantiche, condividendo il desiderio di una letteratura italiana con un carattere "universale".

I romantici italiani si aggregarono attorno alla rivista milanese _Il Conciliatore_, che purtroppo ebbe vita breve (1818-1819), soppressa dalle autorità austriache. Tra i principali esponenti del gruppo vi furono Pietro Borsieri, autore dell'ironico _Avventure letterarie di un giorno_ e il redattore del _Programma del "Conciliatore"_, e Ludovico di Breme, intellettuale di respiro europeo e forse l'unico italiano pienamente in grado di confrontarsi con le idee degli idéologues. Il gruppo tentò di perpetuare lo spirito del miglior illuminismo italiano, affiancando alla novità romantica una visione storica della cultura e promuovendo il senso civile e una coscienza nazionale condivisa.

=== Giovanni Berchet

Giovanni Berchet, milanese di nascita, è noto principalmente per la _Lettera semiseria di Giovanni Grisostomo al suo figliuolo_, pubblicata nel 1816 nella _Biblioteca italiana_. Quest'opera è considerata il manifesto del romanticismo italiano. Attraverso la finzione narrativa di un padre che spiega al figlio collegiale il significato della poesia romantica, Berchet presenta alcune traduzioni da lui realizzate di ballate del poeta tedesco Gottfried August Bürger per illustrare il carattere essenzialmente "popolare" della poesia romantica e il suo legame storico con il popolo.

In questo rapporto tra scrittore e pubblico, il "popolo" è concepito come espressione del gusto medio borghese, contrapposto tanto agli intellettuali di élite, definiti "parigini", quanto alle classi più ignoranti, gli "ottentotti". Berchet, esule politico per la sua attività carbonara, visse in Francia, Inghilterra e Belgio, dedicandosi alla traduzione di opere significative come _Il Bardo_ di Thomas Gray e il romanzo _Il curato di Wakefield_ di Oliver Goldsmith. Inoltre, con opere quali _I profughi di Parga_ (1819-1820) e le _Romanze_ (1824), cercò di incarnare quel gusto "popolare" che aveva teorizzato nei suoi scritti.

=== Silvio Pellico

Silvio Pellico (1789-1854), originario di Saluzzo in Piemonte, rappresenta una figura centrale del romanticismo risorgimentale italiano. Intellettuale di notevole erudizione e membro attivo di una vivace rete di letterati italiani e stranieri, si distingueva principalmente per la sua produzione di tragedie. La sua opera più celebre, _Francesca da Rimini_, fu accolta con un significativo successo nel 1815. Pellico partecipò inoltre all'iniziativa letteraria del _Conciliatore_, pubblicandovi la prima parte di un romanzo intitolato _Breve soggiorno in Milano di Battistino Barometro_, che rimase incompiuto.

Nel 1820 fu arrestato con l'accusa di affiliazione alla carboneria e incarcerato ai Piombi di Venezia. La sua condanna a morte venne successivamente commutata alla detenzione presso la fortezza dello Spielberg, situata in Moravia, dove trascorse dieci anni di prigionia fino al 1830. Liberato grazie ad un atto di grazia, Pellico scrisse l'opera autobiografica per cui è maggiormente ricordato, _Le mie prigioni_ (1832). Quest'opera riscosse un immenso successo sia in Italia sia all'estero e fu tradotta in diverse lingue, a partire dal francese nel 1833.

Il testo, letto spesso in chiave politica, più che come un documento meramente personale, rappresenta una denuncia indiretta del regime austriaco. In esso l'autore descrive il carcere come una realtà dominata dall'ingiustizia e dalla violenza, un luogo popolato da emarginati e vittime, ma illuminato anche da gesti occasionali di umana pietà. 

Dopo la liberazione, Pellico tornò a dedicarsi al teatro tragico con opere come _Leoniero da Dertona_ e _Gismonda da Mandrisio_ (1832), _Corradino_ (rappresentata nel 1834 e pubblicata postuma) e _Eugilde della Roccia_ (1832). Tuttavia, nessuna di queste opere raggiunse il successo della celebre _Francesca da Rimini_. Di minore rilevanza è da segnalare il suo trattato morale _Dei doveri dell'uomo_, pubblicato nel 1834.

== Carlo Porta

Carlo Porta (1775-1821), poeta dialettale milanese, occupa un ruolo peculiare nel panorama del romanticismo italiano, rappresentando una corrente che potrebbe essere definita realismo romantico. Funzionario statale di professione, debutta nel mondo letterario con la pubblicazione del poemetto _El lavapiatt del Meneghin ch'è mort_ (1792), seguito da una vivace e popolare rivisitazione in dialetto milanese dell'_Inferno_ di Dante, realizzata intorno al 1804. Nel contesto delle polemiche letterarie del tempo, Porta si oppose energicamente alle critiche rivolte alla poesia dialettale da Giordani sulla rivista _Biblioteca italiana_, il quale l'acusava di favorire un dannoso particolarismo da superare a vantaggio della lingua nazionale. Porta replicò con sonetti dai toni aspri e si avvicinò, seppur con riserve, alle istanze romantiche. La sua adesione sembra piuttosto una forma di simpatia verso una modernità più spontanea e comunicativa, essenziale non solo al romanticismo ma alla poesia in sé.

Nella Milano culturale dell'epoca, Porta ricoprì un ruolo significativo facendo parte di un circolo intellettuale composto da giovani letterati lombardi come G. Berchet, T. Grossi ed E. Visconti; vi partecipò anche lo scrittore francese Stendhal, che nutriva grande ammirazione per la sua poesia. Tra il 1814 e il 1816 Porta iniziò a raccogliere le sue opere in quaderni autografi. Dopo la sua morte, gli scritti subirono censure morali da parte di Luigi Tosi. Una selezione delle sue poesie fu pubblicata nel 1817, e una raccolta più ampia vide la luce nel 1826 grazie all'amico Tommaso Grossi.

Il mondo di Porta rappresenta una straordinaria descrizione linguistica del popolo e della borghesia che animano le piazze e i mercati della Milano dell'epoca. La sua opera raggiunge un livello altissimo di comicità rapida e vivace, accanto a una satira sociale pungente e malinconica, difficilmente eguagliabile nel resto del nostro Ottocento, salvo forse nel caso del poeta romano Giuseppe Gioachino Belli.

Fondamentale nell'opera di Porta è la sua profonda, ma mai banale, empatia per le vite dei perdenti e degli oppressi, così come l'infinita varietà espressiva dei registri dialettali. Tra i suoi lavori più significativi, veri pilastri della nostra letteratura, si annoverano i componimenti poetici _On miracol_ (1813-14), _La nomina del cappellan_ (1819-20), _I desgrazi de Giovannin Bongee_ (1812-13), _La Ninetta del Verzee_ (1814), _El lament del Marchionn di gamb avert_ (1816) e _On funeral_ (1816).

== Giuseppe Gioachino Belli

Giuseppe Gioachino Belli è una figura complessa, a lungo sottovalutata nel panorama della letteratura italiana, e rappresenta, insieme a Porta, una voce cruciale del romanticismo realistico. Nato nel 1791 da una famiglia impiegatizia fedele al regime pontificio, lavorò per molti anni come funzionario dell'amministrazione papale. La sua formazione, prevalentemente autodidatta, fu ampia ma disordinata, caratterizzata sin dall'inizio da una forte passione per la letteratura. Belli ebbe modo di conoscere e apprezzare profondamente la poesia dialettale di Porta. Tra il 1830 e il 1837 e poi dal 1842 al 1849, scrisse i suoi celebri _Sonetti_ in romanesco, pur arrivando a rinnegare in seguito la propria produzione dialettale, coerentemente con il suo crescente conservatorismo.

I 2279 sonetti di Belli furono pubblicati integralmente solo nel 1952. Nella sua Introduzione, scritta nel 1831, il poeta spiegò chiaramente l'obiettivo del proprio lavoro: "Ho deciso di lasciare un monumento di ciò che è oggi la plebe di Roma". Belli si avvicinava a questa realtà senza illusioni pedagogiche o ideali romantici; non cercava mitiche purezze da esaltare nel popolo, bensì osservava una plebe romana corrosa dalle stratificazioni millenarie delle civiltà che si erano succedute.

Questa osservazione, tuttavia, è distaccata: Belli non appartiene a quel mondo ma lo descrive attraverso uno strumento narrativo efficace. Una voce narrante si interpone tra il poeta e i temi dell'opera, utilizzando un dialetto privo di variazioni stilistiche o di registro. In questo modo, sonetto dopo sonetto, viene delineato un universo immobile e ripetitivo: l'inferno romano dove non c'è possibilità di trasformazione. La chiusa finale di ciascun sonetto spesso riduce a nulla ciò che inizialmente era stato suggerito.

Da questo senso di impotenza sistematica nasce la comicità amara del poeta: uno sberleffo che talvolta si erge contro i potenti. Il mondo dei _Sonetti_ è intrinsecamente ingiusto; nemmeno nella morte è possibile trovare redenzione. Eppure, qua e là emergono scorci di profonda delicatezza e frammenti di umanità ferita, che il poeta sembra quasi nascondere per pudore.

#pagebreak()
#set page(fill: black.lighten(90%))
== *🧩* La seconda generazione romantica <senza_numero>

La seconda generazione romantica si sviluppa in un momento di crisi per il movimento romantico, segnato dalla chiusura del _Conciliatore_ e dalla scomparsa di figure come Porta e Ludovico di Breme. A Milano, Alessandro Manzoni rimane un riferimento isolato, nonostante la sua posizione appartata e il disinteresse per le polemiche culturali. Tra gli autori di rilievo vi è Tommaso Grossi, che oltre a produrre opere interessanti in dialetto come _Prineide_ (1817) e _La fuggitiva_ (1816), si distingue per lavori in lingua italiana, tra cui _Ildegonda_ (1820), una novella romantica in versi, e il romanzo storico _Marco Visconti_ (1834), ispirato dal modello manzoniano.

Un'altra figura rilevante è Cesare Cantù, noto soprattutto per la sua monumentale _Storia universale_ (1838-1846), sebbene non raggiunga la profondità dei primi romantici. Più vicino a questi ultimi appare Giovita Scalvini, che si segnala per la sua produzione originale e per un’acuta capacità critica. Tra i suoi contributi più significativi si trovano il poemetto _Il fuoriuscito_, iniziato nel 1822, e il _Saggio sui Promessi Sposi di Manzoni_ (1829), apprezzato per la sua lungimiranza.

A Firenze, nel 1821, l'"Antologia" nasce grazie all'iniziativa del ginevrino Giampietro Vieusseux, con la collaborazione di personalità come Gino Capponi, Cosimo Ridolfi e Giuseppe Montani. La rivista eredita in parte lo spirito innovativo del _Conciliatore_, prendendo però le distanze dai dibattiti ormai esauriti tra classicisti e romantici per proporre una visione letteraria moderna e aperta alla dimensione europea.

#pagebreak()
#set page(fill: main_letteratura.lighten(90%))
== In sintesi <senza_numero>

/ Romanticismo: I temi centrali della cultura romantica comprendono l'esaltazione dell'individualismo e del genio, l'affermazione del continuo evolversi della storia, e la supremazia della passione, del sogno e del dramma personale. Anche la fiaba rappresenta un mezzo per esplorare le passioni autentiche e spontanee del popolo.

/ Romanticismo italiano: Giovanni Berchet, con la _Lettera semiseria di Giovanni Grisostomo al suo figliuolo_ (1816), esprime il carattere "popolare" della poesia romantica, intesa nel senso di borghese. Silvio Pellico, grazie a _Le mie prigioni_ (1832), raggiunge un ampio successo narrando le sue sofferenze come patriota incarcerato dagli austriaci.

/ Porta: Partigiano del movimento romantico, Carlo Porta scrive in un versatile dialetto milanese. Le sue _Poesie_ (1826) sono una pietra miliare della satira sociale, caratterizzate da graffiante comicità e dall'infinita capacità espressiva del dialetto.

/ Belli: Nei suoi 2279 sonetti mira a creare un "monumento" dedicato alla plebe romana, ritratta con uno sguardo distaccato in un contesto che appare quasi infernale, segnato da una ripetitività statica. Da questo senso di impotenza nasce la sua ironia amara, cifra distintiva del suo stile.