#import "../../../template_tufte.typ": *
#show: frame-style(styles.thmbox)

#evidenzia[Al di fuori della corte medicea, l'Umanesimo italiano conobbe una significativa diffusione, trovando espressione principale a Venezia, Ferrara e Napoli. Nella tradizione culturale italiana si collocano due esempi di altissimo valore: il poema cavalleresco di Matteo Maria Boiardo, il quale operò presso la corte estense di Ferrara, e la letteratura pastorale di Jacopo Sannazaro, riconosciuto come il principale esponente della corte aragonese a Napoli.]

== La diffusione dell'umanesimo in Italia

Nell'Italia settentrionale, la corte di Milano acquisì rilevanza grazie alla presenza di celebri artisti fiorentini come Donato Bramante e Leonardo da Vinci, nonché agli scrittori Antonio Loschi (1368-1440) e Francesco Filelfo. Altrettanto importante fu la corte ferrarese degli Estensi, resa celebre dall'opera di poeti quali Tito Vespasiano Strozzi (1424-1505), Pasquale Collenuccio (1447-1492), autore delle raffinate _Rime petrarchesche_, Nicolò da Correggio (1450-1508), noto per il dramma _La Fabula di Cefalo_ (1487) e, soprattutto, da Matteo Maria Boiardo.

Un contributo significativo si registrò anche a Venezia, specialmente nel campo delle arti e della letteratura. Tra gli intellettuali veneziani si distinguono Francesco Barbaro (1390-1454), autore del trattato _De re uxoria_ (1416) sull'educazione familiare e matrimoniale, e Leonardo Giustinian (1388-1446), patrizio di vasta erudizione che scrisse orazioni in latino e componimenti poetici in volgare, tra cui gli _Strambotti_, diffusi a partire dal 1474. Venezia rappresentò inoltre un ponte naturale tra la cultura greca e la civiltà latina, configurandosi come il primo centro editoriale italiano attraverso il rapido sviluppo della stampa. In questa città spicca la figura di Aldo Manuzio (1450-1515), umanista e stampatore di prestigio internazionale.

Nella parte centrale della penisola italiana, la corte di Urbino rivestì un ruolo centrale sotto il governo del duca Federico di Montefeltro. Allo stesso modo Roma giocò un ruolo cruciale, ospitando intellettuali del calibro di Giulio Pomponio Leto (1428-1497), fondatore dell'Accademia Pomponiana, e Bartolomeo Sacchi detto il Platina (1421-1481), primo prefetto della Biblioteca Vaticana.

L'Umanesimo napoletano raggiunse un notevole sviluppo sotto la protezione della dinastia aragonese. Fondamentale fu l'Accademia istituita dal Panormita (Antonio Beccadelli, 1394-1471) e successivamente diretta da Giovanni Pontano (1429-1503). Tuttavia, la figura di maggior rilievo rimane Jacopo Sannazaro. Va inoltre menzionata la produzione novellistica di Masuccio Salernitano.

=== Giovanni Pontano

La produzione letteraria di Giovanni Pontano (1429-1503) abbraccia quasi tutti i generi ed è prevalentemente scritta in lingua latina. Tra le sue opere spicca una serie di Dialoghi, di carattere politico e astrologico, in cui emergono i tratti distintivi del suo umanesimo: una concezione attiva della vita, che Pontano tradusse in una persistente opposizione all'ignoranza, alla superstizione, ai pedanti e ai politici del suo tempo. La poesia fu la sua più grande passione, attraverso la quale seppe esprimere una cultura e una sensibilità di altissimo livello, profondamente radicate nei classici e al contempo aperte alla realtà del suo presente.

Pontano compose egloghe e raccolte poetiche come gli _Amores_ (1455-58), gli _Hendecasyllabi sive Baiae_ (1490-1500), nei quali celebra l'atmosfera festosa delle terme di Baia, gli _Iambici_, dedicati alla morte del figlio Lucio, e i _Tumuli_, contenenti epitaffi per la moglie scomparsa, Adriana, e per il figlio. Tra le opere di carattere astrologico troviamo il poema _Urania_ (1476) e il _Meteororum liber_ (_Libro delle meteore_), mentre nel campo della poesia didascalica si distingue il _De hortis Hesperidum_ (_L'orto delle Esperidi_). Il suo capolavoro è probabilmente il poema _De amore coniugali_, dove celebra le gioie della vita familiare. Notevoli sono anche le dodici _Neniae_, dedicate al figlio Lucio, che lo collocano insieme a Poliziano e al Boiardo del _Canzoniere_ ai vertici della produzione lirica dell'Umanesimo.

=== Il _Novellino_ di Masuccio Salernitano

Masuccio Salernitano, pseudonimo di Tommaso Guardati (circa 1415-1475), originario di Sorrento, fu segretario di Roberto di Sanseverino, principe di Salerno, e frequentò la corte napoletana. Qui ebbe modo di entrare in contatto con il Panormita, Giovanni Pontano e Zaccaria Barbaro. È ricordato principalmente per il _Novellino_ (pubblicato postumo nel 1476), una raccolta di cinquanta novelle suddivise tematicamente in cinque decadi. Le influenze principali sono i trattati degli umanisti, in particolare le opere di Giovanni Pontano, senza dimenticare l'influenza fondamentale di Boccaccio.

Il _Novellino_ si distingue per trame drammatiche dai toni cupi e crudeli, che mettono in luce un gusto per l'eccesso e l'orrido. Lo stile narrativo prevale sulla dimensione edificante, rinunciando alle rigide imitazioni solenni di Boccaccio. Al contrario, esso adotta una costruzione più libera ed espressiva, arricchita dall'uso del dialetto nelle scene fortemente caratterizzate da una comicità popolaresca.

== Boiardo e il poema cavalleresco

Matteo Maria Boiardo (1440 o 1441-1494), originario di Scandiano presso Reggio Emilia, è uno degli autori più noti del genere cavalleresco, grazie al suo grande poema _Orlando innamorato_. La sua formazione umanistica si sviluppò nell'ambiente culturale ferrarese e attraverso la vivace esperienza mondana alla corte estense. Tra il 1463 e il 1464 scrisse i quindici _Carmina de laudibus Estensis_ (_Carmi in lode degli Este_), riprendendo motivi mitologici virgiliani, insieme alle dieci egloghe dei _Pastoralia_.

Nel 1476 Matteo Maria Boiardo diede avvio al suo celebre capolavoro, __l'Orlando innamorato__, e parallelamente compose gli _Epigrammata_ in lingua latina, seguendo il modello di Marziale per celebrare la vittoria di Ercole I d'Este contro il cugino Niccolò d'Este, artefice di una congiura ai danni del duca. Nel 1480 fu nominato governatore di Modena e nel 1487 assunse l'importante incarico di capitano a Reggio Emilia, che mantenne sino alla sua morte. Durante questi anni, Boiardo completò le _Egloghe volgari_ e la commedia in cinque atti _Timone_. Tra le opere in lingua volgare vanno ricordati anche gli _Amorum libri tres_ (noto anche come _Canzoniere_), una raccolta poetica che narra la storia d'amore con Antonia Caprara, composta tra il 1469 e il 1476.

Pur riconoscendo nel Petrarca il principale punto di riferimento letterario di Boiardo, diversi studi hanno evidenziato come l'influenza di modelli molteplici – tra cui Virgilio, Tibullo, Ovidio, Properzio, Lucrezio, Claudiano, Dante e gli stilnovisti – insieme a una nuova sensibilità umanistica contribuiscano a superare l'equilibrio classico del petrarchismo. Tali influenze si manifestano attraverso la contaminazione del testo con elementi poetici eterogenei e profondamente innovativi. In questo contesto, si distinguono la rappresentazione idealizzata della natura, l'uso frequente di diminutivi e personificazioni, oltre alle particolari figurazioni animalesche riconducibili alla tradizione poetica cortese e siciliana. Ad oggi, il _Canzoniere_ di Boiardo è universalmente riconosciuto come una delle opere più raffinate e rappresentative della lirica amorosa quattrocentesca.

=== L'''Orlando innamorato"

L_'Orlando innamorato_ è un poema epico-cavalleresco composto in ottave, che raccoglie i temi dei cicli carolingio e bretone della letteratura francese – rispettivamente dedicati alle imprese di Carlo Magno e dei suoi paladini, e agli amori e avventure della corte di re Artù – amalgamandoli con la tradizione dei cantari popolari italiani. La versione completa dell'opera, purtroppo incompiuta, fu pubblicata nel 1495, un anno dopo la morte dell'autore. 

Redatto in dialetto ferrarese "illustre", arricchito da elementi del toscano letterario e da numerosi latinismi, il poema narra le intricate vicende amorose di Angelica, inseguita e contesa dai paladini cristiani Orlando e Ranaldo, entrambi innamorati di lei. La trama è caratterizzata da un continuo alternarsi di inseguimenti e fughe dettate dai mutamenti dei sentimenti dei protagonisti, influenzati dagli effetti magici delle fonti dell'amore e del disamore. Questi eventi conducono a una sequenza vertiginosa di emozioni contrastanti e incontri drammatici.

Dopo aver ucciso il re tartaro Agricane, Orlando ritrova Ranaldo, ormai libero dalle influenze della fonte incantata. Tra i due esplode un acceso conflitto che li divide profondamente. Tuttavia, l'assedio di Parigi da parte del re saraceno Agramante li costringe a ricongiungersi per difendere la cristianità. Carlo Magno interviene poi decretando che Angelica sarà assegnata al cavaliere che meglio combatterà contro i saraceni. Parallelamente, si intreccia la nascita dell'amore tra Ruggiero, cavaliere moro, e Bradamante, guerriera cristiana. L'opera si interrompe bruscamente alla ventiseiesima stanza del nono canto; sarà Ludovico Ariosto a riprenderne il filo narrativo nel suo _Orlando furioso_.

La novità introdotta da Boiardo risiede nella fusione del ciclo carolingio e di quello bretone in un'unica narrazione, dominata dall'ideale umanistico dell'energia amorosa, capace di nobilitare l'uomo ma anche di incutere timore. Questo si traduce nella creazione di personaggi psicologicamente variegati, sebbene in parte stilizzati. Attraverso la combinazione dell'esperienza epica con quella lirica, Boiardo ha saputo interpretare la necessità di superare l'ideale astratto della letteratura amorosa a favore della polifonia del poema moderno.

A fare da contrappunto dialettico agli aspetti umani del poema intervengono gli elementi magici e "meravigliosi", resi attraverso un linguaggio carico di immagini e aggettivazioni iperboliche. Giardini incantati, fonti miracolose, creature mostruose e apparizioni sono solo alcune delle presenze soprannaturali che arricchiscono il testo.

== Iacopo Sannazaro e la letteratura pastorale

Iacopo Sannazaro (1457-1530) rappresenta la figura più emblematica dell'umanesimo napoletano. Il suo contributo alla letteratura fu significativo sia nel campo delle opere in volgare sia in quello della produzione in latino. Membro dell'Accademia Pontaniana, Sannazaro fu nominato gentiluomo presso la corte aragonese nel 1481. Seguì Federico III d'Aragona nell'esilio francese nel 1501, e dopo la morte del re fece ritorno a Napoli. Prima del rientro, la sua attività creativa si concentrò principalmente sulla produzione in volgare: i giochi scenici e le Farse, così come le Rime (pubblicate postume nel 1530), testimoniano una vivace capacità espressiva.

Dal ritorno a Napoli, la sua opera mostrò una crescente predilezione per il latino, che per Sannazaro rimase tuttavia vibrante e poco accademico. Tra i suoi lavori si annoverano le Elegiae, permeate da un senso di alta malinconia; gli Epigrammata; le Eclogae piscatoriae, che trasportano l'ambiente bucolico tra i pescatori della costa napoletana; e il De partu Virginis (Il parto della Vergine), dove il racconto della natività viene reinterpretato tramite gli stilemi della mitologia classica.

Il capolavoro di Sannazaro è senza dubbio l'Arcadia (1501), opera che mescola prosa e versi e inaugura il genere del "romanzo pastorale". La narrazione trae origine da una vicenda autobiografica: sotto le vesti di Sincero, l'autore immagina un viaggio nell'Arcadia per sfuggire alle sofferenze causate da una dolorosa storia d'amore e assaporare le gioie semplici e genuine della vita pastorale. Il percorso culmina con la scoperta della morte dell'amata.

La nostalgia per un'irrimediabile età dell'oro costituisce il fulcro tematico dell'opera, tradotto in una prosa lirica inedita, dalla trama delicata e quasi impalpabile, animata da un ritmo musicale e impreziosita da riferimenti colti ed eleganti. La fortuna del romanzo fu straordinaria: in Italia conobbe numerosissime edizioni e suscitò altrettanti commenti eruditi. In Spagna, Portogallo, Francia e persino in Inghilterra esercitò un'influenza ampia e duratura.

== In sintesi

/ La diffusione dell'Umanesimo: I centri di diffusione dell'Umanesimo si concentrarono in diverse città italiane che divennero fulcri di innovazione culturale e artistica: Milano, con figure come Bramante e Leonardo da Vinci; Venezia, rappresentata da Ermolao Barbaro e dal contributo della stampa di Aldo Manuzio; Ferrara, con Matteo Maria Boiardo; Roma; Napoli, dove spiccano Giovanni Pontano, ai vertici della poesia lirica del Quattrocento, e Masuccio Salernitano, autore del _Novellino_, la più significativa raccolta di novelle del secolo. A Napoli si distingue anche Jacopo Sannazaro.

/ Boiardo: Matteo Maria Boiardo, nel suo poema cavalleresco _Orlando innamorato_, esprime l'ideale umanistico dell'energia amorosa, capace di elevare l'uomo. Attraverso una sapiente fusione tra esperienza epica e lirica, Boiardo interpreta il superamento dell'astrazione idealistica tipica della letteratura amorosa, a favore della complessità contemporanea del poema polifonico. Sebbene il _Canzoniere_ sia modellato su Petrarca, la commistione di influenze diverse rompe l'equilibrio petrarchesco, arricchendo il testo con elementi poetici originali ed eterogenei.

/ Sannazaro: Jacopo Sannazaro, nell'opera _Arcadia_, unisce prosa e versi dando vita al prototipo del romanzo pastorale, destinato al successo europeo duraturo. Il tema centrale ruota attorno alla nostalgia di un'inaccessibile età dell'oro, rappresentata con uno stile lirico-musicale impreziosito da numerosi riferimenti dottrinali. Importante è anche la sua produzione in latino: le _Elegiae_, di tono malinconico; le _Eclogae piscatoriae_, dove i temi pastorali sono trasposti tra i pescatori napoletani; e il _De partu Virginis_, rappresentazione della natività di Cristo attraverso schemi narrativi ispirati alla mitologia classica.