#import "../../../template_tufte.typ": *
#show: frame-style(styles.thmbox)

#evidenzia[Il XIV secolo rappresenta l'età aurea della letteratura italiana, un periodo in cui Dante Alighieri, Francesco Petrarca e Giovanni Boccaccio fondano i presupposti stessi dell'identità letteraria nazionale. Essi concepiscono la poesia non solo come strumento conoscitivo, ma anche come veicolo di una lingua nitida, luminosa e comunicativa, in grado di unificare una nazione culturalmente frammentata. Con Dante si raggiunge l'apice della lirica medievale e della poesia allegorico-didattica; con Boccaccio si consolida la tradizione novellistica italiana, che troverà ulteriore compimento nell'opera di Franco Sacchetti, andando ad arricchire anche quella cronachistica. Petrarca, simbolo dell'intellettuale moderno, segna il passaggio dalla tradizione duecentesca alla nuova sensibilità letteraria che darà origine all'Umanesimo. Accanto a questi grandi protagonisti, si colloca la straordinaria produzione degli scrittori religiosi: Mauro Cavalca, Passavanti, santa Caterina da Siena e la tradizione francescana dei _Fioretti_ offrono suggestivi esempi di ricerca spirituale ed espressione letteraria.]

Dante Alighieri è unanimemente riconosciuto come il sommo poeta italiano e uno dei principali autori della letteratura mondiale. La sua opera incarna un'appassionata tensione civile e morale, intrecciata a una profonda spiritualità che rappresenta l'espressione più alta e completa del pensiero e della cristianità medievali. La _Divina Commedia_, con la sua prodigiosa varietà di mezzi espressivi e la sua visione vastissima e profonda, si configura come un momento fondante per la letteratura italiana nella sua dimensione linguistica e culturale.

== La vita

Nato nel 1265 a Firenze, Dante Alighieri proveniva da una famiglia appartenente alla piccola nobiltà guelfa della città. Rimase orfano della madre Bella intorno al 1275 e, successivamente, perse anche il padre, Alighiero di Bellincione, prima del 1283. Nel 1274, ancora bambino, incontrò per la prima volta Beatrice (Bice di Folco Portinari), figura che egli avrebbe amato secondo gli ideali sublimati dello stilnovo fino alla sua prematura scomparsa, avvenuta nel 1290. Nel 1285 contrasse matrimonio con Gemma di Manetto Donati, dalla quale ebbe almeno tre figli. La partecipazione alla battaglia di Campaldino e all'assedio del castello di Caprona nel 1289 segnò il suo primo ingresso nella vita pubblica, in un contesto di conflitti tra i guelfi fiorentini e le forze ghibelline di Arezzo e Pisa. 

Nel 1295 Dante intraprese la carriera politica, preceduta dall'adesione alla corporazione dei medici e degli speziali; durante questa fase fu eletto nel Consiglio speciale del Capitano del Popolo e giunse alla prestigiosa carica di priore. Parallelamente, gli anni Ottanta e i primi anni Novanta del Duecento furono segnati dalle sue prime esperienze poetiche. In questo periodo compose almeno cinquanta Rime di vario metro, che riflettono le influenze della Scuola siciliana, di Guittone d'Arezzo, nonché dei grandi esponenti dello stilnovo, come Guido Guinizelli e Guido Cavalcanti.

La morte di Beatrice nel 1290 rappresentò un momento cruciale nella vita del poeta, innescando una profonda crisi religiosa che lo spinse verso intensi studi filosofici e teologici. Questi studi completarono la sua formazione retorica giovanile, già avviata sotto la guida del maestro Brunetto Latini. Tra il 1292 e il 1293 Dante compose la "Vita nuova", una raccolta di 31 liriche inserite in un racconto che idealizza Beatrice, trasformandola in una figura miracolosa destinata a guidare il poeta nel viaggio ultraterreno narrato nella "Commedia". 

Gli scontri interni alla fazione guelfa tra i Bianchi, fautori di una politica di autonomia, e i Neri, sostenitori del papato e guidati dai Donati (la famiglia della moglie di Dante), lo videro schierarsi con i Bianchi. Tuttavia, nel novembre 1301, mentre Dante si trovava a Roma per un'ambasciata presso Papa Bonifacio VIII, i Neri, con l'appoggio del legato papale Carlo di Valois, presero il controllo della Signoria fiorentina. Accusato di corruzione dai nuovi dominatori, Dante fu condannato a morte in contumacia nel marzo del 1302 e iniziò così un lungo percorso di esilio che sarebbe durato circa due decenni.

=== L'esilio

A partire dal 1304, Dante abbandonò la causa dei Bianchi, ormai indirizzata verso la riscossa armata. Sempre speranzoso di ottenere un'amnistia, iniziò una vita nomade toccando diverse città: soggiornò a Verona presso gli Scaligeri (probabilmente dal 1303), a Treviso sotto la protezione di Gherardo da Camino (tra il 1305 e il 1306), e nella Lunigiana ospite di Moroello Malaspina (nel 1306). Durante questo periodo compose il "Convivio" (1304-1307) e il trattato "De vulgari eloquentia" (1304-1305).

Un nuovo impulso alle sue speranze politiche si accese nel 1310 con la discesa in Italia dell'imperatore Arrigo VII di Lussemburgo. Dante auspicava la restaurazione dell'ordine supremo basato sull'armonia tra l'autorità imperiale e quella papale. Partecipò attivamente al dibattito sulla missione imperiale attraverso alcune epistole, nelle quali celebrava la figura di Arrigo e condannava i fiorentini che si opponevano al sovrano. Tuttavia, la morte improvvisa dell'imperatore nel 1313 pose definitivamente fine ai sogni del poeta di giustizia universale e di un ritorno onorevole nella sua città natale.

Nel maggio del 1315, Dante rifiutò di accettare un'amnistia che prevedeva come condizione un'ammissione di colpa. Nel novembre dello stesso anno, la Signoria fiorentina confermò la condanna a morte per lui e i suoi figli. In quel periodo, tra l'apparizione sulla scena italiana di Arrigo VII e la sua morte, il poeta approfondì le sue idee politiche attraverso un trattato in lingua latina, il _De Monarchia_. 

=== Gli ultimi anni

A seguito della conferma della condanna, Dante trovò rifugio presso Cangrande della Scala a Verona. Qui, nel 1320, tenne una discussione pubblica su una questione scientifica, _De situ et forma aquae et terrae_, mirata a spiegare l'emergere della terra rispetto alle acque nell'emisfero boreale, contraddicendo la dottrina aristotelico-scolastica che prevedeva gli elementi disposti in sfere concentriche. Intorno agli anni 1319-1320 si colloca anche la composizione delle due Egloghe latine, indirizzate a Giovanni del Virgilio. Forse nello stesso 1320 Dante si trasferì definitivamente a Ravenna, accolto da Guido Novello da Polenta. Durante il suo soggiorno in città e al rientro da una missione diplomatica a Venezia in cui si era recato per conto del suo ospite, Dante morì per malattia nella notte tra il 13 e il 14 settembre 1321. Fu sepolto in un'arca situata accanto alla chiesa di San Pier Maggiore, successivamente dedicata a San Francesco.

== Le opere minori

=== La "Vita nuova"

Composta intorno al 1293, a pochi anni dalla morte di Beatrice, questa è la prima opera organica di Dante, un racconto intenso e appassionato del suo amore per lei. Si tratta anche del primo romanzo autobiografico della letteratura italiana e comprende 25 sonetti, 4 canzoni, una stanza e una ballata, intervallati da prose che narrano la storia sentimentale. Il "libro de la memoria" è avaro di eventi: qualche incontro e episodi di scarso rilievo pratico, ma l'essenza dell'opera risiede nel racconto dei moti interiori. Questi superano la concezione "cortese" dell'amore tipica dello stilnovo e di Cavalcanti, avvicinandosi invece a una visione idealizzata in senso cristiano, intesa come mezzo di contemplazione e visione mistica. La _Vita nuova_ contiene alcune delle liriche più celebri di Dante, tra cui _Tanto gentile e tanto onesta pare_ e _Donne ch'avete intelletto d'amore_.  

=== Il "Convivio"

La stesura del _Convivio_, concepito come un'opera dalla struttura enciclopedica in 15 trattati che commentano 14 canzoni, risale agli anni 1304-1307. I principali temi affrontati riguardano l'ordinamento dei cieli, la natura della filosofia e il concetto di nobiltà, non intesa come privilegio di nascita bensì come eccellenza intellettuale e morale. Al centro non è più Beatrice, ma la "donna gentile", già comparsa nella _Vita nuova_ con atteggiamenti compassionevoli nei confronti del poeta dopo il lutto per l'amata. Qui questa figura assume un significato allegorico come personificazione della Filosofia. L'esaltazione del sapere filosofico rappresenta un passaggio fondamentale verso l'esperienza poetica e speculativa della _Commedia_.  

=== Il "De vulgari eloquentia"

Composto tra il 1304 e il 1305 e rimasto incompiuto, il _De vulgari eloquentia_ si concentra sulla teoria linguistica, un tema che Dante aveva solo sfiorato nel _Convivio_. Contrariamente a quanto sostenuto nella precedente opera, qui è il volgare a essere elevato rispetto al latino, considerato artificiale. L'obiettivo principale di Dante è identificare un volgare unitario che possa emergere come lingua ideale per la comunicazione artistica più alta. Questo volgare non deve coincidere con nessun dialetto regionale ma essere simile a una pantera: capace di diffondere il proprio profumo ovunque senza mostrarsi in un luogo specifico. Deve essere "illustre", "cardinale", "aulico" e "curiale", ossia risplendente rispetto gli altri volgari, in grado di farli rivolgere attorno a sé, caratterizzato e ben regolato da un alto decoro ed eleganza. 

=== Il "De monarchia"

Composto dopo la morte di Arrigo VII, il grande e appassionato trattato politico di Dante si struttura in tre libri. Nel primo, l'autore sostiene che una monarchia universale sia indispensabile per il raggiungimento degli ideali più elevati dell'uomo; nel secondo, chiarisce che tale monarchia debba essere romana, poiché Roma, erede dell'antico Impero voluto da un disegno divino, creò le condizioni ideali per l'avvento di Cristo; nel terzo e ultimo libro, delineano i rispettivi ambiti d'azione del pontefice e dell'imperatore. Fondamentale è il principio che il potere imperiale non discende da quello papale, ma direttamente da Dio. Mentre al papa spetta il mandato divino di condurre l'umanità verso la beatitudine eterna, è compito dell'imperatore favorire il raggiungimento della felicità terrena. Questi obiettivi devono essere perseguiti dalle due massime autorità in piena autonomia.

== La "Divina Commedia"

Originariamente denominata semplicemente "Commedia" da Dante stesso, il titolo acquistò l'attributo "divina" grazie a Ludovico Dolce, curatore di un'edizione veneziana stampata dal Giolito nel 1555. Secondo Dante (nel "De vulgari eloquentia" e nell'Epistola a Cangrande), il genere della commedia è caratterizzato da vicende inizialmente drammatiche e destinate a concludersi felicemente, oltre che da uno stile medio-umile, contrapposto alla solennità della tragedia. La composizione dell'opera, iniziata probabilmente nel 1306-1307, occupò il poeta per tutto il resto della sua vita. Il poema è suddiviso in tre cantiche: Inferno (34 canti, di cui 33 più uno introduttivo), Purgatorio e Paradiso (33 canti ciascuno), per un totale di 100 canti composti da 14.233 versi endecasillabi incatenate in terzine (schema ABA BCB CDC DED...).

L'opera narra il viaggio di sette giorni che Dante intraprende nei regni ultraterreni per superare una crisi personale vissuta a metà del suo percorso esistenziale (35 anni). Sarà Beatrice, donna amata dal poeta nella sua giovinezza, a scendere dal Paradiso per affidarlo alla guida di Virgilio, il sommo poeta della latinità. Rafforzato dalla presenza di Virgilio, l'8 aprile (Venerdì Santo) del 1300, anno del Giubileo proclamato da Bonifacio VIII, Dante si avventura nella voragine dell'Inferno per incontrare le anime dannate. Il 10 aprile (giorno di Pasqua) affronta le pendici del Purgatorio, dove intraprende la parte penitenziale del viaggio accanto alle anime in attesa di redenzione. Dopo aver raggiunto il Paradiso Terrestre sotto la tutela diretta di Beatrice, Dante si eleva il 13 aprile (mercoledì di Pasqua) verso i cieli del Paradiso e, nell'Empireo, può finalmente godere della contemplazione di Dio, anche solo per pochi istanti. Lo stesso Dante definisce l'obiettivo dell'opera nella celebre "Epistola a Cangrande": liberare i viventi dalla miseria del peccato e guidarli verso la felicità suprema.

Non vi è dubbio che Dante abbia tratto ispirazione dalla Sacra Scrittura, dai testi della latinità classica e dalla letteratura cristiana. Spicca particolarmente, nel suo immaginario, il rapimento di San Paolo al terzo cielo descritto nella Seconda Lettera ai Corinzi (12) e la discesa agli Inferi di Enea narrata nel VI libro dell'Eneide di Virgilio. La Commedia si configura quindi come un'Eneide della modernità, un'epopea dello spirito cristiano.

=== Valore universale della _Divina commedia_

La _Divina Commedia_ rappresenta un'opera di trasformazione e redenzione, un percorso articolato che conduce dalla comprensione del peccato e del male alla visione mistica e alla purificazione dell'anima umana. Considerata una monumentale enciclopedia della scienza, del pensiero e della spiritualità medievali, è la prima opera certamente classica scritta in lingua volgare, nonché un pilastro della cultura, della poesia e dei valori civili e morali. La sua natura poliedrica la rende straordinariamente versatile, capace di parlare a pubblici estremamente diversificati, inclusi strati popolari. Nel corso dei secoli, si è affermata come il testo più significativo della letteratura italiana, riconosciuto e letto non solo in Italia ma anche nel resto del mondo.

=== _Inferno_

Il viaggio di Dante nell'Inferno sotto la guida di Virgilio rappresenta – analogamente ai percorsi compiuti nel Purgatorio e nel Paradiso – un itinerario conoscitivo. Tale esperienza mira alla comprensione della natura del peccato, delle sue diverse forme di gravità e delle conseguenze che esso comporta sia nella vita terrena sia nell'esistenza ultraterrena. La struttura dell'abisso infernale, modellata secondo principi aristotelici e ciceroniani, si articola in nove cerchi. Nel cosiddetto alto Inferno (i cinque cerchi superiori), Dante incontra le anime di coloro che non furono in grado di dominare le proprie passioni e appetiti naturali. Nel basso Inferno emergono invece le figure dei peccatori più detestabili, ove la colpa risiede nella volontà lucida e deliberata di arrecare danno e offesa, attraverso violenza o frode, a Dio, al prossimo o a se stessi. Tra i personaggi più significativi della prima parte si ricordano Francesca da Rimini, Ciacco e Filippo Argenti; nella seconda compaiono invece Farinata degli Uberti, Cavalcante de' Cavalcanti, Pier delle Vigne, Brunetto Latini, Ulisse, Guido da Montefeltro e Ugolino della Gherardesca. Pur basandosi su una struttura ricorrente nei dialoghi con le anime dannate, Dante introduce elementi narrativi di variazione, come le caratteristiche dei paesaggi di pena regolati dalla legge del contrappasso. Quest'ultima prevede che la pena sia in relazione simbolica o antitetica rispetto alla colpa del dannato. Un ulteriore aspetto di rilievo nel canto infernale sono i sentimenti ambivalenti provati dal poeta nei confronti dei peccatori, che spaziano dallo sdegno e dall'ironia alla profonda partecipazione emotiva.

=== _Purgatorio_

Il Purgatorio è immaginato da Dante come una montagna isolata, nata dallo spostamento delle terre a seguito della caduta di Lucifero dal cielo. Questo luogo si trova su un'isola situata agli antipodi di Gerusalemme, nell'emisfero australe dominato dalle acque. La struttura è organizzata tra due estremi: l'Antipurgatorio, vicino alla spiaggia, e il Paradiso Terrestre, situato sulla sommità della montagna. Lungo il percorso si snodano sette balze corrispondenti ai peccati capitali. I penitenti, procedendo verso l'alto, purificano gradualmente le loro inclinazioni peccaminose. Contrariamente alla discesa infernale dove si incontrano colpe sempre più gravi, l'ascesa purgatoriale segue un principio decrescente di gravità: dai peccati derivanti da un amore mal indirizzato (superbia, invidia e ira), si passa all'accidia, definita come un amore per il bene esercitato con poca energia; infine si giunge ai peccati legati a un amore eccessivo per i beni materiali (avarizia, gola e lussuria). Nel Purgatorio Dante sperimenta una diversa manifestazione divina, quella della misericordia, rispetto alla giustizia incontrata nell'Inferno. Gli incontri con figure storiche e culturali – artisti e poeti come Casella, Sordello da Goito, Bonagiunta da Lucca, Guido Guinizelli, Arnaut Daniel, Stazio e Oderisi da Gubbio – assumono particolare rilievo nello sviluppo narrativo. Nelle ultime cantiche emerge con forza la figura di Beatrice, l'amata donna trasfigurata in simbolo allegorico di Rivelazione divina, Grazia, Amore Divino, Fede e Teologia, e va a sostituire Virgilio. 

=== _Paradiso_

La struttura del Paradiso segue la medesima regola del 9+1 valida per l'Inferno e il Purgatorio: nove livelli o ripartizioni principali più un elemento conclusivo. Nel caso del Paradiso, ai nove cieli (Luna, Mercurio, Venere, Sole, Marte, Giove, Saturno, Stelle Fisse e Primo Mobile) si aggiunge l'Empireo. Qui risiedono i beati che godono della beatitudine eterna. Gli spiriti, però, si manifestano al pellegrino nei cieli che corrispondono all'influsso subito durante la loro vita terrena. Questo crea un ordine gerarchico ben preciso: i primi tre cieli, quelli inferiori (Luna, Mercurio e Venere), accolgono le anime che non hanno raggiunto la perfezione assoluta. Salendo verso l'alto, troviamo i cieli degli spiriti attivi: il Sole con i sapienti, Marte con i militanti per la fede, Giove con i giusti e Saturno con i contemplativi.

Gli ultimi due cieli prima dell'Empireo servono al pellegrino per completare la propria preparazione alla visione divina, assistendo al trionfo di Cristo e della Vergine Maria e sostenendo un esame sulla fede, la speranza e la carità. Infine, il pellegrino raggiunge il cielo Empireo, che rappresenta il vero Paradiso ed è la dimora di Dio e dei beati. Qui Dante osserva una "candida rosa", un'immensa disposizione di anime su troni ordinati a forma di anfiteatro. Tra loro ritrova Beatrice, che simbolicamente cede il ruolo di guida a san Bernardo di Chiaravalle. La preghiera di Bernardo ottiene l'intercessione della Vergine Maria, grazie alla quale il poeta può avvicinarsi al mistero ineffabile della divina essenza.

== In sintesi

/ La vita: Dante Alighieri nacque a Firenze nel 1265, proveniente da una famiglia della piccola nobiltà guelfa. Nel 1285 contrasse matrimonio con Gemma Donati. La morte di Beatrice, avvenuta nel 1290, figura amata da Dante e sublimata in un ideale di amore spirituale, provocò nel poeta una profonda crisi religiosa. A seguito della divisione interna ai Guelfi in fazioni dei Bianchi e dei Neri, Dante si schierò con i Bianchi, sostenitori di una politica d'indipendenza dal potere papale. Tuttavia, nel 1301 i Neri assunsero il controllo politico ed emisero contro di lui una condanna a morte in contumacia. Questa situazione lo costrinse a vivere in esilio fino alla sua morte, avvenuta a Ravenna nel 1321.

/ Le opere minori: Tra le opere giovanili emerge la _Vita nuova_ (1292-93), dove la figura storica di Bice di Folco Portinari, amata dall'autore, viene idealizzata sino a diventare un simbolo di amore divino: la miracolosa Beatrice. Successivamente, Dante compose il _Convivio_ (1304-07), un'opera dove il fulcro della riflessione non è più Beatrice, ma la "donna gentile", introdotta nella _Vita nuova_ come conforto compassionevole del poeta dopo la perdita dell'amata. Tale figura assume qui un ruolo allegorico, rappresentando la Filosofia e fungendo da guida intellettuale.

/ De vulgari eloquentia: Il _De vulgari eloquentia_ (1304-05) è un trattato di natura teorico-linguistica che analizza il potenziale del volgare rispetto al latino. Dante propone l'idea di un volgare superiore, che dovrebbe essere "illustre", "cardinale", "aulico" e "curiale", ovvero dotato di splendore, capace di attrarre gli altri volgari, regolato da norme precise e caratterizzato da altissima dignità e eleganza.

/ La Divina Commedia: Capolavoro assoluto della letteratura occidentale, la _Divina Commedia_ è composta da tre cantiche: _Inferno_ (34 canti), _Purgatorio_ (33 canti) e _Paradiso_ (33 canti), per un totale di 100 canti scritti tra il 1306-07 e l'anno della morte del poeta. L'opera descrive un percorso di conversione spirituale, che si articola dalla consapevolezza del peccato alla redenzione ultima dell'anima umana. Realizzata in terzine di versi endecasillabi, il poema è riconosciuto come il più grande affresco della cultura occidentale e rappresenta con straordinaria intensità la riflessione sulla sofferenza umana, al fine di definire una nuova dignità dell'uomo attraverso il confronto con il dolore e la ricerca del trascendente.