#import "../../../template_tufte.typ": *
#show: frame-style(styles.thmbox)

#evidenzia[Francesco Petrarca fu un maestro della lirica europea, capace di raggiungere vertici di straordinaria raffinatezza formale con il suo __Canzoniere__, opera che esercitò un'influenza profonda sulla poesia italiana e europea. Il __petrarchismo__ si consolidò come modello poetico imitativo e come scuola fino al Settecento, diventando un punto obbligato per chi intendeva la poesia come strumento di introspezione. La sua visione culturale era profondamente influenzata dal legame con i classici latini e dalla curiosità intellettuale che lo rese un precursore dell'Umanesimo.]

== La vita

Nacque ad Arezzo nel 1304 da Eletta Canigiani e da ser Pietro, detto Petracco, un notaio fiorentino di parte bianca esiliato assieme a Dante. Nel 1312 la famiglia si trasferì a Carpentras, in Provenza, dove ser Petracco aveva intenzione di esercitare la professione vicino alla sede papale di Avignone. Petrarca fu mandato a studiare legge a Montpellier e poi, con il fratello Gherardo, a Bologna. In questi anni alimentò l'interesse per i classici (Cicerone, Virgilio, Livio) e per i padri della Chiesa, soprattutto sant'Agostino. Nel 1326, alla morte del padre, tornò ad Avignone. Qui, nella chiesa di Santa Chiara, il giorno di venerdì Santo del 1327, avvenne, secondo la testimonianza dello stesso poeta, l'episodio dell'incontro-innamoramento con Laura, destinata a diventare la figura ispiratrice centrale nel Canzoniere. 

Dopo aver dissipato gran parte del patrimonio familiare, Petrarca intraprese la carriera ecclesiastica. Nonostante ciò, ebbe relazioni amorose da cui nacquero due figli: Giovanni e Francesca. Dal 1330 fu cappellano presso la famiglia del cardinale Giovanni Colonna, posizione che gli permise di viaggiare in Europa. Nel 1333 scoprì a Liegi due importanti opere ciceroniane: la "Pro Archia" e l'apocrifa "Ad equites Romanos". Nel 1335 papa Benedetto XII lo nominò canonico nella cattedrale di Lombez; proprio in quegli anni scrisse lettere al papa chiedendo il ritorno della sede pontificia in Italia.

Dopo un primo viaggio a Roma, durante il quale rimase profondamente colpito dai resti dell'antichità classica, Petrarca si trasferì da Avignone alla tranquilla Valchiusa, dedicandosi alla scrittura. Alternò la produzione in latino, con opere come _Africa_ e _De viris illustribus_, a quella in italiano, impegnandosi nella composizione delle rime che sfoceranno poi nel _Canzoniere_ e nei _Trionfi_. Periodi di isolamento e studio si alternavano a viaggi e attività pubbliche. Grazie alla fama ottenuta dalle opere latine, quelle a cui Petrarca affidava principalmente il suo desiderio di gloria più che alle liriche in volgare, gli fu conferita la laurea poetica in Campidoglio nell'aprile del 1341. Nel 1342 raccolse per la prima volta le sue rime in lingua volgare. La morte di Laura, avvenuta durante l'epidemia di peste che devastò l'Europa, e la decisione del fratello Gherardo di farsi monaco contribuirono ad accentuare l'inquietudine e il conflitto interiore tra il desiderio di solitudine e riflessione e le ambizioni mondane. Nel 1343, a Verona, scoprì le lettere di Cicerone a Attico.

Nel 1347 tornò in Italia per sostenere la riforma politica di Cola di Rienzo, che mirava a unificare l'Italia attraverso un ruolo propulsivo di Roma. In quegli anni si legò in amicizia con Boccaccio e, nel 1351, si stabilì a Padova presso Francesco da Carrara. Tra il 1353 e il 1361 visse alla corte dei Visconti di Milano, dove svolse diverse missioni diplomatiche, inclusa una visita all'imperatore Carlo IV a Praga. Fuggendo dalla peste che dilagava in Lombardia, si trasferì a Venezia; qui, nel 1363, lo visitarono gli amici Boccaccio e Leonzio Pilato. Alternando soggiorni a Padova, Venezia e Arquà sui Colli Euganei ma continuando i suoi viaggi, trascorse gli ultimi anni impegnato nel lavoro intellettuale. Di questo periodo fa parte il _De sui ipsius et multorum ignorantia_, un testo polemico scritto in risposta alle accuse di ignoranza rivoltegli da quattro giovani aristotelici. Petrarca morì ad Arquà (oggi Arquà Petrarca) nella notte tra il 18 e il 19 luglio 1374.

== Le lettere

Le lettere costituiscono una testimonianza essenziale per seguire dettagliatamente il percorso esistenziale e intellettuale di Petrarca. Il poeta stesso organizzò il proprio epistolario per temi: i _Rerum familiarum libri_ (Libri delle cose familiari), il _Sine nomine_ (Senza nome) con lettere polemiche contro il papato avignonese, i _Rerum senilium libri_ (Libri della vecchiaia). Postumi sono le _Variae_ e la singola epistola _Posteritati_ (Alla posterità), prezioso riassunto autobiografico. Attraverso le sue lettere si possono esaminare i numerosi spostamenti del poeta, esplorare i suoi affetti personali, le scelte politiche, le iniziative civili e diplomatiche, le inclinazioni intellettuali, le sue avversioni ideologiche e le riflessioni morali fondamentali che caratterizzarono il suo credo umanistico.

== Il _Secretum_

Il _Secretum_, opera filosofico-morale articolata in tre libri, fu composto tra il 1342 e il 1343 ma ripreso e completato tra il 1356 e il 1358. In esso si svolge un dialogo intenso tra l'autore, Franciscus, e Sant'Agostino (Augustinus), alla presenza della Verità. Nella prima giornata si discute come felicità e infelicità dipendano dalla volontà umana, evidenziando una “malattia della volontà” che impedisce a Francesco di perseguire con forza il bene autentico. La seconda giornata è dedicata a un esame di coscienza sui sette peccati capitali, con particolare enfasi sull'accidia. Nella terza giornata emergono le passioni esiziali che ostacolano una dedizione assoluta alla meditazione sulla vita e sulla morte: l'amore per Laura e l'amore per la gloria.

Bellissime e seducenti catene, rappresentano l'amore per Laura e quello per la gloria. L'amante, pur tentando invano di mascherare come spirituale e virtuoso il sentimento rivolto a una donna d'eccezione, viene smascherato. Sant'Agostino, con arguzia, dimostra come Francesco abbia amato in modo non consono. Alla fine, si giunge al più insidioso dei mali: l'amore per la gloria terrena, che, promettendo la sopravvivenza del nome nel tempo, distoglie lo spirito dalla vera immortalità. Pur mettendo a nudo le sue debolezze e liberando la mente dai vincoli del peccato, Francesco non abbraccia con esclusivo zelo le opere divine, come vorrebbe Agostino. Conclusa la lunga confessione-meditazione, riconosce di aver tratto giovamento da essa e manifesta l'intento di rafforzare la propria volontà. Tuttavia, la rinuncia radicale alle vanità del mondo rimane solo un desiderio non concretizzato.

== Le altre opere latine

Durante il suo primo soggiorno a Valchiusa, Petrarca intraprende la composizione dell'"Africa", poema ambizioso che incarnava il suo desiderio di gloria letteraria, ma che oggi appare un insuccesso poetico a causa della sua retorica imponente. L'Africa è un poema epico scritto in esametri, ispirato alla seconda guerra punica e focalizzato sull'eroica figura di Scipione l'Africano. La narrazione celebra il destino provvidenziale del popolo romano. A questo periodo risalgono anche le prime stesure del "De viris illustribus", una raccolta di biografie di personaggi significativi provenienti dalla storia antica, dalla Sacra Scrittura e dalla mitologia classica. 

La crisi spirituale culminata tra il 1342 e il 1343 conduce Petrarca verso un cristianesimo più intimo e profondamente sentito; alcuni parlano addirittura di una conversione. A testimonianza di questo periodo ci sono i "Salmi penitenziali" del 1348, ispirati al testo biblico ma impregnati da influenze ciceroniane e agostiniane. Negli anni successivi (dal 1343 al 1354), Petrarca compone altre opere significative: i "Rerum memorandarum libri", raccolta incompiuta di aneddoti ed esempi edificanti modellata sui testi di Valerio Massimo; il "De vita solitaria", dove esalta la condizione della solitudine come via per il perfezionamento morale e intellettuale attraverso lo studio e la meditazione religiosa; il "De otio religioso", strettamente connesso al "De vita solitaria" e nato dopo una visita al fratello Gherardo in monastero; e il "De remediis utriusque fortunae", la cui scrittura si estese fino al 1366, opera allegorica che propone riflessioni stoico-cristiane per affrontare virtuosamente gli alti e bassi della sorte. Parallelamente a questi scritti in prosa, si colloca il "Bucolicum carmen", una raccolta di egloghe allegoriche ispirate alla tradizione pastorale virgiliana.

== _Il Canzoniere_

Il "Canzoniere" si è consolidato nei secoli come l'opera più rilevante di Petrarca e ha giocato un ruolo decisivo nello sviluppo della poesia e della poetica occidentali. Frutto di un lavoro di ideazione, revisione e organizzazione che occupò il poeta dal 1335 fino alla fine della sua vita, il "Canzoniere", originariamente intitolato _Rerum vulgarium fragmenta_ (Frammenti in volgare), è composto da 317 sonetti, 29 canzoni, 9 sestine, 7 ballate e 4 madrigali. La struttura dell'opera si articola in due parti (rime in vita e rime in morte di Laura), separate dal componimento "I' vo pensando, et nel penser m'assale".

Frutto della tradizione latina, sia classica che patristica, e di quella volgare moderna, dai provenzali fino allo stilnovo e a Dante, il _Canzoniere_ rappresenta una testimonianza fondamentale di un tentativo di mediazione tra eros e caritas, tra amore profano e amore sacro. Esso si inserisce in quella ricerca di conciliazione tra l'eredità ovidiana e la Sacra Scrittura che ha profondamente influenzato la produzione letteraria medievale, in particolar modo la lirica. La poesia del _Canzoniere_ è caratterizzata da una sintesi raffinata della psicologia amorosa, strettamente radicata nell'esperienza personale del poeta, sublimata e orientata verso soluzioni formali di grande eleganza.

La lingua poetica impiegata da Petrarca si distingue per essere purificata dalla tentazione del realismo, rispondendo a un ideale di alta dignità e di armonia impeccabile. Tuttavia, all'interno dell'opera emerge con forza predominante la figura femminile, simbolo centrale di un mito personale del poeta. Laura incarna una rilettura cristiana del mito della negazione del desiderio erotico, ispirata alla celebre vicenda ovidiana di Apollo e Dafne: come Dafne, Laura si sottrae alle premure dell'amante trasformandosi simbolicamente nel lauro destinato a coronare la fronte del poeta innamorato. L'amore per la donna e l'ambizione alla fama si intrecciano in un percorso meditativo scandagliato con particolare vigore introspettivo, come avviene nel _Secretum_. La narrazione amorosa, articolata in una complessa analisi interiore, raggiunge il suo compimento nella canzone alla Vergine, ultima composizione del _Canzoniere_. Qui Petrarca opera una ritrattazione: all'esaltazione della donna terreno - "poca mortal terra caduca" - subentra la celebrazione della donna divina, la "vera beatrice", evocata quale ultimo rifugio per l'anima, stremata dagli inganni mondani ma ancora assetata di verità assolute.

== _I Trionfi_

L'altra opera poetica in volgare composta da Petrarca sono i _Trionfi_, scritti tra il 1348 e il 1374. Si tratta di un'opera ambiziosa dal carattere allegorico-didattico, articolata in sei sezioni: il Trionfo dell'Amore, della Pudicizia, della Morte, della Fama, del Tempo e dell'Eternità. In essa Petrarca si ispira al modello sommo della _Commedia_ dantesca per inserire il mito amoroso personale, centrato sulla figura di Laura, nel contesto più ampio della storia umana e in quadri morali e metastorici immutabili. Attraverso i _Trionfi_, il poeta drammatizza i grandi temi della sua interiorità, primo fra tutti il conflitto tra la frammentarietà dell'esistenza mondana e l'eterna perfezione dell'assoluto. Questa tensione viene rappresentata con un gusto figurativo e compositivo che resta per molti aspetti legato alla tradizione medievale. Tuttavia, sul piano poetico, l'esito complessivo dell'opera risulta meno efficace rispetto ad altre creazioni petrarchesche.

== In sintesi

/ La vita: Francesco Petrarca nasce ad Arezzo nel 1304, figlio di un notaio fiorentino in esilio, come Dante. La famiglia si trasferisce in Provenza, ad Avignone, allora sede papale. Dopo aver studiato diritto, intraprende la carriera ecclesiastica e alterna periodi di isolamento a Valchiusa, nei pressi di Avignone, a viaggi e attività diplomatiche. Diventa l'intellettuale più celebre del suo tempo, ricevendo nel 1341 la corona di poeta laureato a Roma, sul Campidoglio. Nel 1342-43 attraversa una profonda crisi morale e religiosa a seguito della morte di Laura, sua amata, e della monacazione del fratello. Dal 1351 si stabilisce a Milano presso i Visconti e successivamente a Venezia. Francesco Petrarca muore nel 1374 nella sua residenza di Arquà (oggi Arquà Petrarca), sui Colli Euganei, vicino a Padova.

/ Le lettere: L'epistolario di Petrarca, composto da _Rerum familiarum libri_, _Sine nomine_, _Rerum senilium libri_, le postume _Variae_ e la singola epistola _Posteritati_, rappresenta un'eccezionale autobiografia intellettuale e poetica.

/ Il "Secretum": Redatto tra il 1342 e il 1343, il _Secretum_ è un'opera filosofico-morale scritta in prosa e suddivisa in tre libri. Esplora il tema della virtù e della felicità umana, ponendo il poeta in dialogo con la propria coscienza.

/ Altre opere latine: Fra le opere latine figurano _L'Africa_, poema epico in esametri dedicato alla figura eroica di Scipione l'Africano e celebrativo del destino provvidenziale del popolo romano. I _Salmi penitenziali_, modellati sul testo biblico, introducono una riflessione religiosa. Tra le opere in prosa spiccano il _Rerum memorandarum libri_, raccolta incompiuta di aneddoti ed esempi; il _De vita solitaria_, che esalta la solitudine come condizione ideale per l'elevazione morale e intellettuale; il _De otio religioso_, che approfondisce tematiche analoghe dopo una visita al monastero del fratello; e il _De remediis utriusque fortunae_, opera allegorica che invita ad affrontare virtuosamente le alterne vicende della vita attraverso principi stoico-cristiani. Il _Bucolicum carmen_ raccoglie egloghe allegoriche ispirate alla poesia pastorale virgiliana.

/ Il "Canzoniere": Il _Canzoniere_ raccoglie nella sua versione definitiva 317 sonetti, 29 canzoni, 9 sestine, 7 ballate e 4 madrigali. Quest'opera rappresenta un dialogo intimo del poeta con la propria anima e racchiude la sua tensione verso il dolce errore della coscienza. Il _Canzoniere_ diventa il modello fondativo della lirica d'amore italiana.

/ I "Trionfi": I _Trionfi_ sono un'opera allegorico-didattica scritta in terzine e articolata in sei parti: il Trionfo dell'Amore, della Pudicizia, della Morte, della Fama, del Tempo e dell'Eternità.