#import "../../../template_normal.typ": *
//#show: frame-style(styles.thmbox)

#evidenzia[L'eredità didattica derivante dalla cultura predicatoria e dalla filosofia scolastica rappresenta la base di una vasta produzione letteraria didattico-allegorica. Pur senza offrire veri e propri capolavori, questa tradizione risulta cruciale per comprendere l'ottica di opere straordinarie come la _Commedia_ di Dante. I cronachisti dell'epoca ci permettono di individuare una ricerca di concretezza, unitamente a un gusto municipale e popolare, elementi che ritroviamo anche nelle forme migliori della prosa trecentesca. Romanzi come i _Reali di Francia_ e il _Guerrin Meschino_ di Andrea da Barberino hanno conosciuto una diffusione popolare eccezionale fino al XIX secolo. In questo contesto emerge il capolavoro di Marco Polo: il _Milione_, considerato una delle vette della letteratura medievale e uno dei più straordinari resoconti di viaggio mai scritti.]

== I poemi allegorici
#note(bottom)[== *🧩* Tradizione classica <senza_numero>

La letteratura latina rimane vivace e profondamente radicata durante questo periodo. Non si può tuttavia parlare di un vero e proprio preumanesimo, sebbene agli autori italiani che scrivono in latino debba essere riconosciuto un notevole interesse per la cultura classica, senza che tale interesse implichi una rottura o una crisi nei confronti della consolidata tradizione scolastico-medievale. È opportuno osservare che il processo di conformazione ai modelli della latinità risale già al Duecento. \ Tra le figure rappresentative di questa stagione letteraria spiccano Zanobi da Strada, Giovanni del Virgilio, i membri del cenacolo "veronese" (tra cui Guglielmo da Pastrengo), nonché il colto Ferreto de' Ferreti. Tuttavia, il ruolo più preminente nella lirica latina dell'epoca è rivestito dal padovano Albertino Mussato (1261-1329). Nelle sue opere, Mussato si fece portavoce della difesa della libertà comunale nel contesto dei poteri universali della Chiesa e del Papato. Con l'opera _Evidentia tragediarum Senecae_, egli si dedicò alla promozione del modello di tragedia classica, a cui offrì un significativo contributo con la sua _Ecerinis_. \ In questo clima di riscoperta e valorizzazione degli ideali classici rientrano anche i numerosi volgarizzamenti della letteratura latina, tra cui meritano menzione le traduzioni delle opere ovidiane realizzate da Andrea Lancia.]
Emblema dell'influenza della _Divina Commedia_ e dell'ideale scolastico di un sapere universale sono i numerosi poemi allegorici del Trecento che offrono ampie panoramiche del mondo sotto forma simbolica. Tra le opere più antiche si annovera l'_Intelligenza_, un poemetto allegorico-didattico riscoperto nel 1846. Composto tra la fine del Duecento e l'inizio del Trecento da un anonimo fiorentino, il testo conta 309 stanze in nona rima ispirate ai modelli provenzali e stilnovisti. Racconta l'incontro simbolico del poeta con una donna bellissima, l'Intelligenza, che risiede in un palazzo favoloso rappresentante il corpo umano.

Francesco da Barberino, autore toscano vissuto tra il 1264 e il 1348, ci ha lasciato due opere didattiche pubblicate intorno al 1314: i _Documenti d'Amore_, scritti in versi volgari corredati da commenti in latino, e il _Reggimento e costumi di donna_, un'opera composta in versi misti a prosa.

Cecco d'Ascoli, il cui vero nome era Francesco Stabili, nacque vicino ad Ascoli Piceno intorno al 1269. Fu astrologo presso l'Università di Bologna ma, accusato di eresia, venne condannato al rogo a Firenze nel 1327. Tra le sue opere, incluse commenti, lezioni e poesie, spicca il poema incompiuto intitolato _Acerba_, scritto in sesta rima. Quest'opera, caratterizzata da un tono enciclopedico e didattico, raccoglie conoscenze astronomiche, astrologiche, alchemiche e naturalistiche di matrice araba, spesso in polemica con la _Divina Commedia_ di Dante e con i dogmi aristotelico-tomisti della filosofia scolastica.

Fazio degli Uberti, autore fiorentino (circa 1350-1367), è noto per il _Dittamondo_ (_Dicta mundi_), un poema allegorico-didattico in sei canti di terzine composto tra il 1346 e il 1367 e rimasto incompiuto. Ispirandosi alla struttura della _Commedia_, Fazio immagina che la Virtù gli appaia in sogno per guidarlo verso la salvezza: un viaggio attraverso Europa, Africa e Asia accompagnato dal geografo Solino. L'opera si distingue per il carattere enciclopedico e per la vivacità delle descrizioni, soprattutto quelle naturalistiche.

Federico Frezzi, originario dell'Umbria (circa 1346-1416), fu nominato vescovo di Foligno nel 1404. Scrisse un poema allegorico in terzine intitolato _Quadriregno_ (1394-1403). Nei suoi 74 canti viene raccontato il viaggio dell'uomo dalle passioni alla verità, passando attraverso i regni dell'Amore, di Satana, del Vizio e della Virtù. L'influenza della _Commedia_ è evidente, ma l'opera presenta anche alcuni spunti preumanistici.

== I cronachisti

La Vita di Cola è un'opera anonima scritta in romanesco, appartenente a una cronaca frammentaria del Trecento, pubblicata da Ludovico Antonio Muratori nel 1740. Composta intorno al 1357-58, racconta le vicende di Roma e il tentativo di riforma politica di Cola di Rienzo tra il 1325 e il 1357. Il testo riveste grande rilevanza sia dal punto di vista storico che linguistico.

Dino Compagni, fiorentino nato circa nel 1255 e morto nel 1324, è celebre soprattutto per la Cronica delle cose occorrenti nei tempi suoi, scritta tra il 1310 e il 1312. Quest'opera narra i conflitti che sconvolsero Firenze tra il 1280 e il 1312 e, rispetto al modello tradizionale erudito e oggettivo delle cronache medievali, si distingue per uno stile personale e appassionato. Compagni descrive gli eventi dal proprio punto di vista, come protagonista della scena politica fiorentina, schierato dalla parte popolare e dei Bianchi, proprio come Dante.

Giovanni Villani, vissuto tra il 1280 e il 1348, realizzò una Cronica che rimase inedita sino al 1537. L'opera si estende dalla Torre di Babele fino alla discesa in Italia di Carlo d'Angiò nel 1266. Sebbene caratterizzata da uno stile essenziale e distaccato, si conferma uno dei documenti fondamentali del Trecento. Matteo Villani, fratello di Giovanni (nato tra il 1280 e il 1290 e morto nel 1363), proseguì la Cronica fino al 1363, adottando un approccio più moralistico che documentario.

== Marco Polo

Marco Polo, mercante veneziano nato nel 1254 e morto nel 1324, intraprese nel 1271 un viaggio in Cina con il padre e lo zio, arrivando a diventare uomo di fiducia del Gran Khan Qubilai. Tornato a Venezia nel 1292, fu catturato dai genovesi durante la battaglia della Curzola del 1298. La sua fama è legata all'opera _Divisament dou monde_ (nota anche come _Livres des Merveilles du monde_), meglio conosciuta come _Il Milione_, titolo derivante dal suo soprannome veneziano. Marco Polo la dettò a Rustichello da Pisa, suo compagno di prigionia, utilizzando la lingua francese del tempo, il "volgare gallico".

Il _Milione_ è una miniera di informazioni sull'organizzazione amministrativa della Cina e sulle meraviglie dell'Oriente. La narrazione riflette lo spirito pragmatico e razionale della Venezia mercantile del Duecento, arricchendosi di descrizioni poetiche che esprimono la curiosità inesauribile del mondo medievale verso ciò che è esotico e favoloso. La struttura narrativa è solida; lo stile, privo di pretese letterarie, risulta intenso e vibrante. Per queste ragioni, il critico Luigi Foscolo Benedetto ha definito l'opera come una delle sintesi più potenti lasciate dal Medioevo, una testimonianza laica e terrena che può essere accostata a celebri opere teologiche e filosofiche come la _Summa_ di San Tommaso d'Aquino o la _Divina Commedia_.

== I romanzi

I romanzi del periodo attingono solitamente ai grandi cicli classici (Tebe, Troia, Roma) o a quelli carolingi e bretoni. La forma può essere sia in prosa che in versi. Il _Fiore d'Italia_ di Guido da Pisa è un'opera divulgativa caratterizzata da un racconto semplice ma chiaro e sincero. L'anonimo _Avventuroso Ciciliano_ narra il viaggio di cinque baroni siciliani che fuggono dopo i Vespri siciliani; ricco di digressioni, appare però poco originale. La _Tavola Ritonda_, anch'essa anonima e ispirata ai testi _Meliadus e Roman de Tristan_, rappresenta il miglior volgarizzamento dedicato ai temi bretoni.

Andrea da Barberino (circa 1370-1431) fu un autore prolifico di romanzi e reinterpretò con uno stile vicino al gusto borghese tanto le severe vicende del mondo carolingio quanto le avventurose storie del ciclo bretone. I suoi capolavori, Reali di Francia e Guerrin Meschino, ebbero una straordinaria diffusione fino a tutto l'Ottocento, diventando una parte dell'immaginario popolare.

#pagebreak()
#set page(fill: main_letteratura.lighten(90%))
== In sintesi <senza_numero>

/ Letteratura didattico-allegorica: Tra i testi pionieristici vi è _L'Intelligenza_. Francesco da Barberino lasciò opere quali _Documenti d'Amore_ e _Reggimento e costumi di donna_, pubblicate intorno al 1314. Cecco d'Ascoli fu autore del poema allegorico _Acerba_, mentre Fazio degli Uberti è celebre per il _Dittamondo_, una narrazione cosmografica in versi.  

/ Cronachisti: Dino Compagni compose una coinvolgente _Cronica delle cose occorrenti ne' tempi suoi_ (1310-12), dedicata alle lotte di fazione che imperversarono a Firenze durante il periodo di Dante. Giovanni Villani (1280-1348) redasse una monumentale _Cronica_, che collega la Torre di Babele alla discesa degli Angioini in Italia nel 1266; l'opera fu poi continuata dal fratello Matteo Villani (1280/90-1363) fino al 1363, assumendo un taglio più moralistico che strettamente documentaristico.  

/ Marco Polo e il _Milione_: Mercante veneziano, Marco Polo si recò nel 1271 in Cina accompagnato dal padre e dallo zio, stabilendo solide relazioni con il Gran Khan Qubilai. Tornato a Venezia nel 1292, scrisse il _Milione_ in lingua francese, un resoconto straordinario del suo soggiorno presso la corte cinese. Quest'opera rappresenta una sintesi illuminante del mondo medievale ed è annoverata fra i testi più emblematici della letteratura italiana.  

/ Romanzi: Nel contesto delle tradizioni carolingia e bretone, Andrea da Barberino scrisse noti romanzi quali i _Reali di Francia_ e il _Guerrin Meschino_, che riscossero una notevole popolarità fino all'Ottocento.