#import "../../../template_tufte.typ": *
#show: frame-style(styles.thmbox)

#evidenzia[La letteratura latina nasce alla metà del III secolo a.C.; la data d'inizio fu fissata dai romani stessi nel 240 a.C., anno della prima rappresentazione di un'opera teatrale, forse una tragedia, di Livio Andronico. Fin dalle sue prime manifestazioni essa subisce l'influenza della letteratura greca, con la quale si pone in costante rapporto dialettico. In cinque secoli Roma conquista l'Italia centrale e meridionale, delinea il proprio volto, forgia il proprio ordinamento giudiziario, le proprie istituzioni politiche e religiose, ma non crea nessuna opera letteraria, nonostante il continuo contatto con la cultura ellenistica della Magna Grecia. Ci fu una produzione anonima e tramandata oralmente, che ha però scopi pratici e occasionali e che può essere definita come preletteraria. Si tratta di forme poetiche abbozzate, prive di intenti letterari e scritte in un latino rozzo e primitivo, di cui restano solo scarsi documenti che interessano la storia della cultura e della lingua più che la letteratura. Il loro unico interesse risiede nel fatto che tali documenti hanno esercitato una certa influenza sulla letteratura posteriore, soprattutto per quanto concerne il teatro, l'oratoria e la storiografia.]

== Le iscrizioni

I rari documenti epigrafici pervenuti sono spesso poco chiari e di ardua interpretazione per le difficoltà linguistiche, ma testimoniano che nella Roma arcaica del 600 a.C. era già diffusa la scrittura per uso privato e pubblico, per lo meno nei ceti dominanti e nella classe sacerdotale; si tratta di una scrittura alfabetica di derivazione greca, proveniente dalle città della Magna Grecia.Decisamente oscura, anche per il testo lacunoso, è l'iscrizione del cosiddetto Lapis Niger (pietra nera), risalente ai secc. VII-VI a.C., incisa su un cippo a forma di parallelepipedo trovato, alla fine del 1800, nel Foro romano sotto un lastricato di marmo nero, che la tradizione indicava come la tomba di Romolo. Esso reca le norme religiose per interdire l'accesso a un recinto sacro; compare anche un rex, una figura sacerdotale. Il testo è in caratteri greci e in scrittura bustrofedica ("come i buoi che arano"), per cui le righe si alternano da destra a sinistra e da sinistra a destra, con le lettere opportunamente orientate.Dello stesso periodo e parimenti di difficile interpretazione è la lunga iscrizione sul cosiddetto Vaso di Dueno, un vasetto di terracotta usato forse per qualche rito sacrificale o come contenitore di cosmetici, trovato nell'avvallamento tra il Quirinale e il Viminale. La scrittura va da destra a sinistra e le parole non sono separate l'una dall'altra. Forse si allude alla destinazione votiva del vaso stesso, oppure a una fanciulla che invia all'innamorato un dono; si ricava solo un dato, e forse erroneo: che fu opera di un certo Dueno.Facilmente decifrabile, anche perché di un periodo molto più recente, è la cosiddetta Cista Ficoroni (dal nome dello scopritore), un'iscrizione incisa su un cofanetto di bronzo di forma cilindrica trovato a Preneste (oggi Palestrina): Dindia Malconia mi diede alla figlia; Novio Plauzio mi fece a Roma. Vi sono forti dubbi sull'autenticità della breve scritta sulla Fibula Praenestina, primo documento pervenutoci in lingua latina, anch'essa rinvenuta in una tomba di Preneste: su una fibbia d'oro del 600 a.C. è inciso il nome dell'orafo o del donatore e quello del destinatario: Manio mi fece per Numerio. La scritta è in caratteri greci, da destra a sinistra senza intervallo tra le parole.  

=== Le tombe degli Scipioni

Di grande interesse documentario sono le iscrizioni sepolcrali incise sui sarcofaghi della potente famiglia degli Scipioni, fuori Porta Capena, sulla via Appia. Rappresentano la prima testimonianza diretta del verso saturnio e rivelano una buona conoscenza delle epigrafi funerarie greche. L'epitaffio in onore di Lucio Cornelio Scipione Barbato, console nel 298 a.C., è un rifacimento dell'originale posteriore al 200, come dimostra la lingua, mentre senz'altro più remoto è quello per il figlio omonimo: Moltissimi Romani sono concordi che questo unico / fu il migliore tra gli uomini onesti / Lucio Scipione. Figlio di Barbato. / Costui fu console, censore, edile presso di voi. / Egli conquistò la Corsica e la città di Aleria, / consacrò come dovuto un tempio alle Tempeste.

== La prosa: diritto, cronaca e oratoria

La prosa dei secoli delle origini, pur non facendo parte della comunicazione letteraria, contribuì all'evoluzione linguistica e, pertanto, a creare l'ambiente adatto alla nascita della letteratura.

=== Il diritto

Non si possiede nulla purtroppo di molti documenti storicamente importanti: è questo il caso dei trattati (foedera) di alleanza, di pace, di commercio con i vari popoli con cui i romani di volta in volta venivano in contatto, come quello commerciale con Cartagine del 509 a.C. e il patto con la Lega Italica del 493 a.C. Gli storici romani riportano un arido elenco di trattati, che non riferisce nulla sulla sostanza dei patti conclusi, né sui principi del primitivo diritto internazionale.Anche delle leges regiae (leggi regie), che si facevano risalire a Romolo e ai suoi successori, non sono rimasti che pochi frammenti riportati da giuristi posteriori. Sicuramente non erano scritte ma tramandate oralmente all'interno della classe dominante; si basavano probabilmente su norme consuetudinarie riguardanti il rituale sacrale e il diritto privato. Secondo la tradizione sarebbero state raccolte da un pontefice, Sesto Papirio, all'epoca di Tarquinio il Superbo in un libro, lo Ius civile Papirianum.Enorme importanza storica e giuridica hanno le Leggi delle XII Tavole, la prima legislazione scritta del diritto romano, che Livio, secoli più tardi, definì "la fonte di ogni diritto pubblico e privato". All'epoca di Cicerone costituivano ancora un importante testo scolastico. Dietro le richieste sempre più impellenti della plebe, che esigeva una maggiore certezza del diritto, vennero redatte da una commissione di dieci magistrati, i Decemviri legibus scribundis, nel 451-450 a.C. e scritte su dodici tavole di bronzo esposte nel Foro. Hanno anche grande rilevanza dal punto di vista letterario: pur non essendo l'originale ma versioni posteriori in cui è stato modificato qualche vocabolo, sono il primo documento di prosa organizzata del periodo delle origini. Lo stile è conciso: Se un ladro ruba di notte, e il derubato lo uccide, venga ritenuto ucciso legalmente. Oppure: Nei riguardi di uno straniero vale il diritto di rivendicazione. O ancora: Se un padre avrà venduto il figlio per tre volte, il figlio sia libero dalla patria potestà. Pur non escludendo un'influenza greca, le leggi sono chiaramente il frutto delle consuetudini dei romani e del loro senso pratico. Le XII Tavole non costituiscono un complesso sistematico di tutto il diritto privato e pubblico, sono un importante passo in avanti verso la parificazione dei diritti dei cittadini romani. La sostituzione del diritto consuetudinario con uno scritto rappresentava una grande conquista della plebe; era stato, infatti, interesse dei ceti dominanti, che detenevano il monopolio del potere giudiziario, mantenere una legislazione affidata alla memoria dei giudici.

=== La cronaca

Grande importanza avevano per i romani i "fasti", un vero e proprio calendario civile, redatto dai pontefici. Riportava i giorni dell'anno in cui era lecito dedicarsi alle attività pubbliche (fasti), e quelli in cui non era lecito per motivi religiosi (nefasti). Vi erano inoltre annotati le cerimonie, i mercati, le calamità naturali, gli spettacoli, gli avvenimenti astronomici, i prodigi. In seguito la parola fasti (fasti consulares; fasti pontificales; fasti triumphales) indicò anche gli elenchi dei magistrati in carica annuale, gli atti ufficiali, le vittorie militari.Più tardi, il collegio dei pontefici pubblicò ogni anno sulla Tabula Dealbata (tavola bianca), esposta presso la Regia (sede del pontefice massimo e del rex sacrorum), non solo i nomi dei magistrati, ma anche gli avvenimenti di pubblica importanza, civile, religiosa, commerciale e militare. Questi documenti, scritti e consultabili con il nome complessivo di annales, registravano il ricordo di avvenimenti fondamentali e perciò fornivano una storia del popolo romano.Nel sec. II a.C., riuniti in 80 volumi per ordine del pontefice Publio Muzio Scevola, presero il titolo di Annales Maximi. Sfortunatamente un incendio aveva in gran parte distrutto le annate anteriori al 390 a.C.: per questo sono poche le notizie attendibili dei primi secoli della storia di Roma.Tutti i più importanti magistrati, come i consoli, i questori e i censori, redigevano diari, i commentarii, in cui registravano accuratamente i fatti salienti della loro magistratura e i provvedimenti presi. Era una memorialistica del tutto privata, che però poteva diventare pubblica quando i commentarii venivano depositati presso il collegio dei pontefici. Anche i vari collegi sacerdotali annotavano i loro atti nei Libri pontificum, nei Libri augurum, nei Libri saliorum.

=== L'oratoria e Appio Claudio Cieco

Fin dalla nascita della repubblica, l'oratoria ebbe importanza rilevante, in quanto l'arte del parlare e del convincere dava fama, successo, potere ed era base necessaria della carriera politica. Adatta all'indole pragmatica dei romani, essa costituiva l'unica attività intellettuale degna di un cittadino di ceto elevato. Non si conosce nulla degli oratori precedenti Appio Claudio Cieco, il primo di cui si hanno notizie storiche sicure. Patrizio di origine (sec. IV-III a.C.), molto aperto ai problemi sociali della sua epoca, nel 312, da censore, introdusse uomini nuovi in Senato, persino figli di liberti. Fece costruire il primo acquedotto (Aqua Appia) e dette inizio ai lavori della via Appia (regina viarum), la prima grande strada militare che conduceva a Capua. Fu console nel 307 e nel 296; partecipò alle guerre sannitiche e, ormai vecchio e cieco, persuase il Senato a respingere la pace offerta da Pirro, re dell'Epiro, pronunciando (280) un famoso discorso cui Cicerone alludeva come al primo discorso ufficiale mai pubblicato a Roma. Scrisse un Carmen de moribus, raccolta di massime moraleggianti in versi saturni fra cui, delle tre rimaste, la celebre: "Ognuno è artefice del proprio destino" è la più famosa. Non si sa se nei suoi scritti subì il fascino della cultura greca. Si interessò anche di diritto, facendo raccogliere e pubblicare dal suo segretario, Gneo Flavio, il cosiddetto Ius Flavianum, la prima opera latina di procedura giudiziaria. La tradizione gli attribuisce anche una riforma ortografica, con l'introduzione della consonante r intervocalica, al posto della s, e l'abolizione della z.

== La poesia: i carmina

Nel periodo preletterario delle origini la poesia si limitava alla sfera del pratico e dell'occasionale, cantando i sentimenti più sentiti della vita spirituale, religiosa e civile in componimenti detti carmina (da cano: canto), che usavano il verso saturnio. In ambito letterario il termine viene utilizzato per designare componimenti poetici di notevole estensione, mentre in questa fase antica, carmen non indica solo quello che è cantato, e cioè i componimenti in poesia, ma più genericamente tutto ciò che è di particolare solennità, che sta fuori dal parlato quotidiano, e quindi anche la prosa. Si trova così applicato alle più disparate forme di comunicazione, dalle preghiere alle filastrocche infantili e alle formule magiche, dalle leggi alle profezie e agli incantesimi, dalle nenie funebri ai giuramenti. I carmina hanno un contenuto piuttosto ingenuo e mostrano una certa rozzezza stilistica, nonostante il tentativo di elevare il tono espressivo. Mezzi tecnici poveri (rima, allitterazione, assonanza, figura etimologica e simmetria) e la cadenza di cantilena monotona aiutavano l'apprendimento a memoria.

=== I carmina religiosi

Tra i più antichi canti della poesia religiosa, risalenti al sec. VI a.C., vi è il Carmen Saliare, legato ai riti magico-religiosi dei Salii, è uno dei primi testi romani pervenuti, di cui sono rimasti pochi e spesso incomprensibili frammenti, conservati dagli eruditi latini. Ogni anno, in marzo e in ottobre, per celebrare l'apertura e la chiusura della stagione della guerra, i Salii (da salio: salto), i dodici sacerdoti di Marte, percorrevano in processione, vestiti da antichi guerrieri, i luoghi più importanti di Roma, intonando preghiere di invocazione agli dei, danzando e battendo con il piede il suolo con colpi forti e regolari in ritmo ternario, percuotendo con bastoni gli ancilia, i dodici scudi sacri di bronzo. Secondo la tradizione il collegio dei sacerdoti Salii era stato fondato dallo stesso Numa Pompilio per custodire l'ancile caduto miracolosamente dal cielo, pegno divino per la salvezza di Roma, e gli altri undici perfettamente uguali al primo, costruiti dal fabbro Mamurio Veturio.È invece pervenuta una versione completa e attendibile del Carmen Arvale, risalente al sec. VI, perché il testo veniva trasmesso di generazione in generazione. È un canto propiziatorio affinché gli dei invocati diano fertilità ai campi. Il carmen si trova nei numerosi frammenti di un'epigrafe del 218 d.C. degli Acta fratrum Arvalium, in cui il collegio sacerdotale registrava la propria attività. Il canto, in versi saturni, ognuno ripetuto tre volte tranne l'ultimo ripetuto cinque volte, costituiva il momento culminante della processione della festa Ambarvalia nel mese di maggio. Il carmen, di difficile interpretazione, invoca i Lari, Marte e i Semoni perché proteggano i campi (arva) dalle pestilenze. Veniva eseguito durante il rito della purificazione dei campi e in altre cerimonie dai fratres Arvales, il collegio di dodici sacerdoti, tutti patrizi, dediti al culto della divinità agricola Dia, la terra nutrice, istituito secondo la tradizione da Romolo.

=== I carmina profani

Legati alla sfera privata e profana sono i carmina convivalia, canti che, come riporta Cicerone, "era regola nei banchetti degli antenati che gli invitati cantassero uno dopo l'altro, accompagnati dal flauto, le gesta e le virtù degli uomini illustri". In questi banchetti (convivia) i ceti più elevati si incontravano quasi quotidianamente, ricambiando a turno cene di carattere politico, e la poesia, la musica e la danza assumevano un ruolo importante. I carmina celebravano, probabilmente in saturni, le imprese gloriose di antenati illustri. Non si conosce nulla degli eroi celebrati, perché non è pervenuto neppure un frammento.Brevi canti in saturni sono i carmina triumphalia, che i soldati improvvisavano durante le sfilate delle cerimonie di trionfo dei generali vittoriosi; espressioni rozze e plebee che avevano poco del trionfale, in cui i soldati alternavano alle lodi al vincitore, moteggi, battute triviali e licenziose.Del tutto diverse dai canti trionfali sono le neniae, le lamentazioni funebri in versi che venivano intonate durante le esequie in lode del defunto, prima da un parente e in epoca più tarda dalle praeficae, donne appositamente assoldate. Probabilmente erano in parte improvvisate secondo uno schema fisso. Del resto il funerale dei personaggi in vista di Roma diventava una cerimonia pubblica, con un grandioso corteo cui partecipavano tutti i parenti e gli amici e, simbolicamente, anche gli antenati, rappresentati da persone con maschere di cera. Giunti al Foro, il figlio del defunto, oppure un altro parente stretto o un amico, pronunciava un discorso commemorativo, la laudatio funebris, che celebrava le virtù e le imprese del defunto.

== Il teatro

Fescennino, satura e atellana rappresentano le forme preletterarie teatrali di Roma: sono in versi e tutte di carattere popolare.

=== Il fescennino

Il fescennino, manifestazione tipica del mondo agreste, era un vivace scambio di battute licenziose, in rozzi e improvvisati versi, che i gruppi di contadini si scambiavano nel corso delle cerimonie dopo il raccolto o delle feste dei Liberalia, in onore del dio della fecondità. Il termine sembra derivare dalla cittadina falisca di Fescennium, nell'Etruria meridionale. Il fescennino è un embrione di rappresentazione drammatica, sia per la sua forma di dialogo, sia perché i contadini indossavano maschere grottesche, le personae, fatte di corteccia d'albero. Penetrati in città, durante le feste nuziali, i versi fescennini furono oggetto di una legge delle XII Tavole, perché spesso diffamatori.

=== La satura

Provenivano dall'Etruria anche gli attori (histriones) che, secondo Livio, diedero inizio ai primi ludi scaenici nel 364 a.C. Nel corso delle cerimonie per placare gli dei e allontanare una grave epidemia, fu messo in scena uno spettacolo in cui alcuni artisti danzavano al suono del flauto. I romani alla danza e alla musica aggiunsero in seguito il canto e la recitazione con versi di tipo fescennino. Nacque così la satura, rappresentazione drammatica più complessa, di cui non è rimasto nulla. Il suo nome deriva da satur lanx, piatto colmo di molti cibi diversi, assimilabili ai vari elementi che concorrevano a comporla. La satura terminava spesso con un exodium, vale a dire un fine spettacolo, in cui un attore (exodiarius) eseguiva un canto buffonesco, mimandolo, per allietare gli spettatori.

=== L'atellana

Decisamente più importante per la storia del teatro romano è la nascita verso la fine del sec. IV a.C. dell'atellana (fabula atellana), farsa di origine osca che trae nome da Atella, una piccola città della Campania. Gli attori indossavano maschere che li trasformavano in personaggi facilmente riconoscibili dal pubblico per il modo di pensare, di agire, di parlare, di vestire, e improvvisavano su un rudimentale canovaccio prestabilito di argomento burlesco e grossolano, con un linguaggio plebeo, volgare e osceno. Quattro erano i ruoli fissi più comuni dell'atellana: Pappus, il vecchio rimbambito, lussurioso e avaro, gabbato sempre dall'amante e dal figlio; Maccus, lo scemo e millantatore dalle orecchie d'asino, vittima predestinata dei furbi; Bucco, il servo spaccone, chiacchierone e ghiottone; Dossennus, vecchio gobbo e astuto, saggio e perfido, parassita e amante dei banchetti. Sembra che il metro fosse il versus quadrato, due unità metriche ognuna di due piedi. L'atellana ebbe grande diffusione e continuò a vivere come exodium, anche quando con Livio Andronico, iniziò il teatro su modello greco. Nel sec. I a.C. assunse forma letteraria con Pomponio e Novio, che al canovaccio e all'improvvisazione sostituirono un testo totalmente scritto.

== Il verso saturnio

Il saturnio, l'unico verso usato nella poesia latina arcaica, prende il nome dal dio Saturno che, secondo il mito, si era rifugiato nel Lazio dopo la cacciata dal cielo; è detto anche faunio, in onore di Fauno, il dio indigeno che lo avrebbe inventato. Il poeta Ennio scrive che gli antichi canti erano in saturni e che a questo verso ricorrevano i vati e i fauni, intendendo forse così indicare il suo uso nei canti della tradizione religiosa e agreste. È un verso imprevedibile, dalla struttura estremamente fluida sulla cui natura gli studiosi non sono unanimi: ha un ritmo quantitativo, costruito cioè secondo una precisa successione di sillabe lunghe e brevi, oppure accentuativo, basato cioè su una determinata alternanza di sillabe toniche e sillabe atone, oppure, ancora, quantitativo e accentuativo insieme. Il fatto è che nei pochi versi pervenuti, circa duecento tra epigrafici e letterari, non si riscontrano due saturni uguali. È probabile comunque che nei primi secoli il verso avesse un ritmo accentuativo di origine indoeuropea, e successivamente, in fase soprattutto letteraria, diventasse quantitativo, perché più adatto alla natura della lingua latina. Già nel I sec. d.C. il grammatico Cesio Basso sosteneva fosse quantitativo: composto da due membri o cola che formano un dimetro giambico catalettico e da un itifallico o tripodia trocaica; aggiungeva però che aveva trovato un solo verso formato così. Usato a lungo nei secoli delle origini, il saturnio fu adottato in letteratura da Livio Andronico e da Nevio e poi scomparve per sempre, sostituito dall'esametro di origine greca, forse perché troppo irregolare per il gusto sempre più raffinato degli autori.

== In sintesi

/ Primi secoli (secc.VIII-VII a.C.): Nei primi secoli della sua storia, Roma ha una produzione anonima e tramandata oralmente, ma nulla di specificatamente letterario.
/ Le iscrizioni: I primi documenti pervenuti della lingua latina sono epigrafi di difficile interpretazione come il Lapis Niger (secc. VII-VI), il Vaso di Dueno (secc. VII-VI), la Cista Ficoroni e le iscrizioni sulle tombe della famiglia degli Scipioni (sec. III), interessanti perché prima testimonianza diretta del verso saturnio.
/ La prosa: il diritto: Le Leggi delle XII Tavole costituiscono non solo una grande conquista della plebe, che otteneva la certezza del diritto, ma hanno anche importanza preletteraria come primo documento di prosa organizzata.
/ La prosa: la cronaca: La redazione annuale degli Annales e la loro riunificazione in 80 libri con il titolo di Annales Maximi fornisce la storia del popolo romano.
/ La prosa: l'oratoria: È l'unica attività intellettuale degna di un patrizio, perché necessaria per fare carriera. Appio Claudio Cieco (sec. IV a.C.), il primo oratore di cui ci è giunta notizia, convinse il Senato a respingere la pace con Pirro con una famosa orazione (280) che era ancora letta ai tempi di Cicerone.
/ La poesia: Il più antico verso romano è il saturnio e il primo componimento di cui si ha memoria è il carmen. Di questo genere sono i più antichi inni religiosi: il Carmen Saliare e il Carmen Arvale; il primo cantato dai sacerdoti Salii in primavera e in autunno per l'apertura e la chiusura della guerra; il secondo dai sacerdoti Arvali per propiziare la fertilità dei campi. Profani sono i carmina convivalia e triumphalia e le neniae.
/ Le origini del teatro: Forma primitiva di poesia teatrale sono i versi fescennini, battute licenziose che i contadini si scambiavano durante le feste, e la satura, rappresentazione più complessa, di origine etrusca, con canto, recitazione, danza e gesticolazioni mimiche. Decisamente più importante per il teatro è l'atellana, farsa di origine osca recitata su un canovaccio da maschere fisse, quali Pappus, Maccus, Bucco e Dossennus.

