#import "../../../template_normal.typ": *
//#show: frame-style(styles.thmbox)

#evidenzia[Ludovico Ariosto è senza dubbio una figura centrale della poesia rinascimentale italiana. Con l'Orlando furioso, egli offre una visione moderna e idealizzata della dignità umana, combinando un'eleganza narrativa raffinata con la vivacità comica e, talvolta, ironica propria del tradizionale racconto epico. Ariosto incarna il Rinascimento nella sua forma più potente e gioiosa, rappresentando un modello di perfezione letteraria che integra magistralmente musica, plasticità figurativa, chiarezza stilistica e ricchezza poetica.]

== La vita

Ludovico Ariosto nacque a Reggio Emilia nel 1474 da una famiglia legata agli Estensi; il padre era un militare al loro servizio. A Ferrara studiò giurisprudenza, senza grande interesse, prima di dedicarsi completamente alle lettere. Già nel 1493 partecipava all'organizzazione di spettacoli teatrali presso la corte ferrarese, dove in seguito fu impiegato come funzionario ricoprendo ruoli militari e diplomatici. Nel 1502 fu nominato capitano di guarnigione a Canossa e dal 1503 al 1517 lavorò come segretario personale del cardinale Ippolito d'Este.

Questi incarichi lo costrinsero a viaggiare, non sempre con entusiasmo, tra Ferrara, Bologna, Modena, Mantova, Firenze e Roma. Dal 1504 iniziò la stesura dell'Orlando furioso, che lo avrebbe impegnato per tutta la vita, mentre fra il 1508 e il 1509 compose le due commedie _La Cassaria_ e _I Suppositi_, entrambe presentate a corte. Nel 1517 rifiutò di accompagnare il cardinale Ippolito nella sede vescovile di Agri in Ungheria. Assunto al servizio del duca Alfonso d'Este, riuscì finalmente a dedicarsi con maggiore serenità alla produzione letteraria. Nel 1520 concluse _Il Negromante_, la sua terza commedia, e nel 1521 pubblicò la seconda edizione del _Furioso_, preceduta dalla prima del 1516. Nello stesso anno scrisse la _Satira V_, nella quale emerge il tormento per l'incarico di governatore della Garfagnana che ricoprì dal 1522 al 1525, gestendo anche difficili situazioni presso Castelvecchio insieme al figlio Virginio.

Tornato a Ferrara nel 1525, dove fu nominato sovrintendente agli spettacoli di corte, acquistò una casa modesta e visse lì fino alla morte, nel 1533. In quel periodo si dedicò con passione alla revisione stilistica dell'Orlando furioso, che giunse alla sua terza edizione nel 1532. Dopo la sua morte apparve un'edizione postuma del poema (1545), che includeva i _Cinque Canti_, dalla datazione incerta e probabilmente composti tra la prima e la seconda edizione del Furioso.

== Le opere minori

All'inizio della sua carriera letteraria Ariosto si dedicò prevalentemente a commedie e liriche latine, cimentandosi anche in traduzioni di autori classici come Terenzio e Plauto. Le prime due commedie, _La Cassaria_ (1508) e _I Suppositi_ (1509), inizialmente scritte in prosa e poi rielaborate in versi, sono ambientate in contesti quotidiani e riflettono l'influenza del modello novellistico di Boccaccio attraverso una rappresentazione vivace di vizi e virtù umane. Meno riuscita appare _Il Negromante_ (1520), scritta in endecasillabi sdruccioli; più apprezzata è invece _La Lena_ (1528), una commedia di carattere che vede il trionfo delle astuzie di due giovani innamorati contro gli interessi di una coppia corrotta.

Si ritiene che Ludovico Ariosto abbia iniziato a comporre versi in volgare solo in età matura, probabilmente all'inizio del suo legame con Alessandra Benucci, nel 1513, donna che avrebbe poi sposato segretamente nel 1527. Le sue _Rime_, ispirate al modello petrarchesco e influenzate dall'opera di Matteo Maria Boiardo, comprendono 41 sonetti, 12 madrigali, 5 canzoni e 27 capitoli in terza rima. Di particolare rilievo sono le sette _Satire_, scritte tra il 1517 e il 1524: componimenti in terzine che si rifanno alle epistole del poeta latino Orazio. Esse costituiscono uno dei vertici più alti della poesia ariostesca e si presentano come un dialogo epistolare diretto a personaggi reali cui furono effettivamente indirizzate. 

Il tono vivace e polifonico di queste opere è arricchito da riflessioni, confronti e inserti di natura favolistica. L'importante epistolario di Ariosto, composto da ben 214 lettere scritte tra il 1498 e il 1532, rivela invece il lato più privato e umano del poeta, accanto alle numerose comunicazioni di carattere ufficiale.

== L'_Orlando furioso_

L'_Orlando furioso_, poema epico-cavalleresco in ottave, fu sottoposto a tre redazioni principali: la prima del 1516, la seconda del 1521 (di 40 canti) e la definitiva del 1532 (con un totale di 46 canti). Ariosto affinò progressivamente la lingua dell'opera, avvicinandola al fiorentino letterario e attenuando le influenze regionalistiche presenti nella versione iniziale. Il pregio stilistico del poema risiede infatti nella capacità di armonizzare lessico familiare e termini tecnici all'interno di una lingua letteraria sostenuta da un sapiente impianto metrico e musicale.

La narrazione riprende dalle vicende lasciate in sospeso nell'_Orlando innamorato_ di Boiardo: Re Carlo Magno decreta che Angelica sarà concessa in sposa a colui che si distinguerà maggiormente nella battaglia contro i Mori. Il poema si sviluppa lungo tre direttrici principali: l'azione epica, che incornicia il racconto ed è focalizzata sulla guerra tra cristiani e saraceni; l'azione sentimentale, che segue Orlando nella sua disperata ricerca di Angelica, culminata nella perdita e nel recupero del senno; e l'azione celebrativa, che ruota intorno all'amore tra il moro Ruggiero e la guerriera cristiana Bradamante, dal cui matrimonio e dalla conversione di Ruggiero al cristianesimo avrà origine la dinastia estense.

Alla trama principale si intrecciano continuamente racconti secondari proposti da vari personaggi, che contribuiscono a moltiplicare i centri narrativi del poema e a intrecciare le varie vicende. Gli interventi in prima persona dell'autore svolgono una funzione coordinatrice, suggerendo significati morali o psicologici agli eventi narrati. La struttura "aperta" dell'opera riflette l'imprevedibilità della vita, segnalando il passaggio dal teocentrismo medievale alla nuova sensibilità umanistica caratterizzata da una visione antropocentrica.

=== Il giudizio critico

Sul piano critico, l'_Orlando furioso_ è lodato per la profonda ironia con cui Ariosto riesce a conciliare armoniosamente le contraddizioni umane, offrendo una superiore contemplazione della natura stessa dell'uomo. Amato dai contemporanei, il poema ha raccolto ampi consensi nei secoli successivi. Benedetto Croce ha evidenziato come Ariosto sia riuscito a rappresentare con serenità i contrasti del mondo, mentre Italo Calvino ha descritto l'opera come uno straordinario gioco combinatorio di percorsi e destini intrecciati che riflettono l'incessante movimento della vita umana.

#pagebreak()
#set page(fill: main_letteratura.lighten(90%))
== In sintesi <senza_numero>

/ Ludovico Ariosto: Ludovico Ariosto (1474-1533), nato a Reggio Emilia, si trasferì a Ferrara per proseguire gli studi. Prestò servizio come funzionario politico e diplomatico presso la corte degli Estensi, organizzando anche spettacoli teatrali. \ Tra le sue opere minori spiccano quattro commedie: _La Cassaria_ (1508) e _I Suppositi_ (1509), entrambe ispirate al modello novellistico di Boccaccio, si distinguono per l'attenzione alle dinamiche umane e sociali; _Il Negromante_ (1520) risulta più complessa nella struttura; _La Lena_ (1528) è considerata la più riuscita. Le _Satire_ (1517-1524), scritte in terzine e ispirate alle epistole di Orazio, sono tra le vette dell'arte poetica di Ariosto. \ La sua opera maggiore, _Orlando furioso_, è un poema epico-cavalleresco strutturato in 46 canti in ottava rima. Il testo si articola su tre piani: l'azione epica, centrata sulla guerra tra cristiani e saraceni; l'azione sentimentale, focalizzata sulla tormentata ricerca di Angelica da parte di Orlando; e l'azione celebrativa, che esplora la travagliata relazione amorosa tra Ruggiero e Bradamante. \ Ariosto adotta una lingua equilibrata e uniforme, vicina al fiorentino letterario, evitando marcati influssi regionalistici. La sua grandezza risiede nella capacità di armonizzare le contraddizioni umane con ironia e distacco.
