#import "../../../template_tufte.typ": *
#show: frame-style(styles.thmbox)

#evidenzia[Conquistata l'Italia meridionale, Roma si trovò a confrontarsi con Cartagine, la città nordafricana situata nell'area dell'attuale Tunisi, che esercitava una posizione dominante nel Mediterraneo occidentale grazie al controllo di parte della Sicilia e delle colonie in Sardegna, Corsica, Spagna e Baleari.

I rapporti tra Roma e Cartagine, inizialmente amichevoli, si incrinarono col passare del tempo a causa delle crescenti interferenze reciproche nei traffici commerciali. Le tensioni sfociarono in una serie di conflitti noti come le Guerre Puniche, combattuti tra il III e il II secolo a.C. Alla fine di queste guerre, Roma consolidò la sua posizione di suprema potenza nel Mediterraneo. La terza guerra punica culminò con la completa distruzione di Cartagine da parte dei Romani. Durante questi scontri, Roma ampliò il suo dominio su Sardegna, Corsica, Sicilia (che diventò la prima provincia romana), Spagna, Gallia Cisalpina e Transalpina, Grecia e Asia Minore.]

== La prima Guerra punica

Nella prima Guerra Punica, Cartagine, fondata intorno all'814 a.C. dai Fenici, aveva imposto un rigido monopolio commerciale nel Mediterraneo, limitando l'approdo delle navi mercantili alla sola città madre e non alle sue colonie. I rapporti iniziali tra Roma e Cartagine furono caratterizzati da trattati basati sul rispetto reciproco: nel 508 a.C. fu stipulato un accordo commerciale che regolava le espansioni territoriali delle due potenze. Successivamente, questo trattato fu rinnovato nel 348 e nel 306 a.C., definendo ancora più chiaramente le rispettive sfere d'influenza.

La rottura si verificò nel 264 a.C., quando i Mamertini di Messina chiesero aiuto a Roma per difendersi dall'attacco dei Cartaginesi. Roma inviò un esercito guidato dal console Appio Claudio, che affrontò sia i Cartaginesi che il loro alleato Gerone II di Siracusa. Quest'ultimo, però, passò al fianco di Roma nel 263 a.C.

Per vincere la guerra fu fondamentale l'abilità dei Romani nel contrastare la superiorità navale di Cartagine, tradizionalmente dominante sul mare. Nel 260 a.C., grazie all'utilizzo dei corvi, ponti mobili che consentivano di agganciare le navi nemiche, la flotta romana comandata da Gaio Duilio sconfisse quella cartaginese nella battaglia di Milazzo.

La spedizione romana in Africa, guidata da Attilio Regolo nel 256 a.C., si concluse tragicamente con la sua cattura e morte. Tuttavia, la vittoria decisiva arrivò grazie al comando di Lutazio Catulo nella battaglia delle Egadi del 241 a.C., che costrinse Cartagine ad abbandonare la Sicilia e a pagare una pesante indennità di guerra.

La Sicilia, eccezion fatta per il territorio di Siracusa, divenne la prima provincia romana. In queste province, obbligate al pagamento di tributi, il potere e l'amministrazione furono affidati a funzionari romani come proconsoli o propretori. A completamento della pace del 238 a.C., i Romani sottrassero ai Cartaginesi anche il controllo della Sardegna e della Corsica.

== La seconda Guerra punica

Prima di avviare il secondo conflitto contro Cartagine, Roma si impegnò in una campagna di espansione nella regione adriatica dell'Illiria, tra il 230 e il 228 a.C., riducendola a un piccolo principato e garantendosi il controllo strategico sul canale d'Otranto. Contestualmente, a seguito di un tentativo di incursione da parte dei Galli, le forze romane reagirono efficacemente, arrivando a occupare Mediolanum (l'attuale Milano) e consolidando la loro presenza nella Pianura Padana nel 225 a.C.

Nel frattempo, i Cartaginesi, costretti ad abbandonare le isole mediterranee, rivolsero la loro attenzione verso la Spagna, dove intrapresero un'ampia campagna di conquista sotto la guida di Amilcare Barca e, successivamente, del figlio Annibale. Quest'ultimo, educato dal padre in un clima di profondo sentimento di ostilità contro Roma, assunse il comando e diede il via a una serie di operazioni che culminarono con l'attacco alla città di Sagunto, alleata dei Romani, provocando lo scoppio della seconda guerra punica nel 218 a.C. Prima che Roma riuscisse a inviare un esercito in Spagna, Annibale attraversò le Alpi con una marcia leggendaria e conseguì vittorie cruciali sulle legioni romane al Ticino (218), al Trasimeno (217) e, soprattutto, a Canne nel 216. Nonostante ciò, i suoi successi non furono sufficienti a disgregare la confederazione romano-italica.

Contemporaneamente, in Spagna, un contingente romano sotto il comando di Publio e Gneo Scipione impediva l'invio di rinforzi ad Annibale. In Italia, Quinto Fabio Massimo, nominato dittatore, adottò una strategia di logoramento per limitare l'efficacia delle campagne cartaginesi. Tuttavia, la sua leadership venne presto sostituita dai consoli Lucio Emilio Paolo e Terenzio Varrone, i quali preferirono un confronto diretto. Questo approccio culminò nella catastrofica battaglia di Canne, dove si registrarono circa 30.000 caduti tra i 50.000 soldati romani presenti. Nonostante la devastazione inflitta, Annibale rinunciò alla marcia su Roma, consentendo alla città eterna di riorganizzarsi rapidamente.

Nel 211 a.C., un esercito romano inviato in Sicilia conquistò Siracusa, che fu trasformata in città tributaria di Roma. Contemporaneamente in Macedonia, le truppe romane impegnate nella prima Guerra Macedonica sotto Filippo V perseguivano un obiettivo esclusivamente difensivo che portò alla stipula della Pace di Fenice nel 205 a.C. Quando Asdrubale, fratello di Annibale, riuscì a condurre un esercito dalla Spagna all'Italia, fu intercettato e sconfitto al Metauro nel 207, subendo una grave perdita umana e politica.

Nel 206 Publio Cornelio Scipione, futuro Scipione l'Africano, assunse il comando delle truppe romane in Spagna e conseguì una vittoria decisiva nella battaglia di Ilipa. Successivamente invase il territorio africano, costringendo Annibale a ritirarsi dall'Italia. La sconfitta finale dei Cartaginesi nella battaglia di Zama nel 202 sancì la loro resa totale: oltre alla cessione dei possedimenti europei e della Numidia (dichiarata indipendente sotto Massinissa, alleato romano), Cartagine fu obbligata a versare una significativa indennità di guerra a Roma.

== Dall'espansione in Oriente alla terza Guerra punica

Dopo la vittoria contro Cartagine, Roma tornò a intervenire in Macedonia su richiesta di Atene, che chiedeva aiuto contro Filippo V. Nel 200 a.C. ebbe così inizio la seconda guerra macedonica. Nel 197 a.C., i Romani, guidati da Tito Quinzio Flaminio, sconfissero Filippo nella battaglia di Cinocefale, obbligandolo a consegnare la flotta, a pagare un'indennità di guerra e a riconoscere la libertà delle città greche. Con questa vittoria, il protettorato macedone fu sostituito da quello romano.

Quando Antioco III di Siria rifiutò di ritirare le sue truppe dalla Grecia liberata dai Romani, Roma lo attaccò nel 191 a.C., sconfiggendolo alle Termopili. L'anno seguente, Lucio Cornelio Scipione sbarcò in Asia e inflisse una decisiva sconfitta alle forze siriache nella battaglia di Magnesia. Nel 171 a.C., un nuovo conflitto si profilò con la Macedonia a seguito dell'ascesa al trono di Perseo, figlio di Filippo V, noto per la sua forte ostilità nei confronti dei Romani. 

Dopo tre anni di conflitti, Lucio Emilio Paolo riportò la vittoria sull'esercito macedone nella battaglia di Pidna. La Macedonia fu smembrata in quattro repubbliche, tutte poste sotto l'influenza di Roma. Due rivolte seguirono alla vittoria romana: quella di Andrisco in Macedonia, sedata nel 146 a.C. da Cecilio Metello, e quella della Lega Achea, repressa nello stesso anno dal console Lucio Mummio.

Nel frattempo, a Roma cresceva il sentimento anticarataginese, alimentato da figure come il senatore Marco Porcio Catone, che sostenevano la necessità di eliminare Cartagine una volta per tutte. La situazione giunse a un punto di svolta quando Cartagine dichiarò guerra a Massinissa, re dei Numidi, esasperata dai soprusi di quest'ultimo. In risposta, Roma dichiarò guerra a Cartagine nel 149 a.C., dando inizio alla terza guerra punica. Nonostante gli iniziali negoziati e la resa dei Cartaginesi, la loro strenua resistenza continuò fino al 146 a.C., quando Scipione Emiliano espugnò Cartagine, distruggendo completamente la città e trasformando il suo territorio nella provincia d'Africa.

Nel 133 a.C., Scipione Emiliano pose fine alla rivolta di Numanzia in Spagna dopo anni di guerriglia, aprendo così la strada alla romanizzazione del territorio. Contestualmente, Roma si assicurò il controllo della Gallia meridionale, estendendo il proprio dominio dalle Alpi ai Pirenei e trasformandola nella provincia della Gallia Narbonense. Questi successi dimostrarono ancora una volta la potenza e la stabilità dell'impero romano.

== Approfondimento: Carthago delenda est

Le relazioni tra Roma e Cartagine si trasformarono nel tempo da collaborazioni e alleanze in una rivalità senza tregua. Dopo le ripetute vittorie contro le popolazioni italiche e contro Pirro, Roma iniziò a guardare con ostilità al predominio cartaginese sulla Sicilia e sul Mediterraneo. La competizione si fece spietata, alimentando un odio profondo tra le due civiltà.

Questo odio venne rappresentato simbolicamente dal giuramento fatto da Amilcare al giovane figlio Annibale: eterno rancore contro i Romani. Un sentimento analogo animava Marco Porcio Catone a Roma. Pur avendo criticato duramente i costosissimi preparativi di Publio Scipione per invadere l'Africa dalla Sicilia, Catone considerava Cartagine un nemico eterno da eliminare: "Carthago delenda est" divenne il mantra con cui esprimeva questa convinzione.

La ferocia dimostrata verso Cartagine rappresentò un'eccezione nel pensiero politico di Catone. Solitamente consigliava prudenza e moderazione nei confronti dei popoli sottomessi. Tuttavia, la rivalità con Cartagine si dimostrò più forte di ogni principio umanitario, tradendo quell'idea di “humanitas” che egli stesso riteneva essenziale per la grandezza dell'uomo. Al contrario, l'assenza di tale virtù finiva per corrompere i costumi e il carattere.

== In sintesi


LA PRIMA GUERRA PUNICA (264-241 a.C.)

Nel 264 a.C., i Mamertini di Messina chiesero l'intervento romano per difendersi dai Cartaginesi, dando avvio alla prima guerra tra Roma e Cartagine. Nel 260 a.C. la flotta romana riportò una schiacciante vittoria a Milazzo, mentre nel 256 a.C. fallì l'audace spedizione di Attilio Regolo in Africa. La svolta decisiva arrivò nel 241 a.C., quando Roma trionfò alle Egadi, trasformando la Sicilia nella prima provincia romana. Conclusa la pace, nel 238 a.C. i Romani sottrassero ai Cartaginesi anche la Sardegna e la Corsica.

DALLA SOTTOMISSIONE DELL'ILLIRIA ALLA SECONDA GUERRA PUNICA (230-202 a.C.)

Tra il 230 e il 228 a.C., Roma piegò l'Illiria, ampliando la sua influenza nei Balcani. Nel 225 a.C. respinse una minacciosa incursione dei Galli, li sconfisse e conquistò Mediolanum. Parallelamente, tra il 237 e il 219 a.C., Cartagine espanse il proprio dominio in Spagna. L'attacco di Annibale contro Sagunto, alleata di Roma, scatenò una nuova guerra nel 218 a.C. Annibale attraversò terraferma fino all'Italia e colse grandi successi militari, tra cui le vittorie al Ticino (218), al Trasimeno (217) e la devastante battaglia di Canne (216). Quinto Fabio Massimo intraprese una strategia di logoramento, ma fu sostituito dai consoli Lucio Emilio Paolo e Terenzio Varrone, che subirono una pesante sconfitta a Canne. Nel 211 a.C., Roma conquistò Siracusa, rendendola tributaria. Una guerra contro Filippo V di Macedonia portò al protettorato romano su parte del territorio macedone e alcune città ioniche nel 205 a.C. L'avanzata di Asdrubale, fratello di Annibale, fu fermata con la sua sconfitta al Metauro nel 207 a.C. Nel 206 Publio Cornelio Scipione ottenne una vittoria cruciale a Ilipa e invase l'Africa, costringendo Annibale ad abbandonare l'Italia. La battaglia finale si svolse a Zama nel 202 a.C., dove Scipione sconfisse Cartagine e ne sancì la resa definitiva.

DALL'ESPANSIONE IN ORIENTE ALLA TERZA GUERRA PUNICA (200-146 a.C.)

Nel 200 a.C., Roma intraprese una nuova guerra contro Filippo V, che fu sconfitto nel 197 a.C. a Cinocefale, segnando la fine della seconda guerra macedonica. Nel 191 a.C., Roma vinse contro Antioco III di Siria, consolidando la propria presenza orientale. Tra il 171 e il 168 a.C., i Romani affrontarono Perseo, figlio di Filippo V, nella terza guerra macedonica, smembrando la Macedonia in quattro repubbliche autonome. Il conflitto con Cartagine riemerse nel 149 a.C., culminando nel 146 con la completa distruzione della città da parte di Scipione Emiliano durante la terza guerra punica. Nello stesso anno, Roma domò le rivolte guidate da Andrisco in Macedonia e dalla Lega achea in Grecia. Nel 133 a.C. ebbe inizio la sistematica conquista della Spagna.