#import "../../../template/_global/template.typ": *
#import "../../../template/_global/config.typ": *

#intro[Il risveglio spirituale, sociale, economico, politico e demografico che interessò l'Occidente cristiano nell'XI secolo ebbe tra i suoi effetti principali le crociate. La riforma promossa da Gregorio VII, che mirava a emancipare la Chiesa dall'influenza del potere laico, riaffermò il ruolo centrale del Papato come guida spirituale e, in parte, politica della Cristianità.

La stabilità ritrovata nel Sacro Romano Impero riaccese la questione dei rapporti con l'Oriente, impossibili da gestire attraverso l'Impero bizantino, con cui i legami si erano deteriorati ben prima della frattura definitiva del 1054.

La Prima Crociata nacque come un pellegrinaggio armato dei popoli cristiani d'Europa, guidati dai cavalieri, per rivendicare il controllo della Terra Santa e, in particolare, di Gerusalemme con il Santo Sepolcro. Il territorio era allora sotto il dominio del Califfato islamico ortodosso che, con la dinastia dei Turchi Selgiuchidi, aveva ripreso il controllo della Palestina nel 1076.

Nella concezione cavalleresca cristiana, la crociata non era vista esclusivamente come un'operazione militare, ma rappresentava anche un simbolo rituale e spirituale: una lotta contro le passioni che intralciavano il cammino personale verso Dio. Questa visione trovava un parallelismo nel concetto islamico di jihad e avvicinava idealmente cristiani e musulmani. La prima crociata ufficiale prese avvio nel 1097 e culminò con la conquista di Gerusalemme nel 1099.

Le crociate successive si rivelarono invece globalmente dei fallimenti. Oltre alla prima impresa, le Repubbliche marinare italiane ebbero un ruolo attivo in queste spedizioni. In particolare, la quarta crociata fu finanziata da Venezia, assumendo connotati molto diversi dai pellegrinaggi originari.]

== I precedenti con l'Islam

Per quanto riguarda i precedenti rapporti con l'Islam, una prima azione di riscatto contro i musulmani si verificò durante il regno omayyade in Spagna. Nel 1063, sotto la guida di papa Alessandro II, si assistette al sostegno da parte delle popolazioni locali impegnate nella lotta contro gli invasori. Ferdinando I di Castiglia conquistò Coimbra e condusse varie spedizioni in tutta la penisola iberica. Suo figlio Alfonso VI occupò Toledo nel 1085, mentre altri alleati cristiani riuscirono a conquistare Saragozza. Cavalieri provenienti dalla Linguadoca, dalla Normandia e dalla Provenza si unirono alla battaglia per sostenere la causa cristiana.

Di fronte a queste difficoltà, gli emiri omayyadi chiesero rinforzi agli Almoravidi, giunti dal Maghreb per sostenere la loro resistenza. Con l'arrivo degli Almoravidi l'avanzata cristiana fu rallentata, ma lo scontro riprese intensamente alla fine dell'XI secolo grazie al coinvolgimento massiccio di contingenti normanni e francesi. Gli Almoravidi cercarono non solo di supportare gli Omayyadi ma anche di sottometterli, prendendo Siviglia e invadendo la Catalogna nei primi anni del XII secolo. Tuttavia, furono fermati da una forte reazione cristiana.

Alfonso I d'Aragona riconquistò Saragozza nel 1118 e ne fece la capitale del suo regno. Gli Almoravidi furono successivamente soppiantati dagli Almohadi, originari dell'Africa settentrionale. Questi ultimi ripresero il conflitto contro i cristiani ma vennero definitivamente respinti nella battaglia di Las Navas de Tolosa nel 1212. Da quel momento, le tensioni tra i due fronti si attenuarono significativamente.

== La Prima Crociata

Verso la metà dell'XI secolo, i Turchi Selgiuchidi sottrassero l'Asia Minore all'Impero Bizantino, avanzando fino alle regioni dell'Egeo, del Mar Nero e del Bosforo, oltre a occupare le terre della Siria e della Palestina. In quel periodo, l'Occidente cristiano, profondamente coinvolto nella lotta per le investiture e segnato dal recente scisma del 1054 con la Chiesa orientale, non intraprese alcuna azione per difendere i cristiani d'Oriente.

Una svolta si ebbe nel 1081, quando l'imperatore bizantino Alessio I Comneno sollecitò l'intervento dei principi occidentali. La richiesta di aiuto giunse anche a Piacenza nel 1095 tramite alcuni ambasciatori bizantini. Papa Urbano II, cogliendo l'opportunità, trasformò questa richiesta di natura difensiva in una proposta di più ampio respiro: promuovere la riconquista dei luoghi sacri al Cristianesimo. Durante il Concilio di Clermont dello stesso anno, il pontefice rivolse un appello al popolo franco, esortandolo a intervenire in Oriente. La Crociata fu concepita dal papa come una guerra santa, condotta dai soldati di Cristo sotto la guida del suo vicario terreno. Tuttavia, Urbano II evidenziò anche le implicazioni sociali e politiche dell'impresa, che avrebbe coinvolto le tensioni e le forze latenti all'interno del contesto europeo.

Dall'annuncio del papa sorsero subito spedizioni spontanee e disordinate, tra cui quella nota come la "crociata dei pezzenti" o degli "innocenti". Questa fu guidata da Pietro l'Eremita e composta principalmente da avventurieri, contadini, donne, anziani e bambini. Partendo dalla Francia orientale, i membri di questa spedizione si mantennero saccheggiando le campagne e attaccarono varie comunità ebraiche lungo il percorso. Giunti in Asia Minore, furono però definitivamente sconfitti e sterminati dai Turchi.

La prima crociata organizzata propriamente prese avvio nel 1097 da Costantinopoli. I suoi partecipanti comprendevano francesi, danesi, inglesi, normanni e diversi individui in cerca di avventura o di nuove terre da conquistare. Tra i leader più celebri si annoverano Goffredo di Buglione, duca della Bassa Lorena; Raimondo di Saint-Gilles, conte di Tolosa; Roberto Courteheuse, duca di Normandia; Boemondo di Taranto e suo nipote Tancredi; Baldovino di Fiandra; e Stefano di Blois. La Germania declinò la partecipazione, mentre l'Italia contribuì solo successivamente attraverso il coinvolgimento delle Repubbliche marinare.

Il primo successo della crociata fu la conquista di Nicea, che si arrese all'autorità dell'Imperatore bizantino. Successivamente Baldovino di Fiandra, insieme ai cavalieri loreni, avanzò verso la Cilicia e la Mesopotamia, stabilendo una contea con capitale Edessa. Nel frattempo il grosso delle forze crociate raggiunse Antiochia, che fu sottoposta a un lungo assedio durato sette mesi. Boemondo di Taranto, figura trainante dell'attacco, ottenne dagli altri leader crociati l'impegno che la città sarebbe stata posta sotto il suo dominio. Nel 1098 Antiochia fu infine espugnata; i crociati la saccheggiarono e massacrarono gran parte dei suoi abitanti.

L'anno seguente, nel 1099, grazie al supporto navale dei Genovesi, fu conquistata anche Gerusalemme. Similmente ad Antiochia, la città fu saccheggiata e i suoi abitanti furono sterminati. A seguito della vittoria furono istituiti i regni cristiani d'Oriente: il principato di Antiochia sotto Boemondo di Taranto, la contea di Tripoli sotto Raimondo di Tolosa e il Regno di Gerusalemme guidato da Goffredo di Buglione.

Per garantire la sicurezza dei pellegrinaggi nei territori conquistati e per consolidare il controllo militare e religioso sull'area furono istituiti ordini religioso-cavallereschi. Oltre agli obblighi tradizionali di povertà, castità e obbedienza tipici degli ordini monastici, i membri di queste congregazioni giurarono anche di combattere perpetuamente contro gli infedeli. Fra i principali ordini meritano una menzione gli Ospedalieri o Giovanniti, i Templari, chiamati così perché risiedevano nel sito dove in passato era sorto il tempio di Salomone a Gerusalemme, e i Cavalieri Teutonici, creato da alcuni tedeschi di Brema e Lubecca per assistere i pellegrini provenienti dalla Germania. 

#note(top)[== *🧩* I riti crociati <senza_numero>

L'esperienza crociata si definiva spiritualmente e simbolicamente come una forma di pellegrinaggio penitenziale verso il Santo Sepolcro. Come i pellegrini, i crociati ricevevano una benedizione speciale prima della partenza e beneficiavano della protezione ecclesiastica sui propri beni e familiari durante tutta la durata dell'impresa. A ciò si aggiungeva la concessione dell'indulgenza plenaria, ovvero il perdono completo dei peccati, insieme alla sospensione di procedimenti giudiziari eventualmente pendenti.

I crociati indossavano abiti con una croce visibile, simbolo distintivo della loro particolare condizione. L'istituzione della crociata venne ufficialmente codificata nella costituzione Ad liberandam Terram Sanctam del IV Concilio Lateranense del 1215. Questo documento stabiliva che l'organizzazione e il finanziamento delle crociate fossero prerogativa del Papato, che raccoglieva le risorse necessarie attraverso specifiche misure fiscali. A partire dalla metà del XII secolo, il termine crociata fu esteso per indicare anche le guerre contro gli Slavi pagani e i Mongoli che minacciavano l'Occidente.]

== Le altre crociate

Tra il 1135 e il 1144, i musulmani riuscirono a riprendere parte dei territori crociati, tra cui il Principato di Antiochia, la Contea di Edessa e la Contea di Tripoli. Questi eventi rappresentarono un significativo rovescio per le posizioni cristiane in Terra Santa. In risposta, tra il 1147 e il 1149, fu organizzata la Seconda Crociata, promossa dal papa Eugenio III e sostenuta attivamente da san Bernardo di Chiaravalle. La spedizione coinvolse sovrani di rilievo come Luigi VII di Francia e l'imperatore Corrado III. Tuttavia, il loro esercito subì una pesante sconfitta a Dorileo nel 1147, e i successivi tentativi di conquistare Damasco e Ascalona nel 1148 si rivelarono infruttuosi.

Nel 1187, sotto la guida di Salah-ad-din, noto come Saladino, i musulmani conquistarono Gerusalemme, evento che scatenò la Terza Crociata (1189-1192). Papa Clemente III chiamò i sovrani cristiani a partecipare alla missione, tra cui Guglielmo di Sicilia, l'imperatore Federico I Barbarossa, Filippo II Augusto di Francia e Riccardo Cuor di Leone, re d'Inghilterra. Tuttavia, la morte di Barbarossa nel 1190 disgregò il suo esercito, mentre Riccardo riuscì a conquistare Cipro lo stesso anno e, in collaborazione con Filippo II, anche San Giovanni d'Acri nel 1191. Nonostante due vittorie contro Saladino, gli sforzi per riconquistare Gerusalemme fallirono. Alla fine, Saladino e Riccardo stipularono una tregua quinquennale, e fu istituito un ridotto II Regno di Gerusalemme, con base a San Giovanni d'Acri e affidato a Corrado del Monferrato.

La Quarta Crociata (1202-1204), proclamata da papa Innocenzo III, vide la partecipazione di nobili francesi e italiani. Tuttavia, il suo sviluppo fu pesantemente influenzato dai finanziamenti veneziani, che imposero come condizione agli eserciti crociati l'assedio della ribelle Zara. Nel 1203, il doge Enrico Dandolo assunse la guida della crociata, ma invece di orientare gli sforzi verso la riconquista musulmana dell'Egitto, si concentrò su Costantinopoli. Questo cambiamento strategico causò la scomunica da parte del papa. La capitale bizantina fu infine conquistata nel 1204; l'imperatore Isacco II fu deposto e sostituito da Baldovino di Fiandra, dando origine all'Impero Latino d'Oriente.

La Quinta Crociata (1217-1221), bandita da papa Onorio III, ebbe come obiettivo la conquista dell'Egitto. Nel 1217 i crociati si radunarono a San Giovanni d'Acri e nel 1219 presero Damietta. Tuttavia, nel 1221 il sultano d'Egitto propose la restituzione di Gerusalemme in cambio della pace, offerta che fu respinta dal legato pontificio. La risposta culminò in una disfatta per i cristiani, che persero anche Damietta.

Nella Sesta Crociata (1228-1229), l'imperatore Federico II di Svevia negoziò il Trattato di Giaffa con il sultano d'Egitto. In base all'accordo, Gerusalemme, Betlemme e Nazareth furono restituite ai crociati senza spargimenti di sangue.

La Settima Crociata fu guidata esclusivamente da Luigi IX di Francia nel tentativo di liberare Gerusalemme, caduta nuovamente in mano musulmana nel 1244. Tuttavia, il re fu catturato a El-Mansura nel 1250 e rilasciato solo dopo aver ceduto Damietta, precedentemente riconquistata dai crociati nel 1249. Luigi IX si ritirò quindi a San Giovanni d'Acri, dove rimase per quattro anni nella speranza di riprendere le ostilità. Tuttavia, il disinteresse degli altri sovrani cristiani lo costrinse a tornare in patria.

L'Ottava Crociata, proclamata da papa Clemente IV nel 1270, fallì prima ancora di iniziare: Luigi IX, giunto a Tunisi, morì a causa della peste. Tra le crociate si distingue quella indetta da Innocenzo III nel 1208 contro gli albigesi (noti anche come Catari), considerati eretici in Francia. Questa campagna, durata fino al 1229, si concluse con l'annessione della Provenza al dominio di re Luigi VIII. Gli albigesi sopravvissuti furono perseguitati dall'Inquisizione, un tribunale ecclesiastico gestito dai domenicani per preservare l'ortodossia religiosa e combattere le eresie.

#note(top)[== *🧩* Bilancio delle crociate nell'interpretazione storica <senza_numero>

Il bilancio politico e militare delle crociate fu in gran parte negativo, ma le loro conseguenze sul piano degli scambi spirituali e culturali si rivelarono invece positive.

Durante il periodo delle crociate prese avvio una vasta opera di traduzione delle opere degli autori musulmani in latino, un processo che fu essenziale per la trasmissione del sapere e che influenzò profondamente la storia di numerose discipline scientifiche e culturali, come teologia, filosofia, medicina, fisica, matematica e storiografia.

Sul piano religioso è necessario distinguere tra le diverse crociate, poiché se alcune furono chiaramente condizionate da obiettivi politici, altre – in particolare la prima e quella guidata da Federico II, che portò alla pacifica cessione di Gerusalemme ai cristiani – conservarono maggiormente il carattere di pellegrinaggio spirituale.

Dal punto di vista economico, gli Stati occidentali non conseguirono vantaggi significativi dalle crociate. Le Repubbliche marinare italiane registrarono un certo arricchimento, seppur non straordinario; i loro principali poli commerciali rimasero i porti bizantini e Alessandria d'Egitto. Inoltre, le stesse Repubbliche trassero buoni profitti dai commerci con i crociati stanziati in Palestina, fornendo loro navi e approvvigionamenti.]

== Le Repubbliche marinare e le crociate

Le crociate giocarono un ruolo importante nel consolidamento delle Repubbliche marinare italiane, il cui sviluppo economico aveva iniziato a delinearsi già dal IX secolo. Bari e Amalfi furono le prime a emergere con forza. Bari cadde sotto il controllo bizantino nel 870, mentre Amalfi continuò a prosperare fino al XIII secolo, quando venne incorporata nel Regno normanno. Più a nord, sulla costa tirrenica, Pisa e Genova raggiunsero un grande splendore commerciale, mentre Venezia si affermò lungo la costa adriatica.

Pisa e Genova iniziarono la loro espansione nel Mediterraneo occidentale, per poi estendere i propri interessi verso l'Oriente. Alleate contro i Saraceni, conquistarono la Sardegna e fornirono significativi supporti navali alla Prima Crociata. Il successo militare permise loro di stabilire colonie in numerose città conquiste. I mercanti insediati in queste colonie usufruivano di quartieri esclusivi dove potevano operare liberamente, senza interferenze delle autorità locali e senza essere gravati da imposizioni fiscali.

Venezia, sin dal X secolo, si era già affermata come protagonista del commercio con l'Oriente e l'Europa centrale, grazie ai privilegi ottenuti dall'Impero bizantino cui formalmente era sottomessa. In cambio del suo sostegno per riconquistare la ribelle Zara, la città finanziò la Quarta Crociata e ottenne nuovi territori dalla costituzione dell'Impero Latino d'Oriente. Questo contribuì ad acuire la rivalità con Genova e Pisa. I conflitti con Genova caratterizzarono tutto il XIII secolo e si conclusero solo al termine della Guerra di Chioggia (1378-1381), che segnò il ritiro della Repubblica ligure dall'Adriatico.

#pagebreak()
#set page(fill: accent.sto.lighten(90%))
== In sintesi <senza_numero>

/ Precedenti delle Crociate: Nel 1063, le popolazioni locali si ribellarono al dominio degli Omayyadi in Spagna, un'insurrezione sostenuta dal papa Alessandro II. La lotta proseguì con l'intervento degli Arabi Almoravidi, fino a quando Alfonso I d'Aragona riuscì a riconquistare Saragozza nel 1118, trasformandola nella capitale del suo regno. Successivamente, i combattimenti continuarono contro gli Almohadi, i quali furono definitivamente sconfitti nella battaglia di Las Navas de Tolosa del 1212.

/ La Prima Crociata: Durante il Concilio di Clermont, tenuto nel 1095, papa Urbano II invitò il popolo franco ad intervenire in Oriente contro le forze musulmane. Seguendo tale appello, nel 1096 Pietro l'Eremita guidò una spedizione composta da poveri e cavalieri disperati verso l'Oriente; tuttavia, questi furono massacrati dai Turchi. Nel corso della campagna principale, guidata da principi cristiani, i crociati ottennero importanti successi militari: conquistarono Nicea nel 1097, Antiochia nel 1098 e infine Gerusalemme nel 1099. Questi eventi portarono alla formazione degli Stati crociati in Oriente. Tuttavia, tra il 1135 e il 1144, le forze musulmane riconquistarono alcune importanti posizioni: parte del Principato di Antiochia, la Contea di Edessa e la Contea di Tripoli.

/ Le altre crociate: La Seconda Crociata ebbe per protagonisti Luigi VII di Francia e Corrado III di Germania, i quali tentarono senza successo di conquistare Damasco e Ascalona. Nel 1187 Gerusalemme cadde nuovamente nelle mani dei musulmani sotto la guida di Saladino. \ Durante la Terza Crociata (1189-1192), Riccardo Cuor di Leone prese il controllo dell'isola di Cipro e, insieme a Filippo II di Francia, conquistò San Giovanni d'Acri nel 1191; tuttavia, i tentativi di riconquistare Gerusalemme risultarono infruttuosi. \ La Quarta Crociata (1202-1204), finanziata dalla Repubblica di Venezia, deviò dal suo obiettivo originario e portò alla conquista di Zara e Costantinopoli. Tale evento segnò la nascita dell'Impero Latino d'Oriente. \ Tra il 1208 e il 1229, fu intrapresa in Francia una crociata contro gli eretici albigesi. Nel frattempo, la Quinta Crociata si concentrò sulla conquista di Damietta, nel 1219, ma si concluse con una pesante sconfitta dovuta al rifiuto dei crociati di accettare un accordo che offriva la città in cambio di Gerusalemme e della pace. Successivamente, grazie a trattati diplomatici, Gerusalemme, Betlemme e Nazareth tornarono temporaneamente sotto il controllo crociato. \ L'ultima significativa crociata fu quella promossa per riconquistare Gerusalemme dopo la sua perdita definitiva nel 1244. Tuttavia, anche questa spedizione si concluse con un fallimento, segnato dalla resa dell'unico sovrano partecipante, Luigi IX di Francia. Le crociate successive non ebbero rilevanza strategica e segnarono il declino del movimento crociato europeo.
