#import "../../../template_normal.typ": *
//#show: frame-style(styles.thmbox)

#evidenzia[La gestione dell'Impero ideata da Diocleziano, nota come Tetrarchia, anziché risolvere il problema della successione, finì per complicarlo ulteriormente. Costantino, emerso come vincitore tra i pretendenti al potere, rafforzò l'autorità centrale, riorganizzò in maniera più efficiente l'esercito e cercò di porre fine alle tensioni religiose e culturali che affliggevano l'Impero.

Con la promulgazione dell'Editto di Milano, che garantiva ampie libertà ai cristiani, il destino dell'Impero cominciò gradualmente a intrecciarsi con quello della Chiesa. Negli ultimi decenni del IV secolo, i Goti, insediatisi all'interno dei confini imperiali grazie a una concessione dell'imperatore d'Oriente Valente, inflissero una grave sconfitta alle armate romane, penetrarono in Tracia e minacciarono direttamente Costantinopoli. La pace fu successivamente negoziata dal nuovo imperatore d'Oriente, Teodosio, che integrò i Goti nell'Impero come alleati, impiegandoli sempre più frequentemente come soldati nelle fila dell'esercito romano. 

Teodosio e Graziano, allora imperatore d'Occidente, sancirono con l'Editto di Tessalonica l'adozione del Cristianesimo come unica religione ufficiale dello Stato. Alla morte di Teodosio, tuttavia, il generale vandalo Stilicone, pur al servizio di Roma, non fu in grado di contenere l'invasione dei Goti, che diede origine al primo regno barbarico nel territorio delle Gallie. Nel 410 il visigoto Alarico inflisse un duro colpo alla dignità imperiale saccheggiando Roma. Nel frattempo, anche i Vandali e gli Unni continuarono a invadere l'Impero, ormai incapace di rialzarsi sotto la guida degli ultimi imperatori. L'epilogo giunse nel 476, anno in cui Odoacre, capo delle truppe barbare, destituì Romolo Augustolo, ultimo imperatore d'Occidente.]

== L'Impero di Costantino e la diffusione del Cristianesimo

L'abdicazione di Diocleziano e Massimiano inizialmente sembrò confermare l'efficacia del sistema tetrarchico: i due Cesari ascesero alla posizione di Augusti e designarono nuovi Cesari. Tuttavia, la morte di Costanzo Cloro provocò l'insorgere di violente contese per la successione. Tra i vari pretendenti al potere emersero in Occidente il figlio di Costanzo Cloro, Costantino (che nel 312 sconfisse il rivale Massenzio nella celebre battaglia di Ponte Milvio a Roma) e in Oriente Licinio (designato da Diocleziano stesso nel tentativo di placare le tensioni). 

Nel 313, i due Augusti si incontrarono a Milano e promulgarono un Editto che riconosceva la libertà di culto ai cristiani e introduceva leggi favorevoli nei loro confronti. Tuttavia, quando Licinio riprese a perseguitare la comunità cristiana, Costantino lo affrontò militarmente. Dopo averlo sconfitto nel 324, assunse il titolo di unico imperatore e trasferì la capitale dell'Impero a Bisanzio, ribattezzandola Costantinopoli. Impose una significativa riforma dell'esercito e ampliò l'apparato burocratico; inoltre consolidò definitivamente la figura dell'imperatore come sovrano assoluto d'ispirazione orientale, circondato da un'aura sacrale simbolica.

Nel 332 Costantino sconfisse i Goti e consolidò ulteriormente i confini orientali dell'Impero. Tuttavia, morì nel 337 mentre si preparava per una campagna militare contro i Persiani. Durante il suo regno, adottò una politica progressivamente più favorevole nei confronti del Cristianesimo, promuovendo attivamente la diffusione della religione tra i sudditi orientali e concedendo ai cristiani ruoli significativi all'interno dell'esercito e dell'amministrazione statale.

#note(top)[== *🧩* Il Cristianesimo delle origini <senza_numero>

Il Cristianesimo si inserisce nel panorama delle religioni che trovano in Abramo il proprio progenitore. La sua peculiarità risiede però nel fatto che il nucleo della rivelazione non si basa su una Legge o un Libro, bensì sul Cristo stesso, il Verbo incarnato.  

Come forma di rinnovamento dell'antica alleanza tra Dio e Israele, il Cristianesimo si affermò rapidamente come una religione universale, grazie soprattutto alla predicazione di san Paolo. Tuttavia, sin dai primi secoli le complesse dottrine relative alla Trinità e alla doppia natura (umanità e divinità) del Cristo generarono una moltitudine di eresie.  

Per evitare fratture insanabili tra le diverse tradizioni religiose abramiche, è essenziale riconoscere il legame tra l'Incarnazione e l'istituzione dell'Eucaristia: un mezzo rituale fondamentale per il Cristianesimo nel suo percorso di comunione con Dio. Similmente al rispetto delle prescrizioni della Legge per gli ebrei o alla recitazione dei versetti coranici per i musulmani, l'Eucaristia rappresenta un punto cardine del culto cristiano. L'unicità dell'Incarnazione riflette il ruolo gerarchico della Chiesa, presieduta dal papa come vicario del Cristo.]

== Il Cristianesimo e i motivi delle persecuzioni

Le prime comunità cristiane nacquero in seguito alla predicazione di Gesù Cristo, vissuto durante i regni di Augusto e Tiberio, insieme all'opera degli apostoli e all'attività itinerante di Paolo di Tarso. I centri principali del Cristianesimo erano Antiochia, Corinto, Efeso, Alessandria e Roma. Nonostante le diverse persecuzioni periodiche ordinate da imperatori come Nerone, Domiziano, Decio, Valeriano e Diocleziano, la diffusione del Cristianesimo all'interno dell'Impero Romano non fu mai interrotta.

Le motivazioni delle persecuzioni erano molteplici. Da un lato, le autorità politiche temevano il potere crescente delle comunità cristiane, che con la loro struttura gerarchica venivano percepite come una sorta di "Stato nello Stato". Dall'altro, il rifiuto dei cristiani di riconoscere la divinità dell'imperatore e l'inquietudine dell'opinione pubblica, che attribuiva le crisi dell'Impero alla vendetta degli dei, contribuirono ad alimentare i conflitti. La situazione mutò con gli imperatori Costantino e Teodosio, sotto i quali il Cristianesimo divenne una componente fondamentale dell'Impero.

== Da Giuliano a Teodosio

Alla morte di Costantino, il potere passò ai suoi tre figli: Costante, Costanzo e Costantino II. Dopo la prevalenza di Costanzo sugli altri fratelli, egli scelse Giuliano come suo successore. Giuliano, celebre per la vittoria sugli Alamanni nel 357, tentò di ripristinare il paganesimo eliminando i cristiani dalle posizioni dirigenziali e circondandosi di filosofi e intellettuali pagani. A causa del suo abbandono della fede cristiana, venne soprannominato "l'Apostata". Nel tentativo di accrescere il proprio prestigio presso il popolo, Giuliano progettò una campagna contro l'Impero persiano ma trovò la morte in battaglia prima di portarla a termine.

Verso la fine del IV secolo, i Goti, spinti dagli Unni, raggiunsero il confine danubiano e chiesero di entrare nell'Impero. Valente, imperatore d'Oriente, acconsentì sperando di usarli come rinforzi militari. Tuttavia, i continui saccheggi ad opera dei Goti causarono una guerra che culminò nel 378 con la disfatta dell'esercito romano nella battaglia di Adrianopoli, in Tracia. I Goti allora si dispersero nella regione saccheggiando e distruggendo ciò che incontravano. In Occidente Graziano mantenne il controllo dell'Impero, mentre in Oriente fu nominato imperatore Teodosio, un generale originario della Spagna.

Teodosio scelse di negoziare anziché combattere. Sotto questo accordo, i Goti divennero alleati dell'Impero romano, si integrarono sposando donne romane e ottenendo incarichi prestigiosi. Nel 380, Graziano e Teodosio promulgarono l'Editto di Tessalonica che stabilì il Cristianesimo come unica religione ufficiale dell'Impero. Con questa legge furono abolite definitivamente tutte le pratiche pagane tradizionali, inclusi i sacrifici rituali, i giochi olimpici e i culti legati ai templi.

== Il crollo dell'Impero d'Occidente

Alla morte di Teodosio, unico imperatore dopo la scomparsa di Graziano, il potere fu trasmesso ai suoi figli Arcadio (a Oriente) e Onorio (a Occidente), entrambi ancora molto giovani. La loro tutela fu affidata al generale di origine vandala Stilicone. I Goti, fino a quel momento mantenuti sotto controllo tramite concessioni di terre e denaro, iniziarono a diventare sempre più esigenti, spingendosi a invadere l'Italia sotto la guida di Alarico; Stilicone, pur avendoli sconfitti militarmente, optò per una tregua negoziata.  

Nel frattempo, altre popolazioni barbariche premevano in Gallia e Spagna: Svevi, Alamanni e Vandali. La classe dirigente imperiale, dopo aver trasferito la capitale a Ravenna e aver fatto eliminare Stilicone, tentò di contrastare gli invasori. Alarico saccheggiò Roma nel 410; il suo successore, Ataulfo, fondò nelle Gallie il primo regno barbarico e si unì in matrimonio con Galla Placidia, sorella di Onorio. Intanto, i Vandali guidati da Genserico occuparono Cartagine nel 429, sottraendo definitivamente all'Impero la fertile provincia d'Africa.  

Nel 430, l'Impero d'Occidente era ormai ridotto all'Italia, a parte della Gallia e a aree limitate nei Balcani. All'inizio del V secolo gli Unni, una popolazione asiatica guidata dal temibile Attila, irruppero in Europa saccheggiando numerose città orientali. Il generale romano Ezio decise di allearsi con i Visigoti e affrontò gli Unni nella battaglia dei Campi Catalaunici, nella Francia settentrionale, ottenendo una vittoria nel 451.  

Quando Attila tornò in Italia l'anno successivo, devastando il Veneto, fu inviato incontro papa Leone I per negoziare la pace. Colpiti da un'epidemia di peste, gli Unni si ritirarono e Attila morì nel 453 in Pannonia. Nonostante la fine della minaccia unna, l'Impero era ormai al collasso. Valentiniano III, ufficialmente imperatore e discendente di Teodosio, aveva perso il controllo effettivo a favore del generale Ezio. Alla morte di Valentiniano III nel 455, i Vandali saccheggiarono Roma, depredandola di ogni sua ricchezza.  

Successivamente si susseguirono vari imperatori sotto l'influenza del barbaro Ricimero. Fu in questo contesto che il patrizio Oreste proclamò imperatore il proprio figlio Romolo Augustolo. Tuttavia, dopo pochi mesi Romolo Augustolo fu deposto da Odoacre, comandante dell'esercito barbarico al servizio dell'Impero. Accettando l'investitura da Zenone, imperatore d'Oriente, Odoacre governò l'Italia: questo decreto segnava la fine dell'Impero romano d'Occidente.  

#pagebreak()
#set page(fill: main_storia.lighten(90%))
== In sintesi <senza_numero>


/ Costantino: Il sistema di successione ideato da Diocleziano dimostra una stabilità limitata, funzionando solo per un breve periodo. Alla morte di Costanzo Cloro si apre una fase di lotta per il potere che vede emergere due principali contendenti: Costantino e Massenzio. Costantino prevale nel 312, sconfiggendo Massenzio nella battaglia di Ponte Milvio, mentre Licinio acquisisce potere in Oriente. Con il celebre Editto di Milano del 313 i due sovrani garantiscono la libertà di culto ai cristiani, segnando una svolta epocale nella storia religiosa dell'impero. Nel 324 Costantino, dopo aver sconfitto Licinio, trasferisce la capitale da Roma a Bisanzio, ribattezzandola Costantinopoli. Nel 332 consegue una vittoria contro i Goti, consolidando ulteriormente la sua autorità. Muore nel 337 lasciando un lascito politico e religioso di grande rilevanza.

/ Dai figli di Costantino a Teodosio: Costantino designa suoi successori i figli Costantino II, Costante e Costanzo. La competizione interna tra i tre conduce alla prevalenza di Costanzo II, che assume il governo effettivo dell'impero. A lui succede Giuliano, soprannominato "l'Apostata" per il tentativo di restaurare il Paganesimo; durante il suo regno (361-363), sconfigge gli Alamanni nel 357. Successivamente emerge la figura di Valente (364-378), il quale ammette i Goti all'interno delle frontiere imperiali nel 375, consentendo loro di stanziarsi. \ Tuttavia, nel 378, i Goti infliggono una disastrosa sconfitta alle armate romane presso Adrianopoli. Con l'ascesa di Graziano (367-383) in Occidente e Teodosio (379-395) in Oriente, la politica religiosa cambia radicalmente: l'Editto di Tessalonica del 380 dichiara il Cristianesimo religione ufficiale e unica dell'Impero Romano. Alla morte di Eugenio nel 394, Teodosio riunisce il potere diventando sovrano unico.

/ Crollo dell'Impero d'Occidente: Con la morte di Teodosio nel 395, l'Impero Romano viene suddiviso tra i suoi giovani figli: Arcadio in Oriente e Onorio in Occidente. Il generale Stilicone assume la tutela del giovanissimo Onorio e ottiene successi militari significativi, sconfiggendo i Goti guidati da Alarico sia nel 402 sia nel 406. Nel 404 la capitale dell'Impero d'Occidente viene trasferita da Milano a Ravenna. \ Con l'inizio del V secolo, Vandali, Svevi e Alamanni penetrano nelle Gallie e in Spagna. Il saccheggio di Roma da parte di Alarico nel 410 rappresenta uno degli eventi più drammatici della fase decadente dell'impero. Successivamente, Ataulfo, successore di Alarico, fonda nelle Gallie il primo regno barbarico indipendente. Nel frattempo, i Vandali guidati da Genserico invadono l'Africa settentrionale e conquistano Cartagine nel 429. \ Nel 451 il generale Ezio riesce a fermare l'avanzata degli Unni in Gallia, mentre nel 452 papa Leone I negozia direttamente con Attila per evitare un ulteriore saccheggio dell'Italia. Il quadro politico diventa sempre più instabile con l'assassinio di Valentiniano III nel 455 e il successivo saccheggio di Roma da parte dei Vandali. \ Negli anni seguenti, l'Impero d'Occidente assiste alla rapida successione di imperatori deboli, spesso controllati dal generale barbaro Ricimero. Il colpo finale avviene nel 476 con la deposizione di Romolo Augustolo da parte di Odoacre, determinando formalmente la fine dell'Impero Romano d'Occidente. L'Oriente rimarrà ancora saldo fino alla caduta di Costantinopoli nel XV secolo.



