#import "../../../template_normal.typ": *
//#show: frame-style(styles.thmbox)

#evidenzia[Il termine "Ancien Régime" fu ideato dai rivoluzionari francesi per descrivere in chiave negativa il sistema politico e socio-economico della Francia prerivoluzionaria, contrapponendolo al "nuovo regime" nato dal processo rivoluzionario.

Questo sistema si caratterizzava in tre aspetti: politico, rappresentato dallo Stato monarchico assoluto; sociale, con una suddivisione dei sudditi in ceti, ordini o corporazioni più o meno privilegiate, a cui i rivoluzionari opposero il principio dell'uguaglianza dei cittadini; economico, segnato dai gravosi diritti feudali, dalle decime, dalle immunità e dai vincoli alla compravendita della terra, nonché dalla presenza di corporazioni obsolete.

Da tempo lo spirito riformatore aveva posto l'accento sull'esigenza di superare i privilegi e le limitazioni dello Stato monarchico assoluto. Tale necessità culminò in un movimento rivoluzionario che si distinse per programmi radicali spesso seguiti da violenze. La crisi trovò il suo apice tra il 1788 e il 1789, aggravata dall'insolubilità del deficit finanziario e dalla penuria alimentare con l'impennata dei prezzi dei cereali causata dalle cattive raccolte del secondo semestre.]

== Dall'Assemblea dei Notabili all'Assemblea Legislativa

L'unica soluzione prospettata per affrontare la crisi finanziaria del Regno di Francia sarebbe stata l'estensione del carico fiscale alle proprietà ecclesiastiche e nobiliari, che fino a quel momento godevano dell'esenzione dalle imposte. Questo fu il fulcro della proposta presentata dal controllore generale delle finanze, Charles-Alexandre de Calonne, all'Assemblea dei Notabili riunita nel febbraio del 1787. Tuttavia, sia l'Assemblea che il Parlamento di Parigi, composto prevalentemente da membri della nobiltà, respinsero tale proposta, sostenendo che fosse prerogativa degli Stati Generali deliberare su tali questioni. Gli Stati Generali, la tradizionale assemblea rappresentativa dei tre ordini di sudditi francesi (clero, nobiltà e terzo stato), non si riunivano dal 1614. Il successore di Calonne, Étienne-Charles de Loménie de Brienne, consigliò al re Luigi XVI di convocare gli Stati Generali per il primo maggio 1789.

La convocazione degli Stati Generali inaugurò un intenso periodo di mobilitazione civile, durante il quale furono redatti numerosi _cahiers de doléance_, documenti che raccoglievano le rimostranze e le richieste delle varie classi sociali e delle città nei confronti del governo e del monarca. Grazie alla pressione esercitata dal Terzo Stato, fu concesso il raddoppio del numero dei suoi rappresentanti: alla seduta inaugurale svoltasi a Versailles il 5 maggio 1789 parteciparono 578 delegati del Terzo Stato contro i 291 del clero e i 270 della nobiltà. Tuttavia, non fu accolta la richiesta di votare per testa anziché per ordine, come stabilito dalla prassi tradizionale. In risposta a questa frustrazione politica, i deputati del Terzo Stato si proclamarono Assemblea Nazionale il 17 giugno 1789 e giurarono di non sciogliersi prima di aver dotato la Francia di una costituzione, evento noto come il Giuramento della Pallacorda (20 giugno 1789).

Luigi XVI fu costretto, seppur controvoglia, a ordinare alla nobiltà e al clero di unirsi all'assemblea, che il 9 luglio si proclamò Assemblea Nazionale Costituente. La reazione della corte reale, caratterizzata dal licenziamento del ministro delle finanze Jacques Necker (ben visto dalla popolazione) e dal concentramento di truppe intorno a Parigi, innescò la celebre insurrezione popolare del 14 luglio 1789. Tale rivolta culminò con la presa della Bastiglia, simbolo dell'assolutismo monarchico, e con la creazione di una municipalità rivoluzionaria insieme a una milizia cittadina volontaria denominata Guardia Nazionale.

Nel corso delle settimane successive, alimentata dalle insurrezioni che dalle zone urbane si propagavano alle campagne, l'Assemblea Costituente adottò una serie di provvedimenti radicali. Il 4 agosto fu decretata l'abolizione del regime feudale, seguita dalla soppressione dei privilegi di Stato e della decima ecclesiastica. Il 26 agosto vide la proclamazione della _Dichiarazione dei Diritti dell'uomo e del cittadino_, che sancì i principi fondamentali delle libertà personali e civili, l'uguaglianza giuridica, l'inviolabilità della proprietà privata e l'indipendenza della magistratura. Inoltre, il 2 novembre i beni ecclesiastici furono espropriati e trasformati in "beni nazionali", successivamente venduti per favorire un'ampia redistribuzione terriera a vantaggio della piccola proprietà contadina.

La generale riorganizzazione amministrativa del territorio culminò nel febbraio del 1790 con la suddivisione della Francia in 83 dipartimenti. Contestualmente, la riforma religiosa portò alla promulgazione della _Costituzione Civile del clero_ (12 luglio 1790), imponendo al clero l'obbligo di prestare un giuramento civico. Tale misura provocò la condanna da parte di papa Pio VI e una profonda divisione interna tra i sacerdoti "costituzionali", favorevoli al giuramento, e quelli "refrattari", contrari all'obbedienza civica.

Le riforme introdotte in questo periodo si rivelarono complessivamente favorevoli ai ceti abbienti moderati e furono rese possibili grazie all'abile opera di mediazione condotta tra l'Assemblea Costituente e la corte, un ruolo svolto in particolare da figure di rilievo come Lafayette, Bailly e Mirabeau.

Tuttavia, l'equilibrio già precario venne infranto quando Luigi XVI, fortemente contrario al progressivo smantellamento dell'_Ancien Régime_, fu indotto a tentare una fuga clandestina nella speranza di ottenere il sostegno delle truppe a lui fedeli e la protezione del cognato Leopoldo II d'Asburgo. 

La fuga si concluse con la cattura del re e della sua famiglia a Varennes il 20 giugno 1791. Riportato a Parigi, Luigi XVI venne sospeso dalle sue funzioni, mentre nel paese iniziava a manifestarsi un movimento repubblicano di crescente vigore, guidato dal club dei Cordiglieri. Quest'ultimo, ispirato all'ordine francescano e caratterizzato dalla presenza di figure politiche prominenti come Marat, Des Moulins e Danton, divenne un centro nevralgico della radicalizzazione politica.

Il 13 settembre 1791 Luigi XVI fu costretto ad approvare la Costituzione votata dall'Assemblea Costituente. Questo documento attribuiva al re il potere esecutivo e il diritto di veto, mentre il potere legislativo veniva delegato a un'assemblea eletta secondo un sistema di suffragio ristretto basato sul censo, segnando così l'inizio della monarchia costituzionale.

In questo contesto di tensioni crescenti, i deputati girondini, esponenti moderati, cercarono di superare la crisi finanziaria e politica consolidando la coesione nazionale attraverso una guerra contro le monarchie assolute europee. Ne scaturì la dichiarazione di guerra da parte della Francia agli Asburgo, alleati della Prussia, il 20 maggio 1792. L'opposizione del re ai decreti emanati dall'Assemblea Legislativa e l'invasione austro-prussiana determinarono una crescente interconnessione tra guerra rivoluzionaria ed estremizzazione politica interna.

== La Repubblica, la Convenzione e il Terrore

#note(bottom)[== *🧩* La Rivoluzione in Italia <senza_numero>
Le idee democratiche illuminate penetrarono progressivamente negli ambienti intellettuali piemontesi e napoletani durante la Rivoluzione francese. Nel 1793 diversi Stati italiani, tra cui lo Stato Pontificio e il Regno di Napoli, aderirono alla Prima Coalizione antifrancese; tuttavia, il Granducato di Toscana fu il primo a siglare un accordo di pace con la Francia regicida.  

Tra il 1796 e il 1799, durante la Prima Campagna d'Italia condotta dal generale Bonaparte, il Regno di Sardegna e l'Austria vennero piegati militarmente. Questa serie di vittorie consentì alla Francia di negoziare favorevoli trattati di pace con i duchi padani e lo Stato Pontificio (come il Trattato di Tolentino del 19 febbraio 1797). 

La strategia francese mirava a consolidare il legame tra i popoli italiani e la Francia tramite una rete di repubbliche giacobine che gravitavano economicamente e politicamente sotto il controllo diretto del Direttorio. Questo processo fu particolarmente evidente nel caso della Repubblica Cisalpina, spesso soggetta a colpi di Stato che ricalcavano quanto avveniva nella Francia direttoriale. Tali repubbliche sorsero inizialmente al nord (Cispadana e Cisalpina nel 1797; Ligure nel medesimo anno) e in seguito al sud (Romana nel 1798 e Partenopea nel 1799).

Inoltre, i francesi occuparono territori come Piemonte, Toscana e Venezia; quest'ultima fu poi ceduta all'Austria tramite il Trattato di Campoformio del 17 ottobre 1797. 

Tuttavia, la reazione austro-russa del 1799 pose fine a queste esperienze democratiche in Italia.]

Con il rifiuto ostinato di Luigi XVI di ratificare la creazione di un'armata volontaria, il malcontento popolare raggiunse il culmine durante la "giornata rivoluzionaria" del 20 giugno 1792, quando la folla parigina invase le Tuileries, costringendo il sovrano ad accettare le richieste. Successivamente, il Manifesto del Duca di Brunswick, emesso il 25 luglio e caratterizzato da minacce di distruzione contro Parigi nel caso di violenze alla famiglia reale, contribuì ad accentuare la delegittimazione della monarchia.

L'insurrezione del 10 agosto, condotta congiuntamente dai Cordiglieri e dai Giacobini, portò alla formazione di una Comune insurrezionale a Parigi, diventata il nuovo centro politico del paese. Un ulteriore assalto alle Tuileries determinò l'incarcerazione della famiglia reale il 12-13 agosto.

Le avanzate delle truppe nemiche, l'aggravamento della crisi economica causata dall'eccessiva circolazione degli assegnati – una cartamoneta garantita dai "beni nazionali" ma ormai svalutata – e la veemente campagna politica dei rivoluzionari più radicali, tra cui spiccava Marat, crearono un clima di paura collettiva. Questo contesto favorì gli eccidi del 5-6 settembre dove vennero letteralmente massacrati nobili e detenuti accusati di simpatie controrivoluzionarie e comportò l'istituzione del Tribunale Rivoluzionario, che inaugurò una fase di terrore destinata a influenzare profondamente le vicende successive della Rivoluzione francese.

Nel contesto del tumultuoso periodo della Rivoluzione francese, venne eletta mediante suffragio universale una nuova assemblea, la Convenzione Nazionale, che il 21-22 settembre 1792 proclamò ufficialmente la Repubblica. Due giorni prima, il generale Dumouriez era riuscito a fermare l'avanzata delle truppe prussiane nella battaglia di Valmy, segnando un momento cruciale per la difesa rivoluzionaria.

Durante il processo al sovrano deposto, la fazione politica più radicale della Montagna, composta prevalentemente da giacobini, prese il sopravvento e riuscì a ottenere la condanna a morte del re Luigi XVI, che fu giustiziato tramite ghigliottina il 21 gennaio 1793. Tuttavia, le successive sconfitte militari subite dalle truppe rivoluzionarie per mano della coalizione nemica, il tradimento del generale Dumouriez e l'insorgenza di una rivolta controrivoluzionaria nella regione della Vandea (febbraio-marzo), ostile alla leva obbligatoria decretata dalla Convenzione, favorirono ulteriormente l'ascesa dei montagnardi. Questi, sotto la guida di Danton e Robespierre e sostenuti dagli strati popolari parigini noti come "sanculotti", portatori di radicali istanze democratiche, consolidarono il loro potere.

Per fronteggiare la crisi interna ed esterna, il 6 maggio fu istituito il Comitato di Salute Pubblica, inizialmente dominato da Danton fino a luglio e poi da Robespierre. Il comitato adottò misure economiche come il calmiere sui prezzi dei cereali, richiesto dai sanculotti per far fronte alla difficile congiuntura economica. Al contempo, i girondini vennero messi fuori legge; molti furono giustiziati o costretti all'esilio. Il regime instaurato assunse connotati dittatoriali e impose un rigido controllo su tutti gli aspetti dell'amministrazione pubblica, sull'esercito e sulla vita sociale, sotto la supervisione diretta del Comitato di Salute Pubblica. Questo agiva con l'obiettivo di eliminare le opposizioni interne, considerate strettamente connesse ai nemici esterni.

Il 23 agosto venne decretata la leva obbligatoria di massa, seguita il 5 settembre dalla decisione di porre il Terrore come strumento principale del governo. Sul fronte bellico, il brillante stratega Carnot guidava le armate rivoluzionarie, mentre sul piano interno la Legge sui sospetti, promulgata il 17 settembre, conferiva al Tribunale Rivoluzionario l'autorità di condannare a morte su base indiziaria tutti gli individui sospettati di attività controrivoluzionarie, compresi nobili e oppositori politici.

Le richieste di smorzamento del clima di Terrore si scontrarono con la ferma opposizione di Robespierre. Quest'ultimo, ormai in posizione predominante all'interno del Comitato di Salute Pubblica dopo aver ridimensionato gli altri comitati del governo rivoluzionario, reagì eliminando fisicamente sia i rappresentanti dell'ala radicale (come Hébert nel marzo 1794) sia quelli dell'ala più moderata o "indulgente" (tra cui Danton e Desmoulins nel maggio 1794).

L'estensione della Legge sui sospetti anche ai membri del parlamento provocò un rafforzamento delle opposizioni nei confronti di Robespierre, soprannominato "l'Incorruttibile". La situazione militare migliorò significativamente dopo la decisiva vittoria nella battaglia di Fleurus del 26 giugno 1794, favorendo un cambio di rotta politica. L'esaurimento del Terrore culminò nel colpo di Stato del 27 luglio (9 Termidoro dell'Anno II secondo il calendario repubblicano), che portò all'esecuzione degli esponenti del governo responsabili delle purghe, tra cui lo stesso Robespierre. Questo evento segnò una svolta importante nella storia della Rivoluzione francese e fu accompagnato dall'introduzione di varie misure innovative da parte della Convenzione Nazionale.

== Dal 9 termidoro al 18 brumaio

I termidoriani e gli ex girondini mantennero il controllo del potere anche dopo la dissoluzione della Convenzione e la creazione di un nuovo regime repubblicano, istituito con la Costituzione dell'Anno III (1795), noto come Direttorio, in riferimento all'organo al quale era attribuito il potere esecutivo. 

Questo regime, sostenuto dalle forze moderate e borghesi della Rivoluzione — tra cui proprietari terrieri, finanzieri, fornitori dell'esercito, speculatori e imprenditori — oltre che dal supporto di alcuni generali, fu costretto, per garantirsi la sopravvivenza, a reprimere l'opposizione sia dei monarchici, sconfitti dal generale Bonaparte il 5 dicembre 1795, sia dei superstiti sanculotti e montagnardi, protagonisti della Congiura degli Eguali guidata da Babeuf nel 1796.

Sul piano interno, il Direttorio fu caratterizzato da una profonda instabilità istituzionale, segnata da continui colpi di Stato volti a neutralizzare le fazioni che guadagnavano eccessivo potere: esempi significativi furono quelli del 4 settembre 1797, dell'11 maggio 1798 e del 18 giugno 1799. Sul piano internazionale, invece, si distinse per l'espansione della Rivoluzione in Europa attraverso una serie di campagne militari fortunate; queste permisero alla Francia di annettere territori seguendo la logica delle "frontiere naturali" e di creare un sistema di Stati satelliti noti come "repubbliche sorelle" (tra cui la Repubblica Batava, 1795, e diverse realtà italiane come Cispadana, Ligure, Cisalpina, Elvetica, Romana e Partenopea tra il 1796 e il 1799).

Tuttavia, il collasso di queste repubbliche, causato dall'avanzata della Seconda Coalizione antifrancese (1798) e dal fallimento pressoché totale della spedizione in Egitto contro l'Inghilterra (1798-99), ebbe ripercussioni significative sulla scena interna francese. Il colpo di Stato del 18 brumaio (9 novembre 1799) segnò la fine del Direttorio e affidò la Repubblica alle mani di Napoleone Bonaparte tramite l'istituzione del Consolato.

#pagebreak()
#set page(fill: main_storia.lighten(90%))
== In sintesi <senza_numero>

/ 1789-92: Con la convocazione degli Stati Generali, preceduta dalla redazione dei _cahiers de doléance_, il Terzo Stato, frustrato dalla mancata concessione del voto per testa, si dichiara Assemblea Nazionale. A questa si uniscono, seppur con molta esitazione, il clero e la nobiltà. La reazione della Corte scatena una rivolta a Parigi culminata nella presa della Bastiglia. L'Assemblea Costituente introduce riforme radicali: abolizione del regime feudale, nazionalizzazione dei beni ecclesiastici e costituzione civile del clero. Questi provvedimenti incontrano l'opposizione di Luigi XVI, che tenta la fuga. Catturato a Varennes, il re è costretto a ratificare la nuova Costituzione, trasformando la Francia in una monarchia costituzionale. Nel frattempo, i girondini, per superare l'impasse politico, dichiarano guerra all'Austria.

/ 1792-95: Le sconfitte militari, l'ambiguità del re nei confronti dei nemici e la crisi economica alimentano un'ondata rivoluzionaria a Parigi, orchestrata dai membri più radicali del popolo e dai club estremisti (montagnardi e sanculotti). Dopo numerosi massacri di sospetti traditori, viene eletta la Convenzione Nazionale, che sancisce la fine della monarchia e la nascita della repubblica. Sul fronte militare arriva una svolta positiva con la vittoria di Valmy. Luigi XVI viene processato, condannato a morte e ghigliottinato. Tuttavia, nuove sconfitte militari, il malcontento economico e la rivolta in Vandea favoriscono l'ascesa al potere dei montagnardi e inaugurano il periodo del Terrore. Robespierre guida un governo autoritario eliminando sia gli estremisti come gli hebertisti sia i patrioti moderati come Danton e Desmoulins. La prosecuzione delle politiche rivoluzionarie, anche quando non più necessarie, spinge le forze moderate a destituire Robespierre con il colpo di Stato del 9 termidoro.

/ 1795-99: Con l'instaurazione del Direttorio, sostenuto dai borghesi e dalle correnti moderate, vengono repressi sia i tentativi di restaurazione monarchica sia le spinte estremiste. Per consolidare il potere, il governo si avvale dell'aiuto dei generali repubblicani che esportano la rivoluzione in Europa. Tra questi emerge Napoleone Bonaparte, protagonista della conquista dell'Italia. Tuttavia, rientrando dal fallimento della spedizione d'Egitto, Napoleone sfrutta il discredito del Direttorio, indebolito da scandali e sconfitte, per rovesciare il governo con il colpo di Stato del 18 brumaio.

